stages:
  - install
  - lint
  - test
  - e2e

variables:
  NODE_VERSION: "20.x"
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/.yarn-cache"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .yarn-cache/
    - node_modules/
    - packages/*/node_modules/
    - packages/*/dist/

before_script:
  - node --version
  - yarn --version

install:
  stage: install
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn-cache
  artifacts:
    expire_in: 1 hour
    paths:
      - node_modules/
      - packages/*/node_modules/

lint:
  stage: lint
  needs: ["install"]
  script:
    - yarn eslint
    - yarn types:check
  allow_failure: false

unit-tests:
  stage: test
  needs: ["install"]
  script:
    - yarn test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - coverage/
      - test-results/
    reports:
      junit:
        - test-results/junit.xml

playwright-tests:
  stage: e2e
  needs: ["install"]
  image: mcr.microsoft.com/playwright:v1.48.0-jammy
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - apt-get update
    - apt-get install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    - apt-get install -y nodejs
    - npm install -g yarn
    - yarn install --frozen-lockfile --cache-folder .yarn-cache
    - yarn playwright install --with-deps
  script:
    # Build the application first
    - yarn build:all
    # Run E2E tests
    - yarn playwright test
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - playwright-report/
      - test-results/
      - trace/
    reports:
      junit:
        - test-results/junit.xml
  allow_failure: false

smoke-tests:
  stage: e2e
  needs: ["install"]
  image: mcr.microsoft.com/playwright:v1.48.0-jammy
  before_script:
    - apt-get update
    - apt-get install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    - apt-get install -y nodejs
    - npm install -g yarn
    - yarn install --frozen-lockfile --cache-folder .yarn-cache
    - yarn playwright install chromium
  script:
    # Build the application
    - yarn build:all
    # Run only smoke tests
    - yarn playwright test --grep @smoke
  timeout: 10 minutes
  allow_failure: false