enableGlobalCache: true

enableTelemetry: false

globalFolder: ./.yarn/global

nmMode: hardlinks-global

nodeLinker: pnp

pnpFallbackMode: all

pnpMode: strict

yarnPath: .yarn/releases/yarn-4.0.0-rc.45.cjs
