cacheFolder: ./.yarn/cache

checksumBehavior: reset

compressionLevel: 0

enableGlobalCache: true

enableInlineBuilds: true
enableHardenedMode: false

enableStrictSsl: true

enableTelemetry: false

enableTransparentWorkspaces: true

networkConcurrency: 8

nmHoistingLimits: workspaces

nmMode: hardlinks-local

nodeLinker: pnp

pnpEnableEsmLoader: true

pnpEnableInlining: false

pnpFallbackMode: dependencies-only

pnpMode: loose

pnpIgnorePatterns:
  - "esprima"
  - "supports-color"
  - "encoding"

packageExtensions:
  "vite@*":
    dependencies:
      supports-color: "*"
  "debug@*":
    dependencies:
      supports-color: "*"
  "vite-plugin-top-level-await@*":
    dependencies:
      rollup: "*"
  "vitest@*":
    dependencies:
      esprima: "*"
      supports-color: "*"
  "@vitest/runner@*":
    dependencies:
      esprima: "*"
      supports-color: "*"
  "@vitest/ui@*":
    dependencies:
      esprima: "*"
      supports-color: "*"
  "node-fetch@*":
    dependencies:
      encoding: "*"
  "@vitejs/plugin-react-swc@*":
    dependencies:
      supports-color: "*"
  "eslint@*":
    dependencies:
      supports-color: "*"
  "chalk@*":
    dependencies:
      supports-color: "*"
  "happy-dom@*":
    dependencies:
      supports-color: "*"
  "jsdom@*":
    dependencies:
      supports-color: "*"
  "@testing-library/jest-dom@*":
    dependencies:
      supports-color: "*"
      
supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - current
  os:
    - linux
    - darwin
    - win32

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.9.1.cjs
