checksumBehavior: reset

enableGlobalCache: true
enableTelemetry: false

enableInlineBuilds: true

nodeLinker: node-modules

pnpEnableEsmLoader: true

pnpEnableInlining: true

pnpFallbackMode: all

pnpMode: strict

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.6.0.cjs
