cacheFolder: ./.yarn/cache

checksumBehavior: reset

compressionLevel: 0

enableGlobalCache: true

enableHardenedMode: false

enableInlineBuilds: true

enableStrictSsl: true

enableTelemetry: false

enableTransparentWorkspaces: true

networkConcurrency: 8

nmHoistingLimits: workspaces

nmMode: hardlinks-local

nodeLinker: pnp

pnpEnableEsmLoader: true

pnpEnableInlining: false

pnpFallbackMode: dependencies-only

pnpIgnorePatterns:
  - encoding

pnpMode: loose

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - current
  os:
    - linux
    - darwin
    - win32

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.9.2.cjs
