cacheFolder: ./.yarn/cache

checksumBehavior: reset

compressionLevel: 0

enableGlobalCache: true

enableHardenedMode: false

enableInlineBuilds: true

enableStrictSsl: true

enableTelemetry: false

enableTransparentWorkspaces: true

networkConcurrency: 8

nmHoistingLimits: workspaces

nmMode: hardlinks-local

nodeLinker: pnp

packageExtensions:
  "@testing-library/jest-dom@*":
    dependencies:
      supports-color: "*"
  "@vitejs/plugin-react-swc@*":
    dependencies:
      supports-color: "*"
  "@vitest/runner@*":
    dependencies:
      esprima: "*"
      supports-color: "*"
  "@vitest/ui@*":
    dependencies:
      esprima: "*"
      supports-color: "*"
  "chalk@*":
    dependencies:
      supports-color: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  eslint@*:
    dependencies:
      supports-color: "*"
  happy-dom@*:
    dependencies:
      supports-color: "*"
  jsdom@*:
    dependencies:
      supports-color: "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
  vite-plugin-top-level-await@*:
    dependencies:
      rollup: "*"
  vite@*:
    dependencies:
      supports-color: "*"
  vitest@*:
    dependencies:
      esprima: "*"
      supports-color: "*"

pnpEnableEsmLoader: true

pnpEnableInlining: false

pnpFallbackMode: dependencies-only

pnpIgnorePatterns:
  - esprima
  - supports-color
  - encoding

pnpMode: loose

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - current
  os:
    - linux
    - darwin
    - win32

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.9.2.cjs
