checksumBehavior: reset

enableGlobalCache: true

enableInlineBuilds: true

enableTelemetry: false

nodeLinker: node-modules

pnpEnableEsmLoader: true

pnpEnableInlining: true

pnpFallbackMode: all

pnpMode: strict

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.7.0.cjs
