enableTelemetry: true
enableGlobalCache: true
enableInlineBuilds: false
pnpEnableEsmLoader: false

tsEnableAutoTypes: true

nodeLinker: pnp

pnpFallbackMode: all

pnpMode: strict

yarnPath: .yarn/releases/yarn-4.5.0.cjs
