cacheFolder: ./.yarn/cache

checksumBehavior: reset

compressionLevel: mixed

enableGlobalCache: true

enableInlineBuilds: true

enableStrictSsl: true

enableTelemetry: false

enableTransparentWorkspaces: true

networkConcurrency: 8

nmHoistingLimits: workspaces

nmMode: hardlinks-local

nodeLinker: node-modules

pnpEnableEsmLoader: true

pnpEnableInlining: false

pnpFallbackMode: all

pnpIgnorePatterns:
  - debug*
  - esprima*
  - supports-color*

pnpMode: loose

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - current
  os:
    - linux
    - darwin
    - win32

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.9.1.cjs
