# Cache and performance settings
enableGlobalCache: true
enableInlineBuilds: true
compressionLevel: mixed
cacheFolder: ./.yarn/cache
checksumBehavior: reset

# Package management settings
nodeLinker: node-modules
nmMode: hardlinks-local
nmHoistingLimits: workspaces
enableTransparentWorkspaces: true

# PnP settings
pnpMode: loose
pnpEnableEsmLoader: true
pnpEnableInlining: false
pnpFallbackMode: all
pnpIgnorePatterns:
  - "debug*"
  - "esprima*"
  - "supports-color*"

# Network settings
networkConcurrency: 8
enableStrictSsl: true

# TypeScript settings
tsEnableAutoTypes: true

# Platform support
supportedArchitectures:
  os: [linux, darwin, win32]
  cpu: [x64, arm64]
  libc: [current]

# Telemetry
enableTelemetry: false

# Yarn path
yarnPath: .yarn/releases/yarn-4.7.0.cjs
