export const files = {
  "assets/app.css": "QmdumnLemYHH9pLCiUXqCuNebvH6EFn4dF5UuWaqNC9BYd",
  "assets/fonts/KFOlCnqEu92Fr1MmEU9fBBc9.ttf":
    "QmVB1APqxwoFrkjZ9B2kYmukzGPdVrdct1JdxhkPbeY28Q",
  "assets/fonts/KFOlCnqEu92Fr1MmSU5fBBc9.ttf":
    "QmSuFCECZFdYirnXLK6xfaZWPmqP77LsRCnrdsmU9KVoMT",
  "assets/fonts/KFOlCnqEu92Fr1MmWUlfBBc9.ttf":
    "Qmd8qKxYJaKoiR9EsxgQqwkD5XBzayCHKwNJuhQuUF5ApJ",
  "assets/fonts/KFOmCnqEu92Fr1Mu4mxP.ttf":
    "QmRbTrHtUz6mKUsu7FFzfUBcr4VuoCt9TtpMnJG1P135bS",
  "assets/normalize.min.css": "QmVaRzLwnw3Nnoq8KHNBSTun6m3v2WvVaUbRpukVpcGJUX",
  "assets/roboto.css": "QmafZGaL6TznhmwtJ78ggkm7phbCiuEVXcTxfLwbZG6PoT",
  "assets/social-media-computer-icons-share-icon-png":
    "QmcsMurTbnEVPqP42x15FiisSjQdXJ7vGGHhf279UtwPxE",
  "assets/syntiwave.jpg": "QmVP5gg9nYuPg1au5pBmdn75xmUvuGevRPLhEngyEyQfkT",
  "assets/triangle-geometry.png":
    "QmZ5Nic3MRHT8m9SY5ZrSp38UHGEYmJqgk4RAmDV3xXqa1",
  "assets/zed-icon-big.png": "QmeHY7RZzR5wm9ELZr5xgq6XMQKjRAHgmxoQaCzHjgpRm8",
  "favicon.ico": "QmWF8oNe7SDdaY6t4WrJ8ZzM46dHEFmHDXzd8MBeNrELxe",
  "index.html": "QmR5E8XvCVwwDvReWrTS15ZNveyL7WNURkgeMRxeikndg9",
  "ipfs.json": "QmbBV3Li2S1VDtjj2EMW9AFtuMDppanNMYgJr3nzEpwKTf",
  "manifest.json": "QmTBHTEYaAy537jiSxtGsyDWNAAXQsvtCtmLgBvbGPFdK3",
  "node_legacy/@babel/@types/csstype/LICENSE":
    "QmZ9fseCz1pfFHux7muviXzDBKHF2eC4UAkyvHr34cNB9X",
  "node_legacy/@babel/@types/csstype/README.md":
    "QmPAGzEWQDxqKrZYoJm5AuBMdb6ch58YBcg4XrGGBXZDLz",
  "node_legacy/@babel/@types/csstype/index.d.ts":
    "QmQVBHSqpuMYatdfySzFExa4iEzodFwgHZYt61tpxbKgjy",
  "node_legacy/@babel/@types/csstype/index.js.flow":
    "QmaBdMT1oLabsFSSb4P41yhUv45Pp5dw2q8RH9jVtMtRc2",
  "node_legacy/@babel/@types/csstype/package.json":
    "QmZrvXJT5SoFhyjxLNZFg3Er4sEMupXkj9J2n2uokskLjr",
  "node_legacy/@babel/@types/react/LICENSE":
    "QmUTmHFik6fBSpJj8QxxdHV7BNbBuT6JpshoB8kjqCUwmU",
  "node_legacy/@babel/@types/react/README.md":
    "QmTj3jDPGkQ3UGW431Lq4oMZSgARfWHJ9pRZ65PB3pyV1e",
  "node_legacy/@babel/@types/react/experimental.d.ts":
    "QmTditSoEGdSVwjuiDM7iJGYNNEsxfrwP2Y2F4vsrTDBCi",
  "node_legacy/@babel/@types/react/global.d.ts":
    "QmYWoAkGksDA6zVMcctQpA8xWdGGnhk6NkT17TPLoCLsn4",
  "node_legacy/@babel/@types/react/index.d.ts":
    "QmYM43xyPLpVHep2LdYXCJahGMeYPasBxWMQyLMwqfxyv7",
  "node_legacy/@babel/@types/react/jsx-dev-runtime.d.ts":
    "QmXkiNDEBDb5JzUX374dKEX6Eeb8TY7JdDbYqVdmR4faVB",
  "node_legacy/@babel/@types/react/jsx-runtime.d.ts":
    "QmXkiNDEBDb5JzUX374dKEX6Eeb8TY7JdDbYqVdmR4faVB",
  "node_legacy/@babel/@types/react/package.json":
    "QmXoctn2SpWp2k66sbKN893Ms9D2AXojvmjLYKETTtrxqR",
  "node_legacy/@babel/@types/react-dom/LICENSE":
    "QmUTmHFik6fBSpJj8QxxdHV7BNbBuT6JpshoB8kjqCUwmU",
  "node_legacy/@babel/@types/react-dom/README.md":
    "QmUpvTKGPfghe3Cc31q4dca4fhqf85g8TAdg7BMZ3A5TvX",
  "node_legacy/@babel/@types/react-dom/experimental.d.ts":
    "QmZk5GydHWngtYkUJzdA7gygUZtQJG3FBkzzwvVGtMJ8Ap",
  "node_legacy/@babel/@types/react-dom/index.d.ts":
    "QmWGv3U2cn7KwND5Sxmgw75awkXJGgyxSksW37JQGWBGfq",
  "node_legacy/@babel/@types/react-dom/node-stream/index.d.ts":
    "QmdMuhJLS8zNjak6og3pxzqpmnPDBLbew5vyYfVEM76qmF",
  "node_legacy/@babel/@types/react-dom/package.json":
    "QmcNczN2yEqUh1TJTVWeAHvw3pnWHUXojW2ps2pz4dmbNf",
  "node_legacy/@babel/@types/react-dom/server/index.d.ts":
    "QmNsCC6Hq5uW2aoKiyRL5vfkxdSNagjspu2CJuAfgY5tZq",
  "node_legacy/@babel/@types/react-dom/test-utils/index.d.ts":
    "QmeWaCcEa449gZ454nQg1oK7zXVZMNwfkwqtA2nFrJJc1N",
  "node_legacy/@babel/standalone/LICENSE":
    "QmZqNk275fZv9p2XtmVbDu5cwqnkhKrrFN3wbYJqGzpznc",
  "node_legacy/@babel/standalone/README.md":
    "Qmd7fqhRTRNoZVVTMt3YuJjUzLUDjajmyyYdQigncNqkAE",
  "node_legacy/@babel/standalone/babel.js":
    "QmYsHEj7QyeLRK17JqduUcZo73AxxYLZTJ1T5ZMyrFPQqC",
  "node_legacy/@babel/standalone/babel.min.js":
    "QmdCiW5wGiJKavAHxWwg6Q1ADWVoVVwQjVC1zHMRGdR287",
  "node_legacy/@babel/standalone/package.json":
    "QmdKc28DprNXfJdbv9MRbxBQ8GXxbfDXebJXDruZdM7HHU",
  "node_legacy/@babel/standalone/test/babel.js":
    "QmSVHZ25VdQAypNkJWq97qUuv5bcULo5hGWvqgjkZLVYtk",
  "node_legacy/comlink/comlink.min.js":
    "QmXxvh5CjqR5b2gDgeGLpi52sJT57bmnse9JaofpHCm5i3",
  "node_legacy/comlink/comlink.min.mjs":
    "QmQaWVwJtXHsDocKk3FzJBaNA6VUhuiqbhTgUgVfBJRHiZ",
  "node_legacy/ipfs/CHANGELOG.md":
    "QmR7n57AAu9LWnG5SrbhdGYkkFosXUCMBuyQMXb9zgo8F5",
  "node_legacy/ipfs/README.md":
    "QmPqW8dQSrEUnJR2M4Arwk42iNoqFpF1a1CR11ntbab1ch",
  "node_legacy/ipfs/dist/index.min.js":
    "Qmf8UzMwbDoatpss7FACVL1fcR8QkPK6kUCbUvAfQ2N7wM",
  "node_legacy/ipfs/dist/index.min.js.LICENSE.txt":
    "QmSgtBgxRMqSnJAK9Lkn5necqaTtcWzH7mY2bXkqH7QSTs",
  "node_legacy/ipfs/dist/src/cli.d.ts":
    "QmXZPqWpB37Ge4pw6JrYghKJeCCDtkxZd9uZUKnSbucMmV",
  "node_legacy/ipfs/dist/src/cli.d.ts.map":
    "Qmd6YQrboQhqoZBZHzEUd1wGe3ZW4LpuGWsWvgFTyhj5rE",
  "node_legacy/ipfs/dist/src/index.d.ts":
    "QmduDHodVek1Qmk61JobR5szpAj7RDidoNkhfJTLLTj3oM",
  "node_legacy/ipfs/dist/src/index.d.ts.map":
    "Qme8AciEXCfQy8eZhwMhpFcCdE7cH12URucWDFHGEHPHRP",
  "node_legacy/ipfs/dist/tsconfig.tsbuildinfo":
    "QmXkYZ1uFPvszQcSaNweLLtciUj6M14BtdnCjL6YALBu3J",
  "node_legacy/ipfs/node_modules/lru-cache/LICENSE":
    "QmYgnjmy99it9ojz9x3NxMGoTiHys7sGLCYVcvwM2UizPd",
  "node_legacy/ipfs/node_modules/lru-cache/README.md":
    "QmQhDELJ8uETbwxkBkqQqtgikuZAphX2ecPwUp8pa7PVrB",
  "node_legacy/ipfs/node_modules/lru-cache/index.js":
    "Qmb3mQTfaKYro74cF8MsPCsv8ZgtLqFaKCreRm5yXVhTiU",
  "node_legacy/ipfs/node_modules/lru-cache/package.json":
    "QmZNGS31JbPNuftbkJQJjMwo3upRDYRdhAg1KdVfJ1XWEH",
  "node_legacy/ipfs/node_modules/semver/CHANGELOG.md":
    "QmY93Qf5JxcK2CHC9vzRY7hVEm8K6qgcoNTmKePV1r6hov",
  "node_legacy/ipfs/node_modules/semver/LICENSE":
    "QmYgnjmy99it9ojz9x3NxMGoTiHys7sGLCYVcvwM2UizPd",
  "node_legacy/ipfs/node_modules/semver/README.md":
    "QmWXkzxRQsbPXYMZMbTnCbitWNWHooDdEcFXqosYfMRkWT",
  "node_legacy/ipfs/node_modules/semver/bin/semver.js":
    "QmQuD1TRfLQv21uBWWGeynvXriEjE7gfKUFrrmeDGVvrsq",
  "node_legacy/ipfs/node_modules/semver/classes/comparator.js":
    "QmeDdemzFkuBQBkFTCb6djFB4EsKLZeGhZrqyX7Ar67717",
  "node_legacy/ipfs/node_modules/semver/classes/index.js":
    "QmUGhA7uptJ9qsGXGAxT7JXPXhHDK92EYC25pZvF7TBJ6A",
  "node_legacy/ipfs/node_modules/semver/classes/range.js":
    "QmUUWyS42mnWTnz4CuL6tvU2pMj2jmCdgzmvDkiccMHsHM",
  "node_legacy/ipfs/node_modules/semver/classes/semver.js":
    "QmU2HBiiq3VBpVujQhK5YwCW9nTnyuiLYdcqYsM3MzPheo",
  "node_legacy/ipfs/node_modules/semver/functions/clean.js":
    "QmX4wLunWawFZhcjMV6eXMVpH5KJGtQwVAvTENMTajAsXL",
  "node_legacy/ipfs/node_modules/semver/functions/cmp.js":
    "QmRziijeEBoaxLRYvEkWkgKnPigH6pkXaSdKinaSfKVa4N",
  "node_legacy/ipfs/node_modules/semver/functions/coerce.js":
    "QmdrFib3aZhBUJ5wugE9xVTPsgx21b3J642d6waR1JKYn5",
  "node_legacy/ipfs/node_modules/semver/functions/compare-build.js":
    "QmQdjsxtGrxsV4kaSoeQszo3EoVzaQMpQVBAMYazxnK31y",
  "node_legacy/ipfs/node_modules/semver/functions/compare-loose.js":
    "QmUVREJCW585Tpr5snSEdXjNntPWC7TUmdc6Su1Gkruuh9",
  "node_legacy/ipfs/node_modules/semver/functions/compare.js":
    "QmaMRJWxiivfkUxAdZi6C12cWK9A3wBezSpSL9w8STEpEr",
  "node_legacy/ipfs/node_modules/semver/functions/diff.js":
    "QmTw9khYZoQDq7xApfBbynG2eK4qY9WFunw79zTKQnhJu7",
  "node_legacy/ipfs/node_modules/semver/functions/eq.js":
    "QmdkUsCjpAyKf4WBSRdiCijhYQqyvvk8ukV64UVHL8oafA",
  "node_legacy/ipfs/node_modules/semver/functions/gt.js":
    "QmawVv12tbr6W85TyMSLsJ9wNCTTBFXhBMiKdS7kNT1gaq",
  "node_legacy/ipfs/node_modules/semver/functions/gte.js":
    "QmQKbnRUNV5XaEoTz2GZZHTZfckqWdtRLoBLSAUg2VGgZQ",
  "node_legacy/ipfs/node_modules/semver/functions/inc.js":
    "Qma33MTwEDbRdK9m76H3GD79f2DDiqx3nfgSvahtwQ7xm1",
  "node_legacy/ipfs/node_modules/semver/functions/lt.js":
    "QmSa4qGbSd4QaqAwVPYdHv3a1MnTfRVNhZQP3jHfzMAuPi",
  "node_legacy/ipfs/node_modules/semver/functions/lte.js":
    "QmWYfuTmM68JohuqSCuutwuLxBF6qKRKRdNi5Rvyubk1uZ",
  "node_legacy/ipfs/node_modules/semver/functions/major.js":
    "QmZSX5tqFgm4Kvt4frGTCQ9nMGfNyDVirWP1rSWuhWix5j",
  "node_legacy/ipfs/node_modules/semver/functions/minor.js":
    "QmXkNN1XREV55YXAXxE73YV2CzC1yFqrAEszv388K81Ngi",
  "node_legacy/ipfs/node_modules/semver/functions/neq.js":
    "Qmcgo7maNNDCMVfS7ovrVX1nnEapTkeu6Virb7KQmEHTas",
  "node_legacy/ipfs/node_modules/semver/functions/parse.js":
    "QmQeRv1cwSzMdeZNutC2xeRSSnMsStJSM83fTn1chDomhS",
  "node_legacy/ipfs/node_modules/semver/functions/patch.js":
    "QmUDAwuBf6dcxbKPpanFihP5v5JKvWZBB1YrnipybjT8SV",
  "node_legacy/ipfs/node_modules/semver/functions/prerelease.js":
    "QmQUd63E5EGvff7FMy1jiZZvPLhuaCNiMiuZYCR9FxLNPJ",
  "node_legacy/ipfs/node_modules/semver/functions/rcompare.js":
    "QmPT7jzcZbZfzx3Vydr3RWfjzi78HmtLgqCxeLKrBuMYPP",
  "node_legacy/ipfs/node_modules/semver/functions/rsort.js":
    "QmNurxuj3ZHJ8c52GJXdqNbZ12SuFMc2q6UWDNfzJ4hibu",
  "node_legacy/ipfs/node_modules/semver/functions/satisfies.js":
    "QmY944f3fwHo2LD6PxNAeABG5hekb7icbxrvrvmCN8BGb9",
  "node_legacy/ipfs/node_modules/semver/functions/sort.js":
    "QmTVyg7X7Jw6zJrXb1Tm78D58BaAC9ZEUZN9Knyr2irbd2",
  "node_legacy/ipfs/node_modules/semver/functions/valid.js":
    "QmZMdhxfULQeitiE88hAFfAomatnN1fpG6eKsa7J9nSThd",
  "node_legacy/ipfs/node_modules/semver/index.js":
    "QmW2q5QyDBfWUN45irbfqurgF5okTuzZh5CJNDZC1TvrCh",
  "node_legacy/ipfs/node_modules/semver/internal/constants.js":
    "QmefxeWwFMLS4TUNTmiqmQej49p75sSKCep9GNMKU2NmHU",
  "node_legacy/ipfs/node_modules/semver/internal/debug.js":
    "QmU4YKnQipxfQw2Kc5JpnZrQAttxKnzwv83GAnQaZUqJbN",
  "node_legacy/ipfs/node_modules/semver/internal/identifiers.js":
    "QmVppTdjeKTEhSS4tnFhfUFy7nLrhFEfc7pzt8FjU4n5fE",
  "node_legacy/ipfs/node_modules/semver/internal/parse-options.js":
    "QmZt39N8eSkiLGopoDe2eARUCcWETmLwJRnhYWAfZ4gEq6",
  "node_legacy/ipfs/node_modules/semver/internal/re.js":
    "QmbR6qnPgjqQBreNUoejKLr1CKMLsakdXCRVEFC6zyK3GK",
  "node_legacy/ipfs/node_modules/semver/package.json":
    "QmXWCWagcqT5Jycm1LSpJ1qZvdTyQ1jh6zCikrUPv1wjg7",
  "node_legacy/ipfs/node_modules/semver/preload.js":
    "QmTMnbSBEu21KkCkfsyFXY65or1fPVb3sgLgBVcqKAzBdg",
  "node_legacy/ipfs/node_modules/semver/range.bnf":
    "QmTdmj4AyNZcMQKTJKbCs36HDPabHVyXQ6z8xsbPHt4sa3",
  "node_legacy/ipfs/node_modules/semver/ranges/gtr.js":
    "QmT6xFM9yGATDT4yLCg8DTFu1kB8JXoxXc7FHKyAW9isgv",
  "node_legacy/ipfs/node_modules/semver/ranges/intersects.js":
    "QmPneChbok7QCcw7UtpjKtBkqUdVTE1bHg3vj5Et6gv419",
  "node_legacy/ipfs/node_modules/semver/ranges/ltr.js":
    "QmYyq45cdEAFLAwLEEtLr9aiDFJDVCDC9WTqCSo7Pg3H7s",
  "node_legacy/ipfs/node_modules/semver/ranges/max-satisfying.js":
    "QmdKamc3g9YzJGVWZ5yM2JtNPgaPXhANmjoyzCB7LQJPkk",
  "node_legacy/ipfs/node_modules/semver/ranges/min-satisfying.js":
    "QmeNtpvdfFtxkd73VCH4qaLwzLTdREPXQs49FZoFZz6CXW",
  "node_legacy/ipfs/node_modules/semver/ranges/min-version.js":
    "QmUzp6Y4ccFZCz52ms7puCLWbzXvLbLv7cy9kxSwccqvtZ",
  "node_legacy/ipfs/node_modules/semver/ranges/outside.js":
    "QmRNTrLG5WdN4b4SroTSAbNEpBoGV8ZLkLtP1BEyFAMqmY",
  "node_legacy/ipfs/node_modules/semver/ranges/simplify.js":
    "QmNqHm7mAiKNwx35w2gCtojtYBDkhTC8Fzt3MKeSLzkQp2",
  "node_legacy/ipfs/node_modules/semver/ranges/subset.js":
    "QmVYbe9g3rfpHzsqdFXQwYdfPxhPqqwm4ukoYnWkRzLkhZ",
  "node_legacy/ipfs/node_modules/semver/ranges/to-comparators.js":
    "Qme7zP4Mr48ujjaJPH3RKC8bTm5fRkFnEL3FrXs2Bm2DXr",
  "node_legacy/ipfs/node_modules/semver/ranges/valid.js":
    "QmUdKKpekFWGhdkt3FesmCar3urtkgW2F4WcujPSEMKYKk",
  "node_legacy/ipfs/package.json":
    "QmaVwjR8x3Jj7L3XBX9dv91DUBtAeVtLjyu5M8zCzBoX3G",
  "node_legacy/ipfs/src/cli.js":
    "QmRSoqMRBkUeyPLUGmTWgpx6jCpBCPwzDXDFcpUfKN6kso",
  "node_legacy/ipfs/src/index.js":
    "QmdvJUvmZE54beuJozuHxUqVrRZ9D3LTrKnMv1uoeA76u2",
  "node_legacy/ipfs-message-port-client/CHANGELOG.md":
    "QmbHzj97YThEZEG4Wki5B3SP3faGLbF7im78U82fMf2o9o",
  "node_legacy/ipfs-message-port-client/README.md":
    "QmTQvQXKaWPSk1W4J6Ebohkk3Z7aBoxPDa28VWsPs1hbcf",
  "node_legacy/ipfs-message-port-client/dist/index.min.js":
    "Qmafe9mxRXaKs8AYq8PuSMz4YXebcKkGSBCLqrePoMuJwT",
  "node_legacy/ipfs-message-port-client/dist/src/block.d.ts":
    "QmVt74d56eTUzDj5Hgy1HdpYtQV9bpJtT1QMUE8E43Nei3",
  "node_legacy/ipfs-message-port-client/dist/src/block.d.ts.map":
    "QmPvz7CqN3RLhzbufMB8wK444BZCSkGvWq9AJK4ECHX93z",
  "node_legacy/ipfs-message-port-client/dist/src/client/error.d.ts":
    "QmdssZCqQLdsyc2CyDjpK7T1qrXVKgLsMieZgUsABVk861",
  "node_legacy/ipfs-message-port-client/dist/src/client/error.d.ts.map":
    "QmQewEQUzFyyVw8k9fAwaFPwvKkfV3fRLjLqY2M3iZ8yoJ",
  "node_legacy/ipfs-message-port-client/dist/src/client/query.d.ts":
    "QmPvUit71cE2hdCm6N4sRkEzbjjgRh6ed5LrqJk8wom1DD",
  "node_legacy/ipfs-message-port-client/dist/src/client/query.d.ts.map":
    "QmaEEUreywjiUq93qJDNT8HN72ALJSESTrwxaRtCdvDtBU",
  "node_legacy/ipfs-message-port-client/dist/src/client/service.d.ts":
    "QmfTyWfZudpdUnkZRYdgcABpmTb652rYEjAvGQGJaTNq44",
  "node_legacy/ipfs-message-port-client/dist/src/client/service.d.ts.map":
    "QmdNJQNA8G5qwQoPh9ey9bzUqw8pE7qV5zgbQqxC6WXjph",
  "node_legacy/ipfs-message-port-client/dist/src/client/transport.d.ts":
    "QmRNuxuKJi8ePyEFjykgmwt7oyvPhcnPQdj97kMYjT993Z",
  "node_legacy/ipfs-message-port-client/dist/src/client/transport.d.ts.map":
    "QmSnKrhz5dojaJkK19wAQQrySRTXoXx4wXMQvQVQmJcPet",
  "node_legacy/ipfs-message-port-client/dist/src/client.d.ts":
    "Qmey6tX1Zi1C1aJ1bqL4UNowTpCmswABTCbRZjGtgzqc36",
  "node_legacy/ipfs-message-port-client/dist/src/client.d.ts.map":
    "QmYUyubPoTDrazxwtPRFnYGWq2SMoFLYmX1nbgZDmteipP",
  "node_legacy/ipfs-message-port-client/dist/src/core.d.ts":
    "QmccPy1Bm4VukW2BmPLZ9xmwccTo9BnT1ti2TQPRYDaazJ",
  "node_legacy/ipfs-message-port-client/dist/src/core.d.ts.map":
    "QmRAVrwJ6gt5eHfHPPJ8KaPEHojZCZ3kHqMctxjF4P1wjj",
  "node_legacy/ipfs-message-port-client/dist/src/dag.d.ts":
    "Qma5p9dR95ct3hhDEJB6A8q9NTTGYd9vjzwpf4iWYnq5Hx",
  "node_legacy/ipfs-message-port-client/dist/src/dag.d.ts.map":
    "QmZo4hzo424dXHx11L3625TT72CQiTYGJVF7HaqnPsSB7c",
  "node_legacy/ipfs-message-port-client/dist/src/files.d.ts":
    "QmQ3xYDLmQMZDeUHpouUAFE1WitssvteKgt9QUyus5rV2p",
  "node_legacy/ipfs-message-port-client/dist/src/files.d.ts.map":
    "QmW6SQBewAS4J7d1ReDwMtrD57mDuF93oBAsWrUUwcZEzW",
  "node_legacy/ipfs-message-port-client/dist/src/index.d.ts":
    "QmYUDye3KLNfMK7vSuvHHpvTYKzKNf9oWbveW8rM5YyUkr",
  "node_legacy/ipfs-message-port-client/dist/src/index.d.ts.map":
    "QmQJrfPuGGSYoTVsa1b3pqtFoNdBZbxFKr24oj2y4w7ors",
  "node_legacy/ipfs-message-port-client/dist/src/interface.d.ts":
    "QmbiL6NibHU72iuGgow7HVwMcZniiHBg1A7yP9e2YvwDRT",
  "node_legacy/ipfs-message-port-client/dist/src/interface.d.ts.map":
    "QmU9hRnTB1QEZQALwteoEZLTxhtSKThouZJPxyLke3BHdL",
  "node_legacy/ipfs-message-port-client/dist/tsconfig.tsbuildinfo":
    "QmbCy1WbUnddDkpiM8Deh19h9JFP2ejkrZ4TQPHErJAbgM",
  "node_legacy/ipfs-message-port-client/package.json":
    "QmVXhgNs2u1wuxewRi7M2RyCyhRdLfdPgu469GKxTvi6sC",
  "node_legacy/ipfs-message-port-client/src/block.js":
    "QmP2JzzDqhjW8jESuRSuG4Si15AtT1c4jrWKb3hpYMfbXx",
  "node_legacy/ipfs-message-port-client/src/client/error.js":
    "QmaATcHDww5PX95Bu1eG5oMCsMosX7YSpCPk4wV8dg5EYE",
  "node_legacy/ipfs-message-port-client/src/client/query.js":
    "QmTpyK4YjhMEEJHMWiUFsjWS1tEtnBSqCyC59YhXaBBCjP",
  "node_legacy/ipfs-message-port-client/src/client/service.js":
    "QmZ8ZxL2gjEfBkiAyFRhioN1LnaCcz9mSp2yjdmtatUfQL",
  "node_legacy/ipfs-message-port-client/src/client/transport.js":
    "QmUZ32NHeiVNPG8PucNv6jP9kTMcvH3kHVxakaMk7xrVaj",
  "node_legacy/ipfs-message-port-client/src/client.js":
    "QmS1qMcTmr7KNtrYxbyoPxkKMiF1i5RtGS2r1mNiiPU7Xb",
  "node_legacy/ipfs-message-port-client/src/core.js":
    "Qmaev7Ug41FGDs3PXhkNnLAAmGqvk3KrCn1URtHFQnAkrx",
  "node_legacy/ipfs-message-port-client/src/dag.js":
    "QmVtPUfymB171teNH9KE1MxQbgb4m1YwqccTSo69wikCVv",
  "node_legacy/ipfs-message-port-client/src/files.js":
    "QmPRJxJN7pDhqWWmECFqNchjDJWP15KvPXKZdCrTJ81jeq",
  "node_legacy/ipfs-message-port-client/src/index.js":
    "QmVvazEJWAuKcVtPcsfXahWybrvnHNaU39TbNycaLs8DDB",
  "node_legacy/ipfs-message-port-client/src/interface.ts":
    "Qmdm6SvYvpnCFH6m3nMnvq1UxbBMJqxJzJtUag6dCUVFMq",
  "node_legacy/ipfs-message-port-protocol/CHANGELOG.md":
    "QmP7xWa7rTtfCzvhZcnQGag7deHDxhS84UevSBqqXVs1fd",
  "node_legacy/ipfs-message-port-protocol/README.md":
    "QmTmxXmRU3VFGBM4cQUBdvSyDuxKhZvMx52Kowq4hcP83y",
  "node_legacy/ipfs-message-port-protocol/dist/index.min.js":
    "QmXu8xAV9M9mz4uTxBFbSQo7NwYXMrLfGJShzBreDoXn3k",
  "node_legacy/ipfs-message-port-protocol/dist/src/block.d.ts":
    "QmSVenf1M3upECV3F1BT7ifuebfhLubNuofAR82VudnBj2",
  "node_legacy/ipfs-message-port-protocol/dist/src/block.d.ts.map":
    "Qme7wUPuJgWdjrjy2p6j3oEVmzn7ZUmz9CtNmEjdEW9AFt",
  "node_legacy/ipfs-message-port-protocol/dist/src/cid.d.ts":
    "QmbimqEjFfTqGAb4fnQ7emnixeYCqT2zDSVvY9XtvwdSLD",
  "node_legacy/ipfs-message-port-protocol/dist/src/cid.d.ts.map":
    "QmWGsjSLL6kHhghXbeB9ymTBbabb7dZRLkNqtpYCSyxdwD",
  "node_legacy/ipfs-message-port-protocol/dist/src/core.d.ts":
    "QmdqG3uDx4pGK1wGrFtfasPM8kG5acoech7qkPtW5iBjUU",
  "node_legacy/ipfs-message-port-protocol/dist/src/core.d.ts.map":
    "QmdsiTaqTXndRQATkLSovCxCNvtzoTALLfDzxRVYvpcQiQ",
  "node_legacy/ipfs-message-port-protocol/dist/src/dag.d.ts":
    "QmRUMUDBK4B3R6sVojitKRt2abJtmwryDUS9NegStjmVpx",
  "node_legacy/ipfs-message-port-protocol/dist/src/dag.d.ts.map":
    "Qma8ZsmVDeepnwKgra89zRgK1Cu7iKcQLNXpjCx4BL9wXC",
  "node_legacy/ipfs-message-port-protocol/dist/src/data.d.ts":
    "QmTdgy2AZsMVE5khtEHqZcrPzUcU5BatNgwPi3AWsQVxCJ",
  "node_legacy/ipfs-message-port-protocol/dist/src/data.d.ts.map":
    "QmeFr1wqj9eFNttfysqqrdJidnuAh2HpS7xVPjcuWhJMLj",
  "node_legacy/ipfs-message-port-protocol/dist/src/error.d.ts":
    "QmSEERnqGWEsMr3jnsFMRUHVY3qcPrfGmjuMhWNoEqdrPb",
  "node_legacy/ipfs-message-port-protocol/dist/src/error.d.ts.map":
    "QmNMoPQc1RGQ3DMSFHKRQLMTuUDbzgaH1LoaDdAKf9XgfL",
  "node_legacy/ipfs-message-port-protocol/dist/src/index.d.ts":
    "QmNRKuQHKK9z4bVdRy3vemtviyzAtzAiL52PnoNdhDg9gk",
  "node_legacy/ipfs-message-port-protocol/dist/src/index.d.ts.map":
    "Qme8AciEXCfQy8eZhwMhpFcCdE7cH12URucWDFHGEHPHRP",
  "node_legacy/ipfs-message-port-protocol/dist/src/rpc.d.ts":
    "QmeJiftgYf5iSf7jVLCCKrNuBsfsx14FNWugHcm2quCjED",
  "node_legacy/ipfs-message-port-protocol/dist/src/rpc.d.ts.map":
    "Qmdm1zVmD4w4KEPp7hYLYS5ZnaSm2VzMWXege7DsA4tevp",
  "node_legacy/ipfs-message-port-protocol/dist/tsconfig.tsbuildinfo":
    "QmeN2WPDixMMxQLjkSoUN6j4U5fpna7fKQXBZF7EmbBX2k",
  "node_legacy/ipfs-message-port-protocol/package.json":
    "QmXxfqU3s8979NJrV4oroGn3rPoHzXqKUGEVQvYFrJWA3h",
  "node_legacy/ipfs-message-port-protocol/src/block.js":
    "QmPmmDAXB758s1ARWKffcQaxk4B47zPY9YEH2RzqLSVbVe",
  "node_legacy/ipfs-message-port-protocol/src/cid.js":
    "Qmese1XU8n6sjYQjWxgYb5oC2fDXTNneUUfSay41H6J4DQ",
  "node_legacy/ipfs-message-port-protocol/src/core.js":
    "QmX6zzXJJqS7BXiUUdufYhMc6rbeQ6TUy5QHFHr9GdpJwk",
  "node_legacy/ipfs-message-port-protocol/src/dag.js":
    "QmUq3ueh72oVr9gKZqMrLgVEHyiVYWWquCp89iQoyFVkVr",
  "node_legacy/ipfs-message-port-protocol/src/data.ts":
    "QmS3DySRey4HkfYgJcXgUQ3EUDKc4LdjLrSZhuqj1rTTDp",
  "node_legacy/ipfs-message-port-protocol/src/error.js":
    "QmTmEF1Zug2xa6BagRpSqxMXK9NrtQPatYSG1YAxqLWmQK",
  "node_legacy/ipfs-message-port-protocol/src/index.js":
    "QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH",
  "node_legacy/ipfs-message-port-protocol/src/rpc.ts":
    "Qmez23fBYWB3df5ByWTdkUUZrKXywzPFsYjdf4UdVgSCUd",
  "node_legacy/ipfs-message-port-server/CHANGELOG.md":
    "QmUb6EPE1AfrdmpqEJHADspfqS1hSSqTs59MzFb1GGtAPt",
  "node_legacy/ipfs-message-port-server/README.md":
    "QmVRMYbkAp5HqcPvWdrtQZ9h14w5BgzgsN7VzBxfgYW94E",
  "node_legacy/ipfs-message-port-server/dist/index.min.js":
    "QmQnP9m71YVty4Wr1VL8tCAv3P6v9cG7gaA1cGk4W7JxMZ",
  "node_legacy/ipfs-message-port-server/dist/src/block.d.ts":
    "QmcLa4WbBgVEXFiraNB12vvF8kKm5cmiLzKhyQRTUR9gx9",
  "node_legacy/ipfs-message-port-server/dist/src/block.d.ts.map":
    "QmZ9oZiRczq8L6oqciu4JumTz6ftBy89oQF6ZLwkcK1kp4",
  "node_legacy/ipfs-message-port-server/dist/src/core.d.ts":
    "QmbtCXG6EAyaaFdqDdtWqkxdZnguK1ZftjnHxNMFVqqRPm",
  "node_legacy/ipfs-message-port-server/dist/src/core.d.ts.map":
    "QmRxjN11sya71haCMM2UUztJFr2ZdVhTDzjR8SobhKLVdA",
  "node_legacy/ipfs-message-port-server/dist/src/dag.d.ts":
    "QmeKPpPYfj6Ce4ps79MtUfEUZsLPQ3hSJzVCbS3vJyVWGA",
  "node_legacy/ipfs-message-port-server/dist/src/dag.d.ts.map":
    "QmZmFCNRErT8E6E2XSmwWj6HT1NnSY8iA93W6n1p6mmxyh",
  "node_legacy/ipfs-message-port-server/dist/src/files.d.ts":
    "QmRSSkUZ6UtnRSsuCmCwoUsoL2sGAQh36s3RQBCZk33SQ8",
  "node_legacy/ipfs-message-port-server/dist/src/files.d.ts.map":
    "QmcHWcyi2fLfqqzDNanASJ657S9kVZAFiCEAyMz8rzoUKR",
  "node_legacy/ipfs-message-port-server/dist/src/index.d.ts":
    "QmUBBjnhLn3zgaX9XS6XXEnmSXA6aJRMhQWKDFRcxUHqo7",
  "node_legacy/ipfs-message-port-server/dist/src/index.d.ts.map":
    "Qme8AciEXCfQy8eZhwMhpFcCdE7cH12URucWDFHGEHPHRP",
  "node_legacy/ipfs-message-port-server/dist/src/ipfs.d.ts":
    "QmR7cB6sHzPUUwFQfZc51f9S7dLrNv11wcZfhRgMW3XgYF",
  "node_legacy/ipfs-message-port-server/dist/src/ipfs.d.ts.map":
    "QmZVgFECqULeWjwuu332CgHC4DN1xj71Hoq31xXkveNKkT",
  "node_legacy/ipfs-message-port-server/dist/src/server.d.ts":
    "Qmce3uPgWoxmvHirbg4uf8w1is9HeK5VYgFcMTv24fqSgp",
  "node_legacy/ipfs-message-port-server/dist/src/server.d.ts.map":
    "QmQbVgoCyef9VusSrBCG1m6mbbsVbDwVWPiriyfdi3Hbh6",
  "node_legacy/ipfs-message-port-server/dist/src/service.d.ts":
    "QmSkwRVtdgtKqB3gZw8ZFTPBGbC4aT7dfGD9yk25nqGPTG",
  "node_legacy/ipfs-message-port-server/dist/src/service.d.ts.map":
    "QmZNt3LU7HXu5CrvEByPxiQJdm9yv6SfhSHeEzPKSr4tvT",
  "node_legacy/ipfs-message-port-server/dist/tsconfig.tsbuildinfo":
    "QmPrSE7a29CkHY7XGege1yv2ouDGE5P4jYkDG6ke8KSfKV",
  "node_legacy/ipfs-message-port-server/package.json":
    "QmesLEDq9JrCY78TBekbmeCxB4vgAhC1CAQzo87XoJe1GW",
  "node_legacy/ipfs-message-port-server/src/block.js":
    "QmdvQDazwMrzhC9wg8XtBU5djALdejVXy7MmHBb7cfMiai",
  "node_legacy/ipfs-message-port-server/src/core.js":
    "QmQoju6R8A1LmiqYLNkAbsDPuAmYiNjDgUzbFETqTKYpbo",
  "node_legacy/ipfs-message-port-server/src/dag.js":
    "QmdbbkdTdV8yMQfJszDexEyYCtnVWjEfJUeHC3AZhZYKw8",
  "node_legacy/ipfs-message-port-server/src/files.js":
    "QmY1HZAFj8Ds5HjcP9neF36tieF7krZFiiHPJ4AqX2GPNS",
  "node_legacy/ipfs-message-port-server/src/index.js":
    "QmT7qMsy1ZkwMjtAzS3YntD4mmrCxRAcEedZqGbUR7HH7c",
  "node_legacy/ipfs-message-port-server/src/ipfs.ts":
    "QmcBdwFFhnCjn6QCYByqYjfg2KtZEkazysfYCmtHS97bao",
  "node_legacy/ipfs-message-port-server/src/server.js":
    "QmS892z6Pta4c6BFkNvijtJtneCpfVNyqxrjGvAFbCNqGW",
  "node_legacy/ipfs-message-port-server/src/service.js":
    "QmbbwNuvEyzN2kADS1Dm5nT9FvLPmkKbKnJjevCVGdHxAH",
  "node_legacy/monaco-editor/min/vs/base/browser/ui/codicons/codicon/codicon.ttf":
    "QmSZoSuoxtUCZTbioWHcgYFer5h95B5aCsnmZKTKfGBi77",
  "node_legacy/monaco-editor/min/vs/base/worker/workerMain.js":
    "Qmf3qcRcE2herHvxoJxmpt9pTQEYFKNgGAV7FTRjYmSt7g",
  "node_legacy/monaco-editor/min/vs/basic-languages/abap/abap.js":
    "QmQadeJmRHXKA2232bheb9SxKqPyXY7oPa4E3et5buMTcP",
  "node_legacy/monaco-editor/min/vs/basic-languages/apex/apex.js":
    "QmdTSqNjLTmADzU43tSBXwSHdogSThZarMkY7WWyVQWJm2",
  "node_legacy/monaco-editor/min/vs/basic-languages/azcli/azcli.js":
    "QmexFPQnTzqbQ8JtsDNCzs4fj1G4ch8DLy6aoxWkDp18p1",
  "node_legacy/monaco-editor/min/vs/basic-languages/bat/bat.js":
    "QmRrBd8emiRwE5HwDAFDWn5kKL35nmiDEYL7bpKEtuWAne",
  "node_legacy/monaco-editor/min/vs/basic-languages/cameligo/cameligo.js":
    "QmddTpj6zzJsnRZYtYPNeT7RWU5MHKaxamHBp5V4u3pqen",
  "node_legacy/monaco-editor/min/vs/basic-languages/clojure/clojure.js":
    "QmZdWQ2FHLuFf4VUQpkxSL67vMe7TDQEBcPXS9VoTER7WP",
  "node_legacy/monaco-editor/min/vs/basic-languages/coffee/coffee.js":
    "QmavgCnQgBtsgVqkxzStEN8dpNTg9Z6w9Do4uvTLxxTHcc",
  "node_legacy/monaco-editor/min/vs/basic-languages/cpp/cpp.js":
    "QmU3BGe6JR7krSiVvjjr7DC8Uhosoj97ePzRn5Z5GFq7gk",
  "node_legacy/monaco-editor/min/vs/basic-languages/csharp/csharp.js":
    "QmQ6LLCyteSfTY6KnTy6fnWbV8LutMfEBRArb3FockGJ7T",
  "node_legacy/monaco-editor/min/vs/basic-languages/csp/csp.js":
    "QmZfWP8nUbqcbuRo4cALc1868WRtHsg3Hu8jGcHtpFug6K",
  "node_legacy/monaco-editor/min/vs/basic-languages/css/css.js":
    "QmdEwNFFEC7rNgjWF8pvXiiyV2n8i7jbwoARmFWGaN8p1q",
  "node_legacy/monaco-editor/min/vs/basic-languages/dart/dart.js":
    "QmcjX1xh9MX5GrT1YcGBU1jmcJFaELyKqfLQzbGE1jWSC9",
  "node_legacy/monaco-editor/min/vs/basic-languages/dockerfile/dockerfile.js":
    "QmaUQuPueApnZpStjpab42bhpqyH2qfwyAEgha89LQ5412",
  "node_legacy/monaco-editor/min/vs/basic-languages/ecl/ecl.js":
    "QmcnMijWQc3o9H72ic3sCQDvgHqeMQduiEysos8oDniJva",
  "node_legacy/monaco-editor/min/vs/basic-languages/fsharp/fsharp.js":
    "QmYDGW5aQGDD6urL1oFdQZerBYZkk53bM58YjK4CjPDCbo",
  "node_legacy/monaco-editor/min/vs/basic-languages/go/go.js":
    "QmQK4GKHoAiNcuY8QCS5uJExNp1tXn2JRvEeFXTmxJTMhB",
  "node_legacy/monaco-editor/min/vs/basic-languages/graphql/graphql.js":
    "QmRrG6hE5a98vJPQEbBQ5o5VyC28RroqybAMGoYsLewWCy",
  "node_legacy/monaco-editor/min/vs/basic-languages/handlebars/handlebars.js":
    "QmP8FYb1oizpyU2wHnpQE9tjn7YMYb67L6sNj1WKnnq85B",
  "node_legacy/monaco-editor/min/vs/basic-languages/hcl/hcl.js":
    "QmWPEftgke8ktiXTNNu4pPeQrmdYnUtgYJ15CU8ERvKb7P",
  "node_legacy/monaco-editor/min/vs/basic-languages/html/html.js":
    "QmVAT4KarhmTCmdZnPzT9ya6RgmNPWF6SmPtmD95d6uWbf",
  "node_legacy/monaco-editor/min/vs/basic-languages/ini/ini.js":
    "QmaKiDBK1J46vhgV74duPtPkGopdRhz3aqEf7TabprTdUM",
  "node_legacy/monaco-editor/min/vs/basic-languages/java/java.js":
    "QmfWroFaWrWVEi1uj3McTxdeYJeLQ4Heq7zFk1CMirKwxF",
  "node_legacy/monaco-editor/min/vs/basic-languages/javascript/javascript.js":
    "QmcKySaP74S5rvFXpLrUZpqR7SfTDPK38Bc8LZ3jdhRTv5",
  "node_legacy/monaco-editor/min/vs/basic-languages/julia/julia.js":
    "QmStjB7Fa811FvZKhdbPE9uYv679mpdAWW8GaSEeHPeXGj",
  "node_legacy/monaco-editor/min/vs/basic-languages/kotlin/kotlin.js":
    "QmPXsLsD2whgKyZ6qDSBruJkug8Uzzwg64YaYnjpREqxiP",
  "node_legacy/monaco-editor/min/vs/basic-languages/less/less.js":
    "QmWCNr9UbUPeyURrb1xrumd6MyRkPPc8HUQaNSqoPRxbwV",
  "node_legacy/monaco-editor/min/vs/basic-languages/lexon/lexon.js":
    "QmdWNiMh3tAGRrScRXQqrHev6BUVFcxootVTUMCnmBT1rQ",
  "node_legacy/monaco-editor/min/vs/basic-languages/lua/lua.js":
    "QmW1k1uAPTX4PZHQqHXZEct6eWBWJ1xvCL7ukkSKWKKwn8",
  "node_legacy/monaco-editor/min/vs/basic-languages/m3/m3.js":
    "QmQQmJaUmhQGmYV727NujtHmVAcPLW8NQ8F6y3r3TkbSvD",
  "node_legacy/monaco-editor/min/vs/basic-languages/markdown/markdown.js":
    "QmTCuzDbZ7u7KWXCvTnrd5rftEBZj5DS7XUKXNAHGPQsR1",
  "node_legacy/monaco-editor/min/vs/basic-languages/mips/mips.js":
    "Qma8UddL8aeBuVp3VAuN6qMjPbnqzoJ4rEXpiFTsNCKcsu",
  "node_legacy/monaco-editor/min/vs/basic-languages/msdax/msdax.js":
    "QmUdtzrNwznGLoANE2xsxwJ2SjMdSC7fEUB4EafBNmvFXA",
  "node_legacy/monaco-editor/min/vs/basic-languages/mysql/mysql.js":
    "QmQK5z6zXjBtsKYKAZX4kyVg7FbeTXgqqoyb7e5b817qph",
  "node_legacy/monaco-editor/min/vs/basic-languages/objective-c/objective-c.js":
    "Qmbmn6RZwiSZzAFvk9JYFg5xKjezRpNcVnbcHU1PkySydm",
  "node_legacy/monaco-editor/min/vs/basic-languages/pascal/pascal.js":
    "QmcuaxaiyTixwbX2fzeYDQFUd8faS7cJDfMdoHu4o46e3A",
  "node_legacy/monaco-editor/min/vs/basic-languages/pascaligo/pascaligo.js":
    "QmZipZBSoS6vrd8TttERitN1YxGby4Y56B5QMJFwNPyUTu",
  "node_legacy/monaco-editor/min/vs/basic-languages/perl/perl.js":
    "QmXDzZ4q3H8D2mJpUVE9bBv19mM6A7Yau6abWxPfXBRKat",
  "node_legacy/monaco-editor/min/vs/basic-languages/pgsql/pgsql.js":
    "QmZBXE2Z5mDz4HVQHXFYhv2Csx1eaTLmudNpbfBEKc46mt",
  "node_legacy/monaco-editor/min/vs/basic-languages/php/php.js":
    "QmTYz8PBPssQLkWSGVPMFbdGG1CeguT4U6fXLwrhJuhQdJ",
  "node_legacy/monaco-editor/min/vs/basic-languages/postiats/postiats.js":
    "QmQbCsmkNT2VVfJfa3rs4KQG4VSpngmQ39JsmXsHt4RyoJ",
  "node_legacy/monaco-editor/min/vs/basic-languages/powerquery/powerquery.js":
    "QmNtvLt5ZeKk5tvhDaNzCNcLYwNAvcn5EjG3gRrZdyWhze",
  "node_legacy/monaco-editor/min/vs/basic-languages/powershell/powershell.js":
    "QmZWWD9vaEo2svv7n96ygqBepNoU4MnH2CMHEYcDdf5VaR",
  "node_legacy/monaco-editor/min/vs/basic-languages/pug/pug.js":
    "QmbtS2jdkj5mrqNGW5Gr4SmyVgQDof3FQYhXDxvtAXy9hA",
  "node_legacy/monaco-editor/min/vs/basic-languages/python/python.js":
    "QmW8qv4RrV839ygUXXhS9YtWr3NZJxuQQC52iKW6DkT27j",
  "node_legacy/monaco-editor/min/vs/basic-languages/r/r.js":
    "QmbFiUj8NmzZjWYPj6Hn72pzF6SRPZpHAZYuyv37K2Ye3w",
  "node_legacy/monaco-editor/min/vs/basic-languages/razor/razor.js":
    "QmZFme9wrTL9AneHdRpUXPdiDnR8Khi6mZXF1s5byPU9je",
  "node_legacy/monaco-editor/min/vs/basic-languages/redis/redis.js":
    "QmRtfCUu23on3DvG7JnawRcAJQEH22DdJa5ENPeTZ7ZYhn",
  "node_legacy/monaco-editor/min/vs/basic-languages/redshift/redshift.js":
    "QmZ8fSUxQWpLMSegrMyYVAwBmWJkHqyyyy1GGDketarEa7",
  "node_legacy/monaco-editor/min/vs/basic-languages/restructuredtext/restructuredtext.js":
    "QmRK1epSWkyWUptXsRerQvrwkKzZz5xRCLxarMQeH2TbUN",
  "node_legacy/monaco-editor/min/vs/basic-languages/ruby/ruby.js":
    "QmcgkF7pc2JKy26H61ifoXePcNn8qLvSHkqVHbHGu8NZ4b",
  "node_legacy/monaco-editor/min/vs/basic-languages/rust/rust.js":
    "QmcAe36RuKN9doiiULLpLT2j1MxwSERQaW9hTmvSPNrW7y",
  "node_legacy/monaco-editor/min/vs/basic-languages/sb/sb.js":
    "QmeLjs76FTCiasjBfKUJeSCmR8CUX4SPdTKncSzrGbhv2e",
  "node_legacy/monaco-editor/min/vs/basic-languages/scala/scala.js":
    "Qmb97P75otZbNVEANAPyfUFi7VHPd51ceKLqcG1Ypjw3oY",
  "node_legacy/monaco-editor/min/vs/basic-languages/scheme/scheme.js":
    "QmPGWbVAA6PprdR4rcBVkNfanmdiLBb8BwhvYssPKR3YQ7",
  "node_legacy/monaco-editor/min/vs/basic-languages/scss/scss.js":
    "QmU3Js2pcoD9RnsboarLNwhqu7PDcy4a99zQYCqYPWMKrd",
  "node_legacy/monaco-editor/min/vs/basic-languages/shell/shell.js":
    "QmU8V9oVSr6xbkef43R2LqsWAXjktSaYgRcapmVUREfVQ2",
  "node_legacy/monaco-editor/min/vs/basic-languages/solidity/solidity.js":
    "QmNjagxH1gGzB8HzdEi4zmq4LfexW1kr78oAGNf577TEPM",
  "node_legacy/monaco-editor/min/vs/basic-languages/sophia/sophia.js":
    "QmVc12FM86QnpRboDPvKbmzc1K16uEw8sC7zMSUzg8fR7o",
  "node_legacy/monaco-editor/min/vs/basic-languages/sql/sql.js":
    "QmfTfjdtz44h38LCaDHoFf5Y1PbMXkaoZScfKDum18NJua",
  "node_legacy/monaco-editor/min/vs/basic-languages/st/st.js":
    "QmdnEQT15Q9VJzCCFq5EeGK6hqNBUJWzGGBioTce6VeaEr",
  "node_legacy/monaco-editor/min/vs/basic-languages/swift/swift.js":
    "QmW2sYnHcjUBDU1HobyKL33XKeK33Vq6TUv24LCmmJs3Fb",
  "node_legacy/monaco-editor/min/vs/basic-languages/systemverilog/systemverilog.js":
    "QmSQKczUYZHPztbdtSorWbShKkmh4V717tZJ8PR4KZay6Z",
  "node_legacy/monaco-editor/min/vs/basic-languages/tcl/tcl.js":
    "Qmegd5jMqH7PiVgGqVdR1sF3sU6jp9aQrqtGSDEoePNyZZ",
  "node_legacy/monaco-editor/min/vs/basic-languages/twig/twig.js":
    "QmRPpHoskpuPrs2M6NszL2frdL63HGt7Q19WYyunoVUW82",
  "node_legacy/monaco-editor/min/vs/basic-languages/typescript/typescript.js":
    "QmXuqf5k2auC8Ct3YY1eKExr4oRombhGjjPzet5LtKzVXS",
  "node_legacy/monaco-editor/min/vs/basic-languages/vb/vb.js":
    "QmaYNvE8koZozz7KNhKsVfNFimQXhWJjr21MXNZEyVjnSL",
  "node_legacy/monaco-editor/min/vs/basic-languages/xml/xml.js":
    "QmbwsibJBeqj5n8XrSYrJJ485ShETXp97bAzXJ6dfSv3ts",
  "node_legacy/monaco-editor/min/vs/basic-languages/yaml/yaml.js":
    "QmXcQGoymhqkBUNu6XmsxtJKFB4LJTa1ZPorTbTMdyj6bU",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.css":
    "QmSzdWPzQYqaY5N9veiSL1CBSyV4t2xRP7ubrCUdrozSQY",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.js":
    "QmQEEA6HH4ojKWkYp7RPbBvaJQrqcwDEMZBMznMKns8tgv",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.de.js":
    "QmNSUWkix74QCdcx6wFyENb77Dmox6hFHnagCaGwoZELk3",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.es.js":
    "QmWXAzg3j1QF1hRL3fbrtJEDZrip9EQKZ1UBRvfPKz8Dz2",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.fr.js":
    "Qmd3o6sH6bmgG2ccEfwGBQvfGNP9nrtLAiDKQkuSvEexAQ",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.it.js":
    "QmRc8LK7FEB8zx9iNDZdkmp9amsnb9bE3cBb3xzGzw69yv",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.ja.js":
    "QmbVaALbTe8LuBb8TNsHbMvFDYSfTbqY6J25BJkHKmEmMy",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.js":
    "QmW6z4arCb94XieRvgGKLoRQTfpiU9c7twCna1iGKfCJQr",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.ko.js":
    "QmQaZBTvR9u45Uhtc4bkrqMHa6UJGGnRpq3V8YTkeex5Gb",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.ru.js":
    "QmRVeMceeQhe9eG27jWG2VrG77czs9WP5Lo31iAwvZtbSN",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.zh-cn.js":
    "QmSEs1Wt2Zewr5a1gPqeT2Ai4sicJkXYv7gxK5Uxz2r1Te",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.zh-tw.js":
    "QmZruSnR2vB67h8zfLH657353cVjLBzrYKmvcxzuHbvbWc",
  "node_legacy/monaco-editor/min/vs/language/css/cssMode.js":
    "QmexiZdpLjrhWcSRv9hqG11J9RcNzKq3KCEWjQzwuXMGnY",
  "node_legacy/monaco-editor/min/vs/language/css/cssWorker.js":
    "QmeuVXbBie3Jx39JX9Jhs2AapjCg9cm46zRSBxn28dFMdq",
  "node_legacy/monaco-editor/min/vs/language/html/htmlMode.js":
    "QmaZxEicUqX6UA9rofzFiKUifZ5VgxZmJKs7tCEZX2jMwM",
  "node_legacy/monaco-editor/min/vs/language/html/htmlWorker.js":
    "QmRoc9Nwoi4Ee5YGctmqYj3w894jqZzzz7d1k7R6edmZNr",
  "node_legacy/monaco-editor/min/vs/language/json/jsonMode.js":
    "QmZFdmAuVpg36P5TTZdnMwwciGH4pw8ZhyQXaRntg4eKBf",
  "node_legacy/monaco-editor/min/vs/language/json/jsonWorker.js":
    "QmakoMUhhPDtFACJkrDQqGmAp73CBV7qfLBB1dkW4DoF69",
  "node_legacy/monaco-editor/min/vs/language/typescript/tsMode.js":
    "QmbqBNP3zjTDdBoJb4RLe4hLWM1XLZ7hbrw9ncjro2jLB6",
  "node_legacy/monaco-editor/min/vs/language/typescript/tsWorker.js":
    "Qme5CG16onxJQaf6U6CA1JRsutXvLEeSDJvLm5SaaK8XS8",
  "node_legacy/monaco-editor/min/vs/loader.js":
    "QmVUDYpMtYpoqXLD4QvfhDZqdALegmvxdhHH7KmzBsB6U2",
  "node_legacy/monaco-editor/min-maps/vs/base/worker/workerMain.js.map":
    "QmWFqQ5tsRuddVT9vHJ5HXAh8jf2Unzbaoc73MYDphBchZ",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.js.map":
    "QmfNwpurWca6iPkqGgUTpeuLo13bqZmQ6L8UpGDoXMbkc7",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.de.js.map":
    "QmcRhL734QupfBSvymYxEvTwJQuuyfGpSP1xttYp6eWcD8",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.es.js.map":
    "QmdUnLHk3U4aU6SZrABcAiCdNS3mnLhQkFqWes57cyHGsb",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.fr.js.map":
    "QmYVbsiHX3pp8rWJd4fXLdeVtH3NcNn1Stw6BCWaLxFu2G",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.it.js.map":
    "QmXxFvGMG6u1dFLG5SgS9cNdLiZmiCHk9BRCtyF2sVzVFW",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.ja.js.map":
    "Qma3efZBuwXqRhS1bKkWexwjdT31Eq3MyVsD2dRgVCrWEq",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.js.map":
    "QmQv9Fex1ZzmcJudivSxTdJHCCzbKo2q8WJK9TBdqbEDs2",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.ko.js.map":
    "QmPTbF8AgvKxyXx17fusKr3NoUFu7idqb1nYjiq4JZTyrD",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.ru.js.map":
    "QmbtZGY57RWdPVsY3joEXJS6tYArcSqArvg7RBUNUwoUD8",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.zh-cn.js.map":
    "QmTbycJ5dsuDshTWyQyUv8daQEYEZqu3YWqPdufX2RQ9uh",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.zh-tw.js.map":
    "QmNsPRBmQ744opmqWYzfqeHbcY2bfMwV7xLnXu3F67H1Uh",
  "node_legacy/monaco-editor/min-maps/vs/loader.js.map":
    "QmaMbR3XpK6d3Aaq2vAcBEyntWRTrPZJzc2AZaFPPEPvT6",
  "node_legacy/monaco-editor/monaco.d.ts":
    "Qmb4L21DED7KgAoXB7PfCXvkV4JTWQN4ehwpkdf6JNv8Uo",
  "node_legacy/monaco-editor/package.json":
    "QmZcryZqRY2N7kTaE3fQuEuPirbWDCvMeBVzV5QRdP28u4",
  "node_legacy/parser-babel.mjs":
    "QmNZakKRLQBUJSY8XvTCnCJoU3vWGCYEiCkFDV3WuZmtJZ",
  "node_legacy/parser-html.mjs":
    "QmNQPbdnaiQz91ZKa11kCAByJS1bjj39W1XZWranQ3dMYp",
  "node_legacy/simple-window-manager.es.js":
    "QmcvtuWHJa3nkqaBfFMriqZz3N15RDeGErhF26tjPThxgM",
  "node_legacy/standalone.mjs":
    "QmbkuH4RqHi2cUk3w7PMD9LDNaSkEaYA9Pcy9Wv6rTnwYk",
  "node_legacy/workbox-window.prod.mjs":
    "QmT29Y78zyhb8a7WWc2BEhS2XpZij6bJhJZnLnbKTKsE5m",
  "node_legacy/workbox-window.prod.mjs.map":
    "QmRTrYSzfnFKPQESDgH6t26Fb2AzZpn51PcCor3Rh9zomY",
  "package.json": "QmQ2eT5JPeQApGrVmehPy98neQh2QWZvkfW1QNEHtCXaKL",
  "src/codeLoader.js": "Qmes9BZyoxDBhxQjQMgGEsQ5Wu1TbYmYbiuZ7qhZb7MNCN",
  "src/data.js": "QmaQTFDx5Bg8P7cDm16knnxa6XZ8AG4uj9hzrkE1o4pagc",
  "src/db.js": "QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH",
  "src/emotion-react-renderer/dist/DraggableWindow.js":
    "Qmatqd4HAF76oyBRpW7tGEMt1rDW2TNijeNVhxZg8GwbTX",
  "src/emotion-react-renderer/dist/renderer.js":
    "QmZ3ALpiydQ75zpZH3xJS94NSJQP2vZ32K5zeCoCwDwC18",
  "src/emotion-react-renderer/package.json":
    "QmQ3pkjA9KBkBqHSNiZQzBypuo64a6JB9oYUZg23bRoQQ9",
  "src/emotion-react-renderer/src/DraggableWindow.tsx":
    "QmfXRFvz4dXzLdRYznK6isrynfqg8DvBViRfFEK8KnBSmH",
  "src/emotion-react-renderer/src/renderer.ts":
    "QmWSfHLfX7spZkr87PrHM3jpwMrbbzhB2PjLgFzYM5metv",
  "src/emotion-react-renderer/tsconfig.json":
    "QmVf1pkrppvUoQ7dmSQ5XH7WM1PY7SqAwxR3TR8pT2oGVA",
  "src/examples/starterNoFramerMotion.js":
    "QmWVABuMCi74dqH3AiGtWU1SEBzvmhiRCADWYCupQZYuAs",
  "src/examples/starter_framer.js":
    "QmaVBy5PCmFhEKZ7gMtLZUyAy8FBfgDnPeLm6HgCnrC6KF",
  "src/formatter.js": "QmWnFrxvNhB6vdhbn6HqP21eWHYfSj7fL3nFZytwyWnHZB",
  "src/hash.js": "QmdxcDb4VPHLam5GBfV4uo2yJggRoyvoG687hfqnJ3Dq9C",
  "src/importScript.d.ts": "QmV1V5Fb2ZxP5Kn31nSU7FS2TtrDMg6wR7sMTsKeeR1txL",
  "src/importScript.js": "QmWNzoXJSf9aHxMEbDGsdMfyfJKwtpfL1Q9ni1xuSF5c9X",
  "src/ipfsClient.js": "QmdFmHJLfm7QQEuLrgcMS8XTAQicsznbA8i5n7YB9eDSvB",
  "src/openWindows.js": "QmXKW898AhdfVcSgkc3Z5S5CrpxJNAinrpD2FLx9JtN5tr",
  "src/refs.d.ts": "QmV4VN2uGcNzHPQi51JkVC4p9RzDpe5sEk4sX4u9ub3J4p",
  "src/renderPreviewWindow.js":
    "QmRLs3SMWp9GMjBXMSY5NuAso9qdJ2tY5UBmLa4SKpybhu",
  "src/sendSignalToQrCode.js": "QmUZCYd79dcmX6bC62UFeaweyg2n7oZYfWbX4bm774ig4w",
  "src/shadb/dist/diff.d.ts": "QmXv6B78NKbJLMyErUn6XRUkXxvkata8i6CR5JCC721QJx",
  "src/shadb/dist/diff.js": "QmbfZsnJhysseRS92eSEc2SX7hBaaLPTojb7oqc6XaBqzy",
  "src/shadb/dist/diffChars.d.ts":
    "QmR9hNHu2ZNp9CopGNmME4KgNuyAzMZcZ1hUaZwnjXfkE4",
  "src/shadb/dist/diffChars.js":
    "QmNRK5ZC2ZEdMfrTozGkgGJdHiMWYbfk84Gi3kBD4rgMBQ",
  "src/shadb/dist/getDbObj.d.ts":
    "QmSN6JKpmgGd8mwb8gEKViV5juyt4jpw4e5wQqFpzGUiF2",
  "src/shadb/dist/getDbObj.js":
    "QmW2LmUqcg8fzLtjroo3JHbUUXDq16X9n3dBUE4WUVQzG3",
  "src/shadb/dist/sha256.d.ts":
    "QmQCcqJvRmWrgHXvwifwqPziL9UUNckyDZbPbLGb4SbS9k",
  "src/shadb/dist/sha256.js": "QmWZyJbdb4B22fLgpbDqNo6wU2sWccyecceKz6bor64hFi",
  "src/shadb/dist/shaDB.d.ts": "Qmb1jkMJhCGHnrFigsUkCNo1uwebGfrxXQH4EHSpnh6zFY",
  "src/shadb/dist/shaDB.js": "QmX5mSevBrVHk6mpp1VNaCMqmCYC7azWBUFgrzpHnG4NDp",
  "src/shadb/dist/vendor/diffChars.d.ts":
    "Qmf31P3dFhCyz9X8GkuUytpn3cmJwsggF4kPTbmwaiekRt",
  "src/shadb/dist/vendor/diffChars.js":
    "QmWraRefVQpUCBAgehPQ6s9UoSsijufs4ss85cfzC4UAzE",
  "src/shadb/dist/vendor/diffMin.d.ts":
    "QmUEzhNXqsRtc45fB5if9wchLEL1wgmY58wX27E5zUCJtp",
  "src/shadb/dist/vendor/diffMin.js":
    "QmSnfENK6NQjDwhyH98PASsLaGbwf7DQmzMuWFgZd2B8BT",
  "src/shadb/dist/vendor/idb.d.ts":
    "QmRDw3SijUK8mQZ2H5CzJtKk8zknGsCz4mz58EzsjEC738",
  "src/shadb/dist/vendor/idb.js":
    "QmcN5teqqpdPuRL4h3qgD5WCG5pvYicBeQtSyjf8m318yL",
  "src/shadb/package.json": "QmdJpmSF6xuL5xEY9fbK8TLoCNxwXmAsTZh64mpXmZbmsF",
  "src/shadb/src/diff.js": "Qmda6YhbwL9XYtLgmK3HGPpGw5zFcRox54cRKaJjNUMWAE",
  "src/shadb/src/diffChars.js":
    "QmWyRfBNH9Epu8Fg6qKghPCm41ht6xG54jZ6iANubmRv6d",
  "src/shadb/src/getDbObj.js": "QmWHmVpjUyjtseZDdvxbZNYiDx3MXTgmZhwBpqCP8CrEtb",
  "src/shadb/src/sha256.js": "QmUYHM48BTQuN4TFNHBH5dYaZ16FRNu2tbeF6JdHnBKc6g",
  "src/shadb/src/shaDB.js": "QmQ7TuHw5n1XZVwpfsxfMeWUHYqc35tEQx4ypbJw523GJV",
  "src/shadb/src/vendor/diffChars.js":
    "QmYouKSa5NHx5yL9smkrpzkCs6y3yQ1eabWrg6UiHReEXd",
  "src/shadb/src/vendor/diffMin.js":
    "QmRfja8k2HwGwJZPfGjjPGBxoKxpNu4vjsKGYPQUfrJQfA",
  "src/shadb/src/vendor/idb.js":
    "QmNp8FjMfXJzPbm3AuY3M3YX2nHeo76rkrDvh5nfvSUm7G",
  "src/shadb/tsconfig.json": "QmSweNRyD6aAUjpMnt8zKE5LAxvvLoZPy9Qj3r4THEhaUd",
  "src/shadb/tsconfig.tsbuildinfo":
    "QmUpLqjjT8y73roTZgP6iKFVBANwbYapwt5vfeCcyCNvWf",
  "src/share.js": "QmdfdnJU3rb4UT7pqAmQh56sgB2pMUryzikjNrwvQjB8xh",
  "src/smart-monaco-editor/LICENSE.md":
    "QmPm5DAe7QC3g23Dv3s2CSaEaBBJE3pAxQneLESWnyriFh",
  "src/smart-monaco-editor/README.md":
    "Qmc8vNQBVDXUdyMi671KuJG2YbmWxBDYBH7yReT19mbbpR",
  "src/smart-monaco-editor/dist/editor.d.ts":
    "QmZZZ3UjjGrNVCuyDx67fvvmf1rPmq8wnh9DUcdAoLMtsK",
  "src/smart-monaco-editor/dist/editor.js":
    "QmPM5fRdgoHgXnZxj7Sg4G3bhTZwpwTqB2mazF81jM36Qb",
  "src/smart-monaco-editor/dist/monaco.d.ts":
    "QmPNrqP54db6P45nw6d3BFmerEAxLzbz2ynbByCrLderPF",
  "src/smart-monaco-editor/dist/monaco.js":
    "QmbJtqvS31TXa9GHm4e8FjK837kpHPU13fZkHbgkFL1FQR",
  "src/smart-monaco-editor/dist/scripts/screenshots.d.ts":
    "QmS5gMBfgk8pSufk8fk4D9VXz74GvEaKgB8sP1dJTDKMtQ",
  "src/smart-monaco-editor/dist/scripts/screenshots.js":
    "QmZj5ZmAy4A2ow36UjUkWKkK1HXKL1tMofYxTYLVoSMJoD",
  "src/smart-monaco-editor/favicon.ico":
    "QmWF8oNe7SDdaY6t4WrJ8ZzM46dHEFmHDXzd8MBeNrELxe",
  "src/smart-monaco-editor/index.html":
    "QmVQxvRvunUpXoZqC67ZUPoNSRpvyB4dKNmEQTtntCNqms",
  "src/smart-monaco-editor/package.json":
    "Qmd4t5HYPjrhNLe8icrVBo6DSCJDjzNm4aSN1rgWYaxooT",
  "src/smart-monaco-editor/src/editor.d.ts":
    "QmXFYH4YMX7W5dDHwbLZS5NqtCSqRf6n9NcmaEZjFsLBtF",
  "src/smart-monaco-editor/src/editor.ts":
    "QmUL1csnFNNNrNQPgYkXeWj4QVUH65Wh3yhUjn62gEP6iR",
  "src/smart-monaco-editor/src/monaco.d.ts":
    "QmdsjvXNr9ufGi4osAtDQuo4tji41DfCKzbCNhLo7F5Gc1",
  "src/smart-monaco-editor/src/monaco.js":
    "QmPU117QEcnXLQb58T54ehhMzj79d6BYATsSz3wgiV7Gj1",
  "src/smart-monaco-editor/src/refs.d.ts":
    "QmUXoLQ9zNGWxd1c1yNBjSf4RoTwFMEbLcq8hL2ewCd6ba",
  "src/smart-monaco-editor/src/scripts/screenshots.d.ts":
    "QmS5gMBfgk8pSufk8fk4D9VXz74GvEaKgB8sP1dJTDKMtQ",
  "src/smart-monaco-editor/src/scripts/screenshots.js":
    "QmYUzn9XSFiduCLmzj4Ewcn5GnxwPaDKYDGAxdakydncmg",
  "src/smart-monaco-editor/tsconfig.json":
    "QmTqtxpjAgAVTAsFTHNuHE2cRCXSzKzfsrVwhFSaGsqea8",
  "src/smart-monaco-editor/tsconfig.tsbuildinfo":
    "QmesdUy5yMyDpXE1pAcqVBcQf4HHhtTxMmVNec2qgC16H3",
  "src/starter.js": "QmQN8pfPkYDNrM6TQ69cxrRarHUZyECR7k9dVM76DP1b4T",
  "src/starterTsx.tsx": "QmQ9AHQxPPsDqonKSH5q5zHeiHHSds2P7gcmUVEWkm4QW7",
  "src/templates.js": "QmZpg8VY2dzzzKjr547W48fS1fPLEkrit6CivrCtvLvkeY",
  "src/transpile.js": "QmYrE2KA4h24JsuZyNRgvvV3Czc9ZMXe6WdwPaGx9ztyxU",
  "src/versions.js": "QmY7WStUTGSpEKwvWxk22aSosFZJm3SKsufcWMt21FPmRg",
  "src/workBox.js": "QmXBC3W7YbyiLmTvJMuTfdxBd7Uoot2S3pHrrcq8qijEMw",
  "src/workers/ipfs/README.md":
    "QmbdTTJXo4rWcSfDFooCBXWGYtCnbixPpSJh9hjAQ6KMFw",
  "src/workers/ipfs/dist/gateways.d.ts":
    "QmaqVQHmb2ESQaLajE5YAbgw1PzYPRwpLbwEFLJfEBARWk",
  "src/workers/ipfs/dist/gateways.js":
    "QmNVuHYaC7MuqYnsRJ2J9kY7TotGALZ868F2jx4ryvmETK",
  "src/workers/ipfs/dist/ipfs.client.d.ts":
    "QmWS9QuitocbrTURXm5wABCFTYCkfAZMPLH4159F6Eoya3",
  "src/workers/ipfs/dist/ipfs.client.js":
    "QmV9YnQ5Kbp3js6QHPC4L3dGt5NshZr4xUaMf8QASanDRL",
  "src/workers/ipfs/dist/ipfs.server.d.ts":
    "QmehfY8Fwd6g979memvTZG7Zx2o6QcVLi6iSNJTBDvmdY7",
  "src/workers/ipfs/dist/ipfs.server.js":
    "QmUxKobsyqyFmfVKpLz4vhthe2ED8NGUgM7DS1oKUeT6mG",
  "src/workers/ipfs/package.json":
    "QmZqBNpawhVtVjJVq1zNKxoszq5hHNmF6skwqD6Ufwos6K",
  "src/workers/ipfs/src/gateways.js":
    "QmVGZy8bP96dMrzL4vTg7ppfpJVAFbtUZ1Go57fvsParbe",
  "src/workers/ipfs/src/ipfs.client.ts":
    "QmcaF3rgV1NmSYzBEV7FJy1jFWx27BNLTr7QycKKbaLwr7",
  "src/workers/ipfs/src/ipfs.server.ts":
    "QmPYR7RSLFHvYdJshHE6ZfAMqZGm7XUfSjcQdbCsNvUgQ7",
  "src/workers/ipfs/src/ref.d.ts":
    "QmZV7knX51sBSfDb7mFNcghGtF3RKyczc6z4Uz7zXS25zo",
  "src/workers/ipfs/tsconfig.json":
    "QmYHbMSMqJLVt643gR6twoh1Fh2pmRefGPr9GEfXQSemHg",
  "src/workers/ipfsWorker.js": "QmcLGgTBu8PpRLfweMhjju1QbLiHhUiZaWiwbz4ydiXeYH",
  "src/workers/sw.js": "QmWNJTAf5Do7u59KhJji66qRakRKuGodc3E5Vj7yHAXXtQ",
  "src/workers/transpile.worker.js":
    "QmUCHZ1UmHevxwNqsDYz8uTNs5TdiNCGFsuc1H5uzLAqpf",
  "src/workers/tsconfig.json": "QmXYJq1mVyQPZk4cxwDrFoj5XEBBs3rgRApV6zQ1mq3FAH",
  "tsconfig.json": "QmdYYNAMVJJgs9nYR2tc4oVC6Fxcwcv7K1b8QH4H2372EY",
  "assets/fonts": "QmYAJJ726yRoCVerLBgUHdLax1JKS85SYLrnrG54WxSDtK",
  "assets/synthwave-vscode": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "assets": "QmbYYAWatTsdjhjf2LCLM1oyUdrazGx1VEzp5zgf7n2DUc",
  "node_legacy/@babel/@types/csstype":
    "QmWU7D5cy7riYJsRWvJavMyzoziid8kHLwUYvsUCvXSYSh",
  "node_legacy/@babel/@types/react":
    "QmdpY31YCrngCkCgmPkhAt7FQbqv2obyTnc9nU6hDuSH3n",
  "node_legacy/@babel/@types/react-dom/node-stream":
    "QmQMqc8ngDH3hSG2wdpxZ5rPwUXznZ8QmGGgjAGEdg2XrQ",
  "node_legacy/@babel/@types/react-dom/server":
    "QmUMJXYY3ZmvcYcQRztvRFrQBnLYwFgtUGiocC4mSCNwBR",
  "node_legacy/@babel/@types/react-dom/test-utils":
    "QmQaHQZxh28YGknuBArVYDaeSxTsWkMkYJ58tU6jbL4gzm",
  "node_legacy/@babel/@types/react-dom":
    "QmaD9A3GAy24JDtmbJLqMkG8mjGN6BkrrUedVqa748kL3z",
  "node_legacy/@babel/@types": "QmVi4Ncusrt5wKaG5fs2jG1QVH1Z9Z5TmW4uP4eqPh8v8H",
  "node_legacy/@babel/standalone/test":
    "Qmdbni8ySNyYHkWS2SgxoLVBT4or3F6nBe61F8FBDwDthg",
  "node_legacy/@babel/standalone":
    "QmeQ1gDZFjKQFLkVYWURPyJjhSV4Q84T5AaraV4Dtzsjgq",
  "node_legacy/@babel": "QmW37MbVKUvzzMXVZkwqCJoSHucjS7vDCu3HMfAsHRyi9m",
  "node_legacy/comlink": "QmTQek4dMBFHR9YmfaC39AHc561J1AyV7zmgPhgtTsP4q7",
  "node_legacy/ipfs/dist/src": "QmYAUdjvoYnA3SE4riK9hBDhdZjr4GWMm9FuM6syBfxztN",
  "node_legacy/ipfs/dist": "QmdvQ91wEBkvBNTLWezJYLT1cgmaCgj2WJ1x2xGSggJrdv",
  "node_legacy/ipfs/node_modules/lru-cache":
    "QmZ7zzPHogjPLe2kBQVj7sziZGcNmb8MgJYzT5mpboGKb7",
  "node_legacy/ipfs/node_modules/semver/bin":
    "QmfQbAdjNAcAYUbCXboMHZ9oY2bDtVSFWWMyGnYo8SS5W3",
  "node_legacy/ipfs/node_modules/semver/classes":
    "QmRfyhpkUsXkMsPSoHXPVMQiX4jBq2pWpj2BgtZ4yJYScS",
  "node_legacy/ipfs/node_modules/semver/functions":
    "Qmazmq7B6QnkYqbdL2DFKEML3qqoP8tx2aFpF6eoLajYka",
  "node_legacy/ipfs/node_modules/semver/internal":
    "QmXR5WYAnzYUBTCp1kurcVVs1RQ55GjnoUKJHbDBB7t7oc",
  "node_legacy/ipfs/node_modules/semver/ranges":
    "QmdsJBXUVPwQ9ERx2Zd7RF8NMzKZCQRXo4tScmiGDKayri",
  "node_legacy/ipfs/node_modules/semver":
    "QmZNjrGXyCQVMEGwzr4SfnoeeHN9koerabn2rAyASf7gc8",
  "node_legacy/ipfs/node_modules":
    "QmdDgU3Pun5ZSDP9sFD5BASP1s3aW4xUkbC2c6xtqrDLxb",
  "node_legacy/ipfs/src": "QmYdcvCbpKGq2bT7Y35cnhGDAmFdULQ99bcQRre7C3iFDL",
  "node_legacy/ipfs": "QmUeKqrtNkaEKuib4DiQySmBES89TgtWy83ksHpQpkukxQ",
  "node_legacy/ipfs-message-port-client/dist/src/client":
    "QmZup1QoUb9PRv51TDmWAZMi7P9DUMcMwsY9iSzZYj59UE",
  "node_legacy/ipfs-message-port-client/dist/src":
    "QmRRhUpVVPhAujdbqRbTC4EUioCVZERCuwpPdx9Zk5SFkX",
  "node_legacy/ipfs-message-port-client/dist":
    "QmcvYWqnmkLmoS8D262vTMbkVDvNycFrzMQzPcerJquNuQ",
  "node_legacy/ipfs-message-port-client/src/client":
    "Qma7mVuyQwQ3384fJov2cuWjR6CXVE5k1WWBsJ6iUXzSqj",
  "node_legacy/ipfs-message-port-client/src":
    "QmUyymcxnh6hpkekqTbcphh4zQqifBuopgjK8Buypn28ej",
  "node_legacy/ipfs-message-port-client":
    "QmbeYVX62aoKMEo5svQUkdfjxQQD5v8BgKuz591gJsKhuW",
  "node_legacy/ipfs-message-port-protocol/dist/src":
    "QmRAQWWth3CGqTDMp58Eof9aPdaPLkzaryaZaYQEAawHvq",
  "node_legacy/ipfs-message-port-protocol/dist":
    "QmdvcKmKmVyxCfDDNjpQtSH7PzUgLrBNoVFMeaxsJNz1zh",
  "node_legacy/ipfs-message-port-protocol/src":
    "QmfLuvmz977mG2dziie5e8GkWKshjXJMbADpg3KC1xkBpN",
  "node_legacy/ipfs-message-port-protocol":
    "QmPXHMM3CJFjh2viwWzPh6Vn3dHFyJBJe8NRzy26XSKTjr",
  "node_legacy/ipfs-message-port-server/dist/src":
    "QmQdTdnQGHJY3fut5GXQa8tsZVpGC1Rj7wT61fpd1Viukd",
  "node_legacy/ipfs-message-port-server/dist":
    "QmTCu7LVcSrpLJ4Zf6JqDuSFjb6NsiQdBAUsT7ZJT2orzW",
  "node_legacy/ipfs-message-port-server/src":
    "QmPLf9dLYAtMwu3KN9kB4mXXN6icfpYCBn1ENMDGkqHLQV",
  "node_legacy/ipfs-message-port-server":
    "QmRQnASzHAxFVbJ4KjoDJ5B9SMuPzcT6fMaAL6UM9FAX8s",
  "node_legacy/monaco-editor/min/vs/base/browser/ui/codicons/codicon":
    "QmTCgjV4XfAZ2VRNyA7pAbXHteAHQfDj7aqyFXVLf8Ub4w",
  "node_legacy/monaco-editor/min/vs/base/browser/ui/codicons":
    "QmTbKb2XPymx49kXJoVrTeH2Bht2V8XChAqAdUPp7u6YEC",
  "node_legacy/monaco-editor/min/vs/base/browser/ui":
    "QmdHNauu9eZm2au7tVGPZriJd8JCwm19PXQL21VqNLVMag",
  "node_legacy/monaco-editor/min/vs/base/browser":
    "QmPhr7LDwZRZRvr7sep5JwoXnPTQqXGuDxRXf3f7p4tdc7",
  "node_legacy/monaco-editor/min/vs/base/worker":
    "QmZ1DJUEqwXHtHTjTKgsq7mosu3iPTwhHkV8YdT1KUhDhm",
  "node_legacy/monaco-editor/min/vs/base":
    "QmdriZzrfEBCYdtmCaRtDfmMCQS8pwXaYnLrgx3cRY9yF5",
  "node_legacy/monaco-editor/min/vs/basic-languages/abap":
    "QmeRNeu74P9CgGNDhqowFs2BzxV4YUbr7MRMZtCAEKiwfj",
  "node_legacy/monaco-editor/min/vs/basic-languages/apex":
    "QmWgMoswMUrBAi94DoCsn5mwvGyLVrS3aVB1j1GSJe4kty",
  "node_legacy/monaco-editor/min/vs/basic-languages/azcli":
    "Qmc79388xh6Ddaev1uvkkANh9KTCHmthJrWwT79NFVXyQC",
  "node_legacy/monaco-editor/min/vs/basic-languages/bat":
    "QmeUiBRTE6TSvcjG6fmK1Xa6NmTxg69qmbohqaxyrshrDv",
  "node_legacy/monaco-editor/min/vs/basic-languages/cameligo":
    "QmaCje7dLsTCGb2tKu884zpXPoapzSvgmUqzngdMyau4C1",
  "node_legacy/monaco-editor/min/vs/basic-languages/clojure":
    "QmTtbo7PnVtZ1s3cJ4ezbYjh3wSibVg5Fw6LAeDdw6yzzX",
  "node_legacy/monaco-editor/min/vs/basic-languages/coffee":
    "QmdYQsvj6x5JDNK6PYDsA6WPYfKBot2dDtzUFX8N29ToD5",
  "node_legacy/monaco-editor/min/vs/basic-languages/cpp":
    "Qme7CKfGZjGQozGr7Lc5hDzn9QSRBS1nERcxYZ3hTuD3aa",
  "node_legacy/monaco-editor/min/vs/basic-languages/csharp":
    "QmRoNLZUjxt1iZnRnD2LPf6U4KnW9daLH1BbEqdfro4Vcy",
  "node_legacy/monaco-editor/min/vs/basic-languages/csp":
    "QmXUPfjPNk6tfuLKV2K1vkNWjhJhUy8rKd6LVTAme4agfW",
  "node_legacy/monaco-editor/min/vs/basic-languages/css":
    "QmSs7ApyA6VD5PL94hnerWqutjMJnReG8TdZGNfedc3W98",
  "node_legacy/monaco-editor/min/vs/basic-languages/dart":
    "Qmdi65Yy8P7VAC6BYWdXawz8Tf39ua5k57DaJJvkfhRFpK",
  "node_legacy/monaco-editor/min/vs/basic-languages/dockerfile":
    "QmdxtR5pS1PW7BaoxkZqtVLem71tdtM7kawibevJdPoARp",
  "node_legacy/monaco-editor/min/vs/basic-languages/ecl":
    "QmaMZvz72kRNUvGuTEW3KoeDiGnLGr4DjUGUTcRAUywUZb",
  "node_legacy/monaco-editor/min/vs/basic-languages/fsharp":
    "QmZPNYgTk7ZqcjcJoeJf8T5ucCuiu3xnRyuK11LDu68DEe",
  "node_legacy/monaco-editor/min/vs/basic-languages/go":
    "QmZkAcsGDPe7tqbkFeoQ1UoEEir113PYsJEkznbjAyXyp4",
  "node_legacy/monaco-editor/min/vs/basic-languages/graphql":
    "QmZsGGMqm1jbQL2EAAbVtvePbvVyrLCA7Tt3YwNgGw3Grb",
  "node_legacy/monaco-editor/min/vs/basic-languages/handlebars":
    "Qmey7d2sep1g97VapXj4QanLZrLXrrkt2RjeGzFKCaWEAE",
  "node_legacy/monaco-editor/min/vs/basic-languages/hcl":
    "QmPYF7wbUWBq86s6amkKzw8gFJhow41t1qQCokhSaxC2dS",
  "node_legacy/monaco-editor/min/vs/basic-languages/html":
    "QmdiJK26pBKVnzrJt81Ch1TYooki2J4xuyCcj2V8HSeezU",
  "node_legacy/monaco-editor/min/vs/basic-languages/ini":
    "QmdKkAPGXLmNykdeNkVwjUXmc1iEx8Q7s1fD6RDRVA5pBh",
  "node_legacy/monaco-editor/min/vs/basic-languages/java":
    "QmYdA8mTrqUKTBdnVidVaRQF4dhyWJnyz7fvChKs8QamjP",
  "node_legacy/monaco-editor/min/vs/basic-languages/javascript":
    "QmdWep3UKpkTvKKMgP34tAfAGEL3eVJcp4GuRCJzkQ6gr9",
  "node_legacy/monaco-editor/min/vs/basic-languages/julia":
    "QmWYvuZSKteaffjVHu5pexbXM3SmuuPbNwdUSQDmg4VfSf",
  "node_legacy/monaco-editor/min/vs/basic-languages/kotlin":
    "QmX7mawF3BknKBzXPZ5Nnahuo88Cpg6cwJmpzPCwKRSpBH",
  "node_legacy/monaco-editor/min/vs/basic-languages/less":
    "QmSEqdQWguWkKXUcLBmwVicMURaTyxu4uSTdTu2BaZfaQz",
  "node_legacy/monaco-editor/min/vs/basic-languages/lexon":
    "QmWFmtGB27ZdK9wayQNDo1Xv9HQ9TPmByGZdPeCMoYxgqn",
  "node_legacy/monaco-editor/min/vs/basic-languages/lua":
    "QmZMiSLaV46QSxT97cjF7E59vVDPaasjwW3EBrjA8zeNba",
  "node_legacy/monaco-editor/min/vs/basic-languages/m3":
    "QmUrNUak9RbWDVGbvdofB49as1et7ArvHTY6JTVPfd5Tt7",
  "node_legacy/monaco-editor/min/vs/basic-languages/markdown":
    "QmfUmqW53FmbDvXs3b2tegGWXgTv7YvnzPhGxkkbrFMvCk",
  "node_legacy/monaco-editor/min/vs/basic-languages/mips":
    "QmWoFkCZk4nZjKjFHWfqwCNrnEv89UsgYuAfbsZfTspe8Z",
  "node_legacy/monaco-editor/min/vs/basic-languages/msdax":
    "Qmas5MfPaTFU3uvTsLL4UXxLa17acpnddTsFwUBS7SfyWq",
  "node_legacy/monaco-editor/min/vs/basic-languages/mysql":
    "QmNm14Q6CqkPz88kmA1dqDTggNi2jyjGU93nRndeeoEyGu",
  "node_legacy/monaco-editor/min/vs/basic-languages/objective-c":
    "QmRr1FcbVmEEJA9HYQvP8NZnFEiodNnwbDoVVy8Z5CXEhT",
  "node_legacy/monaco-editor/min/vs/basic-languages/pascal":
    "QmRtAngE8axaka5Wb8Fk3ui8U7awreHAVs11m1jGmXWQcG",
  "node_legacy/monaco-editor/min/vs/basic-languages/pascaligo":
    "QmRNigEaw8FmrXik9AWAaztuA6FjzMEv6N9dum3rFA185D",
  "node_legacy/monaco-editor/min/vs/basic-languages/perl":
    "Qme8kaXN3n21VStSZCUDFV8CrHocjytGpgPWgSvenuRtTF",
  "node_legacy/monaco-editor/min/vs/basic-languages/pgsql":
    "QmNZ7oJno8bPRDR6VWuJeYy2NwRYKWHFmQ1jCeV5Xk4PSd",
  "node_legacy/monaco-editor/min/vs/basic-languages/php":
    "Qmf7W9auy5MAySXnXo5bEg3eoDQhptAAME6QWQeNexZLW4",
  "node_legacy/monaco-editor/min/vs/basic-languages/postiats":
    "QmYMnT1XPmYmbiVhKTvBaiqwaufTcacNH5feE3EpKbiic3",
  "node_legacy/monaco-editor/min/vs/basic-languages/powerquery":
    "QmcAdq4ccWhMX8d5EFHXSmYrEmUujHErGLAnERnaWYzAcc",
  "node_legacy/monaco-editor/min/vs/basic-languages/powershell":
    "Qmd7HXTvDd79yU5UEaXenL6xG4KWfZpCq2s1BTv6i8WBpz",
  "node_legacy/monaco-editor/min/vs/basic-languages/pug":
    "QmQJeH3Cc4FebtvzwCohAXx3dnqetX2AeCfuvrp2nMnCpX",
  "node_legacy/monaco-editor/min/vs/basic-languages/python":
    "QmSVvCsMawMtd3cTe7YoFr27sdc3btnMguAbcQ6PzgVLL4",
  "node_legacy/monaco-editor/min/vs/basic-languages/r":
    "QmVNwkR7aV5KPqGJ1aqRwAYPdgZvgUM2CSBEnygSrmRkPh",
  "node_legacy/monaco-editor/min/vs/basic-languages/razor":
    "Qmc4FHoUdNUQY1kNAbBmwd3x4KZCHVZ2rTgP1XXwQVbvPt",
  "node_legacy/monaco-editor/min/vs/basic-languages/redis":
    "QmWu8dGZ4Aiqn6LB7Wu22DQDRckHnvSG9vhm8wBqqAw1fZ",
  "node_legacy/monaco-editor/min/vs/basic-languages/redshift":
    "QmY1FeyqgDW5wmd1P8QH1oGKqDhK2bfFZAFwSCEjQFmMya",
  "node_legacy/monaco-editor/min/vs/basic-languages/restructuredtext":
    "Qmdb7CKsjg4sEtVvq8aPLBbKnadr9iuGArCuM26hKcv7nd",
  "node_legacy/monaco-editor/min/vs/basic-languages/ruby":
    "QmPCxRNJAMTcQ1t5rKnHwfsQvs2MTT8ibp7r3neKRqLbj5",
  "node_legacy/monaco-editor/min/vs/basic-languages/rust":
    "QmPRfcEQGbFQHMUhLXbzXrgE7ubreSJNPH8AQ5WtLsN7VW",
  "node_legacy/monaco-editor/min/vs/basic-languages/sb":
    "QmQnFgcm3xax856UB4wJqHfbdDvT8Abyu1HYpnwdATU5gc",
  "node_legacy/monaco-editor/min/vs/basic-languages/scala":
    "Qmb3o9M7PxKMwVSHXZUSBayMNraNyF6Paie3zpx4fXK2TH",
  "node_legacy/monaco-editor/min/vs/basic-languages/scheme":
    "QmbLT3x5q7LV5gfGWmUXAbc4SiSKGtf526DU3XQEXNHKLL",
  "node_legacy/monaco-editor/min/vs/basic-languages/scss":
    "QmXDg3fxFP4PN887YpzxNjtCDndwCu2eVSRvFkS1JxWZx3",
  "node_legacy/monaco-editor/min/vs/basic-languages/shell":
    "QmQbA1KSCK796soF2B9aDukvdcVQVzV9ehWHa88drt2LFF",
  "node_legacy/monaco-editor/min/vs/basic-languages/solidity":
    "QmbyRxaRDmT1q42RovFc8kisgTqpkGiroSBTjasFNuQgKv",
  "node_legacy/monaco-editor/min/vs/basic-languages/sophia":
    "QmcdLVwPbzuoyVCASdTZASyb5WSTBiLuYEUHAFwNHBbRfB",
  "node_legacy/monaco-editor/min/vs/basic-languages/sql":
    "QmdNHFcygc9mRzQhLWCy3inY92kfxG4kcJu7LNUXWwiMq2",
  "node_legacy/monaco-editor/min/vs/basic-languages/st":
    "QmVupYw27ogzT9evBvMiYprt9ktjEw3snkLthnXFpDF7QR",
  "node_legacy/monaco-editor/min/vs/basic-languages/swift":
    "QmTsb4hAmfuKa1c63QMEv6J1wTA4qpehRhYvcPyn5StqCe",
  "node_legacy/monaco-editor/min/vs/basic-languages/systemverilog":
    "QmboFP5BVTcm5w7f7V5GNE6xS6NqpwEhNwYkUA9pbzL3e9",
  "node_legacy/monaco-editor/min/vs/basic-languages/tcl":
    "QmNfZVnCQ1R6RkRRXzriQEvb3pRrVZKLXfCQBoHBch4tcr",
  "node_legacy/monaco-editor/min/vs/basic-languages/twig":
    "QmPp71vQXY1vCQrDA6ehre5jctc9ztCokFdma7GdqrSLjR",
  "node_legacy/monaco-editor/min/vs/basic-languages/typescript":
    "QmPWGEHYUYSE4q47SYKAfcWcvoxCvsxqnejQSnHmj8QVrT",
  "node_legacy/monaco-editor/min/vs/basic-languages/vb":
    "QmfRPFT5Ykp7xDgaa2bp8t4QVjMWG14pAmBpXpfUkE9Ldm",
  "node_legacy/monaco-editor/min/vs/basic-languages/xml":
    "Qmd632Xcdd7TXGrn3qhPfogH3XpwFb9jMqk25pYgW8N6gH",
  "node_legacy/monaco-editor/min/vs/basic-languages/yaml":
    "QmPSHJebgzKtoC22AbL7xPNdq7tYBUfivjZKMp5YBoYkaT",
  "node_legacy/monaco-editor/min/vs/basic-languages":
    "QmYHV56gyFSq2L1Mwq1gUqZuJb4kNgLye1TAQbPFNHf1os",
  "node_legacy/monaco-editor/min/vs/editor":
    "QmWJvQqbLB7deJ4u99gRFBvpTQk7vAZYoJu2Uy1pofm4Tr",
  "node_legacy/monaco-editor/min/vs/language/css":
    "QmNazVg79Ry4Nvj82JFrkPXEFhwvFRDjmbyFRL51mYKftF",
  "node_legacy/monaco-editor/min/vs/language/html":
    "Qmcx9JJXD7QzcUDm5fdY4iWuNLfjDEdWBXVb2wCdJrv3eg",
  "node_legacy/monaco-editor/min/vs/language/json":
    "Qmbj2H1LQnaTqPPntq41mf2pwLqutwhNxzW3nc5xZZffFD",
  "node_legacy/monaco-editor/min/vs/language/typescript":
    "QmbFGz2Lz3GDBnxYK2SgXna1T8AMWPzrD7Za6PUUjtPhe5",
  "node_legacy/monaco-editor/min/vs/language":
    "QmactqmNvJp33cL2utSPmFQTFxZgyzmE4tuqDLxn1mL213",
  "node_legacy/monaco-editor/min/vs":
    "QmT6wUtxJ8GTfashXGD6nR5iSMZTmVwKL9yusWXpt6TVN5",
  "node_legacy/monaco-editor/min":
    "QmU8XUFph69p8VF2nG1v472pz2nHyetSdgy5a8HDb9CQEW",
  "node_legacy/monaco-editor/min-maps/vs/base/worker":
    "QmbFiGfcpPndc8UWPoRDm1WnEseqQuF7igtBJRNeobce58",
  "node_legacy/monaco-editor/min-maps/vs/base":
    "QmX16u4KjB2UqmVXBEhtkjMwtxBpn744d7azm23JizbZUQ",
  "node_legacy/monaco-editor/min-maps/vs/editor":
    "QmVEYmA4dKS8bEYJks2qtz7x9jvJAvP4v4yaE2D1qcaSBy",
  "node_legacy/monaco-editor/min-maps/vs":
    "QmRtBn5v8TeJMBSmxTxNAqtGU1pYYcJQLR21tatmmMeq8B",
  "node_legacy/monaco-editor/min-maps":
    "QmRAa5yuHV88NiX2QaCh3pAQcAHERkt93AegWUge9qAaC8",
  "node_legacy/monaco-editor": "QmcnxLLS3N99aZUWs39MvLVrFbjCaTcs5HGgusThGZphvu",
  "node_legacy": "QmWVTMExuFrFLXRBQXpQvS6TopAYH1fqNujLJ5uZYfkTbq",
  "node_modules": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "src/emotion-react-renderer/dist":
    "QmeJEWVM2SczjoywzLE6nkoejskamp8Q4wyEtTU9x7qpGB",
  "src/emotion-react-renderer/node_modules":
    "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "src/emotion-react-renderer/src":
    "QmaiAYipMcBDMfSAaAebzpvBVShAvL5gHbicUw5RgcUVTz",
  "src/emotion-react-renderer":
    "QmNUC2zub9cEGT4pjqy3Lj1natCf2tZ4P1o6NWhw6DMrVg",
  "src/examples": "QmZDutnUy26UNWoF3AYZd16bU2tVp2JDdmjNN1ScCDRGXy",
  "src/shadb/dist/vendor": "QmYdCotAyEWZMuwFmTH1Q9Vpz6LzKQ9ryRWyT4gS6umhz3",
  "src/shadb/dist": "QmZ2fGgNfogdBuyodkmVWC1dJa4QWGoHjqh5DRej1wmfCG",
  "src/shadb/node_modules": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "src/shadb/src/vendor": "QmSxCEdubJ7wcURDmJim12nVffaRTDe5wF4e5bfcvkWTF4",
  "src/shadb/src": "QmRAfdSAxNVGDXfHoX6G6ojFxiUWnuprNzw8ynV5QKgW8o",
  "src/shadb": "QmPNjt1yGtpxtMPTfa8Vbq9YBgNDLhvSQzZemNZo5Eco5g",
  "src/smart-monaco-editor/dist/scripts":
    "QmUZruQhR3JEi3knevKng6AKpxN3vcswuRrCp4DiW9aYMM",
  "src/smart-monaco-editor/dist":
    "QmWs2hGWL4JJSW1NMviaqp6zAxi53scknjYZxPZr9pkygJ",
  "src/smart-monaco-editor/node_modules":
    "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "src/smart-monaco-editor/src/scripts":
    "Qme94rT99UbaVwYxeK2ERakcHAABqofabkBbiSUuKztFzg",
  "src/smart-monaco-editor/src":
    "QmSaiU1Wk9e2A3DYdHdrQE83FYsiKy28c8nCKD1E1dThn1",
  "src/smart-monaco-editor": "QmVoPDDp5jwJ4i7s2qrYGvpi9Wb9BjDhH3c9zBDsysZqMA",
  "src/workers/ipfs/dist": "QmXRShoseu2G8qdzjnaQJUeDjdz3UEv2EUd68oohq19Q6B",
  "src/workers/ipfs/node_modules":
    "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "src/workers/ipfs/src": "QmaY2UrSpouuMkzxxMj4mBCJrP1v8mXQeYf7jhqP29jeY6",
  "src/workers/ipfs": "QmZPHzZKnwNdQgCCKCvJSjmF2THxV2gYbpRMvc96NsYuaP",
  "src/workers": "QmTG44yjiFXybsCx7VJJiVUrAXYvFKXrEGq21mVC4ezXx7",
  "src": "QmQS4JyNQeqVtWD15K1w5CCosz6yxHVNfBvEheWNLycCzF",
  "": "QmeuVNCezjb1juaYTi4e3uTenCsdZSJsvrgYpPhZqdGPLi",
  "foo": "bar",
};
