export const files = {
  "assets/app.css": "Qmbh94S3j1gDwhW9eMQ16ZKeZe3sRSQCYqWtCRVARU8HYM",
  "assets/fonts/KFOlCnqEu92Fr1MmEU9fBBc9.ttf":
    "QmVB1APqxwoFrkjZ9B2kYmukzGPdVrdct1JdxhkPbeY28Q",
  "assets/fonts/KFOlCnqEu92Fr1MmSU5fBBc9.ttf":
    "QmSuFCECZFdYirnXLK6xfaZWPmqP77LsRCnrdsmU9KVoMT",
  "assets/fonts/KFOlCnqEu92Fr1MmWUlfBBc9.ttf":
    "Qmd8qKxYJaKoiR9EsxgQqwkD5XBzayCHKwNJuhQuUF5ApJ",
  "assets/fonts/KFOmCnqEu92Fr1Mu4mxP.ttf":
    "QmRbTrHtUz6mKUsu7FFzfUBcr4VuoCt9TtpMnJG1P135bS",
  "assets/normalize.min.css": "QmVaRzLwnw3Nnoq8KHNBSTun6m3v2WvVaUbRpukVpcGJUX",
  "assets/roboto.css": "QmafZGaL6TznhmwtJ78ggkm7phbCiuEVXcTxfLwbZG6PoT",
  "assets/social-media-computer-icons-share-icon-png":
    "QmcsMurTbnEVPqP42x15FiisSjQdXJ7vGGHhf279UtwPxE",
  "assets/synthwave.jpg": "QmVP5gg9nYuPg1au5pBmdn75xmUvuGevRPLhEngyEyQfkT",
  "assets/triangle-geometry.png":
    "QmZ5Nic3MRHT8m9SY5ZrSp38UHGEYmJqgk4RAmDV3xXqa1",
  "assets/zed-icon-big.png": "QmeHY7RZzR5wm9ELZr5xgq6XMQKjRAHgmxoQaCzHjgpRm8",
  "favicon.ico": "QmWF8oNe7SDdaY6t4WrJ8ZzM46dHEFmHDXzd8MBeNrELxe",
  "index.html": "QmShARLeUYm6Z8MnXWMcaURhDrkVd3hphoVaT1SNpaJkm1",
  "ipfs.json": "QmbBV3Li2S1VDtjj2EMW9AFtuMDppanNMYgJr3nzEpwKTf",
  "manifest.json": "QmTBHTEYaAy537jiSxtGsyDWNAAXQsvtCtmLgBvbGPFdK3",
  "node_legacy/@babel/standalone/LICENSE":
    "QmZqNk275fZv9p2XtmVbDu5cwqnkhKrrFN3wbYJqGzpznc",
  "node_legacy/@babel/standalone/README.md":
    "Qmd7fqhRTRNoZVVTMt3YuJjUzLUDjajmyyYdQigncNqkAE",
  "node_legacy/@babel/standalone/babel.js":
    "QmYsHEj7QyeLRK17JqduUcZo73AxxYLZTJ1T5ZMyrFPQqC",
  "node_legacy/@babel/standalone/babel.min.js":
    "QmdCiW5wGiJKavAHxWwg6Q1ADWVoVVwQjVC1zHMRGdR287",
  "node_legacy/@babel/standalone/package.json":
    "QmdKc28DprNXfJdbv9MRbxBQ8GXxbfDXebJXDruZdM7HHU",
  "node_legacy/@babel/standalone/test/babel.js":
    "QmSVHZ25VdQAypNkJWq97qUuv5bcULo5hGWvqgjkZLVYtk",
  "node_legacy/comlink/comlink.min.js":
    "QmXxvh5CjqR5b2gDgeGLpi52sJT57bmnse9JaofpHCm5i3",
  "node_legacy/comlink/comlink.min.mjs":
    "QmQaWVwJtXHsDocKk3FzJBaNA6VUhuiqbhTgUgVfBJRHiZ",
  "node_legacy/ipfs-message-port-client/CHANGELOG.md":
    "QmbHzj97YThEZEG4Wki5B3SP3faGLbF7im78U82fMf2o9o",
  "node_legacy/ipfs-message-port-client/README.md":
    "QmTQvQXKaWPSk1W4J6Ebohkk3Z7aBoxPDa28VWsPs1hbcf",
  "node_legacy/ipfs-message-port-client/dist/index.min.js":
    "Qmafe9mxRXaKs8AYq8PuSMz4YXebcKkGSBCLqrePoMuJwT",
  "node_legacy/ipfs-message-port-client/dist/src/block.d.ts":
    "QmVt74d56eTUzDj5Hgy1HdpYtQV9bpJtT1QMUE8E43Nei3",
  "node_legacy/ipfs-message-port-client/dist/src/block.d.ts.map":
    "QmPvz7CqN3RLhzbufMB8wK444BZCSkGvWq9AJK4ECHX93z",
  "node_legacy/ipfs-message-port-client/dist/src/client/error.d.ts":
    "QmdssZCqQLdsyc2CyDjpK7T1qrXVKgLsMieZgUsABVk861",
  "node_legacy/ipfs-message-port-client/dist/src/client/error.d.ts.map":
    "QmQewEQUzFyyVw8k9fAwaFPwvKkfV3fRLjLqY2M3iZ8yoJ",
  "node_legacy/ipfs-message-port-client/dist/src/client/query.d.ts":
    "QmPvUit71cE2hdCm6N4sRkEzbjjgRh6ed5LrqJk8wom1DD",
  "node_legacy/ipfs-message-port-client/dist/src/client/query.d.ts.map":
    "QmaEEUreywjiUq93qJDNT8HN72ALJSESTrwxaRtCdvDtBU",
  "node_legacy/ipfs-message-port-client/dist/src/client/service.d.ts":
    "QmfTyWfZudpdUnkZRYdgcABpmTb652rYEjAvGQGJaTNq44",
  "node_legacy/ipfs-message-port-client/dist/src/client/service.d.ts.map":
    "QmdNJQNA8G5qwQoPh9ey9bzUqw8pE7qV5zgbQqxC6WXjph",
  "node_legacy/ipfs-message-port-client/dist/src/client/transport.d.ts":
    "QmRNuxuKJi8ePyEFjykgmwt7oyvPhcnPQdj97kMYjT993Z",
  "node_legacy/ipfs-message-port-client/dist/src/client/transport.d.ts.map":
    "QmSnKrhz5dojaJkK19wAQQrySRTXoXx4wXMQvQVQmJcPet",
  "node_legacy/ipfs-message-port-client/dist/src/client.d.ts":
    "Qmey6tX1Zi1C1aJ1bqL4UNowTpCmswABTCbRZjGtgzqc36",
  "node_legacy/ipfs-message-port-client/dist/src/client.d.ts.map":
    "QmYUyubPoTDrazxwtPRFnYGWq2SMoFLYmX1nbgZDmteipP",
  "node_legacy/ipfs-message-port-client/dist/src/core.d.ts":
    "QmccPy1Bm4VukW2BmPLZ9xmwccTo9BnT1ti2TQPRYDaazJ",
  "node_legacy/ipfs-message-port-client/dist/src/core.d.ts.map":
    "QmRAVrwJ6gt5eHfHPPJ8KaPEHojZCZ3kHqMctxjF4P1wjj",
  "node_legacy/ipfs-message-port-client/dist/src/dag.d.ts":
    "Qma5p9dR95ct3hhDEJB6A8q9NTTGYd9vjzwpf4iWYnq5Hx",
  "node_legacy/ipfs-message-port-client/dist/src/dag.d.ts.map":
    "QmZo4hzo424dXHx11L3625TT72CQiTYGJVF7HaqnPsSB7c",
  "node_legacy/ipfs-message-port-client/dist/src/files.d.ts":
    "QmQ3xYDLmQMZDeUHpouUAFE1WitssvteKgt9QUyus5rV2p",
  "node_legacy/ipfs-message-port-client/dist/src/files.d.ts.map":
    "QmW6SQBewAS4J7d1ReDwMtrD57mDuF93oBAsWrUUwcZEzW",
  "node_legacy/ipfs-message-port-client/dist/src/index.d.ts":
    "QmYUDye3KLNfMK7vSuvHHpvTYKzKNf9oWbveW8rM5YyUkr",
  "node_legacy/ipfs-message-port-client/dist/src/index.d.ts.map":
    "QmQJrfPuGGSYoTVsa1b3pqtFoNdBZbxFKr24oj2y4w7ors",
  "node_legacy/ipfs-message-port-client/dist/src/interface.d.ts":
    "QmbiL6NibHU72iuGgow7HVwMcZniiHBg1A7yP9e2YvwDRT",
  "node_legacy/ipfs-message-port-client/dist/src/interface.d.ts.map":
    "QmU9hRnTB1QEZQALwteoEZLTxhtSKThouZJPxyLke3BHdL",
  "node_legacy/ipfs-message-port-client/dist/tsconfig.tsbuildinfo":
    "QmbCy1WbUnddDkpiM8Deh19h9JFP2ejkrZ4TQPHErJAbgM",
  "node_legacy/ipfs-message-port-client/package.json":
    "QmVXhgNs2u1wuxewRi7M2RyCyhRdLfdPgu469GKxTvi6sC",
  "node_legacy/ipfs-message-port-client/src/block.js":
    "QmP2JzzDqhjW8jESuRSuG4Si15AtT1c4jrWKb3hpYMfbXx",
  "node_legacy/ipfs-message-port-client/src/client/error.js":
    "QmaATcHDww5PX95Bu1eG5oMCsMosX7YSpCPk4wV8dg5EYE",
  "node_legacy/ipfs-message-port-client/src/client/query.js":
    "QmTpyK4YjhMEEJHMWiUFsjWS1tEtnBSqCyC59YhXaBBCjP",
  "node_legacy/ipfs-message-port-client/src/client/service.js":
    "QmZ8ZxL2gjEfBkiAyFRhioN1LnaCcz9mSp2yjdmtatUfQL",
  "node_legacy/ipfs-message-port-client/src/client/transport.js":
    "QmUZ32NHeiVNPG8PucNv6jP9kTMcvH3kHVxakaMk7xrVaj",
  "node_legacy/ipfs-message-port-client/src/client.js":
    "QmS1qMcTmr7KNtrYxbyoPxkKMiF1i5RtGS2r1mNiiPU7Xb",
  "node_legacy/ipfs-message-port-client/src/core.js":
    "Qmaev7Ug41FGDs3PXhkNnLAAmGqvk3KrCn1URtHFQnAkrx",
  "node_legacy/ipfs-message-port-client/src/dag.js":
    "QmVtPUfymB171teNH9KE1MxQbgb4m1YwqccTSo69wikCVv",
  "node_legacy/ipfs-message-port-client/src/files.js":
    "QmPRJxJN7pDhqWWmECFqNchjDJWP15KvPXKZdCrTJ81jeq",
  "node_legacy/ipfs-message-port-client/src/index.js":
    "QmVvazEJWAuKcVtPcsfXahWybrvnHNaU39TbNycaLs8DDB",
  "node_legacy/ipfs-message-port-client/src/interface.ts":
    "Qmdm6SvYvpnCFH6m3nMnvq1UxbBMJqxJzJtUag6dCUVFMq",
  "node_legacy/ipfs-message-port-protocol/CHANGELOG.md":
    "QmP7xWa7rTtfCzvhZcnQGag7deHDxhS84UevSBqqXVs1fd",
  "node_legacy/ipfs-message-port-protocol/README.md":
    "QmTmxXmRU3VFGBM4cQUBdvSyDuxKhZvMx52Kowq4hcP83y",
  "node_legacy/ipfs-message-port-protocol/dist/index.min.js":
    "QmXu8xAV9M9mz4uTxBFbSQo7NwYXMrLfGJShzBreDoXn3k",
  "node_legacy/ipfs-message-port-protocol/dist/src/block.d.ts":
    "QmSVenf1M3upECV3F1BT7ifuebfhLubNuofAR82VudnBj2",
  "node_legacy/ipfs-message-port-protocol/dist/src/block.d.ts.map":
    "Qme7wUPuJgWdjrjy2p6j3oEVmzn7ZUmz9CtNmEjdEW9AFt",
  "node_legacy/ipfs-message-port-protocol/dist/src/cid.d.ts":
    "QmbimqEjFfTqGAb4fnQ7emnixeYCqT2zDSVvY9XtvwdSLD",
  "node_legacy/ipfs-message-port-protocol/dist/src/cid.d.ts.map":
    "QmWGsjSLL6kHhghXbeB9ymTBbabb7dZRLkNqtpYCSyxdwD",
  "node_legacy/ipfs-message-port-protocol/dist/src/core.d.ts":
    "QmdqG3uDx4pGK1wGrFtfasPM8kG5acoech7qkPtW5iBjUU",
  "node_legacy/ipfs-message-port-protocol/dist/src/core.d.ts.map":
    "QmdsiTaqTXndRQATkLSovCxCNvtzoTALLfDzxRVYvpcQiQ",
  "node_legacy/ipfs-message-port-protocol/dist/src/dag.d.ts":
    "QmRUMUDBK4B3R6sVojitKRt2abJtmwryDUS9NegStjmVpx",
  "node_legacy/ipfs-message-port-protocol/dist/src/dag.d.ts.map":
    "Qma8ZsmVDeepnwKgra89zRgK1Cu7iKcQLNXpjCx4BL9wXC",
  "node_legacy/ipfs-message-port-protocol/dist/src/data.d.ts":
    "QmTdgy2AZsMVE5khtEHqZcrPzUcU5BatNgwPi3AWsQVxCJ",
  "node_legacy/ipfs-message-port-protocol/dist/src/data.d.ts.map":
    "QmeFr1wqj9eFNttfysqqrdJidnuAh2HpS7xVPjcuWhJMLj",
  "node_legacy/ipfs-message-port-protocol/dist/src/error.d.ts":
    "QmSEERnqGWEsMr3jnsFMRUHVY3qcPrfGmjuMhWNoEqdrPb",
  "node_legacy/ipfs-message-port-protocol/dist/src/error.d.ts.map":
    "QmNMoPQc1RGQ3DMSFHKRQLMTuUDbzgaH1LoaDdAKf9XgfL",
  "node_legacy/ipfs-message-port-protocol/dist/src/index.d.ts":
    "QmNRKuQHKK9z4bVdRy3vemtviyzAtzAiL52PnoNdhDg9gk",
  "node_legacy/ipfs-message-port-protocol/dist/src/index.d.ts.map":
    "Qme8AciEXCfQy8eZhwMhpFcCdE7cH12URucWDFHGEHPHRP",
  "node_legacy/ipfs-message-port-protocol/dist/src/rpc.d.ts":
    "QmeJiftgYf5iSf7jVLCCKrNuBsfsx14FNWugHcm2quCjED",
  "node_legacy/ipfs-message-port-protocol/dist/src/rpc.d.ts.map":
    "Qmdm1zVmD4w4KEPp7hYLYS5ZnaSm2VzMWXege7DsA4tevp",
  "node_legacy/ipfs-message-port-protocol/dist/tsconfig.tsbuildinfo":
    "QmeN2WPDixMMxQLjkSoUN6j4U5fpna7fKQXBZF7EmbBX2k",
  "node_legacy/ipfs-message-port-protocol/package.json":
    "QmXxfqU3s8979NJrV4oroGn3rPoHzXqKUGEVQvYFrJWA3h",
  "node_legacy/ipfs-message-port-protocol/src/block.js":
    "QmPmmDAXB758s1ARWKffcQaxk4B47zPY9YEH2RzqLSVbVe",
  "node_legacy/ipfs-message-port-protocol/src/cid.js":
    "Qmese1XU8n6sjYQjWxgYb5oC2fDXTNneUUfSay41H6J4DQ",
  "node_legacy/ipfs-message-port-protocol/src/core.js":
    "QmX6zzXJJqS7BXiUUdufYhMc6rbeQ6TUy5QHFHr9GdpJwk",
  "node_legacy/ipfs-message-port-protocol/src/dag.js":
    "QmUq3ueh72oVr9gKZqMrLgVEHyiVYWWquCp89iQoyFVkVr",
  "node_legacy/ipfs-message-port-protocol/src/data.ts":
    "QmS3DySRey4HkfYgJcXgUQ3EUDKc4LdjLrSZhuqj1rTTDp",
  "node_legacy/ipfs-message-port-protocol/src/error.js":
    "QmTmEF1Zug2xa6BagRpSqxMXK9NrtQPatYSG1YAxqLWmQK",
  "node_legacy/ipfs-message-port-protocol/src/index.js":
    "QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH",
  "node_legacy/ipfs-message-port-protocol/src/rpc.ts":
    "Qmez23fBYWB3df5ByWTdkUUZrKXywzPFsYjdf4UdVgSCUd",
  "node_legacy/ipfs-message-port-server/CHANGELOG.md":
    "QmUb6EPE1AfrdmpqEJHADspfqS1hSSqTs59MzFb1GGtAPt",
  "node_legacy/ipfs-message-port-server/README.md":
    "QmVRMYbkAp5HqcPvWdrtQZ9h14w5BgzgsN7VzBxfgYW94E",
  "node_legacy/ipfs-message-port-server/dist/index.min.js":
    "QmQnP9m71YVty4Wr1VL8tCAv3P6v9cG7gaA1cGk4W7JxMZ",
  "node_legacy/ipfs-message-port-server/dist/src/block.d.ts":
    "QmcLa4WbBgVEXFiraNB12vvF8kKm5cmiLzKhyQRTUR9gx9",
  "node_legacy/ipfs-message-port-server/dist/src/block.d.ts.map":
    "QmZ9oZiRczq8L6oqciu4JumTz6ftBy89oQF6ZLwkcK1kp4",
  "node_legacy/ipfs-message-port-server/dist/src/core.d.ts":
    "QmbtCXG6EAyaaFdqDdtWqkxdZnguK1ZftjnHxNMFVqqRPm",
  "node_legacy/ipfs-message-port-server/dist/src/core.d.ts.map":
    "QmRxjN11sya71haCMM2UUztJFr2ZdVhTDzjR8SobhKLVdA",
  "node_legacy/ipfs-message-port-server/dist/src/dag.d.ts":
    "QmeKPpPYfj6Ce4ps79MtUfEUZsLPQ3hSJzVCbS3vJyVWGA",
  "node_legacy/ipfs-message-port-server/dist/src/dag.d.ts.map":
    "QmZmFCNRErT8E6E2XSmwWj6HT1NnSY8iA93W6n1p6mmxyh",
  "node_legacy/ipfs-message-port-server/dist/src/files.d.ts":
    "QmRSSkUZ6UtnRSsuCmCwoUsoL2sGAQh36s3RQBCZk33SQ8",
  "node_legacy/ipfs-message-port-server/dist/src/files.d.ts.map":
    "QmcHWcyi2fLfqqzDNanASJ657S9kVZAFiCEAyMz8rzoUKR",
  "node_legacy/ipfs-message-port-server/dist/src/index.d.ts":
    "QmUBBjnhLn3zgaX9XS6XXEnmSXA6aJRMhQWKDFRcxUHqo7",
  "node_legacy/ipfs-message-port-server/dist/src/index.d.ts.map":
    "Qme8AciEXCfQy8eZhwMhpFcCdE7cH12URucWDFHGEHPHRP",
  "node_legacy/ipfs-message-port-server/dist/src/ipfs.d.ts":
    "QmR7cB6sHzPUUwFQfZc51f9S7dLrNv11wcZfhRgMW3XgYF",
  "node_legacy/ipfs-message-port-server/dist/src/ipfs.d.ts.map":
    "QmZVgFECqULeWjwuu332CgHC4DN1xj71Hoq31xXkveNKkT",
  "node_legacy/ipfs-message-port-server/dist/src/server.d.ts":
    "Qmce3uPgWoxmvHirbg4uf8w1is9HeK5VYgFcMTv24fqSgp",
  "node_legacy/ipfs-message-port-server/dist/src/server.d.ts.map":
    "QmQbVgoCyef9VusSrBCG1m6mbbsVbDwVWPiriyfdi3Hbh6",
  "node_legacy/ipfs-message-port-server/dist/src/service.d.ts":
    "QmSkwRVtdgtKqB3gZw8ZFTPBGbC4aT7dfGD9yk25nqGPTG",
  "node_legacy/ipfs-message-port-server/dist/src/service.d.ts.map":
    "QmZNt3LU7HXu5CrvEByPxiQJdm9yv6SfhSHeEzPKSr4tvT",
  "node_legacy/ipfs-message-port-server/dist/tsconfig.tsbuildinfo":
    "QmPrSE7a29CkHY7XGege1yv2ouDGE5P4jYkDG6ke8KSfKV",
  "node_legacy/ipfs-message-port-server/package.json":
    "QmesLEDq9JrCY78TBekbmeCxB4vgAhC1CAQzo87XoJe1GW",
  "node_legacy/ipfs-message-port-server/src/block.js":
    "QmdvQDazwMrzhC9wg8XtBU5djALdejVXy7MmHBb7cfMiai",
  "node_legacy/ipfs-message-port-server/src/core.js":
    "QmQoju6R8A1LmiqYLNkAbsDPuAmYiNjDgUzbFETqTKYpbo",
  "node_legacy/ipfs-message-port-server/src/dag.js":
    "QmdbbkdTdV8yMQfJszDexEyYCtnVWjEfJUeHC3AZhZYKw8",
  "node_legacy/ipfs-message-port-server/src/files.js":
    "QmY1HZAFj8Ds5HjcP9neF36tieF7krZFiiHPJ4AqX2GPNS",
  "node_legacy/ipfs-message-port-server/src/index.js":
    "QmT7qMsy1ZkwMjtAzS3YntD4mmrCxRAcEedZqGbUR7HH7c",
  "node_legacy/ipfs-message-port-server/src/ipfs.ts":
    "QmcBdwFFhnCjn6QCYByqYjfg2KtZEkazysfYCmtHS97bao",
  "node_legacy/ipfs-message-port-server/src/server.js":
    "QmS892z6Pta4c6BFkNvijtJtneCpfVNyqxrjGvAFbCNqGW",
  "node_legacy/ipfs-message-port-server/src/service.js":
    "QmbbwNuvEyzN2kADS1Dm5nT9FvLPmkKbKnJjevCVGdHxAH",
  "node_legacy/monaco-editor/min/vs/base/browser/ui/codicons/codicon/codicon.ttf":
    "QmSZoSuoxtUCZTbioWHcgYFer5h95B5aCsnmZKTKfGBi77",
  "node_legacy/monaco-editor/min/vs/base/worker/workerMain.js":
    "QmZY4NhzyRmiNk6DmxApE4ZTaaKFDxjRLoNqtXuroQfi7f",
  "node_legacy/monaco-editor/min/vs/basic-languages/abap/abap.js":
    "QmQadeJmRHXKA2232bheb9SxKqPyXY7oPa4E3et5buMTcP",
  "node_legacy/monaco-editor/min/vs/basic-languages/apex/apex.js":
    "QmdTSqNjLTmADzU43tSBXwSHdogSThZarMkY7WWyVQWJm2",
  "node_legacy/monaco-editor/min/vs/basic-languages/azcli/azcli.js":
    "QmexFPQnTzqbQ8JtsDNCzs4fj1G4ch8DLy6aoxWkDp18p1",
  "node_legacy/monaco-editor/min/vs/basic-languages/bat/bat.js":
    "QmRrBd8emiRwE5HwDAFDWn5kKL35nmiDEYL7bpKEtuWAne",
  "node_legacy/monaco-editor/min/vs/basic-languages/cameligo/cameligo.js":
    "QmddTpj6zzJsnRZYtYPNeT7RWU5MHKaxamHBp5V4u3pqen",
  "node_legacy/monaco-editor/min/vs/basic-languages/clojure/clojure.js":
    "QmZdWQ2FHLuFf4VUQpkxSL67vMe7TDQEBcPXS9VoTER7WP",
  "node_legacy/monaco-editor/min/vs/basic-languages/coffee/coffee.js":
    "QmavgCnQgBtsgVqkxzStEN8dpNTg9Z6w9Do4uvTLxxTHcc",
  "node_legacy/monaco-editor/min/vs/basic-languages/cpp/cpp.js":
    "QmU3BGe6JR7krSiVvjjr7DC8Uhosoj97ePzRn5Z5GFq7gk",
  "node_legacy/monaco-editor/min/vs/basic-languages/csharp/csharp.js":
    "QmQ6LLCyteSfTY6KnTy6fnWbV8LutMfEBRArb3FockGJ7T",
  "node_legacy/monaco-editor/min/vs/basic-languages/csp/csp.js":
    "QmZfWP8nUbqcbuRo4cALc1868WRtHsg3Hu8jGcHtpFug6K",
  "node_legacy/monaco-editor/min/vs/basic-languages/css/css.js":
    "QmdEwNFFEC7rNgjWF8pvXiiyV2n8i7jbwoARmFWGaN8p1q",
  "node_legacy/monaco-editor/min/vs/basic-languages/dart/dart.js":
    "QmcjX1xh9MX5GrT1YcGBU1jmcJFaELyKqfLQzbGE1jWSC9",
  "node_legacy/monaco-editor/min/vs/basic-languages/dockerfile/dockerfile.js":
    "QmaUQuPueApnZpStjpab42bhpqyH2qfwyAEgha89LQ5412",
  "node_legacy/monaco-editor/min/vs/basic-languages/ecl/ecl.js":
    "QmcnMijWQc3o9H72ic3sCQDvgHqeMQduiEysos8oDniJva",
  "node_legacy/monaco-editor/min/vs/basic-languages/fsharp/fsharp.js":
    "QmYDGW5aQGDD6urL1oFdQZerBYZkk53bM58YjK4CjPDCbo",
  "node_legacy/monaco-editor/min/vs/basic-languages/go/go.js":
    "QmQK4GKHoAiNcuY8QCS5uJExNp1tXn2JRvEeFXTmxJTMhB",
  "node_legacy/monaco-editor/min/vs/basic-languages/graphql/graphql.js":
    "QmRrG6hE5a98vJPQEbBQ5o5VyC28RroqybAMGoYsLewWCy",
  "node_legacy/monaco-editor/min/vs/basic-languages/handlebars/handlebars.js":
    "QmP8FYb1oizpyU2wHnpQE9tjn7YMYb67L6sNj1WKnnq85B",
  "node_legacy/monaco-editor/min/vs/basic-languages/hcl/hcl.js":
    "QmWPEftgke8ktiXTNNu4pPeQrmdYnUtgYJ15CU8ERvKb7P",
  "node_legacy/monaco-editor/min/vs/basic-languages/html/html.js":
    "QmVAT4KarhmTCmdZnPzT9ya6RgmNPWF6SmPtmD95d6uWbf",
  "node_legacy/monaco-editor/min/vs/basic-languages/ini/ini.js":
    "QmaKiDBK1J46vhgV74duPtPkGopdRhz3aqEf7TabprTdUM",
  "node_legacy/monaco-editor/min/vs/basic-languages/java/java.js":
    "QmfWroFaWrWVEi1uj3McTxdeYJeLQ4Heq7zFk1CMirKwxF",
  "node_legacy/monaco-editor/min/vs/basic-languages/javascript/javascript.js":
    "QmcKySaP74S5rvFXpLrUZpqR7SfTDPK38Bc8LZ3jdhRTv5",
  "node_legacy/monaco-editor/min/vs/basic-languages/julia/julia.js":
    "QmStjB7Fa811FvZKhdbPE9uYv679mpdAWW8GaSEeHPeXGj",
  "node_legacy/monaco-editor/min/vs/basic-languages/kotlin/kotlin.js":
    "QmPXsLsD2whgKyZ6qDSBruJkug8Uzzwg64YaYnjpREqxiP",
  "node_legacy/monaco-editor/min/vs/basic-languages/less/less.js":
    "QmWCNr9UbUPeyURrb1xrumd6MyRkPPc8HUQaNSqoPRxbwV",
  "node_legacy/monaco-editor/min/vs/basic-languages/lexon/lexon.js":
    "QmdWNiMh3tAGRrScRXQqrHev6BUVFcxootVTUMCnmBT1rQ",
  "node_legacy/monaco-editor/min/vs/basic-languages/lua/lua.js":
    "QmW1k1uAPTX4PZHQqHXZEct6eWBWJ1xvCL7ukkSKWKKwn8",
  "node_legacy/monaco-editor/min/vs/basic-languages/m3/m3.js":
    "QmQQmJaUmhQGmYV727NujtHmVAcPLW8NQ8F6y3r3TkbSvD",
  "node_legacy/monaco-editor/min/vs/basic-languages/markdown/markdown.js":
    "QmTCuzDbZ7u7KWXCvTnrd5rftEBZj5DS7XUKXNAHGPQsR1",
  "node_legacy/monaco-editor/min/vs/basic-languages/mips/mips.js":
    "Qma8UddL8aeBuVp3VAuN6qMjPbnqzoJ4rEXpiFTsNCKcsu",
  "node_legacy/monaco-editor/min/vs/basic-languages/msdax/msdax.js":
    "QmUdtzrNwznGLoANE2xsxwJ2SjMdSC7fEUB4EafBNmvFXA",
  "node_legacy/monaco-editor/min/vs/basic-languages/mysql/mysql.js":
    "QmQK5z6zXjBtsKYKAZX4kyVg7FbeTXgqqoyb7e5b817qph",
  "node_legacy/monaco-editor/min/vs/basic-languages/objective-c/objective-c.js":
    "Qmbmn6RZwiSZzAFvk9JYFg5xKjezRpNcVnbcHU1PkySydm",
  "node_legacy/monaco-editor/min/vs/basic-languages/pascal/pascal.js":
    "QmcuaxaiyTixwbX2fzeYDQFUd8faS7cJDfMdoHu4o46e3A",
  "node_legacy/monaco-editor/min/vs/basic-languages/pascaligo/pascaligo.js":
    "QmZipZBSoS6vrd8TttERitN1YxGby4Y56B5QMJFwNPyUTu",
  "node_legacy/monaco-editor/min/vs/basic-languages/perl/perl.js":
    "QmXDzZ4q3H8D2mJpUVE9bBv19mM6A7Yau6abWxPfXBRKat",
  "node_legacy/monaco-editor/min/vs/basic-languages/pgsql/pgsql.js":
    "QmZBXE2Z5mDz4HVQHXFYhv2Csx1eaTLmudNpbfBEKc46mt",
  "node_legacy/monaco-editor/min/vs/basic-languages/php/php.js":
    "QmTYz8PBPssQLkWSGVPMFbdGG1CeguT4U6fXLwrhJuhQdJ",
  "node_legacy/monaco-editor/min/vs/basic-languages/postiats/postiats.js":
    "QmQbCsmkNT2VVfJfa3rs4KQG4VSpngmQ39JsmXsHt4RyoJ",
  "node_legacy/monaco-editor/min/vs/basic-languages/powerquery/powerquery.js":
    "QmNtvLt5ZeKk5tvhDaNzCNcLYwNAvcn5EjG3gRrZdyWhze",
  "node_legacy/monaco-editor/min/vs/basic-languages/powershell/powershell.js":
    "QmZWWD9vaEo2svv7n96ygqBepNoU4MnH2CMHEYcDdf5VaR",
  "node_legacy/monaco-editor/min/vs/basic-languages/pug/pug.js":
    "QmbtS2jdkj5mrqNGW5Gr4SmyVgQDof3FQYhXDxvtAXy9hA",
  "node_legacy/monaco-editor/min/vs/basic-languages/python/python.js":
    "QmW8qv4RrV839ygUXXhS9YtWr3NZJxuQQC52iKW6DkT27j",
  "node_legacy/monaco-editor/min/vs/basic-languages/r/r.js":
    "QmbFiUj8NmzZjWYPj6Hn72pzF6SRPZpHAZYuyv37K2Ye3w",
  "node_legacy/monaco-editor/min/vs/basic-languages/razor/razor.js":
    "QmZFme9wrTL9AneHdRpUXPdiDnR8Khi6mZXF1s5byPU9je",
  "node_legacy/monaco-editor/min/vs/basic-languages/redis/redis.js":
    "QmRtfCUu23on3DvG7JnawRcAJQEH22DdJa5ENPeTZ7ZYhn",
  "node_legacy/monaco-editor/min/vs/basic-languages/redshift/redshift.js":
    "QmZ8fSUxQWpLMSegrMyYVAwBmWJkHqyyyy1GGDketarEa7",
  "node_legacy/monaco-editor/min/vs/basic-languages/restructuredtext/restructuredtext.js":
    "QmRK1epSWkyWUptXsRerQvrwkKzZz5xRCLxarMQeH2TbUN",
  "node_legacy/monaco-editor/min/vs/basic-languages/ruby/ruby.js":
    "QmcgkF7pc2JKy26H61ifoXePcNn8qLvSHkqVHbHGu8NZ4b",
  "node_legacy/monaco-editor/min/vs/basic-languages/rust/rust.js":
    "QmcAe36RuKN9doiiULLpLT2j1MxwSERQaW9hTmvSPNrW7y",
  "node_legacy/monaco-editor/min/vs/basic-languages/sb/sb.js":
    "QmeLjs76FTCiasjBfKUJeSCmR8CUX4SPdTKncSzrGbhv2e",
  "node_legacy/monaco-editor/min/vs/basic-languages/scala/scala.js":
    "Qmb97P75otZbNVEANAPyfUFi7VHPd51ceKLqcG1Ypjw3oY",
  "node_legacy/monaco-editor/min/vs/basic-languages/scheme/scheme.js":
    "QmPGWbVAA6PprdR4rcBVkNfanmdiLBb8BwhvYssPKR3YQ7",
  "node_legacy/monaco-editor/min/vs/basic-languages/scss/scss.js":
    "QmU3Js2pcoD9RnsboarLNwhqu7PDcy4a99zQYCqYPWMKrd",
  "node_legacy/monaco-editor/min/vs/basic-languages/shell/shell.js":
    "QmU8V9oVSr6xbkef43R2LqsWAXjktSaYgRcapmVUREfVQ2",
  "node_legacy/monaco-editor/min/vs/basic-languages/solidity/solidity.js":
    "QmNjagxH1gGzB8HzdEi4zmq4LfexW1kr78oAGNf577TEPM",
  "node_legacy/monaco-editor/min/vs/basic-languages/sophia/sophia.js":
    "QmVc12FM86QnpRboDPvKbmzc1K16uEw8sC7zMSUzg8fR7o",
  "node_legacy/monaco-editor/min/vs/basic-languages/sql/sql.js":
    "QmfTfjdtz44h38LCaDHoFf5Y1PbMXkaoZScfKDum18NJua",
  "node_legacy/monaco-editor/min/vs/basic-languages/st/st.js":
    "QmdnEQT15Q9VJzCCFq5EeGK6hqNBUJWzGGBioTce6VeaEr",
  "node_legacy/monaco-editor/min/vs/basic-languages/swift/swift.js":
    "QmW2sYnHcjUBDU1HobyKL33XKeK33Vq6TUv24LCmmJs3Fb",
  "node_legacy/monaco-editor/min/vs/basic-languages/systemverilog/systemverilog.js":
    "QmSQKczUYZHPztbdtSorWbShKkmh4V717tZJ8PR4KZay6Z",
  "node_legacy/monaco-editor/min/vs/basic-languages/tcl/tcl.js":
    "Qmegd5jMqH7PiVgGqVdR1sF3sU6jp9aQrqtGSDEoePNyZZ",
  "node_legacy/monaco-editor/min/vs/basic-languages/twig/twig.js":
    "QmRPpHoskpuPrs2M6NszL2frdL63HGt7Q19WYyunoVUW82",
  "node_legacy/monaco-editor/min/vs/basic-languages/typescript/typescript.js":
    "QmXuqf5k2auC8Ct3YY1eKExr4oRombhGjjPzet5LtKzVXS",
  "node_legacy/monaco-editor/min/vs/basic-languages/vb/vb.js":
    "QmaYNvE8koZozz7KNhKsVfNFimQXhWJjr21MXNZEyVjnSL",
  "node_legacy/monaco-editor/min/vs/basic-languages/xml/xml.js":
    "QmbwsibJBeqj5n8XrSYrJJ485ShETXp97bAzXJ6dfSv3ts",
  "node_legacy/monaco-editor/min/vs/basic-languages/yaml/yaml.js":
    "QmXcQGoymhqkBUNu6XmsxtJKFB4LJTa1ZPorTbTMdyj6bU",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.css":
    "QmbXkNnJKLvfNM4iBRYJkfY528YPV8A7B9NVAd3s5piqY9",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.js":
    "QmW9zFKi5vpWByMTNHQ9VnnL8pwrHqC1gkgwYkj2ZYQuGS",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.de.js":
    "QmW3qTpPqX9ycqapft2Xni7xkoTsufGAjgQVja9zhAkfVG",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.es.js":
    "QmSaCUy4bwMzsLS7c6H6v2ggw7GNyFtbQaMKEFGJ3XPH9e",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.fr.js":
    "QmVQsJDNumU2rp1nA7CY6Ngu7ubs2guCb6CiYnTZJKtvAz",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.it.js":
    "QmabfmXpX9NTzFNa5WnGS6JCL3wNTxf1F1KvBA1pdxZKkP",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.ja.js":
    "QmPJPymcAjuXzq5G4XKmBLwCpnWfkhRDNBHqezv7ykoHrx",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.js":
    "QmYi5VvE3ggLKUSpPGC7eh9idzQPbKpdiFpzkgAzfEj4Rd",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.ko.js":
    "QmfCFxWntu1K3jfEjaPzeHYfZ1bbZ8CsMWJuQHRPX3DVYA",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.ru.js":
    "QmVYiUHkxfHVbVYToyT3CXdWg7GmfM91irj5AW4xnN7Zm4",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.zh-cn.js":
    "QmcqoasDiKWVY77a6VpczpiBc71AqdZTGhhduQfTKqQStG",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.zh-tw.js":
    "QmbEtbUBABgGHmpAtHAm7ip5wspHvVg7tMZ5YumH7tGYxc",
  "node_legacy/monaco-editor/min/vs/language/css/cssMode.js":
    "QmexiZdpLjrhWcSRv9hqG11J9RcNzKq3KCEWjQzwuXMGnY",
  "node_legacy/monaco-editor/min/vs/language/css/cssWorker.js":
    "QmeuVXbBie3Jx39JX9Jhs2AapjCg9cm46zRSBxn28dFMdq",
  "node_legacy/monaco-editor/min/vs/language/html/htmlMode.js":
    "QmVzK31mqYEnT4eF3NJAFmgwgh1xZAHGSmKnA1Skkpzz8h",
  "node_legacy/monaco-editor/min/vs/language/html/htmlWorker.js":
    "QmNvgocmsQCnn69mVdJMDSDRKj1yDz9jXf5ia2gHL5C1La",
  "node_legacy/monaco-editor/min/vs/language/json/jsonMode.js":
    "QmZFdmAuVpg36P5TTZdnMwwciGH4pw8ZhyQXaRntg4eKBf",
  "node_legacy/monaco-editor/min/vs/language/json/jsonWorker.js":
    "QmakoMUhhPDtFACJkrDQqGmAp73CBV7qfLBB1dkW4DoF69",
  "node_legacy/monaco-editor/min/vs/language/typescript/tsMode.js":
    "QmbqBNP3zjTDdBoJb4RLe4hLWM1XLZ7hbrw9ncjro2jLB6",
  "node_legacy/monaco-editor/min/vs/language/typescript/tsWorker.js":
    "Qme5CG16onxJQaf6U6CA1JRsutXvLEeSDJvLm5SaaK8XS8",
  "node_legacy/monaco-editor/min/vs/loader.js":
    "QmZVS3KugezXqfSab9xDBT2GdHyjt4uMBfSVzyCPhwzBbT",
  "node_legacy/monaco-editor/min-maps/vs/base/worker/workerMain.js.map":
    "QmWFqQ5tsRuddVT9vHJ5HXAh8jf2Unzbaoc73MYDphBchZ",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.js.map":
    "QmdaNh1xj8RCCUASFkhnKCRorgMMvDzPzJUM7eF2ZMWbc7",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.de.js.map":
    "QmdCPRVincgSiFnNPpX75wKSimm63doioUvkCfUhqS1xdG",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.es.js.map":
    "QmVFKJiWByDT9AjCBKkTe8mzBvB6z3kW3gG4rNXmmyR2xM",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.fr.js.map":
    "QmePidANu1dzsBm9X8befBfHVHqvPPNUq74Nr4ST3jPiqu",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.it.js.map":
    "QmPdpypHx3rEgGJfGCsBSCX1DzkqSioH9K7xKjehxUaP3k",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.ja.js.map":
    "QmNkQSwuzsBGJpTY28o8skQhSvAGBN3fbNp27MG3zEsRC6",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.js.map":
    "QmYFEi95XakrhizuBCk1YRfBzerK8zHPFZRTowHnFykDx6",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.ko.js.map":
    "QmYbs5WfWncvCQ3hhJ8pxVe1AxEugsQWR4BEu8wEw4vBGT",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.ru.js.map":
    "QmZvVLi4TzhHL8GGGCa7rCnftayUQXzCvAwCrMGC7aq5bR",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.zh-cn.js.map":
    "QmQ4PikJLgCH7s5qEBLRmkrS9MmkM7XefRyz5gN2646TjL",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.zh-tw.js.map":
    "QmPiBGHvv43xtGREhW6EX97Zmv8kJxEhMp7NTqaFFhiBXd",
  "node_legacy/monaco-editor/min-maps/vs/loader.js.map":
    "QmbJGZieknHNQ7HbEYgkow7SBFEfu3MPgdJDBQ9bxAuB8u",
  "node_legacy/monaco-editor/monaco.d.ts":
    "Qmb4L21DED7KgAoXB7PfCXvkV4JTWQN4ehwpkdf6JNv8Uo",
  "node_legacy/monaco-editor/package.json":
    "QmZcryZqRY2N7kTaE3fQuEuPirbWDCvMeBVzV5QRdP28u4",
  "node_legacy/parser-babel.mjs":
    "QmNZakKRLQBUJSY8XvTCnCJoU3vWGCYEiCkFDV3WuZmtJZ",
  "node_legacy/parser-html.mjs":
    "QmNQPbdnaiQz91ZKa11kCAByJS1bjj39W1XZWranQ3dMYp",
  "node_legacy/regex.js": "QmZWiPyB2csudjP2xX6W4P1PHhZQnvMkCdBagQvCM7jMpA",
  "node_legacy/rng.js": "QmTqi8yzgAq7WJUXtTAX3ccr5meWBaHuGtXx581S1B9kS4",
  "node_legacy/simple-window-manager.es.js":
    "QmcvtuWHJa3nkqaBfFMriqZz3N15RDeGErhF26tjPThxgM",
  "node_legacy/standalone.mjs":
    "QmbkuH4RqHi2cUk3w7PMD9LDNaSkEaYA9Pcy9Wv6rTnwYk",
  "node_legacy/stringify.js": "Qmd56eDfKFpGXVEuPxrN3A3jewVkunFfdqpTdE7LCtSp2h",
  "node_legacy/v4.js": "QmUhNN2k5hbHdHWURhNAQPQLgN455FJSsf3Z8njyYMukfm",
  "node_legacy/validate.js": "QmRi1pudKp7sivw3M8Hk3EAsSRcLExsGZqiuJQCXTWjYgY",
  "node_legacy/workbox-sw.js": "QmZvvd3tM19b9a5b9hn3JiDjnu2jHnUq9qrHtz2c7yJMga",
  "node_legacy/workbox-sw.js.map":
    "QmYrZKmyENAJi6h5mFoq2CVyZzr4syiuehcFqorzAtQttK",
  "node_legacy/workbox-window.prod.mjs":
    "QmT29Y78zyhb8a7WWc2BEhS2XpZij6bJhJZnLnbKTKsE5m",
  "node_legacy/workbox-window.prod.mjs.map":
    "QmRTrYSzfnFKPQESDgH6t26Fb2AzZpn51PcCor3Rh9zomY",
  "package.json": "QmSzjEYPa5n1SNzmUJuLsZFdLQLseDfo4YyTdwzM95PS3q",
  "src/codeLoader.js": "QmZ9vH1svZH1ykL4md5WG4cCfB1AQs2ytKojdVvczBsBJA",
  "src/data.js": "QmXPkELjD2MTHJRikwAn8L6pHxCnjixf5DFS2ySRNvew8T",
  "src/db.js": "QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH",
  "src/emotion-react-renderer/dist/DraggableWindow.js":
    "Qmatqd4HAF76oyBRpW7tGEMt1rDW2TNijeNVhxZg8GwbTX",
  "src/emotion-react-renderer/dist/renderer.js":
    "QmX4unXEXsJ9wPz3DGNPgeya8cr1LrazFViqqJrRPAV264",
  "src/emotion-react-renderer/package.json":
    "QmSGJVhzTivgdwchZ5AoZSF1PgV83G9i1DXyB8mp6iiv2C",
  "src/emotion-react-renderer/src/DraggableWindow.tsx":
    "QmfXRFvz4dXzLdRYznK6isrynfqg8DvBViRfFEK8KnBSmH",
  "src/emotion-react-renderer/src/renderer.ts":
    "QmRpSExrraxqLXtqGHdMCPauSVn8ijVghpmf2SmgWKiwNQ",
  "src/emotion-react-renderer/tsconfig.json":
    "QmVf1pkrppvUoQ7dmSQ5XH7WM1PY7SqAwxR3TR8pT2oGVA",
  "src/examples/app.tsx": "QmRju4JLXE5iNjjqVER1hHqCUBbRGXDvw3WasFUKEvbs7P",
  "src/examples/starterNoFramerMotion.js":
    "QmWVABuMCi74dqH3AiGtWU1SEBzvmhiRCADWYCupQZYuAs",
  "src/examples/starter_framer.js":
    "QmaVBy5PCmFhEKZ7gMtLZUyAy8FBfgDnPeLm6HgCnrC6KF",
  "src/formatter.js": "QmXArukccKkWgDVKtZWCsNcV2gmYhPLursST8CP1x4GVBi",
  "src/hash.js": "Qme3eproEVUGrmqhWou5NzUVqzv8iWg7cUwHPPfTjCTZ4t",
  "src/importScript.d.ts": "QmV1V5Fb2ZxP5Kn31nSU7FS2TtrDMg6wR7sMTsKeeR1txL",
  "src/importScript.js": "QmWNzoXJSf9aHxMEbDGsdMfyfJKwtpfL1Q9ni1xuSF5c9X",
  "src/ipfsClient.js": "QmTjjhptV5UYnbKqN8HtGfuskZWiUz252ycqBbfwZaSbFk",
  "src/openWindows.js": "QmXwq3AHyeNWrdG2WrVzkaujrJZzzJtyxaHAdRivSrjoKU",
  "src/refs.d.ts": "QmV4VN2uGcNzHPQi51JkVC4p9RzDpe5sEk4sX4u9ub3J4p",
  "src/renderPreviewWindow.js":
    "QmRLs3SMWp9GMjBXMSY5NuAso9qdJ2tY5UBmLa4SKpybhu",
  "src/sendSignalToQrCode.js": "QmR9iLJ2C8AbnEGacUXf9eb7GLvXgAweDANqUvdDnSYcA8",
  "src/shadb/dist/diff.d.ts": "QmXv6B78NKbJLMyErUn6XRUkXxvkata8i6CR5JCC721QJx",
  "src/shadb/dist/diff.js": "QmbfZsnJhysseRS92eSEc2SX7hBaaLPTojb7oqc6XaBqzy",
  "src/shadb/dist/diffChars.d.ts":
    "QmR9hNHu2ZNp9CopGNmME4KgNuyAzMZcZ1hUaZwnjXfkE4",
  "src/shadb/dist/diffChars.js":
    "QmNRK5ZC2ZEdMfrTozGkgGJdHiMWYbfk84Gi3kBD4rgMBQ",
  "src/shadb/dist/getDbObj.d.ts":
    "QmSN6JKpmgGd8mwb8gEKViV5juyt4jpw4e5wQqFpzGUiF2",
  "src/shadb/dist/getDbObj.js":
    "QmW2LmUqcg8fzLtjroo3JHbUUXDq16X9n3dBUE4WUVQzG3",
  "src/shadb/dist/sha256.d.ts":
    "QmQCcqJvRmWrgHXvwifwqPziL9UUNckyDZbPbLGb4SbS9k",
  "src/shadb/dist/sha256.js": "QmWZyJbdb4B22fLgpbDqNo6wU2sWccyecceKz6bor64hFi",
  "src/shadb/dist/shaDB.d.ts": "Qmb1jkMJhCGHnrFigsUkCNo1uwebGfrxXQH4EHSpnh6zFY",
  "src/shadb/dist/shaDB.js": "QmX5mSevBrVHk6mpp1VNaCMqmCYC7azWBUFgrzpHnG4NDp",
  "src/shadb/dist/vendor/diffChars.d.ts":
    "Qmf31P3dFhCyz9X8GkuUytpn3cmJwsggF4kPTbmwaiekRt",
  "src/shadb/dist/vendor/diffChars.js":
    "QmcC8KRucgoFQ5EQ43yykZAVDCoYUeCS9tNaHmhXhaVAaQ",
  "src/shadb/dist/vendor/diffMin.d.ts":
    "QmUEzhNXqsRtc45fB5if9wchLEL1wgmY58wX27E5zUCJtp",
  "src/shadb/dist/vendor/diffMin.js":
    "QmQvwZBWXeTmVqjfipWeA5k2L7MMQd4ooqEe7qVAJs8VwV",
  "src/shadb/dist/vendor/idb.d.ts":
    "QmRDw3SijUK8mQZ2H5CzJtKk8zknGsCz4mz58EzsjEC738",
  "src/shadb/dist/vendor/idb.js":
    "QmeDaTt5WPt58TYHpMzMyURp7hMdfUiKm6AbwEtZsQGoc9",
  "src/shadb/package.json": "QmdEBqzb1MVrtd3kw5A6VZaRHLR5fk7c2KYpGjXroKhP5G",
  "src/shadb/src/diff.js": "Qmda6YhbwL9XYtLgmK3HGPpGw5zFcRox54cRKaJjNUMWAE",
  "src/shadb/src/diffChars.js":
    "QmWyRfBNH9Epu8Fg6qKghPCm41ht6xG54jZ6iANubmRv6d",
  "src/shadb/src/getDbObj.js": "QmWHmVpjUyjtseZDdvxbZNYiDx3MXTgmZhwBpqCP8CrEtb",
  "src/shadb/src/sha256.js": "QmUYHM48BTQuN4TFNHBH5dYaZ16FRNu2tbeF6JdHnBKc6g",
  "src/shadb/src/shaDB.js": "QmQ7TuHw5n1XZVwpfsxfMeWUHYqc35tEQx4ypbJw523GJV",
  "src/shadb/src/vendor/diffChars.js":
    "QmRGpEFyhuqLyPYt67ZFftdPK9PMf8UXuvHfXVhZyQ3YAJ",
  "src/shadb/src/vendor/diffMin.js":
    "QmXDjtDjFxzUemcTkNDbQqSimHTNDcpLsfxq5PhbwmuXSf",
  "src/shadb/src/vendor/idb.js":
    "QmdrnoscF7ihtuyZCd1iv7g6Zpvem23yNn6AHU6xTaV5XU",
  "src/shadb/tsconfig.json": "QmSweNRyD6aAUjpMnt8zKE5LAxvvLoZPy9Qj3r4THEhaUd",
  "src/shadb/tsconfig.tsbuildinfo":
    "QmfVuhqQSTcAgMnYK8MJ8K2tehUXMMJRY31wUJaZAqh13m",
  "src/share.js": "Qmf7hs1E4hbGcVzd9FosQVc366akpF5dtrBBfvyfVYKz78",
  "src/smart-monaco-editor/LICENSE.md":
    "QmQAGWaCTkwWF9GMjvoLgCMMgec8bKWRgzB29yti3b5zAL",
  "src/smart-monaco-editor/README.md":
    "Qme5mqxxvVorXuV6y3Wit23U9pUhaMfSDR2YDx1esCCruY",
  "src/smart-monaco-editor/dist/editor.d.ts":
    "QmZZZ3UjjGrNVCuyDx67fvvmf1rPmq8wnh9DUcdAoLMtsK",
  "src/smart-monaco-editor/dist/editor.js":
    "QmTkyhRG8Jvpa57vLdDoq7T8tTB32G3gQESXcV9tGyLGjw",
  "src/smart-monaco-editor/dist/monaco.d.ts":
    "QmPNrqP54db6P45nw6d3BFmerEAxLzbz2ynbByCrLderPF",
  "src/smart-monaco-editor/dist/monaco.js":
    "QmbJtqvS31TXa9GHm4e8FjK837kpHPU13fZkHbgkFL1FQR",
  "src/smart-monaco-editor/dist/scripts/screenshots.d.ts":
    "QmS5gMBfgk8pSufk8fk4D9VXz74GvEaKgB8sP1dJTDKMtQ",
  "src/smart-monaco-editor/dist/scripts/screenshots.js":
    "QmZj5ZmAy4A2ow36UjUkWKkK1HXKL1tMofYxTYLVoSMJoD",
  "src/smart-monaco-editor/favicon.ico":
    "QmWF8oNe7SDdaY6t4WrJ8ZzM46dHEFmHDXzd8MBeNrELxe",
  "src/smart-monaco-editor/index.html":
    "QmVQxvRvunUpXoZqC67ZUPoNSRpvyB4dKNmEQTtntCNqms",
  "src/smart-monaco-editor/node_legacy/@emotion/cache@11.0.0/types/index.d.ts":
    "QmUCj2Y8UvRu3qr495TxRWLjotqJVpGW4m2f373ML9J4q9",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4/types/css-prop.d.ts":
    "QmcqPuhFmv4w5Uaa1zarPmNPW2rEUEuTVpRbkMvkpuRTu2",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4/types/helper.d.ts":
    "QmTgJLTGDTZvVBrNvXmtPZT9W4ekHjXDM4ao62wLddJFo2",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4/types/index.d.ts":
    "Qma8jqDFMjj4MFpsCgZu2BA4PoRBgJpqNRjvG1S7JRwNLN",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4/types/jsx-namespace.d.ts":
    "QmNjM3vwg7JVnPCgNY55nxr6MDNnZfnR46xhNkqMRRWrSH",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4/types/theming.d.ts":
    "QmRR1zmJ1QThGaMQP9CZyo89ny6b6cnN6T4EsNfVuMgMBZ",
  "src/smart-monaco-editor/node_legacy/@emotion/serialize@1.0.0/types/index.d.ts":
    "QmTe7sNkKt6fppui5WQ6KTp4dXAChyirJpmfaiwja8EFLu",
  "src/smart-monaco-editor/node_legacy/@emotion/styled@11.0.0/types/base.d.ts":
    "QmcrDAZs3J1SbebjXv1XmfK5BEdrYAqy4E7vEVFVqjM4RV",
  "src/smart-monaco-editor/node_legacy/@emotion/styled@11.0.0/types/index.d.ts":
    "QmWD3WGSdBRhBbmmv1P4JJyA4XMfazmV8CkY7pFrnVYMeb",
  "src/smart-monaco-editor/node_legacy/@emotion/utils@1.0.0/types/index.d.ts":
    "QmbvhexADU4v3XaaBXJxD4X1g7DMxFPsCWvytbsqvHpAKq",
  "src/smart-monaco-editor/node_legacy/@types/prop-types@15.7.3/index.d.ts":
    "QmXaJ9waDpQDB5rY24AWJwebJhXAvPZ8Zg6xyardJjkVeY",
  "src/smart-monaco-editor/node_legacy/@types/react-dom@17.0.0/index.d.ts":
    "QmUp6zxmTL2cBSqSummQCsVUr8ksVPku73xR47jjGqPyTL",
  "src/smart-monaco-editor/node_legacy/@types/react@17.0.0/global.d.ts":
    "QmRoYgDX13hcDWSUDRNxFZcnPyTqWzzkhJNF9X29Vxrr6g",
  "src/smart-monaco-editor/node_legacy/@types/react@17.0.0/index.d.ts":
    "QmXfhdDibqw2JGSQdiSz55jT81znjCU7yvQ4dmGW5UeKkx",
  "src/smart-monaco-editor/node_legacy/@zedvision/qrious@10.12.14/dist/qrious.d.ts":
    "QmY8cwFxtfD1dPVtvXhWR5uvMpaFVN8VJ2JXNbR2U2hYne",
  "src/smart-monaco-editor/node_legacy/csstype@3.0.6/index.d.ts":
    "QmW9j7PM3CWM83KSKZi7fkGLXVV8MBY7gEyFfHNbde8RjQ",
  "src/smart-monaco-editor/node_legacy/framer-motion@3.2.1/dist/framer-motion.d.ts":
    "QmaGk1drtubxue8LG5k7eHCejNsde79Q21m9tvbYdt7359",
  "src/smart-monaco-editor/node_legacy/popmotion@9.1.0/index.d.ts":
    "QmfVp3E9UrnADC6nJMc46brtFfymJLfhTn42Av9ftYQUaB",
  "src/smart-monaco-editor/node_legacy/popmotion@9.1.0/lib/index.d.ts":
    "QmfVp3E9UrnADC6nJMc46brtFfymJLfhTn42Av9ftYQUaB",
  "src/smart-monaco-editor/package.json":
    "QmQRuPhN56cYWDtMzAN9cgT3rUBTfTjdv6L5hoRjMymXyz",
  "src/smart-monaco-editor/src/editor.d.ts":
    "QmXFYH4YMX7W5dDHwbLZS5NqtCSqRf6n9NcmaEZjFsLBtF",
  "src/smart-monaco-editor/src/editor.ts":
    "QmSX1eCR6u33NTDAmV4HhXRV7D9BBr9c3zqQ31mHbThp9h",
  "src/smart-monaco-editor/src/monaco.d.ts":
    "QmdsjvXNr9ufGi4osAtDQuo4tji41DfCKzbCNhLo7F5Gc1",
  "src/smart-monaco-editor/src/monaco.js":
    "QmPU117QEcnXLQb58T54ehhMzj79d6BYATsSz3wgiV7Gj1",
  "src/smart-monaco-editor/src/refs.d.ts":
    "QmUXoLQ9zNGWxd1c1yNBjSf4RoTwFMEbLcq8hL2ewCd6ba",
  "src/smart-monaco-editor/src/scripts/screenshots.d.ts":
    "QmS5gMBfgk8pSufk8fk4D9VXz74GvEaKgB8sP1dJTDKMtQ",
  "src/smart-monaco-editor/src/scripts/screenshots.js":
    "QmYUzn9XSFiduCLmzj4Ewcn5GnxwPaDKYDGAxdakydncmg",
  "src/smart-monaco-editor/tsconfig.json":
    "QmTqtxpjAgAVTAsFTHNuHE2cRCXSzKzfsrVwhFSaGsqea8",
  "src/smart-monaco-editor/tsconfig.tsbuildinfo":
    "QmTvPhFvNDpBME8am5MbAXDBAijNHpx3F7Aq11BzdRRHB5",
  "src/starterTsx.tsx": "QmQ9AHQxPPsDqonKSH5q5zHeiHHSds2P7gcmUVEWkm4QW7",
  "src/templates.js": "QmbbHgU51zh5JuuAPLsxHngGsyEmjYX3o8LA8dtDph18UJ",
  "src/transpile.js": "QmcqWzx4L1c3dfG7jrwQqy23wrx9mn6jgjoEAxmGyfEsPp",
  "src/workBox.js": "QmUNb95Uy4M1qwMACE8oBvhEP2SYyUCc5gHaAYBs5YpV68",
  "src/workers/files.umd.js": "QmXz9UD47qwzGmRfPPT7EFiX9Xrp8H125nNkJRgRmtUMrm",
  "src/workers/ipfs/README.md":
    "QmbdTTJXo4rWcSfDFooCBXWGYtCnbixPpSJh9hjAQ6KMFw",
  "src/workers/ipfs/dist/gateways.d.ts":
    "QmaqVQHmb2ESQaLajE5YAbgw1PzYPRwpLbwEFLJfEBARWk",
  "src/workers/ipfs/dist/gateways.js":
    "QmNVuHYaC7MuqYnsRJ2J9kY7TotGALZ868F2jx4ryvmETK",
  "src/workers/ipfs/dist/ipfs.client.d.ts":
    "QmViTDo9BBn2p3h6UyQuFXkRAjqVnKMV9PhkqsaKe73xwE",
  "src/workers/ipfs/dist/ipfs.client.js":
    "Qmdp2HBvcvTJPkYqHHJ75RauWt8koyoqqVAhmPWGP8Q5i6",
  "src/workers/ipfs/dist/ipfs.server.d.ts":
    "QmS5gMBfgk8pSufk8fk4D9VXz74GvEaKgB8sP1dJTDKMtQ",
  "src/workers/ipfs/dist/ipfs.server.js":
    "QmZBVJyLM1r4wZHySwQ3hxKUQCZXsV3fL63BScffj7L2BJ",
  "src/workers/ipfs/node_legacy/ipfs.min.js":
    "QmWQMs9pJDk38iaxBKSgCXbwuPXgRqsqHQtTabqQHoRhKF",
  "src/workers/ipfs/node_legacy/server.min.js":
    "QmWQMs9pJDk38iaxBKSgCXbwuPXgRqsqHQtTabqQHoRhKF",
  "src/workers/ipfs/node_modules/typescript/AUTHORS.md":
    "QmbUkjAcMzURNhcZiEj3cuXrPXYorZxj8MQZHHwVuecGzx",
  "src/workers/ipfs/node_modules/typescript/CODE_OF_CONDUCT.md":
    "Qmbno2miGRsQDWbF5GyJbu81ryjVJeGoJ7j6gi2eT1p7YD",
  "src/workers/ipfs/node_modules/typescript/CopyrightNotice.txt":
    "QmS1GmyY727644bWHG66shSwkYfG8g2oceJb9oSjow4R4o",
  "src/workers/ipfs/node_modules/typescript/LICENSE.txt":
    "QmXdVa8YauWC3uob7iZT5YpjA6md2LZnxovWAmXjQpvwhv",
  "src/workers/ipfs/node_modules/typescript/README.md":
    "Qmb2fihv2g1dLJCHboaANdZ4i6LDZoMkjKKJ6V9yRNWqzr",
  "src/workers/ipfs/node_modules/typescript/ThirdPartyNoticeText.txt":
    "QmY9QguZFF1fSXoJ9BoVZoA7otNPG3RtGNGteZq1WFuRw6",
  "src/workers/ipfs/node_modules/typescript/bin/tsc":
    "QmWhutcuZnHFh5DnWkC5QkSRUVov5mRr7HBMfTQAfvK1uY",
  "src/workers/ipfs/node_modules/typescript/bin/tsserver":
    "QmWBnqadu9d872ukazgyoxv9UAB6YQACuUbL9BbR3LL8o1",
  "src/workers/ipfs/node_modules/typescript/lib/README.md":
    "QmatSGmQ2RDmHA3rrRVjvyXtjTPX83EsfcSs8iiA6b6bXF",
  "src/workers/ipfs/node_modules/typescript/lib/cancellationToken.js":
    "QmP81TyX5EYJiFMPTQE88f2nA9AYXJ1JNoPbEc8Xo2sTUb",
  "src/workers/ipfs/node_modules/typescript/lib/cs/diagnosticMessages.generated.json":
    "QmWF1N7WeDuqj49VHJFFRr4n34UoivU8dAEsmvaPFn2V2r",
  "src/workers/ipfs/node_modules/typescript/lib/de/diagnosticMessages.generated.json":
    "QmWBRJv4rfBkQ7HQTRfhb63x1mYcJfrjVxFCbdf54yZ4nw",
  "src/workers/ipfs/node_modules/typescript/lib/es/diagnosticMessages.generated.json":
    "Qmd9Wx6fiQbhFxUG3ZjXSeaLkt9LUfxKwr6r4EA4yjakF2",
  "src/workers/ipfs/node_modules/typescript/lib/fr/diagnosticMessages.generated.json":
    "QmX6ALiMYDfPQW6rNYSksG18sVUojEtRTJ9s94mZG4aMqp",
  "src/workers/ipfs/node_modules/typescript/lib/it/diagnosticMessages.generated.json":
    "QmQafoPQoftH5hkDuhBcPA7yzEbdym1Ty6DrDbf8dnBQEk",
  "src/workers/ipfs/node_modules/typescript/lib/ja/diagnosticMessages.generated.json":
    "QmZy7gJhZVcpcgWhDxrCxDyNcKnM69jZNPuQtFPKuQVoBM",
  "src/workers/ipfs/node_modules/typescript/lib/ko/diagnosticMessages.generated.json":
    "QmNY3MAWnvkFZWY97irLFzqGQabSYCBrbrDqG3KRRqAXzB",
  "src/workers/ipfs/node_modules/typescript/lib/lib.d.ts":
    "QmdjjtxkEEzw79sfLNoLJqE78b1sPv1FSq6hUje4gvRMbW",
  "src/workers/ipfs/node_modules/typescript/lib/lib.dom.d.ts":
    "QmRc94aUMoF2JkuMuypBBSkAwaQvJ51Ux98rzthmpHrEJ1",
  "src/workers/ipfs/node_modules/typescript/lib/lib.dom.iterable.d.ts":
    "QmP1k8cTCtB84UN6kumq5sX4DtwUCMvVwqckcPSiA6vAMD",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2015.collection.d.ts":
    "QmeUsyq7Sq8aHWrFGBKzUJKCmcoZc8BDubKthHjHHU2yw1",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2015.core.d.ts":
    "QmPkD4Kyh6QFKXweyZpxzZMK7Kby1a1gqRxRmj72HxSai8",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2015.d.ts":
    "QmZ965jjxdwMvAbpEPf93gej79TVZP1oj2iq5vycbPeroE",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2015.generator.d.ts":
    "QmV149NLSatoLDYGaZeLoWENULTMhAi5Q9DgVBTzKvbmvn",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2015.iterable.d.ts":
    "QmT7pXCJPR9ATRLiyQ3MXX2LxQx9gyZcB8ktGE7A1d8bwj",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2015.promise.d.ts":
    "QmNjfKhKY934FuoBirEWU6vWn9Y3MK8jTJVcq7KRgFwkth",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2015.proxy.d.ts":
    "QmdgtavVza6U8t8UkKrV3zWkZC1UpiyQm6dRj9fgW2o7gP",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2015.reflect.d.ts":
    "QmV35cMN6eQ4R3fnTxYSPABLvKTSinUWJxFVDGTxZCqRqt",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2015.symbol.d.ts":
    "QmbFQXgnp54azoLPoVQNVae9bmLwvEwBfffTGgk4Wzv327",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts":
    "QmXAwncVpQrpBrVTragyx9QV7Q8VXt9VeYncGsS4jAfiQD",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2016.array.include.d.ts":
    "QmWfAQxCnM7bDRP1zTg4Wbg5jgPhHSzRHee3uxqnsqRL6S",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2016.d.ts":
    "QmRG2SKtAUNVpU7sSRAFtHMY2izRKSSyRubWYQNGA9XtkM",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2016.full.d.ts":
    "QmWjsAA5efgC3m3VzYyNU4QfEgiyrqhQPS8GS6F76UFvfg",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2017.d.ts":
    "QmcD24cKiVP77TQTrGxKVVukfeyJnFtmLMiDK6SEYfk4zU",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2017.full.d.ts":
    "QmZZbYpMTBM6L5h41g9oU39vWqZGajE6fRvPrPzo5qDHef",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2017.intl.d.ts":
    "QmXtHFimoSLunrCmDXodp7yRdyVfhqU8ZVLr5rJGZ7z85P",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2017.object.d.ts":
    "QmZQ61EBemct4VPbJSzjVGHdQiGfmAyb1vCjA9zzCmp1bX",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2017.sharedmemory.d.ts":
    "QmcqDjUo4TpaWP6yqvYSHQ2eaioT4RCzSDpJkVjuZL4A7b",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2017.string.d.ts":
    "QmWaAe3wASwZbUfkAQs7Q7X77JzpnDbsn5QCSPAwu87bs7",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2017.typedarrays.d.ts":
    "QmZ4jibVbR5FqawfdBkxGaadKNtz55eTcqpTZgFJxZhbe6",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2018.asyncgenerator.d.ts":
    "QmYAq8JsuHoPL5eU8oKJaHVJe2J7rGaohGnmUPfhiS4Dio",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2018.asynciterable.d.ts":
    "QmWumppFm7CioN58syBxrfqdG7DR1hCD5DuDSYV1zJKT1H",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2018.d.ts":
    "QmTkQZYKq6ezcN423oZe5NEAhiTkrx8RNizHmNR9KApMgm",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2018.full.d.ts":
    "QmUrmAD4kSudaRvrEBtgchkDoTTChSaKXVTQiDdMDEQ5bf",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2018.intl.d.ts":
    "QmcwkBGCE5hVioFDtve2o1kjB1SPnnFo31s354d5RLgvgP",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2018.promise.d.ts":
    "QmbDoB1zy6CCyA253gD5mWSrVMcgnZC7zxVKaSL5exmX1y",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2018.regexp.d.ts":
    "QmRqABj32iJoC13B1WbNm3veRp3wFMdAaCbgMeJcDVpc8t",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2019.array.d.ts":
    "QmS3ZKnp7u6yV9asQiyvdSa5fwR2ozMMh685n3pohUTtmc",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2019.d.ts":
    "QmUACLTdDpwxcWQLeRLhEUxtbYduZEEkGa7439D8mLmt9z",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2019.full.d.ts":
    "QmNr2QwEujPovtTkUg2172bKtY2rzV2Qq2sPZG8PwgTkCp",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2019.object.d.ts":
    "QmSQF8Doqwn8M7Lg3joTH1xKWbiJTK2tSYjwf7VFgBdkrU",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2019.string.d.ts":
    "QmRnqPkrf7hs7GvYEsNTRWTYEyPTL7fs2wSCSh3GSsww8S",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2019.symbol.d.ts":
    "QmaxvJqfcXvbZTq1gEBaQUvRno4BWmeVChGcLyYRCP77YR",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2020.bigint.d.ts":
    "QmaRJpBkLYt6WhqGTCTfSUjMBrqpBhv8L4Y7Mk79RnDedV",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2020.d.ts":
    "QmSK5ABTyFtXbk4GrS7akemAuVF3yDmoduRSUoBp9mcYoy",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2020.full.d.ts":
    "Qmcocju7Xp6ZCVV3nKwYsTELpr4ziz2CjQXVAQKG54p3hv",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2020.intl.d.ts":
    "QmWstQZikh3RZsiFTZmFKCJfArE8jPGGQLeySK7tfShGeD",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2020.promise.d.ts":
    "QmTKKKxDk4FJFRERaU6midZoddftwQHLCbBskH3tkctRgn",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2020.sharedmemory.d.ts":
    "QmReSDfN75CbgA4JnxkYrVpr2gFZgDcb8wfpnP2fCRuFDp",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2020.string.d.ts":
    "QmSrbBxaYTnoHq3tRmTJS9Y7N6UA2bLGEogEzz1t1UP6pN",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es2020.symbol.wellknown.d.ts":
    "QmTJqgfqkzig7C7EHwuMXptV3cGQXZhGVxVgNh3kYcEFSY",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es5.d.ts":
    "Qmcp3MuDPh7Ej6R4ZsgauPurTt4Jnk24oaahvjgprVzzbC",
  "src/workers/ipfs/node_modules/typescript/lib/lib.es6.d.ts":
    "QmY4zKEDiCPKA8cgtNTw6EmfM3vs4EbzJQ8yk6iYJDZLsJ",
  "src/workers/ipfs/node_modules/typescript/lib/lib.esnext.d.ts":
    "QmaxdBFGgoad5kjMPiBM5xRPUXquxWG5rdw2Ujy3mshV8g",
  "src/workers/ipfs/node_modules/typescript/lib/lib.esnext.full.d.ts":
    "QmRZaoZqtx8R1YrnRGJE6K79B2qmk5z9P7UeeUoT38Fkbx",
  "src/workers/ipfs/node_modules/typescript/lib/lib.esnext.intl.d.ts":
    "QmXxnAAfvYoKXrdxULYbh1jdZkqXJ79qpDbfNG65v87UCb",
  "src/workers/ipfs/node_modules/typescript/lib/lib.esnext.promise.d.ts":
    "QmetQ5HKWtvBNqWnHzAyYZoYyNBPQ9WDSbPPCs5TdCX7Kn",
  "src/workers/ipfs/node_modules/typescript/lib/lib.esnext.string.d.ts":
    "QmSxvJpZBaZ6nxjatuCXxVMBjSd5msZXu7nxEejVQoUJyT",
  "src/workers/ipfs/node_modules/typescript/lib/lib.esnext.weakref.d.ts":
    "QmQ2RC1Dym3s476Fv4siT4trmzZ9jJavpCT8Tsz7DspdqJ",
  "src/workers/ipfs/node_modules/typescript/lib/lib.scripthost.d.ts":
    "QmYRkAwdyqPi7KywqymRraSsFseY3FzmijWoBEhaUpDCqh",
  "src/workers/ipfs/node_modules/typescript/lib/lib.webworker.d.ts":
    "QmPcxUchddVJikewiunsTdojU5VQqiia7XWBPtbxCTmwR8",
  "src/workers/ipfs/node_modules/typescript/lib/lib.webworker.importscripts.d.ts":
    "QmUbNfDnpFTihxiLHYXd76KYUACnHPnWaYmcTvJUzheWNw",
  "src/workers/ipfs/node_modules/typescript/lib/lib.webworker.iterable.d.ts":
    "QmYFAzmsTJrMH2CbLprT39b2pysi9qQg2vaNDKJKT5sND9",
  "src/workers/ipfs/node_modules/typescript/lib/pl/diagnosticMessages.generated.json":
    "QmXZyDyMWwwC3mQoe5awMGoJhYdLFfZspjS11kjJN6i7mx",
  "src/workers/ipfs/node_modules/typescript/lib/protocol.d.ts":
    "QmbXrGF1k8TZvEkj6BfqDaV34vVX2xtHmQgMUS3RXvZv7W",
  "src/workers/ipfs/node_modules/typescript/lib/pt-br/diagnosticMessages.generated.json":
    "QmPsUVAUNBRxgGo73xJZ5WjX2x5LMWp6RdBA1NnP4LJ2XT",
  "src/workers/ipfs/node_modules/typescript/lib/ru/diagnosticMessages.generated.json":
    "QmP4bN6j4Q7gmnqZZF2rYxbrBbN1nNigTBKVnBTR2v4sC2",
  "src/workers/ipfs/node_modules/typescript/lib/tr/diagnosticMessages.generated.json":
    "QmcTmKaBL3itxwW4wxEUF5WhrwdPkSQLz3hvdavMe9G4Vg",
  "src/workers/ipfs/node_modules/typescript/lib/tsc.js":
    "QmUgmRVVjMnvY8jQr25PNAbRY7bP69dtFhhBd38zQv44LR",
  "src/workers/ipfs/node_modules/typescript/lib/tsserver.js":
    "Qmex7F1xAuU27JVbZcMedkjnYxiFczx4uhJba6N2yar7Bi",
  "src/workers/ipfs/node_modules/typescript/lib/tsserverlibrary.d.ts":
    "QmdyAtZUciA1ms3pNJpVfSkXrMJDeiFxX4LmL3yxXKoDwr",
  "src/workers/ipfs/node_modules/typescript/lib/tsserverlibrary.js":
    "QmWnj2zbez667nK8dYESYkMTY5sk99bg85bihQMzBkkkNS",
  "src/workers/ipfs/node_modules/typescript/lib/typesMap.json":
    "QmSxBQV7VACeSvD7cMNMUuEibYMmEbH9EcSNFHg37CNQop",
  "src/workers/ipfs/node_modules/typescript/lib/typescript.d.ts":
    "QmP5YDAz59so62kWXu8TQZVWnHSEZ9VaFGSAQ7HsbQGN4k",
  "src/workers/ipfs/node_modules/typescript/lib/typescript.js":
    "QmbyikitextHGVvCyv3zUrgqXEFwsStvXy49kjdH2cydCp",
  "src/workers/ipfs/node_modules/typescript/lib/typescriptServices.d.ts":
    "QmZ3yUvEeH9EeK3GDDXiP51PS768BgAphDq5EGLKcwi23R",
  "src/workers/ipfs/node_modules/typescript/lib/typescriptServices.js":
    "QmTTmpvmW6KjiUUiBJVWMGReT4g4Yxb3dQpigA21QzeYAF",
  "src/workers/ipfs/node_modules/typescript/lib/typingsInstaller.js":
    "QmZQLKVTCQ5uJKMHgs5HGuD3qRzZWoBuhgnMGSxPBrrf6T",
  "src/workers/ipfs/node_modules/typescript/lib/watchGuard.js":
    "QmQK54JsaPCMRP2CAvyZo3iuRCqrcty6Ymi6ejcd6NfreS",
  "src/workers/ipfs/node_modules/typescript/lib/zh-cn/diagnosticMessages.generated.json":
    "QmU9JMLtdvN5SZ8acvobjTMndTufrV65g6AiFTuvaEqgTG",
  "src/workers/ipfs/node_modules/typescript/lib/zh-tw/diagnosticMessages.generated.json":
    "QmYrkFqSkCNZqChoGA6fc3ucxUSPug2n1Tg8qjo78HM1XN",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHS/Targets/ProjectItemsSchema.xaml.lcl":
    "QmSCoVkFAyDLx27mmcoGoAm7ZkxjW1A44m9nSW2QHMLcAV",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHS/Targets/TypeScriptCompile.xaml.lcl":
    "QmYkYwMGw9SqW6D1w5AbAzeHrAbUSfxtn7iZrjShkwWEQ5",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHS/Targets/TypeScriptProjectProperties.xaml.lcl":
    "QmQJ6WkDqw5yrgrVxUyFLpMsw6UNHZdHRDh2kUkePDAqur",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHS/TypeScriptDebugEngine/TypeScriptDebugEngine.dll.lcl":
    "QmWDVDQmVoByfx28QKHkRT1b7y1z3A9N7fRqxXhYVzQdoz",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHS/TypeScriptLanguageService/Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll.lcl":
    "QmaUcHucR67TMiQF2xHFLJpmVLDrXQz8wbLBe76Xi9jMC2",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHS/TypeScriptTasks/TypeScript.Tasks.dll.lcl":
    "QmcAv6q6doAyU6FKzjoVoz5WN4L81zHvAWHTmQHMvqpBGY",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHT/Targets/ProjectItemsSchema.xaml.lcl":
    "QmbibZ8pvsTM3dqtxLEsM1GoAoYK6rBreMrmaVzEnP5H1i",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHT/Targets/TypeScriptCompile.xaml.lcl":
    "QmNr99ZYYkgN5ncnCAzQQ4kgvyqoRJwSwt7cdv9HB3Dcz4",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHT/Targets/TypeScriptProjectProperties.xaml.lcl":
    "QmTs6fqARNFHStqxsENo8hVZso4cz6wJUbuS9W4LcGgGPG",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHT/TypeScriptDebugEngine/TypeScriptDebugEngine.dll.lcl":
    "QmfZy4mmL3zRpM5t75rn7gHTzZrm4NBFp7QzGNwbec7Qdx",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHT/TypeScriptLanguageService/Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll.lcl":
    "Qma5v28r3HDZfzsAhSRs7nQJH7AZ2mFggoncgqBf5WBeHN",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHT/TypeScriptTasks/TypeScript.Tasks.dll.lcl":
    "QmU2oVtGRtTwhwSQL3QFeVSqx6eC8KEHJQvQEhZ1mzB8S9",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CSY/Targets/ProjectItemsSchema.xaml.lcl":
    "QmZTsyUo8FfinZa65zLm8ED7ysARSCdZyfochqfeKiqKj8",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CSY/Targets/TypeScriptCompile.xaml.lcl":
    "QmQdRgh5bMfDNuxuFWvi68fVY8Tjz9XvACWwyAGVmm84C8",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CSY/Targets/TypeScriptProjectProperties.xaml.lcl":
    "QmaCHyKbVh4AsTm1EsikseETXuSmBh8HFdXL5joW7LfDoS",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CSY/TypeScriptDebugEngine/TypeScriptDebugEngine.dll.lcl":
    "QmVooyp3nRumokHgMjwME6NhueEUbi1FsHSjo46sJPjZuY",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CSY/TypeScriptLanguageService/Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll.lcl":
    "QmY7tRekxckGUHfX7pUUSAiDRAvtRZWEbLbKMG9V84ZQke",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CSY/TypeScriptTasks/TypeScript.Tasks.dll.lcl":
    "QmaUaM8DfhfYDd7Ay4kJehTsfCwTCzaHvxUUfvTD8gFwUo",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/DEU/Targets/ProjectItemsSchema.xaml.lcl":
    "QmNzpenTB8hA5tE9Qajz6BaznHXKVYASkhMsUPeDjqgYnS",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/DEU/Targets/TypeScriptCompile.xaml.lcl":
    "QmWvb2w9HdxWD6Ej5KzCWN9L5Tc3NxQigFrBGVXAXmMMtP",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/DEU/Targets/TypeScriptProjectProperties.xaml.lcl":
    "QmNgmfrF5b9Pi1gseMER25gBTZoFc4nHNMsiz2dXLy4QgB",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/DEU/TypeScriptDebugEngine/TypeScriptDebugEngine.dll.lcl":
    "QmVcBWQ1duNRAfs1w1jkDdt97LC5VmRxd5bVEKBWJgFYXH",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/DEU/TypeScriptLanguageService/Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll.lcl":
    "QmNYK6ZTQLNxRzszCAwzrwYTy7MP17fRAU1PeRXHaysb2a",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/DEU/TypeScriptTasks/TypeScript.Tasks.dll.lcl":
    "QmSG86piw8B5fkc5WR2bAvZzHM6yu9sC2ur31srDwZ2x6A",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ESN/Targets/ProjectItemsSchema.xaml.lcl":
    "QmRD3P2GMCB1Fg3Ruts3WGSmKSfqsr2qd66JBkd2MH3dPz",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ESN/Targets/TypeScriptCompile.xaml.lcl":
    "QmaBDLVTLEft77ubCeQnu4RRQbfYWyTK1Dj2Vq9CYQFinu",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ESN/Targets/TypeScriptProjectProperties.xaml.lcl":
    "QmUY4n5jaRkj5cPgHNj8STiPwHzoLUd63ADMbQt6Htc4GQ",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ESN/TypeScriptDebugEngine/TypeScriptDebugEngine.dll.lcl":
    "QmdhjFbktwDuii3usFy9vBbRUSaBqmUBW8aUwgkVA599Yf",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ESN/TypeScriptLanguageService/Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll.lcl":
    "QmaQPF2uedcuVQNdq4QLB1scEwDNVBQBoJBXeu51eGGBPP",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ESN/TypeScriptTasks/TypeScript.Tasks.dll.lcl":
    "QmNxV2zEcHKBFMcJuwX6upxzRjuEW1tcqJm4uSfJgnWmfw",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/FRA/Targets/ProjectItemsSchema.xaml.lcl":
    "QmezKgvT5TVjiiKJa48QNfkvzLrj9U1tbyjgv4Cd4GZXUH",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/FRA/Targets/TypeScriptCompile.xaml.lcl":
    "QmbZ6qnhvV6BP4KrQth68siDT2vKsLEGoJDd1P8EZwdMyY",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/FRA/Targets/TypeScriptProjectProperties.xaml.lcl":
    "QmeY42kNfgt2heUxUyKJi9qUzP8gtzu7bABEva944k2oZ6",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/FRA/TypeScriptDebugEngine/TypeScriptDebugEngine.dll.lcl":
    "QmX2oWVvsVELmg3UHDUmWVqRgjQUhKXNpXE7G8StQ3fYxn",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/FRA/TypeScriptLanguageService/Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll.lcl":
    "QmYbwrQngBC2TR38edyou6dD7H57jZL8cdYxi7a82dt6kM",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/FRA/TypeScriptTasks/TypeScript.Tasks.dll.lcl":
    "QmcuGuzZneCC7mXvpnYr9VqVDsHT4n1DrQXWV7d6VdNXhm",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ITA/Targets/ProjectItemsSchema.xaml.lcl":
    "QmfWU6WBovVBPnZn3XL2F4f3F7Kan5y3939iVPfZgL5J7x",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ITA/Targets/TypeScriptCompile.xaml.lcl":
    "QmcYreB4vYE3eCSgijPJCFq8xKgXLhypjjD1fMk75XVR2h",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ITA/Targets/TypeScriptProjectProperties.xaml.lcl":
    "QmZ3RmKHxaPiJiqjM4BDmn2VLavDs25y4SUwszmYWrus6G",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ITA/TypeScriptDebugEngine/TypeScriptDebugEngine.dll.lcl":
    "QmPF8HW2MD7p69Zha4MxaCqUi7kPkjXd1tFYQTVYtw31fn",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ITA/TypeScriptLanguageService/Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll.lcl":
    "Qme7XuuaVjFcWCkFnbUXDkFvovbwLs9TYcyzch4vCkfWxz",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ITA/TypeScriptTasks/TypeScript.Tasks.dll.lcl":
    "QmQD4EXs9Sbaa9LPByPHqQ2WppHic8fnp8aMWdmT7AY7t1",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/JPN/Targets/ProjectItemsSchema.xaml.lcl":
    "QmV9ijZsq57W3ED4NvpMR85Rn71yT6XZ9HQAxhBqmuQ3fF",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/JPN/Targets/TypeScriptCompile.xaml.lcl":
    "QmUSRHYojNhYTcmf4CdsNo2odVtvAPN7fWgq6AQkPjc5Sx",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/JPN/Targets/TypeScriptProjectProperties.xaml.lcl":
    "Qmd1ySKLZGBKhDTDvxybs6Mb1jaZ1wZWQT4HffGAKn95kH",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/JPN/TypeScriptDebugEngine/TypeScriptDebugEngine.dll.lcl":
    "QmbYjPtBhUir1CdCYoDR6M1G4yh6DHvvtJspqx611eZt5D",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/JPN/TypeScriptLanguageService/Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll.lcl":
    "QmTzhhaWcMSeegszwi94YVMA86UARRZTBkcWjzfLJN1RwM",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/JPN/TypeScriptTasks/TypeScript.Tasks.dll.lcl":
    "QmXzqLktLJ2LKseLC1JNzrwwmUFkr7AjD5DwAExMyhmcxp",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/KOR/Targets/ProjectItemsSchema.xaml.lcl":
    "QmbbSexcmj8NWi3tVZCY6v7F6LcNy1r4rqyxXgW5SrQkzF",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/KOR/Targets/TypeScriptCompile.xaml.lcl":
    "QmSr9Y2wEsje71qQzHdBaEETuxEBLHWjQvgvpoN3dhS4xs",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/KOR/Targets/TypeScriptProjectProperties.xaml.lcl":
    "QmXPA1Va3WiHyPKDvAYnxW1t3fGdoY8TvLvSniaFr6ZN1A",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/KOR/TypeScriptDebugEngine/TypeScriptDebugEngine.dll.lcl":
    "QmVj6KrvaYq8sPmGchjEyTrh3MM2GBqR9D8H1VesCMdRqe",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/KOR/TypeScriptLanguageService/Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll.lcl":
    "QmbZ2ZHmMB7fje9pidgQYWVRxDaZNTKs77ZdeBthYxNKy8",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/KOR/TypeScriptTasks/TypeScript.Tasks.dll.lcl":
    "QmWuXZQoGUhtP7PXYegz265UskswVAzxkPZz3vCGUCwWYR",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PLK/Targets/ProjectItemsSchema.xaml.lcl":
    "QmSrcnBNmZXjfSH5bR49y83MSCcWGx95cWAoZRNXkLisfn",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PLK/Targets/TypeScriptCompile.xaml.lcl":
    "QmZuxXquCN5hP3tbUKzZji5mrDEoUneen9kHwd7mTLuAkA",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PLK/Targets/TypeScriptProjectProperties.xaml.lcl":
    "QmW9jAHh4MM7sieccVhMHTjbsszE3hBuHbyHk5RNZozJdB",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PLK/TypeScriptDebugEngine/TypeScriptDebugEngine.dll.lcl":
    "QmQCBbnz2go61u9wiJdx5MgZ8GRnrUkBDj9Ubxwfb9V5Xn",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PLK/TypeScriptLanguageService/Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll.lcl":
    "Qme6aRiq7FZqhR1PDo3W4u3p8B6mC8nUskFRJ3Axmg5JD9",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PLK/TypeScriptTasks/TypeScript.Tasks.dll.lcl":
    "QmdsWyLYd9nGTKTUa5RiyHVwWGmmmymvoTfKq6CGEM7TAK",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PTB/Targets/ProjectItemsSchema.xaml.lcl":
    "QmViPwXzVCaRMvGFzbNjrm4kstL7rVTn79sR2uck1NE2ej",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PTB/Targets/TypeScriptCompile.xaml.lcl":
    "Qmdw5SNQj7h5UNG8fjCy8HCHWp1cAe7RP1KHJoqXnZz4vZ",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PTB/Targets/TypeScriptProjectProperties.xaml.lcl":
    "QmTFi6PRogGJDqhATbdpd1CHmmZgWymmqK8tVsGMF1kD4Y",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PTB/TypeScriptDebugEngine/TypeScriptDebugEngine.dll.lcl":
    "Qmbd7AvtMszCnimXurpXdDakHehLDL35nhoNxBkDvf4851",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PTB/TypeScriptLanguageService/Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll.lcl":
    "QmeTvBA55LPxHTz4gJgVG8WE5ksPK2L7FGYQzxBpsRLoof",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PTB/TypeScriptTasks/TypeScript.Tasks.dll.lcl":
    "QmWWP7TN8A6RkomjZap7yDNjsp9L5PJPuCsHxADStXSBqU",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/RUS/Targets/ProjectItemsSchema.xaml.lcl":
    "QmWV2F2Zj3MfHbaM2HK1NpVVzw4DeHz2kwVkTBcdsgPDXn",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/RUS/Targets/TypeScriptCompile.xaml.lcl":
    "QmcNX2B5LbrmmvT5Ne4gFR5JrXB8ffvZBKVH44MGaqdsKm",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/RUS/Targets/TypeScriptProjectProperties.xaml.lcl":
    "QmV1F8KPcsgusd4qD9YLWD6XEz9eWBi4wHk6NCxGAsCc3P",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/RUS/TypeScriptDebugEngine/TypeScriptDebugEngine.dll.lcl":
    "QmP6JURF3PAJzgQMC7wen9R2uFdSN2ENQvK6cUjwEUnjjr",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/RUS/TypeScriptLanguageService/Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll.lcl":
    "QmUkUiY1JCL8X3b2Rh7sm7D46ZMDstesxZjsdjKEVHxcd2",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/RUS/TypeScriptTasks/TypeScript.Tasks.dll.lcl":
    "QmPhMmVBrvugZXTZY6cBQbaHCKo31aiCA7GjYwG8TimQr7",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/TRK/Targets/ProjectItemsSchema.xaml.lcl":
    "Qmc57cgM9i2PerStkdLKUBvDdAJL3gJSShS99kTuPqPbBN",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/TRK/Targets/TypeScriptCompile.xaml.lcl":
    "QmfQnd8cTFazxahq29JWZniqeFihXa4J1MAvtV261ZLHZZ",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/TRK/Targets/TypeScriptProjectProperties.xaml.lcl":
    "Qmcv6sn82gGgw6jSbiFnyBfnMWCGN7SdBHJKxsA2sBTvfg",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/TRK/TypeScriptDebugEngine/TypeScriptDebugEngine.dll.lcl":
    "QmQug2eaNhtUD8vxMCYSWvgH7P8TFwMeh9od7c1vSyFeQc",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/TRK/TypeScriptLanguageService/Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll.lcl":
    "QmUCaJk1TNq4uFsFZrF1afwcruG1wdZjDZ44aNPPW47nx6",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/TRK/TypeScriptTasks/TypeScript.Tasks.dll.lcl":
    "QmW7z5GKCdzHNu3ohqjL2PNwX3NRmpZHRaKALeKnFjHFt2",
  "src/workers/ipfs/node_modules/typescript/package.json":
    "QmdiD5NWnYsL87Jnp93t6y9fVhyVNJeJZAAZ4RMJnrmkov",
  "src/workers/ipfs/node_modules/uint8arrays/CHANGELOG.md":
    "QmRXtm2JnFnryHFiWSSY1VE7Jygo4NV2nJSMtrvQE6JZSz",
  "src/workers/ipfs/node_modules/uint8arrays/README.md":
    "QmY9MLGfvXbn6xuHNzDFrLTg2CVzqjxzCK5XHwSWCXqwtY",
  "src/workers/ipfs/node_modules/uint8arrays/compare.js":
    "QmWZfqfuJ42bPx5TG5gKr7c4VGfCuV9to38sqUtu7q1W6z",
  "src/workers/ipfs/node_modules/uint8arrays/concat.js":
    "QmNVrP4rvag3nDR48q41KEQuomBGfpTpRvd9sLyWRbMjE6",
  "src/workers/ipfs/node_modules/uint8arrays/dist/compare.d.ts":
    "QmY9sxA5ALg2sSzzMzyncNMnXwVBpxAK4LJsfSocPfM317",
  "src/workers/ipfs/node_modules/uint8arrays/dist/compare.d.ts.map":
    "QmT3hMw3SXQ1KEcmDcZaN1KG2kH6mE3kHvZHjq8qUn58zD",
  "src/workers/ipfs/node_modules/uint8arrays/dist/concat.d.ts":
    "QmZwTsvTpg1ETMSzAe4HQNpnA5ZbGqEc3JvzhRG9wAT8EE",
  "src/workers/ipfs/node_modules/uint8arrays/dist/concat.d.ts.map":
    "QmUc64sLfa3eMAiHwRD1tBgrcKrjRyBJgS7dGVMG1LrS2A",
  "src/workers/ipfs/node_modules/uint8arrays/dist/equals.d.ts":
    "QmSfLrAjZpbn8dWXdaFqCVcQ6KRS2RY5ws6utacjkLsxSd",
  "src/workers/ipfs/node_modules/uint8arrays/dist/equals.d.ts.map":
    "QmcYFBPZDKUCRWVpZhycpEAgscw8iGBrfWfggzZAsH2AhE",
  "src/workers/ipfs/node_modules/uint8arrays/dist/from-string.d.ts":
    "QmQN6cdTcBr8e4KsBRQhwg3qfzbGT1gQ7FMncff2G5a7nS",
  "src/workers/ipfs/node_modules/uint8arrays/dist/from-string.d.ts.map":
    "QmeYgvsKqtjhszvVEAixg1J4trSxbiXSUhDVuXh9hhPQie",
  "src/workers/ipfs/node_modules/uint8arrays/dist/index.d.ts":
    "QmdsyZfRU4mwVnh4hUp83BPNqwFKS6qYnfCZuZ2njqaJGS",
  "src/workers/ipfs/node_modules/uint8arrays/dist/index.d.ts.map":
    "Qmdkob61reTPKyrLXxE6QWPasX7K9ksTLjwQvUAbJqwj14",
  "src/workers/ipfs/node_modules/uint8arrays/dist/index.min.js":
    "QmQiz5vD4CYTaT9ajVTB1HshpL3T9MoVzmV8hCUBnGPeo6",
  "src/workers/ipfs/node_modules/uint8arrays/dist/to-string.d.ts":
    "QmaqHtbgosbT5vG3t7vRCRtnQV2aQyvJpZ5nN6vuUGEeWJ",
  "src/workers/ipfs/node_modules/uint8arrays/dist/to-string.d.ts.map":
    "QmaCbyAgABHUuroousZqgiTSCCDrTv6gys8FJZr5EQBzHZ",
  "src/workers/ipfs/node_modules/uint8arrays/equals.js":
    "QmdosQNTM8QV98QJbLytNepyGHwqtrqpoo9Qb1DSZcTpgR",
  "src/workers/ipfs/node_modules/uint8arrays/from-string.js":
    "QmQP5bZHZbeEiHrn6HbVXEWXuThbqh7fMqBoHEvypQCaCg",
  "src/workers/ipfs/node_modules/uint8arrays/index.js":
    "QmSv8uLYAvhDAj8zBytYaGVFfo6G7pBbgCQyDffSowRiCf",
  "src/workers/ipfs/node_modules/uint8arrays/package.json":
    "QmYt6PHciBJ8oVyt4jfMzRjrz8jR2H8wUaXJxc5f3wnaqf",
  "src/workers/ipfs/node_modules/uint8arrays/to-string.js":
    "QmVrsJ8sxzw72wdf5ve6ZaVmrAKMeQrXTFKKt6JJMk928J",
  "src/workers/ipfs/package.json":
    "Qma7iXwSKeGmGjP3SjKokckCh4aRbuidjBn5WanbqDHx2h",
  "src/workers/ipfs/src/gateways.js":
    "QmVGZy8bP96dMrzL4vTg7ppfpJVAFbtUZ1Go57fvsParbe",
  "src/workers/ipfs/src/ipfs.client.ts":
    "QmPHeiaXEFPhPXsg2DpZkdb7NYp9GZ1MCarVFMRdg83Ada",
  "src/workers/ipfs/src/ipfs.server.ts":
    "QmdcUyYNDxR9fKZ6jfuRa6Uzb8vS6BJWiAGaQfUjpoVjrW",
  "src/workers/ipfs/src/ref.d.ts":
    "QmZV7knX51sBSfDb7mFNcghGtF3RKyczc6z4Uz7zXS25zo",
  "src/workers/ipfs/tsconfig.json":
    "QmYHbMSMqJLVt643gR6twoh1Fh2pmRefGPr9GEfXQSemHg",
  "src/workers/ipfsWorker.js": "QmVzkTMiCNd7aaxBVhDNaTVBCkHYZa1Rv2V5vXsX5MPzxh",
  "src/workers/shasums.umd.js":
    "QmTcSv4DXa6USZDdqotYWUdEhRB8voN9hrDdSjsPAvWgjq",
  "src/workers/sw.js": "Qmea5yH32uw2TfGq6vMhp1smHvGJ3nGx6RsVHsc4efQSY9",
  "src/workers/transpile.worker.js":
    "QmSX2qLhymbiH8AqKshiFgPUjJfjfwFFrsbNx16dh7qzX8",
  "src/workers/tsconfig.json": "QmNt8xKcRnN8TVbPqU9kNwUPNy7tinifkhWe8ADPTSVCvJ",
  "tsconfig.json": "QmdYYNAMVJJgs9nYR2tc4oVC6Fxcwcv7K1b8QH4H2372EY",
  "assets/fonts": "QmYAJJ726yRoCVerLBgUHdLax1JKS85SYLrnrG54WxSDtK",
  "assets/synthwave-vscode": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "assets": "QmcLAE4ZmMJ1GT977zHKnX7zzcwVRS25cYzFTTiA9hxtyd",
  "node_legacy/@babel/standalone/test":
    "Qmdbni8ySNyYHkWS2SgxoLVBT4or3F6nBe61F8FBDwDthg",
  "node_legacy/@babel/standalone":
    "QmeQ1gDZFjKQFLkVYWURPyJjhSV4Q84T5AaraV4Dtzsjgq",
  "node_legacy/@babel": "QmQhFnhgvSEwfGYsxau3hLPFtzNhKY8E39v9ob66qNpHz6",
  "node_legacy/comlink": "QmTQek4dMBFHR9YmfaC39AHc561J1AyV7zmgPhgtTsP4q7",
  "node_legacy/ipfs-message-port-client/dist/src/client":
    "QmZup1QoUb9PRv51TDmWAZMi7P9DUMcMwsY9iSzZYj59UE",
  "node_legacy/ipfs-message-port-client/dist/src":
    "QmRRhUpVVPhAujdbqRbTC4EUioCVZERCuwpPdx9Zk5SFkX",
  "node_legacy/ipfs-message-port-client/dist":
    "QmcvYWqnmkLmoS8D262vTMbkVDvNycFrzMQzPcerJquNuQ",
  "node_legacy/ipfs-message-port-client/src/client":
    "Qma7mVuyQwQ3384fJov2cuWjR6CXVE5k1WWBsJ6iUXzSqj",
  "node_legacy/ipfs-message-port-client/src":
    "QmUyymcxnh6hpkekqTbcphh4zQqifBuopgjK8Buypn28ej",
  "node_legacy/ipfs-message-port-client":
    "QmbeYVX62aoKMEo5svQUkdfjxQQD5v8BgKuz591gJsKhuW",
  "node_legacy/ipfs-message-port-protocol/dist/src":
    "QmRAQWWth3CGqTDMp58Eof9aPdaPLkzaryaZaYQEAawHvq",
  "node_legacy/ipfs-message-port-protocol/dist":
    "QmdvcKmKmVyxCfDDNjpQtSH7PzUgLrBNoVFMeaxsJNz1zh",
  "node_legacy/ipfs-message-port-protocol/src":
    "QmfLuvmz977mG2dziie5e8GkWKshjXJMbADpg3KC1xkBpN",
  "node_legacy/ipfs-message-port-protocol":
    "QmPXHMM3CJFjh2viwWzPh6Vn3dHFyJBJe8NRzy26XSKTjr",
  "node_legacy/ipfs-message-port-server/dist/src":
    "QmQdTdnQGHJY3fut5GXQa8tsZVpGC1Rj7wT61fpd1Viukd",
  "node_legacy/ipfs-message-port-server/dist":
    "QmTCu7LVcSrpLJ4Zf6JqDuSFjb6NsiQdBAUsT7ZJT2orzW",
  "node_legacy/ipfs-message-port-server/src":
    "QmPLf9dLYAtMwu3KN9kB4mXXN6icfpYCBn1ENMDGkqHLQV",
  "node_legacy/ipfs-message-port-server":
    "QmRQnASzHAxFVbJ4KjoDJ5B9SMuPzcT6fMaAL6UM9FAX8s",
  "node_legacy/monaco-editor/min/vs/base/browser/ui/codicons/codicon":
    "QmTCgjV4XfAZ2VRNyA7pAbXHteAHQfDj7aqyFXVLf8Ub4w",
  "node_legacy/monaco-editor/min/vs/base/browser/ui/codicons":
    "QmTbKb2XPymx49kXJoVrTeH2Bht2V8XChAqAdUPp7u6YEC",
  "node_legacy/monaco-editor/min/vs/base/browser/ui":
    "QmdHNauu9eZm2au7tVGPZriJd8JCwm19PXQL21VqNLVMag",
  "node_legacy/monaco-editor/min/vs/base/browser":
    "QmPhr7LDwZRZRvr7sep5JwoXnPTQqXGuDxRXf3f7p4tdc7",
  "node_legacy/monaco-editor/min/vs/base/worker":
    "QmNdwwk4x3rbH8pD8KEc4fQGYA1u1pdbmpuauLp9X56o1J",
  "node_legacy/monaco-editor/min/vs/base":
    "QmWht6v8rkZSFbwaNYWn6g9fu9t8fgUonKqEPJqVmoog26",
  "node_legacy/monaco-editor/min/vs/basic-languages/abap":
    "QmeRNeu74P9CgGNDhqowFs2BzxV4YUbr7MRMZtCAEKiwfj",
  "node_legacy/monaco-editor/min/vs/basic-languages/apex":
    "QmWgMoswMUrBAi94DoCsn5mwvGyLVrS3aVB1j1GSJe4kty",
  "node_legacy/monaco-editor/min/vs/basic-languages/azcli":
    "Qmc79388xh6Ddaev1uvkkANh9KTCHmthJrWwT79NFVXyQC",
  "node_legacy/monaco-editor/min/vs/basic-languages/bat":
    "QmeUiBRTE6TSvcjG6fmK1Xa6NmTxg69qmbohqaxyrshrDv",
  "node_legacy/monaco-editor/min/vs/basic-languages/cameligo":
    "QmaCje7dLsTCGb2tKu884zpXPoapzSvgmUqzngdMyau4C1",
  "node_legacy/monaco-editor/min/vs/basic-languages/clojure":
    "QmTtbo7PnVtZ1s3cJ4ezbYjh3wSibVg5Fw6LAeDdw6yzzX",
  "node_legacy/monaco-editor/min/vs/basic-languages/coffee":
    "QmdYQsvj6x5JDNK6PYDsA6WPYfKBot2dDtzUFX8N29ToD5",
  "node_legacy/monaco-editor/min/vs/basic-languages/cpp":
    "Qme7CKfGZjGQozGr7Lc5hDzn9QSRBS1nERcxYZ3hTuD3aa",
  "node_legacy/monaco-editor/min/vs/basic-languages/csharp":
    "QmRoNLZUjxt1iZnRnD2LPf6U4KnW9daLH1BbEqdfro4Vcy",
  "node_legacy/monaco-editor/min/vs/basic-languages/csp":
    "QmXUPfjPNk6tfuLKV2K1vkNWjhJhUy8rKd6LVTAme4agfW",
  "node_legacy/monaco-editor/min/vs/basic-languages/css":
    "QmSs7ApyA6VD5PL94hnerWqutjMJnReG8TdZGNfedc3W98",
  "node_legacy/monaco-editor/min/vs/basic-languages/dart":
    "Qmdi65Yy8P7VAC6BYWdXawz8Tf39ua5k57DaJJvkfhRFpK",
  "node_legacy/monaco-editor/min/vs/basic-languages/dockerfile":
    "QmdxtR5pS1PW7BaoxkZqtVLem71tdtM7kawibevJdPoARp",
  "node_legacy/monaco-editor/min/vs/basic-languages/ecl":
    "QmaMZvz72kRNUvGuTEW3KoeDiGnLGr4DjUGUTcRAUywUZb",
  "node_legacy/monaco-editor/min/vs/basic-languages/fsharp":
    "QmZPNYgTk7ZqcjcJoeJf8T5ucCuiu3xnRyuK11LDu68DEe",
  "node_legacy/monaco-editor/min/vs/basic-languages/go":
    "QmZkAcsGDPe7tqbkFeoQ1UoEEir113PYsJEkznbjAyXyp4",
  "node_legacy/monaco-editor/min/vs/basic-languages/graphql":
    "QmZsGGMqm1jbQL2EAAbVtvePbvVyrLCA7Tt3YwNgGw3Grb",
  "node_legacy/monaco-editor/min/vs/basic-languages/handlebars":
    "Qmey7d2sep1g97VapXj4QanLZrLXrrkt2RjeGzFKCaWEAE",
  "node_legacy/monaco-editor/min/vs/basic-languages/hcl":
    "QmPYF7wbUWBq86s6amkKzw8gFJhow41t1qQCokhSaxC2dS",
  "node_legacy/monaco-editor/min/vs/basic-languages/html":
    "QmdiJK26pBKVnzrJt81Ch1TYooki2J4xuyCcj2V8HSeezU",
  "node_legacy/monaco-editor/min/vs/basic-languages/ini":
    "QmdKkAPGXLmNykdeNkVwjUXmc1iEx8Q7s1fD6RDRVA5pBh",
  "node_legacy/monaco-editor/min/vs/basic-languages/java":
    "QmYdA8mTrqUKTBdnVidVaRQF4dhyWJnyz7fvChKs8QamjP",
  "node_legacy/monaco-editor/min/vs/basic-languages/javascript":
    "QmdWep3UKpkTvKKMgP34tAfAGEL3eVJcp4GuRCJzkQ6gr9",
  "node_legacy/monaco-editor/min/vs/basic-languages/julia":
    "QmWYvuZSKteaffjVHu5pexbXM3SmuuPbNwdUSQDmg4VfSf",
  "node_legacy/monaco-editor/min/vs/basic-languages/kotlin":
    "QmX7mawF3BknKBzXPZ5Nnahuo88Cpg6cwJmpzPCwKRSpBH",
  "node_legacy/monaco-editor/min/vs/basic-languages/less":
    "QmSEqdQWguWkKXUcLBmwVicMURaTyxu4uSTdTu2BaZfaQz",
  "node_legacy/monaco-editor/min/vs/basic-languages/lexon":
    "QmWFmtGB27ZdK9wayQNDo1Xv9HQ9TPmByGZdPeCMoYxgqn",
  "node_legacy/monaco-editor/min/vs/basic-languages/lua":
    "QmZMiSLaV46QSxT97cjF7E59vVDPaasjwW3EBrjA8zeNba",
  "node_legacy/monaco-editor/min/vs/basic-languages/m3":
    "QmUrNUak9RbWDVGbvdofB49as1et7ArvHTY6JTVPfd5Tt7",
  "node_legacy/monaco-editor/min/vs/basic-languages/markdown":
    "QmfUmqW53FmbDvXs3b2tegGWXgTv7YvnzPhGxkkbrFMvCk",
  "node_legacy/monaco-editor/min/vs/basic-languages/mips":
    "QmWoFkCZk4nZjKjFHWfqwCNrnEv89UsgYuAfbsZfTspe8Z",
  "node_legacy/monaco-editor/min/vs/basic-languages/msdax":
    "Qmas5MfPaTFU3uvTsLL4UXxLa17acpnddTsFwUBS7SfyWq",
  "node_legacy/monaco-editor/min/vs/basic-languages/mysql":
    "QmNm14Q6CqkPz88kmA1dqDTggNi2jyjGU93nRndeeoEyGu",
  "node_legacy/monaco-editor/min/vs/basic-languages/objective-c":
    "QmRr1FcbVmEEJA9HYQvP8NZnFEiodNnwbDoVVy8Z5CXEhT",
  "node_legacy/monaco-editor/min/vs/basic-languages/pascal":
    "QmRtAngE8axaka5Wb8Fk3ui8U7awreHAVs11m1jGmXWQcG",
  "node_legacy/monaco-editor/min/vs/basic-languages/pascaligo":
    "QmRNigEaw8FmrXik9AWAaztuA6FjzMEv6N9dum3rFA185D",
  "node_legacy/monaco-editor/min/vs/basic-languages/perl":
    "Qme8kaXN3n21VStSZCUDFV8CrHocjytGpgPWgSvenuRtTF",
  "node_legacy/monaco-editor/min/vs/basic-languages/pgsql":
    "QmNZ7oJno8bPRDR6VWuJeYy2NwRYKWHFmQ1jCeV5Xk4PSd",
  "node_legacy/monaco-editor/min/vs/basic-languages/php":
    "Qmf7W9auy5MAySXnXo5bEg3eoDQhptAAME6QWQeNexZLW4",
  "node_legacy/monaco-editor/min/vs/basic-languages/postiats":
    "QmYMnT1XPmYmbiVhKTvBaiqwaufTcacNH5feE3EpKbiic3",
  "node_legacy/monaco-editor/min/vs/basic-languages/powerquery":
    "QmcAdq4ccWhMX8d5EFHXSmYrEmUujHErGLAnERnaWYzAcc",
  "node_legacy/monaco-editor/min/vs/basic-languages/powershell":
    "Qmd7HXTvDd79yU5UEaXenL6xG4KWfZpCq2s1BTv6i8WBpz",
  "node_legacy/monaco-editor/min/vs/basic-languages/pug":
    "QmQJeH3Cc4FebtvzwCohAXx3dnqetX2AeCfuvrp2nMnCpX",
  "node_legacy/monaco-editor/min/vs/basic-languages/python":
    "QmSVvCsMawMtd3cTe7YoFr27sdc3btnMguAbcQ6PzgVLL4",
  "node_legacy/monaco-editor/min/vs/basic-languages/r":
    "QmVNwkR7aV5KPqGJ1aqRwAYPdgZvgUM2CSBEnygSrmRkPh",
  "node_legacy/monaco-editor/min/vs/basic-languages/razor":
    "Qmc4FHoUdNUQY1kNAbBmwd3x4KZCHVZ2rTgP1XXwQVbvPt",
  "node_legacy/monaco-editor/min/vs/basic-languages/redis":
    "QmWu8dGZ4Aiqn6LB7Wu22DQDRckHnvSG9vhm8wBqqAw1fZ",
  "node_legacy/monaco-editor/min/vs/basic-languages/redshift":
    "QmY1FeyqgDW5wmd1P8QH1oGKqDhK2bfFZAFwSCEjQFmMya",
  "node_legacy/monaco-editor/min/vs/basic-languages/restructuredtext":
    "Qmdb7CKsjg4sEtVvq8aPLBbKnadr9iuGArCuM26hKcv7nd",
  "node_legacy/monaco-editor/min/vs/basic-languages/ruby":
    "QmPCxRNJAMTcQ1t5rKnHwfsQvs2MTT8ibp7r3neKRqLbj5",
  "node_legacy/monaco-editor/min/vs/basic-languages/rust":
    "QmPRfcEQGbFQHMUhLXbzXrgE7ubreSJNPH8AQ5WtLsN7VW",
  "node_legacy/monaco-editor/min/vs/basic-languages/sb":
    "QmQnFgcm3xax856UB4wJqHfbdDvT8Abyu1HYpnwdATU5gc",
  "node_legacy/monaco-editor/min/vs/basic-languages/scala":
    "Qmb3o9M7PxKMwVSHXZUSBayMNraNyF6Paie3zpx4fXK2TH",
  "node_legacy/monaco-editor/min/vs/basic-languages/scheme":
    "QmbLT3x5q7LV5gfGWmUXAbc4SiSKGtf526DU3XQEXNHKLL",
  "node_legacy/monaco-editor/min/vs/basic-languages/scss":
    "QmXDg3fxFP4PN887YpzxNjtCDndwCu2eVSRvFkS1JxWZx3",
  "node_legacy/monaco-editor/min/vs/basic-languages/shell":
    "QmQbA1KSCK796soF2B9aDukvdcVQVzV9ehWHa88drt2LFF",
  "node_legacy/monaco-editor/min/vs/basic-languages/solidity":
    "QmbyRxaRDmT1q42RovFc8kisgTqpkGiroSBTjasFNuQgKv",
  "node_legacy/monaco-editor/min/vs/basic-languages/sophia":
    "QmcdLVwPbzuoyVCASdTZASyb5WSTBiLuYEUHAFwNHBbRfB",
  "node_legacy/monaco-editor/min/vs/basic-languages/sql":
    "QmdNHFcygc9mRzQhLWCy3inY92kfxG4kcJu7LNUXWwiMq2",
  "node_legacy/monaco-editor/min/vs/basic-languages/st":
    "QmVupYw27ogzT9evBvMiYprt9ktjEw3snkLthnXFpDF7QR",
  "node_legacy/monaco-editor/min/vs/basic-languages/swift":
    "QmTsb4hAmfuKa1c63QMEv6J1wTA4qpehRhYvcPyn5StqCe",
  "node_legacy/monaco-editor/min/vs/basic-languages/systemverilog":
    "QmboFP5BVTcm5w7f7V5GNE6xS6NqpwEhNwYkUA9pbzL3e9",
  "node_legacy/monaco-editor/min/vs/basic-languages/tcl":
    "QmNfZVnCQ1R6RkRRXzriQEvb3pRrVZKLXfCQBoHBch4tcr",
  "node_legacy/monaco-editor/min/vs/basic-languages/twig":
    "QmPp71vQXY1vCQrDA6ehre5jctc9ztCokFdma7GdqrSLjR",
  "node_legacy/monaco-editor/min/vs/basic-languages/typescript":
    "QmPWGEHYUYSE4q47SYKAfcWcvoxCvsxqnejQSnHmj8QVrT",
  "node_legacy/monaco-editor/min/vs/basic-languages/vb":
    "QmfRPFT5Ykp7xDgaa2bp8t4QVjMWG14pAmBpXpfUkE9Ldm",
  "node_legacy/monaco-editor/min/vs/basic-languages/xml":
    "Qmd632Xcdd7TXGrn3qhPfogH3XpwFb9jMqk25pYgW8N6gH",
  "node_legacy/monaco-editor/min/vs/basic-languages/yaml":
    "QmPSHJebgzKtoC22AbL7xPNdq7tYBUfivjZKMp5YBoYkaT",
  "node_legacy/monaco-editor/min/vs/basic-languages":
    "QmYHV56gyFSq2L1Mwq1gUqZuJb4kNgLye1TAQbPFNHf1os",
  "node_legacy/monaco-editor/min/vs/editor":
    "QmbZdYJ6QMRGtTQ5uy2S2ftUYwXV9LTbYsdhoDmyb37PvJ",
  "node_legacy/monaco-editor/min/vs/language/css":
    "QmNazVg79Ry4Nvj82JFrkPXEFhwvFRDjmbyFRL51mYKftF",
  "node_legacy/monaco-editor/min/vs/language/html":
    "QmbNh6jdyp2Ji3M65xrfGFSXDxaeBEnfNuAQptWZozpWfz",
  "node_legacy/monaco-editor/min/vs/language/json":
    "Qmbj2H1LQnaTqPPntq41mf2pwLqutwhNxzW3nc5xZZffFD",
  "node_legacy/monaco-editor/min/vs/language/typescript":
    "QmbFGz2Lz3GDBnxYK2SgXna1T8AMWPzrD7Za6PUUjtPhe5",
  "node_legacy/monaco-editor/min/vs/language":
    "QmVVoqonJhqH8oCkpBrBmASMo3EmrievXuMw7QKWmAB5Gw",
  "node_legacy/monaco-editor/min/vs":
    "QmR5LAUnfWWaHnHB5wbQMvZTqP3JThe9H5HGXU4XvdSqM8",
  "node_legacy/monaco-editor/min":
    "QmSPe7wHwQsUAiZ76bNqvC2cVdeX2PYsw2RqK8iNg2Tyoc",
  "node_legacy/monaco-editor/min-maps/vs/base/worker":
    "QmbFiGfcpPndc8UWPoRDm1WnEseqQuF7igtBJRNeobce58",
  "node_legacy/monaco-editor/min-maps/vs/base":
    "QmX16u4KjB2UqmVXBEhtkjMwtxBpn744d7azm23JizbZUQ",
  "node_legacy/monaco-editor/min-maps/vs/editor":
    "QmT36huaTFWDq7AC9k1E6t6z2DyKQP9fES537nCNRpUQRV",
  "node_legacy/monaco-editor/min-maps/vs":
    "QmcdrUDg4qrNycNQohTpToJPxL8vNvaE4yn65qa9u8Q45B",
  "node_legacy/monaco-editor/min-maps":
    "QmQueeHK42SVpGUPGuBG6zCNwGvkHMZkFua1RF7jDCZxjk",
  "node_legacy/monaco-editor": "QmeaRmtz4VoToM7V4CqzoQizQLnrQS35RMgTB5ZaM8sFJ3",
  "node_legacy": "QmX6VaPTh7rmAr3vhTDU3aJUuGjJe5vLLtA9V4D8CMzw7N",
  "node_modules": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "src/emotion-react-renderer/dist":
    "Qme5XNmCToindZrUoxTpjdP8ydY2CpKdWzNYafyxUpt5DF",
  "src/emotion-react-renderer/node_modules":
    "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "src/emotion-react-renderer/src":
    "Qmefpn86rafx41r64VYT9GQFPrEosdZV8MTXFhctsgENvG",
  "src/emotion-react-renderer":
    "QmUoJ4eXzbmRdxRYJ88nNrsV4XEgH67HQEwr8ZZvH2Efrd",
  "src/examples": "QmPysz1ZmDwk5yvsZtiKsnUekFXZiAERnPJh1Z8G5GZ5f7",
  "src/shadb/dist/vendor": "QmTZzgTNwYe9ioj2zaZmme3LZLscde4D54r8J6HpaaHJ5x",
  "src/shadb/dist": "QmPs9fBmE8aZQd62NYjBoWBvdwKZkf45nu81byMAEgmwuQ",
  "src/shadb/node_modules": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "src/shadb/src/vendor": "QmZcc5JirQ5ySPiELM4nJaVBLsKVL3vvNg2KE5uj7rGSr3",
  "src/shadb/src": "QmQqL9VeFmzKpNiihj8AuLZ7ngMn2w1Yi8AkzU78CUJvfJ",
  "src/shadb": "QmWaH672UPqZk9J31quy95xwdLDRR4FagRuXbiVq9A2Z5e",
  "src/smart-monaco-editor/dist/scripts":
    "QmUZruQhR3JEi3knevKng6AKpxN3vcswuRrCp4DiW9aYMM",
  "src/smart-monaco-editor/dist":
    "QmYdCBihHj9hDN6znBDFhC1WRvPbJeMmpPeJsiK2ea5AYm",
  "src/smart-monaco-editor/node_legacy/@emotion/cache@11.0.0/types":
    "QmUEN3GDGpShVYbF8hWwkgFWdCFf4MGFXggEBLLJCW7MHn",
  "src/smart-monaco-editor/node_legacy/@emotion/cache@11.0.0":
    "QmRrpV1ht67hartnVdCGUL6HoZ3VSqxoCJihFi3Qunud26",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4/types":
    "QmanceJtx35wfrY3dqZfRGiFZg7birgBaL65fkJRmRNZiF",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4":
    "QmYv3i1pQ5bjKy3iEEWX66FfxNsUe1GC522xbt4XRdwwyU",
  "src/smart-monaco-editor/node_legacy/@emotion/serialize@1.0.0/types":
    "QmUnre3UQbzpYq1XmEdf5cD24wcsBqWNnHkH75Z9SvsNPR",
  "src/smart-monaco-editor/node_legacy/@emotion/serialize@1.0.0":
    "QmbohaYyrYyu47WW4W3BRV5pxJQY5mVyAiQce9Bn1pQzCT",
  "src/smart-monaco-editor/node_legacy/@emotion/styled@11.0.0/types":
    "QmS5uFuLqN8AGfAiDTZnbjKbueGKve723gjTyVjTBaaz8F",
  "src/smart-monaco-editor/node_legacy/@emotion/styled@11.0.0":
    "QmQgjmWjt2jnyXUyLhMGRCDDWzeTPFpxAPtqyzYxadDENh",
  "src/smart-monaco-editor/node_legacy/@emotion/utils@1.0.0/types":
    "QmUXun6ie598RTouvr2WWASvmZZqErUtHuPXxd1LtdaFZ3",
  "src/smart-monaco-editor/node_legacy/@emotion/utils@1.0.0":
    "QmaWRA2PvGCN9iJefsPvvhtEPVgSH1jNWQsZAXYgcWqVhF",
  "src/smart-monaco-editor/node_legacy/@emotion":
    "QmdkLmXqY4cR3eCHDkEu6wr26oG12tRr7XRVpeNqieU11j",
  "src/smart-monaco-editor/node_legacy/@types/prop-types@15.7.3":
    "QmR4pDyXHid6f9yeQLtTVnCtpjmo43m7JAPwTd1Jbjj3Ta",
  "src/smart-monaco-editor/node_legacy/@types/react-dom@17.0.0":
    "QmRb3L5eSa6HX9KGJKyecoLnfSPNd6tzZdAMg6oQJj2Bsq",
  "src/smart-monaco-editor/node_legacy/@types/react@17.0.0":
    "QmdafiC1ixpU9mcYwH52sYg6yqMJtbAfRtCYzdh7aFD2Tm",
  "src/smart-monaco-editor/node_legacy/@types":
    "QmXxX7YkfkHhWb4j4EiHC7uoUxTjocGSAJna3ShsmuFGRR",
  "src/smart-monaco-editor/node_legacy/@zedvision/qrious@10.12.14/dist":
    "QmVr2gYmRGvQaHm4cbQt11LsXYQq4nMLG4H4MKYgJFvgc7",
  "src/smart-monaco-editor/node_legacy/@zedvision/qrious@10.12.14":
    "QmXJmZqywmjXZaXd4DHrhHLmVj5EDtuAA4gGvbnGXanhvK",
  "src/smart-monaco-editor/node_legacy/@zedvision":
    "QmQqBzB3Xs73A4pZwJpBKV8pcBp81oxYo6dHeDa2PCHF6u",
  "src/smart-monaco-editor/node_legacy/csstype@3.0.6":
    "Qme2hqcm1oQ6yWugA5iMA1qF5vHLNttgYHk9o6pTwSbf3M",
  "src/smart-monaco-editor/node_legacy/framer-motion@3.2.1/dist":
    "QmZTE4Vfab4JarTE9Urhf6QCGi5S4bo7Go6ZFxUKoRNv2y",
  "src/smart-monaco-editor/node_legacy/framer-motion@3.2.1":
    "QmXh5T3JpZhUEGQjPKVLgPCFfiEzMUgdLwmn1QmPs2S7rJ",
  "src/smart-monaco-editor/node_legacy/popmotion@9.1.0/lib":
    "QmTaZJ5REPK49oBHT76FsF8LX952W1mhEKgEzv81pqy997",
  "src/smart-monaco-editor/node_legacy/popmotion@9.1.0":
    "QmTnZe14NmEVosHmhQG1c1L8wvCDnfoaNzcdqszV9RnvBX",
  "src/smart-monaco-editor/node_legacy":
    "QmeDfigXf5xKxJVjmtujdYmYS4wzjeprCaP2BNuCQPkjcG",
  "src/smart-monaco-editor/node_modules":
    "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "src/smart-monaco-editor/src/scripts":
    "Qme94rT99UbaVwYxeK2ERakcHAABqofabkBbiSUuKztFzg",
  "src/smart-monaco-editor/src":
    "QmSQUM9Zkyn5Y6RQTfPKqf5VP5xhKVi76sxsVHLqNHcJvP",
  "src/smart-monaco-editor": "QmSpChJsNHs2LWDLEoBVXWkoUp1LzgjWfZ6iy1WAsQdTJr",
  "src/workers/ipfs/dist": "QmXLKBxQmafNmqJyFg9h4XzHVcabJmXD5k8zdJX33seNRS",
  "src/workers/ipfs/node_legacy":
    "QmSxTFf8YACtJvwT4M2s7sJ4yv4PFB4LYViYLt7vMyMtHJ",
  "src/workers/ipfs/node_modules/typescript/bin":
    "Qmeohoa5kFp6ks4AxvMRBEWdnaotSogEVTps7JK3W8U9HQ",
  "src/workers/ipfs/node_modules/typescript/lib/cs":
    "QmVB9oZQRpcwEFi131q1zbNXAsbDGN8t4MrZwNiHrMg3Ei",
  "src/workers/ipfs/node_modules/typescript/lib/de":
    "QmPftL4ZtrJqVywVFWHDAzjoMJ9F2AsGjRU9oq1agxYuzB",
  "src/workers/ipfs/node_modules/typescript/lib/es":
    "QmYP4DfASo7fXUvByUGbkLF2BzAb5sMQcCesak5xLGSdc9",
  "src/workers/ipfs/node_modules/typescript/lib/fr":
    "QmS7Yb29uRMQmzPR7ZXA9Yvnin3TuGc8izZRAX5cKgJwwc",
  "src/workers/ipfs/node_modules/typescript/lib/it":
    "QmZq4uWZ6xWhfotVDehzMufMhELgGPYZPyJ1YKXRjwv95R",
  "src/workers/ipfs/node_modules/typescript/lib/ja":
    "QmfZmTFcBrNkXtLogUheuVF7r3uZr89YxprZbw5vF7416D",
  "src/workers/ipfs/node_modules/typescript/lib/ko":
    "QmScjmH6qWKCRVSjWXD1uFDxEi7ao4nC7YdJNjEAJNDKcx",
  "src/workers/ipfs/node_modules/typescript/lib/pl":
    "QmVJMLSrzezTnuY6otJ64mxCQQzD8hHrCx2FmtMzn3V78t",
  "src/workers/ipfs/node_modules/typescript/lib/pt-br":
    "QmYrHCrdUf51iJMMWXWp7FrZ6WdrvcSGLxUjNhfTz99R8m",
  "src/workers/ipfs/node_modules/typescript/lib/ru":
    "QmbMnByuqxMcXJPSYSHDrWpYxJofxCXgjc7bfJDNNRhE1H",
  "src/workers/ipfs/node_modules/typescript/lib/tr":
    "QmaDrsHQwh9qYaZoPivSLcB39M39MV7W5a5HAevsrYhSph",
  "src/workers/ipfs/node_modules/typescript/lib/zh-cn":
    "QmRWL4y86TsK63YLoLUbATk5usTeoV6M5SU32abkpiV4Ti",
  "src/workers/ipfs/node_modules/typescript/lib/zh-tw":
    "QmaCxNgiD44UCXEaGML1bQ137dZc2nuNYZFXWdpkzVjqyz",
  "src/workers/ipfs/node_modules/typescript/lib":
    "QmNaHLgK2HicHRu1iK1uqBUSj2o9y7gzEsK1JCPMt7z2oF",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHS/Targets":
    "QmTtDKtCLVHWjGGG2o9K8PeLjatWKCUNmxVoATjUz7vVbK",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHS/TypeScriptDebugEngine":
    "QmbFxYchaWTjvg7szqFZyCfT9ZbRFe2BM63XxVKm8W75Pp",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHS/TypeScriptLanguageService":
    "QmPDZ2nn628CSvZ6JawdsyZwHrXN54CSdTS8p8bZMXz2SV",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHS/TypeScriptTasks":
    "QmSWQhCYQRFLgJhzejSfFXaZiG2nBcvVfRT2JSKvxfHeid",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHS":
    "QmfKViqzVzK8bzEHXnUQJ72FHh7g64vP7nXEfNRXNu11Er",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHT/Targets":
    "QmX8HEDjwqvuPs2eECcMXX3ScJLHJvFvHngzTKrejnN8bS",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHT/TypeScriptDebugEngine":
    "QmeiRXek16NoJshB2nd8qshpNov6sTWVV2pbHW7rhNUcA7",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHT/TypeScriptLanguageService":
    "QmXRXvqBEbdGbrRA1gU34wYA7KDzc3TABgwSoAWg6P8U4f",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHT/TypeScriptTasks":
    "QmNdy7FsMN3JbRhrKhmfCZosmmRNpFbmW7jCEQGhSSMr3B",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CHT":
    "QmZwKY8MXNPGco3gm7e1fq2fZeEszpakMntfhnjJFsPa38",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CSY/Targets":
    "QmNkHYeaunScBE4WHoSryWVMoUoAjvmiy1CBDzgmSMco1N",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CSY/TypeScriptDebugEngine":
    "QmdnfzqKvgZJqGGakDMD9PtqWn1tLdB9DxWXLMaDVPQLqe",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CSY/TypeScriptLanguageService":
    "Qmf9Z5Zy3oMQknUdhNmR3R3cnTy8SC9LZDmBSbhL3Y7fRM",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CSY/TypeScriptTasks":
    "QmeKoayY7Vbj5KAjmeu2L2nLoD3BuLTCaE2Vcuf6hX3vND",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/CSY":
    "QmRnF32SpjsS4ySTCA5R5FPoeFXHEHgwpEdL4dLjMsyunR",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/DEU/Targets":
    "QmSAPnsDP9NnbFfEUWSx74Az7vut2pFCUDCZMkxBetiC7V",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/DEU/TypeScriptDebugEngine":
    "Qmenf5e14i5rv5wmj94NcUgcq2jiFqKXcdLUvGnYpzhnuW",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/DEU/TypeScriptLanguageService":
    "QmRUnxi5Gz9TDkgj2a2zGzkcWzwqAkajYTSLE9hfhUm4zr",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/DEU/TypeScriptTasks":
    "QmWNi6kUxwS5TkudMxL4rvWrKpV96wpyw9XkBy3mxEZVKr",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/DEU":
    "QmPtcznezj9cvqLpRrRf9NDHKeK1TYELV5RmijP2haFyU6",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ESN/Targets":
    "QmPLxYxrYnfhgVnq5d3hJrqJTmHcc4ZiHovR3h2V4T7VdL",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ESN/TypeScriptDebugEngine":
    "QmbzTzDtxtJsemLeyKxPWYWckqvMp8rwY7bNgCwb29onKL",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ESN/TypeScriptLanguageService":
    "QmRN9fpQUyN354oS6xMjp3gdwhU26Kerh2p8Zy8PYPDyEg",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ESN/TypeScriptTasks":
    "QmW8BDJXMzLH5sFmb7kjxQGunmVHjSfjuigC93ut8CHcKK",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ESN":
    "QmeiVnAfk2ELLCweB9KeFGB1TgWVdjLLzYsB5xQzqGh3Bg",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/FRA/Targets":
    "QmadWC73KmUdPPNotEhuXPyhhiwNaER5qdPc1ysxxu9WgA",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/FRA/TypeScriptDebugEngine":
    "QmdiQK3ZFDe4SAFSkcCsGyN3KQx58f29MBQb9YeF4sqGxu",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/FRA/TypeScriptLanguageService":
    "QmexHp4DMf1t9vKfh12yvMRHbHcNXz66HcUXPF6q1tQUZd",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/FRA/TypeScriptTasks":
    "QmcZERiFsgzPFc8H5PUGLNb329nTeoGbdxDt5NmSN3q2EX",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/FRA":
    "QmeGp6kSiDFENtTGJPsiKkzBHXFUYC5xw7j7D4wP9f3Pa6",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ITA/Targets":
    "QmYkUgqbdX78ah4tTqz4kJ5ebKrctjRF2DzdsGnvnjEFpA",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ITA/TypeScriptDebugEngine":
    "QmSSZu7npjFqZ1Tmb5unDWHcekmAzoELnobdveQ8WV76K6",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ITA/TypeScriptLanguageService":
    "Qme98291oTJ2YBBqNeJMH4ej6WoW4jywaD774SHNKY7xPY",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ITA/TypeScriptTasks":
    "QmU3KHLfPRyKsVBHS3gu4gGFRxXBMiBX2NKwMotRfsuPvi",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/ITA":
    "QmZD5qbTUV2HivqU42AULzuFU2FW5ZADPwz82t6LhrNLvt",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/JPN/Targets":
    "QmRDP3d2AtvSiYp6fnKqUy6ooQjsGcg2SH8h4LU5evXBts",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/JPN/TypeScriptDebugEngine":
    "QmVwMps7oeaLG43rMTFdyJ9aKBj8zTWs8MH93ET5TpKKuv",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/JPN/TypeScriptLanguageService":
    "Qmc48Z63fMPFD71nM7nnnSX9z7ZbU4dxgm8DEKVnTGiHfM",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/JPN/TypeScriptTasks":
    "Qme8wY3aWMeKGFruttz1wa8NUdj9Cwz8JMgxzByv8JMKbd",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/JPN":
    "QmXQs9MPUiT5ie5MgxzyxgsjLAvwxRQMQo8DhfHS4AMQVL",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/KOR/Targets":
    "QmZFZRquH2qMMVUaGhE5i2cd78gWhMn7FJyumV7c89K5FK",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/KOR/TypeScriptDebugEngine":
    "QmTBbwtKuoZjrV4ifrW6i4BQF5Q3QpeywcQAxZuAf1KAiX",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/KOR/TypeScriptLanguageService":
    "QmRGK2g4secen78JUALnoSt1cRNGzb3KPMYoKo96VjZh54",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/KOR/TypeScriptTasks":
    "QmY8fLctxdCxf299KFLeSncu3VyzUXEMvZ6UBmNiXgwfAh",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/KOR":
    "QmZEQaEQ9HC73FDFq4ccafbBSA7tGXPASpfwP2QunsZs5v",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PLK/Targets":
    "QmcYGxLEu4CxuAciw6piZsCGDJHJJYass7RQ99Scvwu6js",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PLK/TypeScriptDebugEngine":
    "Qmej6zazLL4PXULhjGm7GBZT43vH3ZzMQ4cJuJ4aBk1kKU",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PLK/TypeScriptLanguageService":
    "QmUM5ZRrKpTWRUWKcajdx8ZSpsmKWVaQi1C8kuatvXhM3D",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PLK/TypeScriptTasks":
    "QmdKHqeExZokVwCuwVY4L2QVcmcCtncduW1GxaRrFJHPT1",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PLK":
    "Qmc9sBdtkDstw8LvxJAuiF6TyXfCeNJ7Yjxsyr6AGzvuQx",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PTB/Targets":
    "QmVV1Qs7TB84AFacvjtgng9SxCVrwbpekCAGArJeVDQLnc",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PTB/TypeScriptDebugEngine":
    "QmV9edrVXa2oyfth2nzVcJdYhHaByB6S9VX42hfGSHr2Mx",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PTB/TypeScriptLanguageService":
    "QmSxMCMSfoB1t9PaWa8oWHcABkHQrojUDpgriV3hBK36oX",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PTB/TypeScriptTasks":
    "QmWtdtLCnkM6rfxB4c4zBBuQtfs1wgDjWr65WD9Xrkq9bR",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/PTB":
    "QmSRZPPQYz6t1MUDtDFBhrXgDfJHyeiALPhZ5YCDucccU2",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/RUS/Targets":
    "QmUPViZzfoikMDgf2Pishk9gBuT5mik8cgJhiMcv3HWDHE",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/RUS/TypeScriptDebugEngine":
    "QmUpwDxZ4qtoDzeAjRy2YzVSTR9ZDVgeixmdwbyrsrCjmW",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/RUS/TypeScriptLanguageService":
    "QmSrg5nnpMku872DUsWdbaD9KU6fdqu7d5G3LSvztVSyMC",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/RUS/TypeScriptTasks":
    "QmUHKYD9aUu1YiyCBjcqWjKiL3c3koU1Puxd8zViVtMni1",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/RUS":
    "Qmc595D4YvdgLFazcvRiskQoqnJ6TNvMLKuMjzNTTQUFZn",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/TRK/Targets":
    "QmciDX7yxQQbYch4QtCR15nfju6GL86TvNEEGr86ZKupQG",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/TRK/TypeScriptDebugEngine":
    "QmNbY9PBL92HM7JnSz8ZqWmpd3Z7uXuPRZJHVnLEyFNbS9",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/TRK/TypeScriptLanguageService":
    "QmPhPfxtcKNBzM3AULFMbxAtAPZHqc92PnoV4jYzN4FJtk",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/TRK/TypeScriptTasks":
    "Qmdb3Abu9uVpkhLv1eQ2RAuNtGfvPJd2jmyrFmeu7va4aF",
  "src/workers/ipfs/node_modules/typescript/loc/lcl/TRK":
    "Qmd69kMdxscdsja4Jz9rmuMzoWEVjrbTBucByQqkdnoKzq",
  "src/workers/ipfs/node_modules/typescript/loc/lcl":
    "QmZA6Sr3UMH9awrc6K2fovqQGCpHZSnMT9gcgq8EWNzgWr",
  "src/workers/ipfs/node_modules/typescript/loc":
    "QmUmez8oJpBpDiqfCekw4pLRT7pW9ccw3Gr8CUKffx1Jba",
  "src/workers/ipfs/node_modules/typescript":
    "QmNPbmCbsKfTDHgKJtRCsiR4mpzRE2PaMdWRsXijqstAwr",
  "src/workers/ipfs/node_modules/uint8arrays/dist":
    "QmWCCvXXpTSh5kHfj3VyPtx9dTroDWWPVwTf3pu7doJaZx",
  "src/workers/ipfs/node_modules/uint8arrays":
    "QmT7LfTSybFyg46BQAfrDdZT8keH3mZmCbjKC3u3nUzAWN",
  "src/workers/ipfs/node_modules":
    "QmNQaS7UCS2GVgwcHdrQDN4rkAWKFTGRjzxWpQk1wUmEVQ",
  "src/workers/ipfs/src": "QmUqoKmHckW1HgxPr5nprzQiwHLgsuryoGeuHFjJiYCeo1",
  "src/workers/ipfs": "QmZiN8p432yhQcYZWqiAGXsLVzFatk7ijmGuWq2otrk99s",
  "src/workers": "QmbypS6VGsNuUh4sG1MPByP64REBzhQSkZrgxCL2819dZd",
  "src": "QmVbRkCmboJixCpWMHhVFdAwCHWDpKG99UhPsVXwC3Ypt1",
  "": "QmX1fVupjqFwxiofwqva3vXhxRyPrw1w9u59NqSFZQHiiZ",
  "foo": "bar",
};
