export const files = {
  "assets/app.css": "QmVC4G4v549yEk5FYngFyx8Szv74yAQrAY7F5adAKcjybE",
  "assets/fonts/KFOlCnqEu92Fr1MmEU9fBBc9.ttf":
    "QmVB1APqxwoFrkjZ9B2kYmukzGPdVrdct1JdxhkPbeY28Q",
  "assets/fonts/KFOlCnqEu92Fr1MmSU5fBBc9.ttf":
    "QmSuFCECZFdYirnXLK6xfaZWPmqP77LsRCnrdsmU9KVoMT",
  "assets/fonts/KFOlCnqEu92Fr1MmWUlfBBc9.ttf":
    "Qmd8qKxYJaKoiR9EsxgQqwkD5XBzayCHKwNJuhQuUF5ApJ",
  "assets/fonts/KFOmCnqEu92Fr1Mu4mxP.ttf":
    "QmRbTrHtUz6mKUsu7FFzfUBcr4VuoCt9TtpMnJG1P135bS",
  "assets/roboto.css": "QmafZGaL6TznhmwtJ78ggkm7phbCiuEVXcTxfLwbZG6PoT",
  "assets/social-media-computer-icons-share-icon-png":
    "QmcsMurTbnEVPqP42x15FiisSjQdXJ7vGGHhf279UtwPxE",
  "assets/synthwave.jpg": "QmVP5gg9nYuPg1au5pBmdn75xmUvuGevRPLhEngyEyQfkT",
  "assets/triangle-geometry.png":
    "QmZ5Nic3MRHT8m9SY5ZrSp38UHGEYmJqgk4RAmDV3xXqa1",
  "assets/zed-icon-big.png": "QmeHY7RZzR5wm9ELZr5xgq6XMQKjRAHgmxoQaCzHjgpRm8",
  "build.mjs": "QmVtjjGwUgbCyDSvRzZymghKu46XfGr3ScQHsvgHCX5hJi",
  "dev.mjs": "QmZJdMmBnSN9x8RM39MNgStXZhqHHCzsGHAK5v4xwAv33w",
  "dev.mjs.map": "QmZrB9c3SG3fqVcZhjpw5XwE2V8pAoen8jTyu4aukYmLct",
  "edit/index.html": "QmfXTNa9t9Yi9mcrrK9Y8fi6yfSzJ89XxCmGShH1CyZjFX",
  "esbuild-dev.mjs": "QmbfgiqxCgRUf74iCDsSiACipM24LmaVxdTP8s7dGifZcL",
  "esbuild.mjs": "QmURcQLkSmycrsKAaMNcWP1sMWgfwzxuTD9S95nbj2fLJB",
  "favicon.ico": "QmWF8oNe7SDdaY6t4WrJ8ZzM46dHEFmHDXzd8MBeNrELxe",
  "index.html": "QmWNKFa6dduFWyx4uHwmjP3EDtxYYFKDq3wbgcUYegavum",
  "js/codeLoader.mjs": "QmXrJTtSJVSMjvNcYC64BHQ2U2Lk6f3VoyWMD4G3KHJyGh",
  "js/data.mjs": "QmcTKaHFKkEcW1EwjwLfpKrxaTFSfvBzyUE8fCiY3QECnd",
  "js/examples/app.tsx": "QmNbioNuTEMZYjG8fuoKMK1Kph4dakn2k8GA5Vspfjr9A8",
  "js/examples/rca.tsx": "QmeAor3DcH3cyk81ETDS4QtkiPdRw1LgacbuszFUChRH4b",
  "js/examples/starter_framer.js":
    "QmfHYHrBujTA1ZnMuLUUwZQ8GLdh55xRpUvoqK4PK3tdUn",
  "js/formatter.mjs": "Qmcvc7jZkrSvbattfsxi1BqmP7d1pVDy4pjjxeiJL8zmQn",
  "js/hash.mjs": "QmcCE35Pbe286x6xHVDLVsxo2ViRTzAsgdWL3HYDQHxy34",
  "js/importScript.d.ts": "QmV1V5Fb2ZxP5Kn31nSU7FS2TtrDMg6wR7sMTsKeeR1txL",
  "js/importScript.mjs": "QmaN34Vrmzujpc8W8jsAnmrLpkXZmgRLHAwogyxJQKMJ9u",
  "js/importmap.json": "QmcX8ghSyqJxowg7xJZQGkp4A7hdJj4Ksq85hRbrp5p3vy",
  "js/ipfsClient.mjs": "QmSz5ruqLbkpvASSVV6wt1sLwYrZjg5dtZjPuZrwn7yfWT",
  "js/openWindows.mjs": "QmRoBeBkKf7wJGEmm71odzPg2axTyX1YqvbcraPXP1BpPQ",
  "js/renderPreviewWindow.mjs":
    "QmfM7fuM9zA4zhXXxKYVrRkDmPWBLRFprUREVU539zEYCK",
  "js/sendSignalToQrCode.mjs": "QmXbBg2iZDJ74f6qpgt8ADNVnUXaEZUKcATg8uSssWQga6",
  "js/share.mjs": "QmTvDwFNzo3WHuwTwkAzrWXy6sHAL3Y8QX2CwzjRXNfyqm",
  "js/starter.js": "QmPxj182MRQuiFi46JgHoe3YtwERJxpfMWK1Cc2XFeFP6Q",
  "js/templates.ts": "QmVvr1YDF5aMGA4MSYZ6k6stsgVvW3yTCK2SpKkvUivezU",
  "js/test.mjs": "QmVnzwNd3k5NioNUeMagb77Q4LRW5DmGxaeBJp7hdoapLK",
  "js/transpile.mjs": "QmcpPZZrhCgSykw5Xh194W86wwpDycgS1SQHfKNVXiT3tE",
  "js/workboxLoader.mjs": "QmeLWcVUx3CxpydK12BJBXE2Xhp46YuE2xftuMCta9u3TF",
  "js/workers/getWorker.mjs": "QmSkBAGo1hbEPYDnHEpBvGihaVij432VMrmRWm1ZoDL3cP",
  "js/workers/ipfsWorker.js": "QmcnGJVvv7Dci6gYCpma6L15bNUabcbnuki1dVwCZYTfWn",
  "js/workers/prettierWorker.js":
    "QmPP3Vpq7Br5xPHL12XDXhR3c2TzwqgRSyLws37sKvHS2N",
  "js/workers/transpile.worker.js":
    "QmUo7nNGTPDUbTkv33Vsge4Ke6BpMAUCQ84uZ6X3dCfNDV",
  "manifest.json": "Qmb8h3PjM5RvHpNZSQztqVdrCHANNT7k8Dsj8Jmv24XmRQ",
  "package.json": "QmebH18WeKwu1x3F4ieTxdXQ73PiHBMP3mbAfsmUiojZz5",
  "scripts/importmapGenerator.mjs":
    "QmXms6rg1U8TbDB4HbKKvWtZGHZvQ2CHe3qnsmD8DfhSa1",
  "sw.js": "QmZs73xvygu9Zx4mvDdwWWv6zL81UGY1geTsVZGrXdnTEf",
  "tsconfig.json": "QmRWz23wpfBrozV1qkw9JztmRnBjHh6sSX4dpbEbWBcyfW",
  "yarn-error.log": "QmdZAKvVENP6xmY6xyYPbWQVE4yZYmuVjG9CrUD24EJnYH",
  "assets/fonts": "QmYAJJ726yRoCVerLBgUHdLax1JKS85SYLrnrG54WxSDtK",
  "assets/synthwave-vscode": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "assets": "QmZSmTroUQNVRJ6nhNGpi3u9Rg3pp3NskVqhLd1NtsrEaV",
  "edit": "QmRBtzxNHPENXEfZwv1aZk9XmznUM6mesSe3GKVB8UwwXS",
  "js/examples": "Qmbcmjf53NLhuNdY6uDDpPeqNbNGAi76Qo4jdZCageGrFJ",
  "js/workers": "QmTUnCiT5WvN25aVGttYn2Qx9PCUvKJjjT4ddypo4vukP6",
  "js": "QmQGQvmBdcb9q8KbCUJvCvJDsSk86xDa2zxy3YWi5A3ZSD",
  "modules": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "node_modules": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "scripts": "QmPDNRUoFBTGTmEDJBxKtMt8kPa99yKNByGthZqWiqGA1J",
  "": "QmR2vQUQotAMogTPw4Hmj26egtkM9VkWeYonchChB6RKbh",
  "foo": "bar",
};
