"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
exports.__esModule = true;
exports.ResultBoxContainer = exports.ResultBox = exports.ErrorContainer = exports.ResultContainer = exports.CodeContainer = exports.Header = void 0;
var styled_1 = require("@emotion/styled");
exports.Header = styled_1["default"].div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    background: #3f51b5;\n    font-family: \"Roboto\";\n    margin: 0;\n    padding: 10px 20px 10px;\n    color: white;\n"], ["\n    background: #3f51b5;\n    font-family: \"Roboto\";\n    margin: 0;\n    padding: 10px 20px 10px;\n    color: white;\n"])));
exports.CodeContainer = styled_1["default"].div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    display: block;\n    width: 100%;\n    height: 70vh;\n"], ["\n    display: block;\n    width: 100%;\n    height: 70vh;\n"])));
exports.ResultContainer = styled_1["default"].div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    display: block;\n    width: 100%;\n"], ["\n    display: block;\n    width: 100%;\n"])));
exports.ErrorContainer = styled_1["default"].div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    display: block;\n    width: 100%;\n    padding: 10px;\n    color: white;\n    background: red;\n    height: 220px;\n    pre{\n        font-size: 1em;\n        line-height: 1;\n    }\n"], ["\n    display: block;\n    width: 100%;\n    padding: 10px;\n    color: white;\n    background: red;\n    height: 220px;\n    pre{\n        font-size: 1em;\n        line-height: 1;\n    }\n"])));
exports.ResultBox = styled_1["default"].div(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n    text-align: center;\n    border-radius: 12px;\n    width: 200px;\n    height: 200px;\n    display: flex;\n    place-content: center;\n    place-items: center;\n    margin: 0;\n    padding: 0;\n    background: rgb(255, 255, 255) none repeat scroll 0% 0%;\n    user-select: none;\n    box-shadow: rgba(0, 0, 0, 0.1) 0px 2px 3px 0px, rgba(0, 0, 0, 0.06) 0px 10px 15px 0px;\n"], ["\n    text-align: center;\n    border-radius: 12px;\n    width: 200px;\n    height: 200px;\n    display: flex;\n    place-content: center;\n    place-items: center;\n    margin: 0;\n    padding: 0;\n    background: rgb(255, 255, 255) none repeat scroll 0% 0%;\n    user-select: none;\n    box-shadow: rgba(0, 0, 0, 0.1) 0px 2px 3px 0px, rgba(0, 0, 0, 0.06) 0px 10px 15px 0px;\n"])));
exports.ResultBoxContainer = styled_1["default"].div(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n    display: block;\n    width: 150px;\n    height: 150px;\n    overflow: hidden;\n"], ["\n    display: block;\n    width: 150px;\n    height: 150px;\n    overflow: hidden;\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6;
