/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RouterImport } from './routes/router'

// Create/Update Routes

const RouterRoute = RouterImport.update({
  id: '/router',
  path: '/router',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/router': {
      id: '/router'
      path: '/router'
      fullPath: '/router'
      preLoaderRoute: typeof RouterImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/router': typeof RouterRoute
}

export interface FileRoutesByTo {
  '/router': typeof RouterRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/router': typeof RouterRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/router'
  fileRoutesByTo: FileRoutesByTo
  to: '/router'
  id: '__root__' | '/router'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  RouterRoute: typeof RouterRoute
}

const rootRouteChildren: RootRouteChildren = {
  RouterRoute: RouterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/router"
      ]
    },
    "/router": {
      "filePath": "router.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
