import * as React from "react";
declare const Select: any;
declare const SelectGroup: any;
declare const SelectValue: any;
declare const SelectTrigger: React.ForwardRefExoticComponent<any>;
declare const SelectScrollUpButton: React.ForwardRefExoticComponent<any>;
declare const SelectScrollDownButton: React.ForwardRefExoticComponent<any>;
declare const SelectContent: React.ForwardRefExoticComponent<any>;
declare const SelectLabel: React.ForwardRefExoticComponent<any>;
declare const SelectItem: React.ForwardRefExoticComponent<any>;
declare const SelectSeparator: React.ForwardRefExoticComponent<any>;
export { Select, SelectGroup, SelectValue, SelectTrigger, SelectContent, SelectLabel, SelectItem, SelectSeparator, SelectScrollUpButton, SelectScrollDownButton, };
