version: "3.9"
services:
  devcontainer:
    # Overrides for development-specific configuration
    user: ${USER:-gitpod}
    
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached
      # For better performance, consider using delegated mount on macOS
      # - ..:/workspace:delegated
      
      # Pass Docker socket for Docker-in-Docker
      - /var/run/docker.sock:/var/run/docker.sock
      
      # For persisting VS Code extensions between container rebuilds
      - vscode-extensions:/home/${USER:-gitpod}/.vscode-server/extensions
    
    # Add capability for debugging
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    
    # Uncomment to use a non-root user
    # user: vscode

volumes:
  vscode-extensions: