name = "durable-objects"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
	{ name = "COUNTER", class_name = "Counter" },
	{ name = "SQL", class_name = "SQLiteDurableObject" },
	{ name = "PRESENCE", class_name = "PresenceDurableObject" }
]

[[migrations]]
tag = "v1" # It might be appropriate to increment the tag or create a new migration block
           # if this were a real-world scenario with existing deployments.
           # For this task, modifying the existing one is fine.
new_classes = ["Counter", "PresenceDurableObject"]
new_sqlite_classes = ["SQLiteDurableObject"]
