export const files = {
  "assets/app.css": "QmVC4G4v549yEk5FYngFyx8Szv74yAQrAY7F5adAKcjybE",
  "assets/fonts/KFOlCnqEu92Fr1MmEU9fBBc9.ttf":
    "QmVB1APqxwoFrkjZ9B2kYmukzGPdVrdct1JdxhkPbeY28Q",
  "assets/fonts/KFOlCnqEu92Fr1MmSU5fBBc9.ttf":
    "QmSuFCECZFdYirnXLK6xfaZWPmqP77LsRCnrdsmU9KVoMT",
  "assets/fonts/KFOlCnqEu92Fr1MmWUlfBBc9.ttf":
    "Qmd8qKxYJaKoiR9EsxgQqwkD5XBzayCHKwNJuhQuUF5ApJ",
  "assets/fonts/KFOmCnqEu92Fr1Mu4mxP.ttf":
    "QmRbTrHtUz6mKUsu7FFzfUBcr4VuoCt9TtpMnJG1P135bS",
  "assets/roboto.css": "QmafZGaL6TznhmwtJ78ggkm7phbCiuEVXcTxfLwbZG6PoT",
  "assets/social-media-computer-icons-share-icon-png":
    "QmcsMurTbnEVPqP42x15FiisSjQdXJ7vGGHhf279UtwPxE",
  "assets/synthwave.jpg": "QmVP5gg9nYuPg1au5pBmdn75xmUvuGevRPLhEngyEyQfkT",
  "assets/triangle-geometry.png":
    "QmZ5Nic3MRHT8m9SY5ZrSp38UHGEYmJqgk4RAmDV3xXqa1",
  "assets/zed-icon-big.png": "QmeHY7RZzR5wm9ELZr5xgq6XMQKjRAHgmxoQaCzHjgpRm8",
  "build.mjs": "QmPh6cfwgazifBaEwWN1GtZDQoeW2e7fZpNKGFBWdRdCau",
  "dev.mjs": "QmYxtr6EqVdjA5Wj8NeNrYRCQVNze5nd8xLftt4P4xRLJh",
  "dev.mjs.map": "QmVpsCtofeTR5KhiuLQNs7hVxCoVDky38KW4u4uPV9mWEc",
  "edit/index.html": "QmfXTNa9t9Yi9mcrrK9Y8fi6yfSzJ89XxCmGShH1CyZjFX",
  "esbuild-dev.mjs": "QmNbYHeZvHhwEYyUTtnFvaoWq8yZ32iX1XXhngcaxHq1DT",
  "esbuild.mjs": "QmSaddDHVdzrh6jNmE1SVq2QdqCeoy2sRskLdYhLTAQBPb",
  "favicon.ico": "QmWF8oNe7SDdaY6t4WrJ8ZzM46dHEFmHDXzd8MBeNrELxe",
  "index.html": "Qma4n5a9jGujZNz4vnTc2EWJzmKzX3bLaPsXR9hqYWBzVU",
  "js/codeLoader.mjs": "QmZbcT6aW3cn8QHgcTaJPKsiVf8gJu87HEbZBMY5ZdfUXt",
  "js/data.mjs": "QmVArHUrpPyQ1dxbnRxc7dS3T3gVJkrmDy9iS9QbttyeYE",
  "js/examples/app.tsx": "QmNbioNuTEMZYjG8fuoKMK1Kph4dakn2k8GA5Vspfjr9A8",
  "js/examples/rca.tsx": "QmeAor3DcH3cyk81ETDS4QtkiPdRw1LgacbuszFUChRH4b",
  "js/examples/starter_framer.js":
    "QmfHYHrBujTA1ZnMuLUUwZQ8GLdh55xRpUvoqK4PK3tdUn",
  "js/formatter.mjs": "Qmcvc7jZkrSvbattfsxi1BqmP7d1pVDy4pjjxeiJL8zmQn",
  "js/importScript.d.ts": "QmV1V5Fb2ZxP5Kn31nSU7FS2TtrDMg6wR7sMTsKeeR1txL",
  "js/importScript.mjs": "QmQBhy9H2prXzc5DnjVcF7qfkEMYVz4TFtwzegpcpEp4Da",
  "js/importmap.json": "QmcuQqXDybwwtH7zvH7WMbijRDqNCwoA1MczJz8LyFY1aT",
  "js/ipfsClient.mjs": "QmbuDJs8LgqAjJKrT4Uyjd3FHYZw9tN9B9RcwdUkNCoRdy",
  "js/openWindows.mjs": "QmaFnxSVkYqEBDhrTpZQTFP5S7Rm2fUtTEDV6ptzpDfnYQ",
  "js/reactLoader.mjs": "Qmacvt7gBakvaKMG81JDDvq2hXWDnTNBoPRfo2WcVXDYhP",
  "js/renderPreviewWindow.mjs":
    "QmUyh5zKwnWAjG8W6rYKc4sRcJkd7wn7HdWGeENiLxca3i",
  "js/sendSignalToQrCode.mjs": "QmP9ZZ462aU9KZkiXykmh7DXuxdJkCYn68neF7bxCfq43M",
  "js/share.mjs": "QmcL4MpDGq82vMRrDEatpb51a7dU9JK5q4R4rzGndCbnMa",
  "js/starter.js": "QmRgj26shzTEx1Kw3ZV5bHaRYSrY7P7oyKjERSF6spwQD6",
  "js/templates.ts": "QmNaKPedMWvBy5iSAdj8ygPVWvhUcg61DPAFpDBTzzsHU3",
  "js/test.mjs": "QmVnzwNd3k5NioNUeMagb77Q4LRW5DmGxaeBJp7hdoapLK",
  "js/transpile.mjs": "QmcpPZZrhCgSykw5Xh194W86wwpDycgS1SQHfKNVXiT3tE",
  "js/workboxLoader.mjs": "QmQ3Aw34jwgHqjYFFmEsSRACr7h98Hma6YknYv8Lop7AA1",
  "js/workers/getWorker.mjs": "QmNsgRYgX3YSwM66LuoZAD4fQy4Xvy4dKKNTn8BSm3bGLE",
  "js/workers/ipfsWorker.js": "QmcnGJVvv7Dci6gYCpma6L15bNUabcbnuki1dVwCZYTfWn",
  "js/workers/prettierWorker.js":
    "QmTzHQedmz11rTh1HHJuyEas3DgSW5ct8BzzSSWMLpQgB7",
  "js/workers/transpile.worker.js":
    "QmSs696TvpjKd6Tm1Wxnzpj3tHrwBJVhKkVpTcQFA9PdLf",
  "manifest.json": "QmXmokoZc6CTgga36sBaEXYvw3fPCjJSCrXx1HzLkQewnm",
  "package.json": "QmQokzNyeZ6ZaadwjuPxZVaXnz9fUWGjuAuZa29oXvabvw",
  "scripts/importmapGenerator.mjs":
    "QmeQcXjE1tWxXBznxQ5vW1G8znaa5XfJzbuQNPPy3spDMS",
  "sw.js": "QmeNE6t7NExCfrKJPtw6HZfZb5xpHpoxFYD6TSwciACfCu",
  "tsconfig.json": "QmRYPKEpGHQR1rcA75SRHtiTFy21r9Gj59giYPeDt4DU93",
  "assets/fonts": "QmYAJJ726yRoCVerLBgUHdLax1JKS85SYLrnrG54WxSDtK",
  "assets": "QmWHZGZtu54TG9suDt4eCUVVnwTmtjLkqU2x9NFcBc81Ca",
  "edit": "QmRBtzxNHPENXEfZwv1aZk9XmznUM6mesSe3GKVB8UwwXS",
  "js/examples": "Qmbcmjf53NLhuNdY6uDDpPeqNbNGAi76Qo4jdZCageGrFJ",
  "js/workers": "Qme7WdDXBHygT32s8YVVttJZnR2bBjyYgjF2hBKLjoktrV",
  "js": "QmUVDYGmVhmHhcKJgr6CpgxG83HrGAHeE15sjupffBx3o6",
  "modules": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "node_modules": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "scripts": "QmbW4MskUSgTKTX2myZhtKu7RBmNXRsaypRDNRAAxTUTrc",
  "": "Qmc7gmV3ArfJDYQhuQJ6jaTikh5V3KCaXRAZXJpCmpQiSj",
  "foo": "bar",
};
