export const files = {
  "assets/app.css": "QmSXB2xnV66gp7yDmWMqesxsnucGJ9ewCUeftZSmwXCBHj",
  "assets/fonts/KFOlCnqEu92Fr1MmEU9fBBc9.ttf":
    "QmVB1APqxwoFrkjZ9B2kYmukzGPdVrdct1JdxhkPbeY28Q",
  "assets/fonts/KFOlCnqEu92Fr1MmSU5fBBc9.ttf":
    "QmSuFCECZFdYirnXLK6xfaZWPmqP77LsRCnrdsmU9KVoMT",
  "assets/fonts/KFOlCnqEu92Fr1MmWUlfBBc9.ttf":
    "Qmd8qKxYJaKoiR9EsxgQqwkD5XBzayCHKwNJuhQuUF5ApJ",
  "assets/fonts/KFOmCnqEu92Fr1Mu4mxP.ttf":
    "QmRbTrHtUz6mKUsu7FFzfUBcr4VuoCt9TtpMnJG1P135bS",
  "assets/roboto.css": "QmafZGaL6TznhmwtJ78ggkm7phbCiuEVXcTxfLwbZG6PoT",
  "assets/social-media-computer-icons-share-icon-png":
    "QmcsMurTbnEVPqP42x15FiisSjQdXJ7vGGHhf279UtwPxE",
  "assets/synthwave.jpg": "QmVP5gg9nYuPg1au5pBmdn75xmUvuGevRPLhEngyEyQfkT",
  "assets/synthwave.webp": "QmVUXK99dtKSob78XiURnzafewgiF7dTy8LkRJMR3yNTaS",
  "assets/triangle-geometry.png":
    "QmZ5Nic3MRHT8m9SY5ZrSp38UHGEYmJqgk4RAmDV3xXqa1",
  "assets/zed-icon-big.png": "QmeHY7RZzR5wm9ELZr5xgq6XMQKjRAHgmxoQaCzHjgpRm8",
  "dev.mjs": "QmPBEWi7MD7txqu1KMZCN2GXxRxmXBS1HfH2n4oZraJBGV",
  "dev.mjs.map": "QmQfGNg9V9nNRzzaJX5v72HwM9fHj76Mh1G31GsV4HduDn",
  "edit/index.html": "QmfXTNa9t9Yi9mcrrK9Y8fi6yfSzJ89XxCmGShH1CyZjFX",
  "esbuild-dev.mjs": "QmUqp7sUH1QAkE8uVZgozsNufupqgDcQR7eMhpjR3GERhv",
  "favicon.ico": "QmWF8oNe7SDdaY6t4WrJ8ZzM46dHEFmHDXzd8MBeNrELxe",
  "index.html": "QmfHsPYT6CGouYHNFYk7A3cnZFNVbF7M6S2RkqqRSC7dX3",
  "js/codeLoader.mjs": "QmNsNXx8hjxEXy6VsCBNc2dxYsY5y14pqwCvBRpdZ9WA6u",
  "js/data.mjs": "QmYiipFsDxwwY4RJ46PJvTAk6eZ73XwczjbwYYbi5Hmzzx",
  "js/examples/app.tsx": "QmNbioNuTEMZYjG8fuoKMK1Kph4dakn2k8GA5Vspfjr9A8",
  "js/examples/rca.tsx": "QmSdyVsc9Lda7zpvN7hAGAuQisgPcLsRztEoRxfkH3F9Cm",
  "js/examples/starter_framer.js":
    "QmfHYHrBujTA1ZnMuLUUwZQ8GLdh55xRpUvoqK4PK3tdUn",
  "js/formatter.mjs": "Qmcvc7jZkrSvbattfsxi1BqmP7d1pVDy4pjjxeiJL8zmQn",
  "js/importScript.d.ts": "QmV1V5Fb2ZxP5Kn31nSU7FS2TtrDMg6wR7sMTsKeeR1txL",
  "js/importScript.mjs": "QmQBhy9H2prXzc5DnjVcF7qfkEMYVz4TFtwzegpcpEp4Da",
  "js/importmap.json": "QmXMyQxVDD6ujLCifB8HhMc3UUhhAZ5tXrevesvzQfzzLg",
  "js/ipfsClient.mjs": "Qma5ZP226wff835FKrLgvaEwYMeQQ8q6EWUL8d7vsNeSHt",
  "js/openWindows.mjs": "QmQDSXPm2xLjd1VZpthAjpt81CRVynQMWM26nNVncnYMdW",
  "js/reactLoader.mjs": "QmQVz3MRExedsNSyzKQyeU5te84tE4ACMzrEEuntyG4MjM",
  "js/renderPreviewWindow.mjs":
    "QmUyh5zKwnWAjG8W6rYKc4sRcJkd7wn7HdWGeENiLxca3i",
  "js/sendSignalToQrCode.mjs": "QmP9ZZ462aU9KZkiXykmh7DXuxdJkCYn68neF7bxCfq43M",
  "js/share.mjs": "QmaUvqqRagjq4becLxjK4mmExXz45QNtxPDwuv2bkG2qaA",
  "js/starter.mjs": "QmTmkvbwsXwLRNbZYRQbpyHcd7w3K1jMyyJbdL9VVjXQem",
  "js/sw.js": "QmPujUc2VFeEwmWV4jnqKraz1Sxva7cneVZyudjjLALuQc",
  "js/templates.ts": "QmfU3mQKWUceUKUTvqZCVQVmNARuoajZRXRfWiJVBDy274",
  "js/test.mjs": "QmVnzwNd3k5NioNUeMagb77Q4LRW5DmGxaeBJp7hdoapLK",
  "js/transpile.mjs": "QmcpPZZrhCgSykw5Xh194W86wwpDycgS1SQHfKNVXiT3tE",
  "js/workboxLoader.mjs": "QmUJazcXnb8Ue2oa37zumPByvPju9BkuP3ooQacZKSNxq8",
  "js/workers/getWorker.mjs": "QmNsgRYgX3YSwM66LuoZAD4fQy4Xvy4dKKNTn8BSm3bGLE",
  "js/workers/ipfsWorker.js": "QmanHgJXuinvNKMm7ACKFyQQrhCLMsPvpyK6KY1ZQYs9Wf",
  "js/workers/prettierWorker.js":
    "QmTzHQedmz11rTh1HHJuyEas3DgSW5ct8BzzSSWMLpQgB7",
  "js/workers/transpile.worker.js":
    "QmURZxeJkk2kQjNfhBb98B9vH6FnbUefPZedZw6RN8rw45",
  "js/ws.mjs": "QmecHrnebUNwPRZrghq2tMuS9ZTXjuPYVNcknAjLbnijF6",
  "manifest.json": "QmXmokoZc6CTgga36sBaEXYvw3fPCjJSCrXx1HzLkQewnm",
  "package.json": "QmNuYWJtER7SVBJYf3CcFbtbn3hfxjdQP9vatku7eU638M",
  "scripts/importmapGenerator.mjs":
    "QmT2bT2Dc1xMtGp7GKacuTo3tro3A5PsgfxmYAddFVB5S4",
  "tsconfig.json": "QmQuH91sPQ36qvHdFaMmbtg8btgPFXXLcdGfuUBDwhH44k",
  "assets/fonts": "QmYAJJ726yRoCVerLBgUHdLax1JKS85SYLrnrG54WxSDtK",
  "assets": "QmedqU5fD5EAX2XssVy6HUM8R71uqyYQzn72fRDDnz13f6",
  "edit": "QmRBtzxNHPENXEfZwv1aZk9XmznUM6mesSe3GKVB8UwwXS",
  "js/examples": "QmbZePTm4aHmFmZefnvz4CNm7omsSHvpGDn4HXSpq1atQB",
  "js/workers": "QmPxzCnYuV32u4nzMyutJcQzSvkUqtT58A2EkaZcYnpHzf",
  "js": "QmfE8b3yiprTZd7PgT4K8iCRJitEbCVPe333AwumxhQDSN",
  "node_modules": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "scripts": "QmW3yywSFJZC8dU8GV1PKGWLCUyBDvQtYWYXVJPxEbM8aX",
  "": "QmPgsmep2KsZGgXg866viyMijSZo5nhTHDrtWkVwveRwE5",
  "foo": "bar",
};
