// Generated by dts-bundle-generator v6.3.0

import * as React from 'react';

declare const react: unknown;
export declare const createContext: typeof React.createContext;
export declare const useDebugValue: typeof React.useDebugValue;
export declare const useState: typeof React.useState;
export default react;

export {};
