export const files = {
  "assets/app.css": "QmVC4G4v549yEk5FYngFyx8Szv74yAQrAY7F5adAKcjybE",
  "assets/fonts/KFOlCnqEu92Fr1MmEU9fBBc9.ttf":
    "QmVB1APqxwoFrkjZ9B2kYmukzGPdVrdct1JdxhkPbeY28Q",
  "assets/fonts/KFOlCnqEu92Fr1MmSU5fBBc9.ttf":
    "QmSuFCECZFdYirnXLK6xfaZWPmqP77LsRCnrdsmU9KVoMT",
  "assets/fonts/KFOlCnqEu92Fr1MmWUlfBBc9.ttf":
    "Qmd8qKxYJaKoiR9EsxgQqwkD5XBzayCHKwNJuhQuUF5ApJ",
  "assets/fonts/KFOmCnqEu92Fr1Mu4mxP.ttf":
    "QmRbTrHtUz6mKUsu7FFzfUBcr4VuoCt9TtpMnJG1P135bS",
  "assets/roboto.css": "QmafZGaL6TznhmwtJ78ggkm7phbCiuEVXcTxfLwbZG6PoT",
  "assets/social-media-computer-icons-share-icon-png":
    "QmcsMurTbnEVPqP42x15FiisSjQdXJ7vGGHhf279UtwPxE",
  "assets/synthwave.jpg": "QmVP5gg9nYuPg1au5pBmdn75xmUvuGevRPLhEngyEyQfkT",
  "assets/triangle-geometry.png":
    "QmZ5Nic3MRHT8m9SY5ZrSp38UHGEYmJqgk4RAmDV3xXqa1",
  "assets/zed-icon-big.png": "QmeHY7RZzR5wm9ELZr5xgq6XMQKjRAHgmxoQaCzHjgpRm8",
  "build.mjs": "QmWc5FSDsdTWesxRzU6UCVZnLd85RyBvoXuJ2nwdJPDTdi",
  "dev.mjs": "Qma8PiiGbq8vr6G1VN9ymK2q7zBu7wVtRD4bGuLxXuZhEx",
  "dev.mjs.map": "Qmdwuh9usGfdEUfNoxqtKDy5UgNmA4Xg5vSke8SmdMzq2m",
  "edit/index.html": "QmfXTNa9t9Yi9mcrrK9Y8fi6yfSzJ89XxCmGShH1CyZjFX",
  "esbuild-dev.mjs": "QmNbYHeZvHhwEYyUTtnFvaoWq8yZ32iX1XXhngcaxHq1DT",
  "esbuild.mjs": "QmSaddDHVdzrh6jNmE1SVq2QdqCeoy2sRskLdYhLTAQBPb",
  "favicon.ico": "QmWF8oNe7SDdaY6t4WrJ8ZzM46dHEFmHDXzd8MBeNrELxe",
  "index.html": "QmNUCUZwKUdgT7z7nUemVgrYoMgLQkJG5RRDChC9EcMy2n",
  "js/codeLoader.mjs": "QmTB9LTHrmi5XSGnc8Jm5jQDuF8Law5TRR6dyUV5DKKmws",
  "js/data.mjs": "QmNZUYVmbTK9gA7s4TDoRJvCCSVJo95EG7fxeh5zF6HDdM",
  "js/examples/app.tsx": "QmNbioNuTEMZYjG8fuoKMK1Kph4dakn2k8GA5Vspfjr9A8",
  "js/examples/rca.tsx": "QmeAor3DcH3cyk81ETDS4QtkiPdRw1LgacbuszFUChRH4b",
  "js/examples/starter_framer.js":
    "QmfHYHrBujTA1ZnMuLUUwZQ8GLdh55xRpUvoqK4PK3tdUn",
  "js/formatter.mjs": "Qmcvc7jZkrSvbattfsxi1BqmP7d1pVDy4pjjxeiJL8zmQn",
  "js/importScript.d.ts": "QmV1V5Fb2ZxP5Kn31nSU7FS2TtrDMg6wR7sMTsKeeR1txL",
  "js/importScript.mjs": "QmQBhy9H2prXzc5DnjVcF7qfkEMYVz4TFtwzegpcpEp4Da",
  "js/importmap.json": "QmNSLFeTDKWAoAfPWKyoJdDNLEzQRmrnU3s4VnHjEP7PjY",
  "js/ipfsClient.mjs": "QmUPQkdW2UBaN7RuTTX4G1k2bF7oG4SfkUjjuZSy7N84cg",
  "js/openWindows.mjs": "QmdGHg1TYyP31NqJkAQKsrWQudjBbLc56GKK4s6unpFAvc",
  "js/reactLoader.mjs": "Qmacvt7gBakvaKMG81JDDvq2hXWDnTNBoPRfo2WcVXDYhP",
  "js/renderPreviewWindow.mjs":
    "QmUyh5zKwnWAjG8W6rYKc4sRcJkd7wn7HdWGeENiLxca3i",
  "js/sendSignalToQrCode.mjs": "QmcwkWzt5EkYykTPgwLyyVvQeftvkEVmjNPgcD1P4jbBBP",
  "js/share.mjs": "QmQsin1ZXZQnpSHqTxhFfuk4PqQfvopE2fz1Ejuqhg6ZpW",
  "js/starter.js": "QmcmKj9KL5SZqbNBwcv1ut1ee8pbq5N2QdHkDpEwRriePH",
  "js/templates.ts": "QmTHRQQctZKTsgZGDP8J3eoZFhKcpkiSBYP859QcPH1tLy",
  "js/test.mjs": "QmVnzwNd3k5NioNUeMagb77Q4LRW5DmGxaeBJp7hdoapLK",
  "js/transpile.mjs": "QmcpPZZrhCgSykw5Xh194W86wwpDycgS1SQHfKNVXiT3tE",
  "js/workboxLoader.mjs": "QmeLWcVUx3CxpydK12BJBXE2Xhp46YuE2xftuMCta9u3TF",
  "js/workers/getWorker.mjs": "QmSkBAGo1hbEPYDnHEpBvGihaVij432VMrmRWm1ZoDL3cP",
  "js/workers/ipfsWorker.js": "QmcnGJVvv7Dci6gYCpma6L15bNUabcbnuki1dVwCZYTfWn",
  "js/workers/prettierWorker.js":
    "QmTzHQedmz11rTh1HHJuyEas3DgSW5ct8BzzSSWMLpQgB7",
  "js/workers/transpile.worker.js":
    "QmUo7nNGTPDUbTkv33Vsge4Ke6BpMAUCQ84uZ6X3dCfNDV",
  "manifest.json": "Qmb8h3PjM5RvHpNZSQztqVdrCHANNT7k8Dsj8Jmv24XmRQ",
  "package.json": "QmTNTi7y6isugHPa6nXTdNGUA8uAx8htqqPED6hVC4r18y",
  "scripts/importmapGenerator.mjs":
    "QmfKS5a9GXS3ZxAigiFGcPvUVJHmw1DbcvdmQn7rP5bQoZ",
  "sw.js": "QmZs73xvygu9Zx4mvDdwWWv6zL81UGY1geTsVZGrXdnTEf",
  "tsconfig.json": "QmRYPKEpGHQR1rcA75SRHtiTFy21r9Gj59giYPeDt4DU93",
  "assets/fonts": "QmYAJJ726yRoCVerLBgUHdLax1JKS85SYLrnrG54WxSDtK",
  "assets": "QmWHZGZtu54TG9suDt4eCUVVnwTmtjLkqU2x9NFcBc81Ca",
  "edit": "QmRBtzxNHPENXEfZwv1aZk9XmznUM6mesSe3GKVB8UwwXS",
  "js/examples": "Qmbcmjf53NLhuNdY6uDDpPeqNbNGAi76Qo4jdZCageGrFJ",
  "js/workers": "QmcB4V7zvE94b5wW492GM7wfFTmChtcAm5t5HrFyZjQRuj",
  "js": "Qmcedf9MejHGj3ejGrjne2CHE48VkBDEuATCgEuwSj2wGJ",
  "modules": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "node_modules": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "scripts": "QmdNRsoUNGpBWuoUSUV9fcG5Ch6DJ5VtTAubFVvkbAJGKN",
  "": "QmYHrsPaNVzQ17MUaVNKu4BU8jG2f4pDDqr8TrmCFhSQjy",
  "foo": "bar",
};
