export const files = {
  "assets/app.css": "Qmbh94S3j1gDwhW9eMQ16ZKeZe3sRSQCYqWtCRVARU8HYM",
  "assets/fonts/KFOlCnqEu92Fr1MmEU9fBBc9.ttf":
    "QmVB1APqxwoFrkjZ9B2kYmukzGPdVrdct1JdxhkPbeY28Q",
  "assets/fonts/KFOlCnqEu92Fr1MmSU5fBBc9.ttf":
    "QmSuFCECZFdYirnXLK6xfaZWPmqP77LsRCnrdsmU9KVoMT",
  "assets/fonts/KFOlCnqEu92Fr1MmWUlfBBc9.ttf":
    "Qmd8qKxYJaKoiR9EsxgQqwkD5XBzayCHKwNJuhQuUF5ApJ",
  "assets/fonts/KFOmCnqEu92Fr1Mu4mxP.ttf":
    "QmRbTrHtUz6mKUsu7FFzfUBcr4VuoCt9TtpMnJG1P135bS",
  "assets/normalize.min.css": "QmVaRzLwnw3Nnoq8KHNBSTun6m3v2WvVaUbRpukVpcGJUX",
  "assets/roboto.css": "QmafZGaL6TznhmwtJ78ggkm7phbCiuEVXcTxfLwbZG6PoT",
  "assets/social-media-computer-icons-share-icon-png":
    "QmcsMurTbnEVPqP42x15FiisSjQdXJ7vGGHhf279UtwPxE",
  "assets/synthwave.jpg": "QmVP5gg9nYuPg1au5pBmdn75xmUvuGevRPLhEngyEyQfkT",
  "assets/triangle-geometry.png":
    "QmZ5Nic3MRHT8m9SY5ZrSp38UHGEYmJqgk4RAmDV3xXqa1",
  "assets/zed-icon-big.png": "QmeHY7RZzR5wm9ELZr5xgq6XMQKjRAHgmxoQaCzHjgpRm8",
  "favicon.ico": "QmWF8oNe7SDdaY6t4WrJ8ZzM46dHEFmHDXzd8MBeNrELxe",
  "index.html": "QmR5YTPn7gRkGNndd8w6WDJisSf73dBkS6ZKd7FU5CR4F1",
  "ipfs.json": "QmbBV3Li2S1VDtjj2EMW9AFtuMDppanNMYgJr3nzEpwKTf",
  "manifest.json": "QmTBHTEYaAy537jiSxtGsyDWNAAXQsvtCtmLgBvbGPFdK3",
  "node_legacy/@babel/standalone/LICENSE":
    "QmZqNk275fZv9p2XtmVbDu5cwqnkhKrrFN3wbYJqGzpznc",
  "node_legacy/@babel/standalone/README.md":
    "Qmd7fqhRTRNoZVVTMt3YuJjUzLUDjajmyyYdQigncNqkAE",
  "node_legacy/@babel/standalone/babel.js":
    "QmYsHEj7QyeLRK17JqduUcZo73AxxYLZTJ1T5ZMyrFPQqC",
  "node_legacy/@babel/standalone/babel.min.js":
    "QmdCiW5wGiJKavAHxWwg6Q1ADWVoVVwQjVC1zHMRGdR287",
  "node_legacy/@babel/standalone/package.json":
    "QmdKc28DprNXfJdbv9MRbxBQ8GXxbfDXebJXDruZdM7HHU",
  "node_legacy/@babel/standalone/test/babel.js":
    "QmSVHZ25VdQAypNkJWq97qUuv5bcULo5hGWvqgjkZLVYtk",
  "node_legacy/comlink/comlink.min.js":
    "QmXxvh5CjqR5b2gDgeGLpi52sJT57bmnse9JaofpHCm5i3",
  "node_legacy/comlink/comlink.min.mjs":
    "QmQaWVwJtXHsDocKk3FzJBaNA6VUhuiqbhTgUgVfBJRHiZ",
  "node_legacy/ipfs-message-port-client/CHANGELOG.md":
    "QmbHzj97YThEZEG4Wki5B3SP3faGLbF7im78U82fMf2o9o",
  "node_legacy/ipfs-message-port-client/README.md":
    "QmTQvQXKaWPSk1W4J6Ebohkk3Z7aBoxPDa28VWsPs1hbcf",
  "node_legacy/ipfs-message-port-client/dist/index.min.js":
    "Qmafe9mxRXaKs8AYq8PuSMz4YXebcKkGSBCLqrePoMuJwT",
  "node_legacy/ipfs-message-port-client/dist/src/block.d.ts":
    "QmVt74d56eTUzDj5Hgy1HdpYtQV9bpJtT1QMUE8E43Nei3",
  "node_legacy/ipfs-message-port-client/dist/src/block.d.ts.map":
    "QmPvz7CqN3RLhzbufMB8wK444BZCSkGvWq9AJK4ECHX93z",
  "node_legacy/ipfs-message-port-client/dist/src/client/error.d.ts":
    "QmdssZCqQLdsyc2CyDjpK7T1qrXVKgLsMieZgUsABVk861",
  "node_legacy/ipfs-message-port-client/dist/src/client/error.d.ts.map":
    "QmQewEQUzFyyVw8k9fAwaFPwvKkfV3fRLjLqY2M3iZ8yoJ",
  "node_legacy/ipfs-message-port-client/dist/src/client/query.d.ts":
    "QmPvUit71cE2hdCm6N4sRkEzbjjgRh6ed5LrqJk8wom1DD",
  "node_legacy/ipfs-message-port-client/dist/src/client/query.d.ts.map":
    "QmaEEUreywjiUq93qJDNT8HN72ALJSESTrwxaRtCdvDtBU",
  "node_legacy/ipfs-message-port-client/dist/src/client/service.d.ts":
    "QmfTyWfZudpdUnkZRYdgcABpmTb652rYEjAvGQGJaTNq44",
  "node_legacy/ipfs-message-port-client/dist/src/client/service.d.ts.map":
    "QmdNJQNA8G5qwQoPh9ey9bzUqw8pE7qV5zgbQqxC6WXjph",
  "node_legacy/ipfs-message-port-client/dist/src/client/transport.d.ts":
    "QmRNuxuKJi8ePyEFjykgmwt7oyvPhcnPQdj97kMYjT993Z",
  "node_legacy/ipfs-message-port-client/dist/src/client/transport.d.ts.map":
    "QmSnKrhz5dojaJkK19wAQQrySRTXoXx4wXMQvQVQmJcPet",
  "node_legacy/ipfs-message-port-client/dist/src/client.d.ts":
    "Qmey6tX1Zi1C1aJ1bqL4UNowTpCmswABTCbRZjGtgzqc36",
  "node_legacy/ipfs-message-port-client/dist/src/client.d.ts.map":
    "QmYUyubPoTDrazxwtPRFnYGWq2SMoFLYmX1nbgZDmteipP",
  "node_legacy/ipfs-message-port-client/dist/src/core.d.ts":
    "QmccPy1Bm4VukW2BmPLZ9xmwccTo9BnT1ti2TQPRYDaazJ",
  "node_legacy/ipfs-message-port-client/dist/src/core.d.ts.map":
    "QmRAVrwJ6gt5eHfHPPJ8KaPEHojZCZ3kHqMctxjF4P1wjj",
  "node_legacy/ipfs-message-port-client/dist/src/dag.d.ts":
    "Qma5p9dR95ct3hhDEJB6A8q9NTTGYd9vjzwpf4iWYnq5Hx",
  "node_legacy/ipfs-message-port-client/dist/src/dag.d.ts.map":
    "QmZo4hzo424dXHx11L3625TT72CQiTYGJVF7HaqnPsSB7c",
  "node_legacy/ipfs-message-port-client/dist/src/files.d.ts":
    "QmQ3xYDLmQMZDeUHpouUAFE1WitssvteKgt9QUyus5rV2p",
  "node_legacy/ipfs-message-port-client/dist/src/files.d.ts.map":
    "QmW6SQBewAS4J7d1ReDwMtrD57mDuF93oBAsWrUUwcZEzW",
  "node_legacy/ipfs-message-port-client/dist/src/index.d.ts":
    "QmYUDye3KLNfMK7vSuvHHpvTYKzKNf9oWbveW8rM5YyUkr",
  "node_legacy/ipfs-message-port-client/dist/src/index.d.ts.map":
    "QmQJrfPuGGSYoTVsa1b3pqtFoNdBZbxFKr24oj2y4w7ors",
  "node_legacy/ipfs-message-port-client/dist/src/interface.d.ts":
    "QmbiL6NibHU72iuGgow7HVwMcZniiHBg1A7yP9e2YvwDRT",
  "node_legacy/ipfs-message-port-client/dist/src/interface.d.ts.map":
    "QmU9hRnTB1QEZQALwteoEZLTxhtSKThouZJPxyLke3BHdL",
  "node_legacy/ipfs-message-port-client/dist/tsconfig.tsbuildinfo":
    "QmbCy1WbUnddDkpiM8Deh19h9JFP2ejkrZ4TQPHErJAbgM",
  "node_legacy/ipfs-message-port-client/package.json":
    "QmVXhgNs2u1wuxewRi7M2RyCyhRdLfdPgu469GKxTvi6sC",
  "node_legacy/ipfs-message-port-client/src/block.js":
    "QmP2JzzDqhjW8jESuRSuG4Si15AtT1c4jrWKb3hpYMfbXx",
  "node_legacy/ipfs-message-port-client/src/client/error.js":
    "QmaATcHDww5PX95Bu1eG5oMCsMosX7YSpCPk4wV8dg5EYE",
  "node_legacy/ipfs-message-port-client/src/client/query.js":
    "QmTpyK4YjhMEEJHMWiUFsjWS1tEtnBSqCyC59YhXaBBCjP",
  "node_legacy/ipfs-message-port-client/src/client/service.js":
    "QmZ8ZxL2gjEfBkiAyFRhioN1LnaCcz9mSp2yjdmtatUfQL",
  "node_legacy/ipfs-message-port-client/src/client/transport.js":
    "QmUZ32NHeiVNPG8PucNv6jP9kTMcvH3kHVxakaMk7xrVaj",
  "node_legacy/ipfs-message-port-client/src/client.js":
    "QmS1qMcTmr7KNtrYxbyoPxkKMiF1i5RtGS2r1mNiiPU7Xb",
  "node_legacy/ipfs-message-port-client/src/core.js":
    "Qmaev7Ug41FGDs3PXhkNnLAAmGqvk3KrCn1URtHFQnAkrx",
  "node_legacy/ipfs-message-port-client/src/dag.js":
    "QmVtPUfymB171teNH9KE1MxQbgb4m1YwqccTSo69wikCVv",
  "node_legacy/ipfs-message-port-client/src/files.js":
    "QmPRJxJN7pDhqWWmECFqNchjDJWP15KvPXKZdCrTJ81jeq",
  "node_legacy/ipfs-message-port-client/src/index.js":
    "QmVvazEJWAuKcVtPcsfXahWybrvnHNaU39TbNycaLs8DDB",
  "node_legacy/ipfs-message-port-client/src/interface.ts":
    "Qmdm6SvYvpnCFH6m3nMnvq1UxbBMJqxJzJtUag6dCUVFMq",
  "node_legacy/ipfs-message-port-protocol/CHANGELOG.md":
    "QmP7xWa7rTtfCzvhZcnQGag7deHDxhS84UevSBqqXVs1fd",
  "node_legacy/ipfs-message-port-protocol/README.md":
    "QmTmxXmRU3VFGBM4cQUBdvSyDuxKhZvMx52Kowq4hcP83y",
  "node_legacy/ipfs-message-port-protocol/dist/index.min.js":
    "QmXu8xAV9M9mz4uTxBFbSQo7NwYXMrLfGJShzBreDoXn3k",
  "node_legacy/ipfs-message-port-protocol/dist/src/block.d.ts":
    "QmSVenf1M3upECV3F1BT7ifuebfhLubNuofAR82VudnBj2",
  "node_legacy/ipfs-message-port-protocol/dist/src/block.d.ts.map":
    "Qme7wUPuJgWdjrjy2p6j3oEVmzn7ZUmz9CtNmEjdEW9AFt",
  "node_legacy/ipfs-message-port-protocol/dist/src/cid.d.ts":
    "QmbimqEjFfTqGAb4fnQ7emnixeYCqT2zDSVvY9XtvwdSLD",
  "node_legacy/ipfs-message-port-protocol/dist/src/cid.d.ts.map":
    "QmWGsjSLL6kHhghXbeB9ymTBbabb7dZRLkNqtpYCSyxdwD",
  "node_legacy/ipfs-message-port-protocol/dist/src/core.d.ts":
    "QmdqG3uDx4pGK1wGrFtfasPM8kG5acoech7qkPtW5iBjUU",
  "node_legacy/ipfs-message-port-protocol/dist/src/core.d.ts.map":
    "QmdsiTaqTXndRQATkLSovCxCNvtzoTALLfDzxRVYvpcQiQ",
  "node_legacy/ipfs-message-port-protocol/dist/src/dag.d.ts":
    "QmRUMUDBK4B3R6sVojitKRt2abJtmwryDUS9NegStjmVpx",
  "node_legacy/ipfs-message-port-protocol/dist/src/dag.d.ts.map":
    "Qma8ZsmVDeepnwKgra89zRgK1Cu7iKcQLNXpjCx4BL9wXC",
  "node_legacy/ipfs-message-port-protocol/dist/src/data.d.ts":
    "QmTdgy2AZsMVE5khtEHqZcrPzUcU5BatNgwPi3AWsQVxCJ",
  "node_legacy/ipfs-message-port-protocol/dist/src/data.d.ts.map":
    "QmeFr1wqj9eFNttfysqqrdJidnuAh2HpS7xVPjcuWhJMLj",
  "node_legacy/ipfs-message-port-protocol/dist/src/error.d.ts":
    "QmSEERnqGWEsMr3jnsFMRUHVY3qcPrfGmjuMhWNoEqdrPb",
  "node_legacy/ipfs-message-port-protocol/dist/src/error.d.ts.map":
    "QmNMoPQc1RGQ3DMSFHKRQLMTuUDbzgaH1LoaDdAKf9XgfL",
  "node_legacy/ipfs-message-port-protocol/dist/src/index.d.ts":
    "QmNRKuQHKK9z4bVdRy3vemtviyzAtzAiL52PnoNdhDg9gk",
  "node_legacy/ipfs-message-port-protocol/dist/src/index.d.ts.map":
    "Qme8AciEXCfQy8eZhwMhpFcCdE7cH12URucWDFHGEHPHRP",
  "node_legacy/ipfs-message-port-protocol/dist/src/rpc.d.ts":
    "QmeJiftgYf5iSf7jVLCCKrNuBsfsx14FNWugHcm2quCjED",
  "node_legacy/ipfs-message-port-protocol/dist/src/rpc.d.ts.map":
    "Qmdm1zVmD4w4KEPp7hYLYS5ZnaSm2VzMWXege7DsA4tevp",
  "node_legacy/ipfs-message-port-protocol/dist/tsconfig.tsbuildinfo":
    "QmeN2WPDixMMxQLjkSoUN6j4U5fpna7fKQXBZF7EmbBX2k",
  "node_legacy/ipfs-message-port-protocol/package.json":
    "QmXxfqU3s8979NJrV4oroGn3rPoHzXqKUGEVQvYFrJWA3h",
  "node_legacy/ipfs-message-port-protocol/src/block.js":
    "QmPmmDAXB758s1ARWKffcQaxk4B47zPY9YEH2RzqLSVbVe",
  "node_legacy/ipfs-message-port-protocol/src/cid.js":
    "Qmese1XU8n6sjYQjWxgYb5oC2fDXTNneUUfSay41H6J4DQ",
  "node_legacy/ipfs-message-port-protocol/src/core.js":
    "QmX6zzXJJqS7BXiUUdufYhMc6rbeQ6TUy5QHFHr9GdpJwk",
  "node_legacy/ipfs-message-port-protocol/src/dag.js":
    "QmUq3ueh72oVr9gKZqMrLgVEHyiVYWWquCp89iQoyFVkVr",
  "node_legacy/ipfs-message-port-protocol/src/data.ts":
    "QmS3DySRey4HkfYgJcXgUQ3EUDKc4LdjLrSZhuqj1rTTDp",
  "node_legacy/ipfs-message-port-protocol/src/error.js":
    "QmTmEF1Zug2xa6BagRpSqxMXK9NrtQPatYSG1YAxqLWmQK",
  "node_legacy/ipfs-message-port-protocol/src/index.js":
    "QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH",
  "node_legacy/ipfs-message-port-protocol/src/rpc.ts":
    "Qmez23fBYWB3df5ByWTdkUUZrKXywzPFsYjdf4UdVgSCUd",
  "node_legacy/ipfs-message-port-server/CHANGELOG.md":
    "QmUb6EPE1AfrdmpqEJHADspfqS1hSSqTs59MzFb1GGtAPt",
  "node_legacy/ipfs-message-port-server/README.md":
    "QmVRMYbkAp5HqcPvWdrtQZ9h14w5BgzgsN7VzBxfgYW94E",
  "node_legacy/ipfs-message-port-server/dist/index.min.js":
    "QmQnP9m71YVty4Wr1VL8tCAv3P6v9cG7gaA1cGk4W7JxMZ",
  "node_legacy/ipfs-message-port-server/dist/src/block.d.ts":
    "QmcLa4WbBgVEXFiraNB12vvF8kKm5cmiLzKhyQRTUR9gx9",
  "node_legacy/ipfs-message-port-server/dist/src/block.d.ts.map":
    "QmZ9oZiRczq8L6oqciu4JumTz6ftBy89oQF6ZLwkcK1kp4",
  "node_legacy/ipfs-message-port-server/dist/src/core.d.ts":
    "QmbtCXG6EAyaaFdqDdtWqkxdZnguK1ZftjnHxNMFVqqRPm",
  "node_legacy/ipfs-message-port-server/dist/src/core.d.ts.map":
    "QmRxjN11sya71haCMM2UUztJFr2ZdVhTDzjR8SobhKLVdA",
  "node_legacy/ipfs-message-port-server/dist/src/dag.d.ts":
    "QmeKPpPYfj6Ce4ps79MtUfEUZsLPQ3hSJzVCbS3vJyVWGA",
  "node_legacy/ipfs-message-port-server/dist/src/dag.d.ts.map":
    "QmZmFCNRErT8E6E2XSmwWj6HT1NnSY8iA93W6n1p6mmxyh",
  "node_legacy/ipfs-message-port-server/dist/src/files.d.ts":
    "QmRSSkUZ6UtnRSsuCmCwoUsoL2sGAQh36s3RQBCZk33SQ8",
  "node_legacy/ipfs-message-port-server/dist/src/files.d.ts.map":
    "QmcHWcyi2fLfqqzDNanASJ657S9kVZAFiCEAyMz8rzoUKR",
  "node_legacy/ipfs-message-port-server/dist/src/index.d.ts":
    "QmUBBjnhLn3zgaX9XS6XXEnmSXA6aJRMhQWKDFRcxUHqo7",
  "node_legacy/ipfs-message-port-server/dist/src/index.d.ts.map":
    "Qme8AciEXCfQy8eZhwMhpFcCdE7cH12URucWDFHGEHPHRP",
  "node_legacy/ipfs-message-port-server/dist/src/ipfs.d.ts":
    "QmR7cB6sHzPUUwFQfZc51f9S7dLrNv11wcZfhRgMW3XgYF",
  "node_legacy/ipfs-message-port-server/dist/src/ipfs.d.ts.map":
    "QmZVgFECqULeWjwuu332CgHC4DN1xj71Hoq31xXkveNKkT",
  "node_legacy/ipfs-message-port-server/dist/src/server.d.ts":
    "Qmce3uPgWoxmvHirbg4uf8w1is9HeK5VYgFcMTv24fqSgp",
  "node_legacy/ipfs-message-port-server/dist/src/server.d.ts.map":
    "QmQbVgoCyef9VusSrBCG1m6mbbsVbDwVWPiriyfdi3Hbh6",
  "node_legacy/ipfs-message-port-server/dist/src/service.d.ts":
    "QmSkwRVtdgtKqB3gZw8ZFTPBGbC4aT7dfGD9yk25nqGPTG",
  "node_legacy/ipfs-message-port-server/dist/src/service.d.ts.map":
    "QmZNt3LU7HXu5CrvEByPxiQJdm9yv6SfhSHeEzPKSr4tvT",
  "node_legacy/ipfs-message-port-server/dist/tsconfig.tsbuildinfo":
    "QmPrSE7a29CkHY7XGege1yv2ouDGE5P4jYkDG6ke8KSfKV",
  "node_legacy/ipfs-message-port-server/package.json":
    "QmesLEDq9JrCY78TBekbmeCxB4vgAhC1CAQzo87XoJe1GW",
  "node_legacy/ipfs-message-port-server/src/block.js":
    "QmdvQDazwMrzhC9wg8XtBU5djALdejVXy7MmHBb7cfMiai",
  "node_legacy/ipfs-message-port-server/src/core.js":
    "QmQoju6R8A1LmiqYLNkAbsDPuAmYiNjDgUzbFETqTKYpbo",
  "node_legacy/ipfs-message-port-server/src/dag.js":
    "QmdbbkdTdV8yMQfJszDexEyYCtnVWjEfJUeHC3AZhZYKw8",
  "node_legacy/ipfs-message-port-server/src/files.js":
    "QmY1HZAFj8Ds5HjcP9neF36tieF7krZFiiHPJ4AqX2GPNS",
  "node_legacy/ipfs-message-port-server/src/index.js":
    "QmT7qMsy1ZkwMjtAzS3YntD4mmrCxRAcEedZqGbUR7HH7c",
  "node_legacy/ipfs-message-port-server/src/ipfs.ts":
    "QmcBdwFFhnCjn6QCYByqYjfg2KtZEkazysfYCmtHS97bao",
  "node_legacy/ipfs-message-port-server/src/server.js":
    "QmS892z6Pta4c6BFkNvijtJtneCpfVNyqxrjGvAFbCNqGW",
  "node_legacy/ipfs-message-port-server/src/service.js":
    "QmbbwNuvEyzN2kADS1Dm5nT9FvLPmkKbKnJjevCVGdHxAH",
  "node_legacy/monaco-editor/min/vs/base/browser/ui/codicons/codicon/codicon.ttf":
    "QmNiTPD7q8ucTwfMqePmN45DarksfCAJytgSJutKP5WjGc",
  "node_legacy/monaco-editor/min/vs/base/worker/workerMain.js":
    "QmTDpYEJ5ub39WupE5qAM8PSpcfe8yQ8HkvEnJVV3nb4hr",
  "node_legacy/monaco-editor/min/vs/basic-languages/abap/abap.js":
    "QmZy6PR7T1ZPe7unYGwmjojCAuT3RUw5MjeyjxgtPQA9CF",
  "node_legacy/monaco-editor/min/vs/basic-languages/apex/apex.js":
    "QmQowotZtoMKgQUa3cwXkUzc2Pu1zFvNsxkyyZg3dYhuta",
  "node_legacy/monaco-editor/min/vs/basic-languages/azcli/azcli.js":
    "QmY41sFTcGShHs16S9n6X6LubsJgsMunNXog6JG9kNBLco",
  "node_legacy/monaco-editor/min/vs/basic-languages/bat/bat.js":
    "QmZreRNh5wQs5eggoNRKCwApGGpTSLbTQFBseoRBtPJBae",
  "node_legacy/monaco-editor/min/vs/basic-languages/cameligo/cameligo.js":
    "QmU84iKcckBD8WYZ4F522hev7TFLQqGRpL8xo6j3UDATGh",
  "node_legacy/monaco-editor/min/vs/basic-languages/clojure/clojure.js":
    "QmZbt5WYvFchJTh58UWArnqBq6fjXhqiXJ9NqTnYMnagdt",
  "node_legacy/monaco-editor/min/vs/basic-languages/coffee/coffee.js":
    "QmT7BRZvRBpYbiGWhzbxnNWiqW2ERiVYdW9RogenBU5ktw",
  "node_legacy/monaco-editor/min/vs/basic-languages/cpp/cpp.js":
    "QmYiz2mBbLQ1CR7MqxRD2UBTUGGCFAx99aZQixSk2yPZHQ",
  "node_legacy/monaco-editor/min/vs/basic-languages/csharp/csharp.js":
    "QmeetU4ynH1tWtv2bF9AR6u8HaiLkvvpSXWFPrU5t3kEab",
  "node_legacy/monaco-editor/min/vs/basic-languages/csp/csp.js":
    "QmSMVtKVDYmvZedmF9BVwLkkS8HHjf2Vx3s7NKhrFbqc5a",
  "node_legacy/monaco-editor/min/vs/basic-languages/css/css.js":
    "QmapJZuR1uH3VqkGDukeghzfyVncGc5jnjozYVwrsYCP3J",
  "node_legacy/monaco-editor/min/vs/basic-languages/dart/dart.js":
    "QmYr9g3ztrrxxcCoSPAszABo5pw7fS3Z93aBRM6TLmARgS",
  "node_legacy/monaco-editor/min/vs/basic-languages/dockerfile/dockerfile.js":
    "QmW4GCgdh8kowzG914L3GpEwo4UWmBLCpt8VKXX6KDssn5",
  "node_legacy/monaco-editor/min/vs/basic-languages/ecl/ecl.js":
    "QmPViH5SGTCNDFJpeJGfZfXb6LXTrKmkJu16RbtyWLbhgo",
  "node_legacy/monaco-editor/min/vs/basic-languages/fsharp/fsharp.js":
    "QmQTUkoo2UaF7RXSViZTnQpd6N9FbxkTpyd9DfvjrhmB81",
  "node_legacy/monaco-editor/min/vs/basic-languages/go/go.js":
    "QmdjiGXvjY2eSft5DAqV5uJmwjTt723NdRmBB7XeAmfnb5",
  "node_legacy/monaco-editor/min/vs/basic-languages/graphql/graphql.js":
    "QmRZtAUeuYCMf9fvADAYw5AHx7EzkAR7C9it4PbxJstajZ",
  "node_legacy/monaco-editor/min/vs/basic-languages/handlebars/handlebars.js":
    "QmQQJqDL4bJEkbLC1ycw2dyR74LyEXAvyVPJ7QbFVK4jqe",
  "node_legacy/monaco-editor/min/vs/basic-languages/hcl/hcl.js":
    "Qmd1Ez1n8KLTGEQETdGwx61zoJo7nL5rjTxHrLeEwy6d4T",
  "node_legacy/monaco-editor/min/vs/basic-languages/html/html.js":
    "Qmcqx6zN8QiWa1DgmGYG59ipTJAkzXTJFJZCYsUz6aqQ4f",
  "node_legacy/monaco-editor/min/vs/basic-languages/ini/ini.js":
    "QmSsgU8FtrqsEf9SvTmSc86jb2Ff8BdZ1j3XadRWtEJhm2",
  "node_legacy/monaco-editor/min/vs/basic-languages/java/java.js":
    "QmNNMPNY6GpUSSY3RbuqNFn71kVYXMkyBpTZFHaJsUbya4",
  "node_legacy/monaco-editor/min/vs/basic-languages/javascript/javascript.js":
    "QmPtqVvqNhoT9FaV9FsKE4bF8mSJdGMYVjPhhEmno52XBr",
  "node_legacy/monaco-editor/min/vs/basic-languages/julia/julia.js":
    "QmUMTdS3KZM7UnKB3YZRGUapQsBvmYJ4WaYgXqdhAAGiWQ",
  "node_legacy/monaco-editor/min/vs/basic-languages/kotlin/kotlin.js":
    "QmYhXpKvhBeNUnjjzgnwZZCGpQVz4y399hZoD1HgkiZgLN",
  "node_legacy/monaco-editor/min/vs/basic-languages/less/less.js":
    "QmUFXaBTq8NUQHEQtYxwxCxuxUGG57P7stGSjepvhE5kjR",
  "node_legacy/monaco-editor/min/vs/basic-languages/lexon/lexon.js":
    "QmdeEAuaCLn5RTBLTPHbARAU7sS6LyrDNmgFFpmGuSezn1",
  "node_legacy/monaco-editor/min/vs/basic-languages/lua/lua.js":
    "Qmb7iXxVpRYvoLekj79hw5SMSbhenLxqqAJ2DZ5CytpeUH",
  "node_legacy/monaco-editor/min/vs/basic-languages/m3/m3.js":
    "Qmb7r49wirgFTv8RhmqrK189Z9pygNypW1mxdEQvb3j81E",
  "node_legacy/monaco-editor/min/vs/basic-languages/markdown/markdown.js":
    "QmVb49MR33miTT56p7SBrw9srwjnjpL7Xk52iT5MMpk6La",
  "node_legacy/monaco-editor/min/vs/basic-languages/mips/mips.js":
    "Qmcv1tQZrWdsx7UzPbTteKWaAfQtjdZW1ZkH3aCLxR1FZX",
  "node_legacy/monaco-editor/min/vs/basic-languages/msdax/msdax.js":
    "QmdcwuXnjyp5DjU6X6153SLoS21MkDpLgjJqTUwsWrcWN4",
  "node_legacy/monaco-editor/min/vs/basic-languages/mysql/mysql.js":
    "QmUZE73WxRv5moKbpo2Wn9NaEoQ2WUDmHs2DdQWiRYc6dh",
  "node_legacy/monaco-editor/min/vs/basic-languages/objective-c/objective-c.js":
    "QmXWKPWnijuq9MfWtespRgkQd86AchPR1evuJWFdK7Rg4m",
  "node_legacy/monaco-editor/min/vs/basic-languages/pascal/pascal.js":
    "QmW5VHZHFCX6Zx2MwDHdjhVA54oLUcQj5teQWtaeS51i6h",
  "node_legacy/monaco-editor/min/vs/basic-languages/pascaligo/pascaligo.js":
    "QmZKqRk7P28u3X9cxx6jhWWAz2fYuPtaH4YvsXxLtuzTwc",
  "node_legacy/monaco-editor/min/vs/basic-languages/perl/perl.js":
    "QmTXhF2HYejHnCubth3cQPavt7oqw4HYju4uPM9bsS82sa",
  "node_legacy/monaco-editor/min/vs/basic-languages/pgsql/pgsql.js":
    "QmVs4W4K8ZnPgj5RAVN5WcKW6RkVLTj73DZb93m4HMVbvr",
  "node_legacy/monaco-editor/min/vs/basic-languages/php/php.js":
    "QmS5LvQD9dbcoi1eo98N8fQ1rqqncCHRT8VRDiaUeQcqJw",
  "node_legacy/monaco-editor/min/vs/basic-languages/postiats/postiats.js":
    "QmQhgFULE1g2bFP6ozTDATvYsbm1LXMLz9gJs3YPcpdStq",
  "node_legacy/monaco-editor/min/vs/basic-languages/powerquery/powerquery.js":
    "QmbGnRX7oSWaHcFUi1PQDjdZ7JZYV7KUUwqXRKzNvkudcr",
  "node_legacy/monaco-editor/min/vs/basic-languages/powershell/powershell.js":
    "QmYqJkevR362KJfVjfD8wd6anv1QDx1QyqHkTvAJUdpL7o",
  "node_legacy/monaco-editor/min/vs/basic-languages/pug/pug.js":
    "QmaycLXRykyu8BsJ8BWGHiShtEG1gcaAVuqM8vYdJgLXXh",
  "node_legacy/monaco-editor/min/vs/basic-languages/python/python.js":
    "QmU4dC2bvzZF3jAYCmiemSxyt8odemZytA9XyNxt2ZMoWE",
  "node_legacy/monaco-editor/min/vs/basic-languages/r/r.js":
    "Qme3yKnDekAiVeuVaLz4tNsRDJwRYVHgmjYykW3HB5HAXz",
  "node_legacy/monaco-editor/min/vs/basic-languages/razor/razor.js":
    "QmQ8v4ZPRPizJGSoSWzZGz5QtDcAEsmdL1Q3ebvzpw5Ue2",
  "node_legacy/monaco-editor/min/vs/basic-languages/redis/redis.js":
    "QmWMaQqvhWnSpfw9XzPJw7FmnoYpzzMFjzftnZThVR7TsB",
  "node_legacy/monaco-editor/min/vs/basic-languages/redshift/redshift.js":
    "Qmbjhr4W9rbTheLF9DANu2YGt4odApzNc3F2BjynohCY4U",
  "node_legacy/monaco-editor/min/vs/basic-languages/restructuredtext/restructuredtext.js":
    "QmcStCWgnmrvt8ysUagsrnLXLEJSuP18CkEpU8hoB5Y6vt",
  "node_legacy/monaco-editor/min/vs/basic-languages/ruby/ruby.js":
    "QmZzNCw5FYaZy5UfHACYpk9xBqkrJjc3oKBJScbry1G6YT",
  "node_legacy/monaco-editor/min/vs/basic-languages/rust/rust.js":
    "QmYibjrupckDcvTNJEJV6JkV9U8Ac4GzPNTZox29ZhsSqc",
  "node_legacy/monaco-editor/min/vs/basic-languages/sb/sb.js":
    "QmeLadb12mF3pGujuDzuqgJVqjV3v78hy9oZHSHX414fpF",
  "node_legacy/monaco-editor/min/vs/basic-languages/scala/scala.js":
    "QmTnyn86mTBVyyzbgMMiWwjF735DuWryN9XL8P4stdasW3",
  "node_legacy/monaco-editor/min/vs/basic-languages/scheme/scheme.js":
    "QmbiMTKy3kafW4yCCAaQWedTYAD7VLC1NtBs4s5CSA1TRH",
  "node_legacy/monaco-editor/min/vs/basic-languages/scss/scss.js":
    "QmVRqS4oCFWYhibS5s1GySoXC6gvsZvhVSfHYcfj7NdKAx",
  "node_legacy/monaco-editor/min/vs/basic-languages/shell/shell.js":
    "QmbRb3ZHnjaNzUbC9CFuFPTeUpLHv5hwjL3N3dgfgrUJaW",
  "node_legacy/monaco-editor/min/vs/basic-languages/solidity/solidity.js":
    "QmYBiWNNFDWsbH2AWCKWDjgt5YDiZps7hDtnesr1R8d3TB",
  "node_legacy/monaco-editor/min/vs/basic-languages/sophia/sophia.js":
    "QmbnzjGDogDrgudKizj74tLXYYqAjG8LDtbEFweSCCUMWR",
  "node_legacy/monaco-editor/min/vs/basic-languages/sql/sql.js":
    "QmatRehwTn6XWKuzC7WBPifBWaGe6usb39sgP9UbkSRnW1",
  "node_legacy/monaco-editor/min/vs/basic-languages/st/st.js":
    "QmWQ76yjV2h4wqaqBXj5vad5BYi6vKmav277TKtuwMywoT",
  "node_legacy/monaco-editor/min/vs/basic-languages/swift/swift.js":
    "QmdyQcCau6GtCYYBtY5mqe1SDPCzDhHzAYXktig4Y1sV7D",
  "node_legacy/monaco-editor/min/vs/basic-languages/systemverilog/systemverilog.js":
    "QmNV7rsp34bKidwL3MvN8Loa73KiGsR69B2B8wt6MrwRfZ",
  "node_legacy/monaco-editor/min/vs/basic-languages/tcl/tcl.js":
    "QmNVNUTU4FXsucKmN7jHdrkoJUKTD65VHfhGt9FGnm47WJ",
  "node_legacy/monaco-editor/min/vs/basic-languages/twig/twig.js":
    "QmUEAuZTyYrNNLptmX5GfeDoNzAyjV3SPZEq1XxADk63gc",
  "node_legacy/monaco-editor/min/vs/basic-languages/typescript/typescript.js":
    "Qmf7bS5fKUFszke3rQvnwVEehJDPpGFAuGmAzgVYbGPmjC",
  "node_legacy/monaco-editor/min/vs/basic-languages/vb/vb.js":
    "QmNgbrb2QCQtH6tRsqLHfwFpKMjWTJ6saju613LVGc9gNz",
  "node_legacy/monaco-editor/min/vs/basic-languages/xml/xml.js":
    "QmPJPZqPm4KjL3zBX5GsHfgwrLu5LfyaPpuPXBNfUScYDd",
  "node_legacy/monaco-editor/min/vs/basic-languages/yaml/yaml.js":
    "QmQwp7xVWhP3BYkRV7yuxN62sAUcdgJxqb3JxCSdpasyo7",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.css":
    "QmZWFNbmB5HLfwq4QP8RKsPG6zHLDKgrkdDYN3ymPrUKzu",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.js":
    "QmTkA1GXJSnUQM9fPdWaLLr6a1LDb21GbYDe36KULRU9sL",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.de.js":
    "QmWpPcpDZNdZVs3eVzAFNYPKob3GRtWb8G11THjqpLyVeM",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.es.js":
    "QmajV8VccGMLcf7Kjtw4pGFPFHxgTQBXkNdxvWfpJW8SoU",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.fr.js":
    "QmNu7PKbbcxV7abMXJoe1XJHa3yfCge8jtBxEakNAzS2Y4",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.it.js":
    "QmaCB3SbTD7abhzUVGZ8Qh34EtRherEYC1MNzNtk5HT2qJ",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.ja.js":
    "Qme95wg8vo4G7Jwz2TuDtpmgUhACWgPSq6LZrcTJfTfcLE",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.js":
    "QmebVHG4SueJ6uevY7eV13vejzwsMKNmg8bWbYNMCNQv4e",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.ko.js":
    "QmdBEgZ8mQjD2WLSxeF1qtjg7SHR8q3vaQjtAovvxSZEf8",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.ru.js":
    "QmYS4ts9H7b7YXGo8S14cFgjcHKCALBgXvGEisLKjxWCKT",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.zh-cn.js":
    "QmXGn1VEShfsRBNQg3f6yfg68faDE7qcE6neciqHcK2tUF",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.zh-tw.js":
    "QmcWLspKBDrrfswKfBR2D3puYqq3SpE843mqmr5EU2FMK5",
  "node_legacy/monaco-editor/min/vs/language/css/cssMode.js":
    "QmWBQS2KhHcfBen4LKkm3VGaVdqtQuFFJ1YFy2SRvj4FsE",
  "node_legacy/monaco-editor/min/vs/language/css/cssWorker.js":
    "QmUbtq2bbGWW1FRLByE2uhbyLvBvwp27J7p71orLJV65Ff",
  "node_legacy/monaco-editor/min/vs/language/html/htmlMode.js":
    "Qma1LPqeYP5JfC3jQrNVqbDW5sPAg31F1TSY83iiQfix7b",
  "node_legacy/monaco-editor/min/vs/language/html/htmlWorker.js":
    "QmQ3FpPSTThYt2nDBvbwrFhSCk4SJMgi5FP9dvsbJ17grh",
  "node_legacy/monaco-editor/min/vs/language/json/jsonMode.js":
    "QmRThgxZ2N5jEYJWrWAMijcmhQZ3eiCX84K1Jd5ta1fhzX",
  "node_legacy/monaco-editor/min/vs/language/json/jsonWorker.js":
    "QmcEbJYiJyBPENjne9d11g9Nrtt57xTSZ43xhxDRQFZxDY",
  "node_legacy/monaco-editor/min/vs/language/typescript/tsMode.js":
    "QmWV3kzWDU56oAJUydmjGyaUnS19fHQ51F39RgMNtXHe6e",
  "node_legacy/monaco-editor/min/vs/language/typescript/tsWorker.js":
    "QmYKGudEpMPegen7soyXBDsVZ3DYmr4yWZTGLSwjjv8a4i",
  "node_legacy/monaco-editor/min/vs/loader.js":
    "QmUAWmVBLSCXRVodDf2YQAvUgJbKAi8X2TBs3mwGPvxoSc",
  "node_legacy/monaco-editor/min-maps/vs/base/worker/workerMain.js.map":
    "QmYadh9JYvX5joq1keNqTAr6VMMBrwcds2XbWqEeySo445",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.js.map":
    "QmQUh8i2A3cCfJ5mSEbrqykAxQUyQM5YYJjPjM9W3P93rn",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.de.js.map":
    "QmPVeo6ASTGAEMfyyqC7euLZFGFDaVvEaYA8bUEEEPozoX",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.es.js.map":
    "Qmd5dH7RuLxYVNtXGsj5hCEAFnSceRQfEEg7YDeDJgtcyk",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.fr.js.map":
    "QmZ97YyGW5XARgMA3eqH9voLZoHD1c2P2irhUHEqfJEW7j",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.it.js.map":
    "QmZnf94CQAmXqp69Dee8LKbay7y21GZZfr8K3FrPKMpaL7",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.ja.js.map":
    "QmabnR8TLoTZqiD8LMnnhHs3pSh4xwqvEKpsqptnyGfPJB",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.js.map":
    "QmcpRXXZjyeMGSRdqBgXsqsVTsy8aQanWG81ePHN7GJVEC",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.ko.js.map":
    "QmcnVGb2YLrF8forGTCAWZ6U6T9Kps6SWWMzDhMAa2B8Vx",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.ru.js.map":
    "QmRPrNLsQEeEyfCewcbeoK3u3NP5tmnWQJKw5i43Ew3Grj",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.zh-cn.js.map":
    "QmQomb5JtZBqJ8FFWyCcEn52gfX728fmBiNVFq9ooYb6UF",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.zh-tw.js.map":
    "QmTm3ppJoshcu6GSXEpfk2YRx5ftn4WvTPdrpGoFpJUpop",
  "node_legacy/monaco-editor/min-maps/vs/loader.js.map":
    "QmTjTFnCNWdurh7ejmnTp6PB5ffmr1r2ttqGhFxmvmhYn7",
  "node_legacy/monaco-editor/monaco.d.ts":
    "QmYR7g6GMzz9JHRaTD3H6FpLVR4wiZDjMf7GaDZc4kEuQZ",
  "node_legacy/monaco-editor/package.json":
    "QmZcryZqRY2N7kTaE3fQuEuPirbWDCvMeBVzV5QRdP28u4",
  "node_legacy/parser-babel.mjs":
    "QmNZakKRLQBUJSY8XvTCnCJoU3vWGCYEiCkFDV3WuZmtJZ",
  "node_legacy/parser-html.mjs":
    "QmNQPbdnaiQz91ZKa11kCAByJS1bjj39W1XZWranQ3dMYp",
  "node_legacy/regex.js": "QmZWiPyB2csudjP2xX6W4P1PHhZQnvMkCdBagQvCM7jMpA",
  "node_legacy/rng.js": "QmTqi8yzgAq7WJUXtTAX3ccr5meWBaHuGtXx581S1B9kS4",
  "node_legacy/simple-window-manager.es.js":
    "QmcvtuWHJa3nkqaBfFMriqZz3N15RDeGErhF26tjPThxgM",
  "node_legacy/standalone.mjs":
    "QmbkuH4RqHi2cUk3w7PMD9LDNaSkEaYA9Pcy9Wv6rTnwYk",
  "node_legacy/stringify.js": "Qmd56eDfKFpGXVEuPxrN3A3jewVkunFfdqpTdE7LCtSp2h",
  "node_legacy/v4.js": "QmUhNN2k5hbHdHWURhNAQPQLgN455FJSsf3Z8njyYMukfm",
  "node_legacy/validate.js": "QmRi1pudKp7sivw3M8Hk3EAsSRcLExsGZqiuJQCXTWjYgY",
  "node_legacy/workbox-sw.js": "QmZvvd3tM19b9a5b9hn3JiDjnu2jHnUq9qrHtz2c7yJMga",
  "node_legacy/workbox-sw.js.map":
    "QmYrZKmyENAJi6h5mFoq2CVyZzr4syiuehcFqorzAtQttK",
  "node_legacy/workbox-window.prod.mjs":
    "QmT29Y78zyhb8a7WWc2BEhS2XpZij6bJhJZnLnbKTKsE5m",
  "node_legacy/workbox-window.prod.mjs.map":
    "QmRTrYSzfnFKPQESDgH6t26Fb2AzZpn51PcCor3Rh9zomY",
  "package.json": "QmPZndj9t8Cr2VfsYxDvXXw8JYXV8PHWqWn94Tut4PvfGV",
  "src/codeLoader.js": "Qmaz1UEnCQoBAmzSJZ6dgeC2tsyDY74c3jFauA2FLa1sDK",
  "src/data.js": "QmRKJPktSjMy6qREy5yZPwHgMtFJgDvKSDR6g54UwEPmFf",
  "src/db.js": "QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH",
  "src/emotion-react-renderer/dist/DraggableWindow.js":
    "Qmatqd4HAF76oyBRpW7tGEMt1rDW2TNijeNVhxZg8GwbTX",
  "src/emotion-react-renderer/dist/renderer.js":
    "QmX4unXEXsJ9wPz3DGNPgeya8cr1LrazFViqqJrRPAV264",
  "src/emotion-react-renderer/package.json":
    "Qma8PKJihFHuAdNtLqra8CWvtdfsDW1bWZtoyMdeAQz4Rz",
  "src/emotion-react-renderer/src/DraggableWindow.tsx":
    "QmfXRFvz4dXzLdRYznK6isrynfqg8DvBViRfFEK8KnBSmH",
  "src/emotion-react-renderer/src/renderer.ts":
    "QmQVjYGxnEhAfQNzbbfcLMJmagfs5sBkJKVjdVi8Hjy3mi",
  "src/emotion-react-renderer/tsconfig.json":
    "QmVf1pkrppvUoQ7dmSQ5XH7WM1PY7SqAwxR3TR8pT2oGVA",
  "src/examples/app.tsx": "QmRju4JLXE5iNjjqVER1hHqCUBbRGXDvw3WasFUKEvbs7P",
  "src/examples/starterNoFramerMotion.js":
    "QmWVABuMCi74dqH3AiGtWU1SEBzvmhiRCADWYCupQZYuAs",
  "src/examples/starter_framer.js":
    "QmaVBy5PCmFhEKZ7gMtLZUyAy8FBfgDnPeLm6HgCnrC6KF",
  "src/formatter.js": "QmXArukccKkWgDVKtZWCsNcV2gmYhPLursST8CP1x4GVBi",
  "src/hash.js": "QmNwbA46c7bRTXeZtxbvcja1g5Pq4G9m59ZfFWQc4sUiQR",
  "src/importScript.d.ts": "QmV1V5Fb2ZxP5Kn31nSU7FS2TtrDMg6wR7sMTsKeeR1txL",
  "src/importScript.js": "QmWNzoXJSf9aHxMEbDGsdMfyfJKwtpfL1Q9ni1xuSF5c9X",
  "src/ipfsClient.js": "QmNXn2zNEBL8e2cksn6Gy9stsAiaxFUGxiKSeHkoLKVhbQ",
  "src/openWindows.js": "QmXwq3AHyeNWrdG2WrVzkaujrJZzzJtyxaHAdRivSrjoKU",
  "src/qrious/AUTHORS.md": "QmSJ3JoGKdJEiHBDC8j6uXHzXHkLBmG3SJgzbPfrWDTBoA",
  "src/qrious/LICENSE.md": "QmVECYZZPoi7YkMEWKtQDu7G9ZXb4fH4QtKfHHc89fEy8h",
  "src/qrious/README.md": "QmQLgHRuBzYPfTvqX3efJdPwVzzJPAXK7rKtXUvseL3FnD",
  "src/qrious/demo.html": "Qmdcpx9zVreub9xBE6QxhfGtZ7Sodsnyx9KCyMyLhqibn2",
  "src/qrious/demo_min.html": "Qmc6Me5Zv7VBGoAbQp3xe8fDEGW28SFCrKYG6yWz4h4SLQ",
  "src/qrious/dist/qrious.esm.js":
    "QmejgC7EcywbuiajeGdfwHgxdD8Tn7Tq6yCqFsLqTZ8jVV",
  "src/qrious/package.json": "QmWuJiMpmDqUaJsRaM2uB14CCyF2BCKZzjmmAy2i9g4bsd",
  "src/qrious/src/QRious.js": "QmWyhyMT7B8vJWGm6kMXrXBhS7pgx4Dqv8TRepBqDxyW7e",
  "src/qrious/src/service/element/BrowserElementService.js":
    "QmaquwSn36sfzcn6seaTvR6YPhJoFVQvh9z9174tzTEjgi",
  "src/refs.d.ts": "QmV4VN2uGcNzHPQi51JkVC4p9RzDpe5sEk4sX4u9ub3J4p",
  "src/renderPreviewWindow.js":
    "QmRLs3SMWp9GMjBXMSY5NuAso9qdJ2tY5UBmLa4SKpybhu",
  "src/sendSignalToQrCode.js": "QmeZxocsjhuRy2v7WdzGegZDsiHVPpZw7WNAqyb5j2mN3G",
  "src/shadb/dist/diff.d.ts": "QmXv6B78NKbJLMyErUn6XRUkXxvkata8i6CR5JCC721QJx",
  "src/shadb/dist/diff.js": "QmbfZsnJhysseRS92eSEc2SX7hBaaLPTojb7oqc6XaBqzy",
  "src/shadb/dist/diffChars.d.ts":
    "QmR9hNHu2ZNp9CopGNmME4KgNuyAzMZcZ1hUaZwnjXfkE4",
  "src/shadb/dist/diffChars.js":
    "QmNRK5ZC2ZEdMfrTozGkgGJdHiMWYbfk84Gi3kBD4rgMBQ",
  "src/shadb/dist/getDbObj.d.ts":
    "QmSN6JKpmgGd8mwb8gEKViV5juyt4jpw4e5wQqFpzGUiF2",
  "src/shadb/dist/getDbObj.js":
    "QmW2LmUqcg8fzLtjroo3JHbUUXDq16X9n3dBUE4WUVQzG3",
  "src/shadb/dist/sha256.d.ts":
    "QmQCcqJvRmWrgHXvwifwqPziL9UUNckyDZbPbLGb4SbS9k",
  "src/shadb/dist/sha256.js": "QmWZyJbdb4B22fLgpbDqNo6wU2sWccyecceKz6bor64hFi",
  "src/shadb/dist/shaDB.d.ts": "Qmb1jkMJhCGHnrFigsUkCNo1uwebGfrxXQH4EHSpnh6zFY",
  "src/shadb/dist/shaDB.js": "QmX5mSevBrVHk6mpp1VNaCMqmCYC7azWBUFgrzpHnG4NDp",
  "src/shadb/dist/vendor/diffChars.d.ts":
    "Qmf31P3dFhCyz9X8GkuUytpn3cmJwsggF4kPTbmwaiekRt",
  "src/shadb/dist/vendor/diffChars.js":
    "QmcC8KRucgoFQ5EQ43yykZAVDCoYUeCS9tNaHmhXhaVAaQ",
  "src/shadb/dist/vendor/diffMin.d.ts":
    "QmUEzhNXqsRtc45fB5if9wchLEL1wgmY58wX27E5zUCJtp",
  "src/shadb/dist/vendor/diffMin.js":
    "QmQvwZBWXeTmVqjfipWeA5k2L7MMQd4ooqEe7qVAJs8VwV",
  "src/shadb/dist/vendor/idb.d.ts":
    "QmRDw3SijUK8mQZ2H5CzJtKk8zknGsCz4mz58EzsjEC738",
  "src/shadb/dist/vendor/idb.js":
    "QmeDaTt5WPt58TYHpMzMyURp7hMdfUiKm6AbwEtZsQGoc9",
  "src/shadb/package.json": "QmQZQjYbDMdjjYK8AwSw8r7rugVE9RBxiFv8mzPrbrfcJg",
  "src/shadb/src/diff.js": "Qmda6YhbwL9XYtLgmK3HGPpGw5zFcRox54cRKaJjNUMWAE",
  "src/shadb/src/diffChars.js":
    "QmWyRfBNH9Epu8Fg6qKghPCm41ht6xG54jZ6iANubmRv6d",
  "src/shadb/src/getDbObj.js": "QmWHmVpjUyjtseZDdvxbZNYiDx3MXTgmZhwBpqCP8CrEtb",
  "src/shadb/src/sha256.js": "QmUYHM48BTQuN4TFNHBH5dYaZ16FRNu2tbeF6JdHnBKc6g",
  "src/shadb/src/shaDB.js": "QmQ7TuHw5n1XZVwpfsxfMeWUHYqc35tEQx4ypbJw523GJV",
  "src/shadb/src/vendor/diffChars.js":
    "QmRGpEFyhuqLyPYt67ZFftdPK9PMf8UXuvHfXVhZyQ3YAJ",
  "src/shadb/src/vendor/diffMin.js":
    "QmXDjtDjFxzUemcTkNDbQqSimHTNDcpLsfxq5PhbwmuXSf",
  "src/shadb/src/vendor/idb.js":
    "QmdrnoscF7ihtuyZCd1iv7g6Zpvem23yNn6AHU6xTaV5XU",
  "src/shadb/tsconfig.json": "QmSweNRyD6aAUjpMnt8zKE5LAxvvLoZPy9Qj3r4THEhaUd",
  "src/shadb/tsconfig.tsbuildinfo":
    "QmYe9m185xM3a8wESdAzFw1wdCY7Aho3qEHBXdwy3rg2JN",
  "src/share.js": "QmaHt8RCd6dGkC7mq34P35oRLGxz1sV88sz8VH6fw8jUkF",
  "src/smart-monaco-editor/LICENSE.md":
    "QmQAGWaCTkwWF9GMjvoLgCMMgec8bKWRgzB29yti3b5zAL",
  "src/smart-monaco-editor/README.md":
    "Qme5mqxxvVorXuV6y3Wit23U9pUhaMfSDR2YDx1esCCruY",
  "src/smart-monaco-editor/dist/editor.d.ts":
    "QmZZZ3UjjGrNVCuyDx67fvvmf1rPmq8wnh9DUcdAoLMtsK",
  "src/smart-monaco-editor/dist/editor.js":
    "QmTkyhRG8Jvpa57vLdDoq7T8tTB32G3gQESXcV9tGyLGjw",
  "src/smart-monaco-editor/dist/monaco.d.ts":
    "QmPNrqP54db6P45nw6d3BFmerEAxLzbz2ynbByCrLderPF",
  "src/smart-monaco-editor/dist/monaco.js":
    "QmbJtqvS31TXa9GHm4e8FjK837kpHPU13fZkHbgkFL1FQR",
  "src/smart-monaco-editor/dist/scripts/screenshots.d.ts":
    "QmS5gMBfgk8pSufk8fk4D9VXz74GvEaKgB8sP1dJTDKMtQ",
  "src/smart-monaco-editor/dist/scripts/screenshots.js":
    "QmZj5ZmAy4A2ow36UjUkWKkK1HXKL1tMofYxTYLVoSMJoD",
  "src/smart-monaco-editor/favicon.ico":
    "QmWF8oNe7SDdaY6t4WrJ8ZzM46dHEFmHDXzd8MBeNrELxe",
  "src/smart-monaco-editor/index.html":
    "QmVQxvRvunUpXoZqC67ZUPoNSRpvyB4dKNmEQTtntCNqms",
  "src/smart-monaco-editor/node_legacy/@emotion/cache@11.0.0/types/index.d.ts":
    "QmUCj2Y8UvRu3qr495TxRWLjotqJVpGW4m2f373ML9J4q9",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4/types/css-prop.d.ts":
    "QmcqPuhFmv4w5Uaa1zarPmNPW2rEUEuTVpRbkMvkpuRTu2",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4/types/helper.d.ts":
    "QmTgJLTGDTZvVBrNvXmtPZT9W4ekHjXDM4ao62wLddJFo2",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4/types/index.d.ts":
    "Qma8jqDFMjj4MFpsCgZu2BA4PoRBgJpqNRjvG1S7JRwNLN",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4/types/jsx-namespace.d.ts":
    "QmNjM3vwg7JVnPCgNY55nxr6MDNnZfnR46xhNkqMRRWrSH",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4/types/theming.d.ts":
    "QmRR1zmJ1QThGaMQP9CZyo89ny6b6cnN6T4EsNfVuMgMBZ",
  "src/smart-monaco-editor/node_legacy/@emotion/serialize@1.0.0/types/index.d.ts":
    "QmTe7sNkKt6fppui5WQ6KTp4dXAChyirJpmfaiwja8EFLu",
  "src/smart-monaco-editor/node_legacy/@emotion/styled@11.0.0/types/base.d.ts":
    "QmcrDAZs3J1SbebjXv1XmfK5BEdrYAqy4E7vEVFVqjM4RV",
  "src/smart-monaco-editor/node_legacy/@emotion/styled@11.0.0/types/index.d.ts":
    "QmWD3WGSdBRhBbmmv1P4JJyA4XMfazmV8CkY7pFrnVYMeb",
  "src/smart-monaco-editor/node_legacy/@emotion/utils@1.0.0/types/index.d.ts":
    "QmbvhexADU4v3XaaBXJxD4X1g7DMxFPsCWvytbsqvHpAKq",
  "src/smart-monaco-editor/node_legacy/@types/prop-types@15.7.3/index.d.ts":
    "QmXaJ9waDpQDB5rY24AWJwebJhXAvPZ8Zg6xyardJjkVeY",
  "src/smart-monaco-editor/node_legacy/@types/react-dom@17.0.0/index.d.ts":
    "QmUp6zxmTL2cBSqSummQCsVUr8ksVPku73xR47jjGqPyTL",
  "src/smart-monaco-editor/node_legacy/@types/react@17.0.0/global.d.ts":
    "QmRoYgDX13hcDWSUDRNxFZcnPyTqWzzkhJNF9X29Vxrr6g",
  "src/smart-monaco-editor/node_legacy/@types/react@17.0.0/index.d.ts":
    "QmXfhdDibqw2JGSQdiSz55jT81znjCU7yvQ4dmGW5UeKkx",
  "src/smart-monaco-editor/node_legacy/@zedvision/qrious@10.12.14/dist/qrious.d.ts":
    "QmY8cwFxtfD1dPVtvXhWR5uvMpaFVN8VJ2JXNbR2U2hYne",
  "src/smart-monaco-editor/node_legacy/csstype@3.0.6/index.d.ts":
    "QmW9j7PM3CWM83KSKZi7fkGLXVV8MBY7gEyFfHNbde8RjQ",
  "src/smart-monaco-editor/node_legacy/framer-motion@3.2.1/dist/framer-motion.d.ts":
    "QmaGk1drtubxue8LG5k7eHCejNsde79Q21m9tvbYdt7359",
  "src/smart-monaco-editor/node_legacy/popmotion@9.1.0/index.d.ts":
    "QmfVp3E9UrnADC6nJMc46brtFfymJLfhTn42Av9ftYQUaB",
  "src/smart-monaco-editor/node_legacy/popmotion@9.1.0/lib/index.d.ts":
    "QmfVp3E9UrnADC6nJMc46brtFfymJLfhTn42Av9ftYQUaB",
  "src/smart-monaco-editor/package.json":
    "QmNTZ1vBJPbpoFouPh9BHY5qSxsnbAc4C71AFHiheTa34p",
  "src/smart-monaco-editor/src/editor.d.ts":
    "QmXFYH4YMX7W5dDHwbLZS5NqtCSqRf6n9NcmaEZjFsLBtF",
  "src/smart-monaco-editor/src/editor.ts":
    "QmSX1eCR6u33NTDAmV4HhXRV7D9BBr9c3zqQ31mHbThp9h",
  "src/smart-monaco-editor/src/monaco.d.ts":
    "QmdsjvXNr9ufGi4osAtDQuo4tji41DfCKzbCNhLo7F5Gc1",
  "src/smart-monaco-editor/src/monaco.js":
    "QmPU117QEcnXLQb58T54ehhMzj79d6BYATsSz3wgiV7Gj1",
  "src/smart-monaco-editor/src/refs.d.ts":
    "QmUXoLQ9zNGWxd1c1yNBjSf4RoTwFMEbLcq8hL2ewCd6ba",
  "src/smart-monaco-editor/src/scripts/screenshots.d.ts":
    "QmS5gMBfgk8pSufk8fk4D9VXz74GvEaKgB8sP1dJTDKMtQ",
  "src/smart-monaco-editor/src/scripts/screenshots.js":
    "QmYUzn9XSFiduCLmzj4Ewcn5GnxwPaDKYDGAxdakydncmg",
  "src/smart-monaco-editor/tsconfig.json":
    "QmTqtxpjAgAVTAsFTHNuHE2cRCXSzKzfsrVwhFSaGsqea8",
  "src/smart-monaco-editor/tsconfig.tsbuildinfo":
    "QmZgEfDhGQ5HY81UY63CEgUEQudwednt56B8ngcu3PoscA",
  "src/starterTsx.tsx": "QmQ9AHQxPPsDqonKSH5q5zHeiHHSds2P7gcmUVEWkm4QW7",
  "src/templates.js": "QmYkDeqsmyfVhokhZPgjGLVu1AUc9bb44Y4MaN3bARNke3",
  "src/transpile.js": "QmcqWzx4L1c3dfG7jrwQqy23wrx9mn6jgjoEAxmGyfEsPp",
  "src/workBox.js": "QmUNb95Uy4M1qwMACE8oBvhEP2SYyUCc5gHaAYBs5YpV68",
  "src/workers/ipfs/README.md":
    "QmbdTTJXo4rWcSfDFooCBXWGYtCnbixPpSJh9hjAQ6KMFw",
  "src/workers/ipfs/dist/gateways.d.ts":
    "QmaqVQHmb2ESQaLajE5YAbgw1PzYPRwpLbwEFLJfEBARWk",
  "src/workers/ipfs/dist/gateways.js":
    "QmNVuHYaC7MuqYnsRJ2J9kY7TotGALZ868F2jx4ryvmETK",
  "src/workers/ipfs/dist/ipfs.client.d.ts":
    "QmViTDo9BBn2p3h6UyQuFXkRAjqVnKMV9PhkqsaKe73xwE",
  "src/workers/ipfs/dist/ipfs.client.js":
    "Qmdp2HBvcvTJPkYqHHJ75RauWt8koyoqqVAhmPWGP8Q5i6",
  "src/workers/ipfs/dist/ipfs.server.d.ts":
    "QmS5gMBfgk8pSufk8fk4D9VXz74GvEaKgB8sP1dJTDKMtQ",
  "src/workers/ipfs/dist/ipfs.server.js":
    "QmZBVJyLM1r4wZHySwQ3hxKUQCZXsV3fL63BScffj7L2BJ",
  "src/workers/ipfs/node_legacy/ipfs.min.js":
    "QmWQMs9pJDk38iaxBKSgCXbwuPXgRqsqHQtTabqQHoRhKF",
  "src/workers/ipfs/node_legacy/server.min.js":
    "QmWQMs9pJDk38iaxBKSgCXbwuPXgRqsqHQtTabqQHoRhKF",
  "src/workers/ipfs/package.json":
    "QmWuVFpRazrRtHsGewuJgen7Ten6N2kXXmYeDa8SKm2hDG",
  "src/workers/ipfs/src/gateways.js":
    "QmVGZy8bP96dMrzL4vTg7ppfpJVAFbtUZ1Go57fvsParbe",
  "src/workers/ipfs/src/ipfs.client.ts":
    "QmPHeiaXEFPhPXsg2DpZkdb7NYp9GZ1MCarVFMRdg83Ada",
  "src/workers/ipfs/src/ipfs.server.ts":
    "QmdcUyYNDxR9fKZ6jfuRa6Uzb8vS6BJWiAGaQfUjpoVjrW",
  "src/workers/ipfs/src/ref.d.ts":
    "QmZV7knX51sBSfDb7mFNcghGtF3RKyczc6z4Uz7zXS25zo",
  "src/workers/ipfs/tsconfig.json":
    "QmYHbMSMqJLVt643gR6twoh1Fh2pmRefGPr9GEfXQSemHg",
  "src/workers/ipfsWorker.js": "QmVzkTMiCNd7aaxBVhDNaTVBCkHYZa1Rv2V5vXsX5MPzxh",
  "src/workers/shasums.umd.js":
    "QmTcSv4DXa6USZDdqotYWUdEhRB8voN9hrDdSjsPAvWgjq",
  "src/workers/sw.js": "QmSR6jVid3SGKoyxjwJ5BCC7WwRT6Rbu1gixY8BDNvkYQC",
  "src/workers/transpile.worker.js":
    "QmSX2qLhymbiH8AqKshiFgPUjJfjfwFFrsbNx16dh7qzX8",
  "src/workers/tsconfig.json": "QmNt8xKcRnN8TVbPqU9kNwUPNy7tinifkhWe8ADPTSVCvJ",
  "tsconfig.json": "QmdYYNAMVJJgs9nYR2tc4oVC6Fxcwcv7K1b8QH4H2372EY",
  "assets/fonts": "QmYAJJ726yRoCVerLBgUHdLax1JKS85SYLrnrG54WxSDtK",
  "assets/synthwave-vscode": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "assets": "QmcLAE4ZmMJ1GT977zHKnX7zzcwVRS25cYzFTTiA9hxtyd",
  "node_legacy/@babel/standalone/test":
    "Qmdbni8ySNyYHkWS2SgxoLVBT4or3F6nBe61F8FBDwDthg",
  "node_legacy/@babel/standalone":
    "QmeQ1gDZFjKQFLkVYWURPyJjhSV4Q84T5AaraV4Dtzsjgq",
  "node_legacy/@babel": "QmQhFnhgvSEwfGYsxau3hLPFtzNhKY8E39v9ob66qNpHz6",
  "node_legacy/comlink": "QmTQek4dMBFHR9YmfaC39AHc561J1AyV7zmgPhgtTsP4q7",
  "node_legacy/ipfs-message-port-client/dist/src/client":
    "QmZup1QoUb9PRv51TDmWAZMi7P9DUMcMwsY9iSzZYj59UE",
  "node_legacy/ipfs-message-port-client/dist/src":
    "QmRRhUpVVPhAujdbqRbTC4EUioCVZERCuwpPdx9Zk5SFkX",
  "node_legacy/ipfs-message-port-client/dist":
    "QmcvYWqnmkLmoS8D262vTMbkVDvNycFrzMQzPcerJquNuQ",
  "node_legacy/ipfs-message-port-client/src/client":
    "Qma7mVuyQwQ3384fJov2cuWjR6CXVE5k1WWBsJ6iUXzSqj",
  "node_legacy/ipfs-message-port-client/src":
    "QmUyymcxnh6hpkekqTbcphh4zQqifBuopgjK8Buypn28ej",
  "node_legacy/ipfs-message-port-client":
    "QmbeYVX62aoKMEo5svQUkdfjxQQD5v8BgKuz591gJsKhuW",
  "node_legacy/ipfs-message-port-protocol/dist/src":
    "QmRAQWWth3CGqTDMp58Eof9aPdaPLkzaryaZaYQEAawHvq",
  "node_legacy/ipfs-message-port-protocol/dist":
    "QmdvcKmKmVyxCfDDNjpQtSH7PzUgLrBNoVFMeaxsJNz1zh",
  "node_legacy/ipfs-message-port-protocol/src":
    "QmfLuvmz977mG2dziie5e8GkWKshjXJMbADpg3KC1xkBpN",
  "node_legacy/ipfs-message-port-protocol":
    "QmPXHMM3CJFjh2viwWzPh6Vn3dHFyJBJe8NRzy26XSKTjr",
  "node_legacy/ipfs-message-port-server/dist/src":
    "QmQdTdnQGHJY3fut5GXQa8tsZVpGC1Rj7wT61fpd1Viukd",
  "node_legacy/ipfs-message-port-server/dist":
    "QmTCu7LVcSrpLJ4Zf6JqDuSFjb6NsiQdBAUsT7ZJT2orzW",
  "node_legacy/ipfs-message-port-server/src":
    "QmPLf9dLYAtMwu3KN9kB4mXXN6icfpYCBn1ENMDGkqHLQV",
  "node_legacy/ipfs-message-port-server":
    "QmRQnASzHAxFVbJ4KjoDJ5B9SMuPzcT6fMaAL6UM9FAX8s",
  "node_legacy/monaco-editor/min/vs/base/browser/ui/codicons/codicon":
    "QmRDaTDHFannojUDz7oBNzTewktam3SmeCaQZo7U7Wj9op",
  "node_legacy/monaco-editor/min/vs/base/browser/ui/codicons":
    "QmaWwv6hAgo2L7j4Vh76KE3jaKMhjiLPQXLuzAM4fQBxej",
  "node_legacy/monaco-editor/min/vs/base/browser/ui":
    "QmcXZHatGpMeybjiyMePnwDBxNoEzYK3boMwLeACGMBdoz",
  "node_legacy/monaco-editor/min/vs/base/browser":
    "QmfGWbFf3Qi9sxWLRqXhSxgw2YGwpm71KmUoQ8c5MHsoLE",
  "node_legacy/monaco-editor/min/vs/base/worker":
    "QmXnDo5uno5jHemotFEwqKCdsX6VHQYLcgZPp5SNzt6fej",
  "node_legacy/monaco-editor/min/vs/base":
    "QmNmzsjJThufrreBDu3cRr7jqbp3oTkFJXLkhctQJhgmaE",
  "node_legacy/monaco-editor/min/vs/basic-languages/abap":
    "QmdhF24bCgD1Gi277bvSAi6ifCWSY9qoAix2uHoTszytJC",
  "node_legacy/monaco-editor/min/vs/basic-languages/apex":
    "QmNvtWkUdA3GCA9oP4sAC3M7PQKj6ZnTjZh5sbtCyDMrHY",
  "node_legacy/monaco-editor/min/vs/basic-languages/azcli":
    "QmaxFy73jESANtUuxFa7t7AJAgB95T2wDdGT5hgVmfh5e8",
  "node_legacy/monaco-editor/min/vs/basic-languages/bat":
    "QmbQC3TRNGK42P2N7VxbYPmu9wyDuu2S9QsoypRGpXwQBx",
  "node_legacy/monaco-editor/min/vs/basic-languages/cameligo":
    "Qmd4f9ruA9hTm1zNGx2bj8z87c8taRVhF7ZNk6KSn7psb7",
  "node_legacy/monaco-editor/min/vs/basic-languages/clojure":
    "QmZ2segwJ2pSrGkF32XV5ukTxZpzUxbRc7PtgzLVWGDMna",
  "node_legacy/monaco-editor/min/vs/basic-languages/coffee":
    "QmURjzsjdH91ArPkkvMc7XNHD4qyppbrpgmuvgadD3csPP",
  "node_legacy/monaco-editor/min/vs/basic-languages/cpp":
    "QmShu7xvR3kgCzKUwRNRCKdS28iZmZat819APStmdepKT5",
  "node_legacy/monaco-editor/min/vs/basic-languages/csharp":
    "QmWnBWSUg9dGQNrpEthxEjFQqJF5UXyQyVPibb7PAqkW1A",
  "node_legacy/monaco-editor/min/vs/basic-languages/csp":
    "QmXzt6rfskVaJbq4x3Es3XXV8MUAp8G2vabPTMXKWtsKVQ",
  "node_legacy/monaco-editor/min/vs/basic-languages/css":
    "QmUAE8knW4nvPGzz1F1sk1yYXShtP5dtm6ryJawacmm5E4",
  "node_legacy/monaco-editor/min/vs/basic-languages/dart":
    "QmVtfgKTtAxU2tu7KcqNxZpTKFQtChhg9ZTmRWbFVbn4Vw",
  "node_legacy/monaco-editor/min/vs/basic-languages/dockerfile":
    "QmU9hX2UFMQuwbJn2Yc7HtXRsyqGFvHg82WSMKUbTE86iN",
  "node_legacy/monaco-editor/min/vs/basic-languages/ecl":
    "QmRbPFCFrTVDCix98aP39uyoBJUqUxbB7iRwPFRgKpceRN",
  "node_legacy/monaco-editor/min/vs/basic-languages/fsharp":
    "QmPmhXdaUeh5gpxeMd85oNt9SPKp2kE9eMmppMBuWoqL8u",
  "node_legacy/monaco-editor/min/vs/basic-languages/go":
    "QmSNy6aZPaxLygqWNDzQqbpRwzyryXFjfeWJPD9tvDta1c",
  "node_legacy/monaco-editor/min/vs/basic-languages/graphql":
    "QmYvZNYASpx7oSF5WbcmQ3BJdf7gCd4oCnC76QpN8pNKd7",
  "node_legacy/monaco-editor/min/vs/basic-languages/handlebars":
    "QmdZ5bvQ3pFngcv91tkqjcBEMn5xquVvvzDydC73mRTQ72",
  "node_legacy/monaco-editor/min/vs/basic-languages/hcl":
    "Qmc3XPQGeYEv9JiKJBsyunPLuz49P9xBZsKG3pLZpzTb9h",
  "node_legacy/monaco-editor/min/vs/basic-languages/html":
    "QmU8k4jBmmH5k6eRiLyLqMh4yETbqLdXpcGYupWNffd6C9",
  "node_legacy/monaco-editor/min/vs/basic-languages/ini":
    "QmWW9TtoDzRaTGNDsgvmt7nXrSMAxgm8dyaoWbyyoVwiuv",
  "node_legacy/monaco-editor/min/vs/basic-languages/java":
    "QmYPCMmeTSD7sasrQxS3zNAndozLtEKZAzvKbJWaZdvuix",
  "node_legacy/monaco-editor/min/vs/basic-languages/javascript":
    "QmNbDyH7wvTCHbMF4XL5yaJ3XyQHyiajBn6dxTjsmvgj9N",
  "node_legacy/monaco-editor/min/vs/basic-languages/julia":
    "QmcivMLAWGf6MjDsoSSgndinDxWx8Jg3FbvCEUMvnKe97e",
  "node_legacy/monaco-editor/min/vs/basic-languages/kotlin":
    "QmV51mYveXU67fpQZbmAJSGXihsENeFr1zmYkip2m3WKL2",
  "node_legacy/monaco-editor/min/vs/basic-languages/less":
    "QmVmJjT1D5uT8yHPmwRKn7MJzGuWET5Un5258mpG9FY5ka",
  "node_legacy/monaco-editor/min/vs/basic-languages/lexon":
    "QmbvpNepamFkmvVMSsXe5kWJGeagtFHMVHzG6i9jLffshX",
  "node_legacy/monaco-editor/min/vs/basic-languages/lua":
    "QmYBgYVcY1teAYZAfV5JYonh1LGeUjwvyJRZuCWBvRa2YC",
  "node_legacy/monaco-editor/min/vs/basic-languages/m3":
    "Qme4fEW6HX3pgHVSiNcQ7e5GqhxiP8grkvex3RCovJoqky",
  "node_legacy/monaco-editor/min/vs/basic-languages/markdown":
    "QmTBeEeXk895ptanSKsJLJT558hn8ZcGaBhhSVG4pixk6d",
  "node_legacy/monaco-editor/min/vs/basic-languages/mips":
    "QmZ6gYxAEkxU8xKa4bzLtVAfupoX18AvTqgpH9rHyJvN82",
  "node_legacy/monaco-editor/min/vs/basic-languages/msdax":
    "QmYehJfnnN9bKAjyK3jH4kr98fWC5SL89T7yxY9mxkg4Zm",
  "node_legacy/monaco-editor/min/vs/basic-languages/mysql":
    "QmVi3m87T1jZp9z9qwyWuXgRTcj5WA8wQkMno22Tf8bLDA",
  "node_legacy/monaco-editor/min/vs/basic-languages/objective-c":
    "QmPW8GaUJyad9oKNVuSyhakybBSjqRHV9NhyH8Vn9DYiFc",
  "node_legacy/monaco-editor/min/vs/basic-languages/pascal":
    "QmUbLCyVAaTzqQZRjGJoanixymqQRe1BycVQvjP1NxMqUL",
  "node_legacy/monaco-editor/min/vs/basic-languages/pascaligo":
    "QmRPGwPikWr8gqL795BeYNhcUTXgNiRsogNhXBTmWkLWG3",
  "node_legacy/monaco-editor/min/vs/basic-languages/perl":
    "QmdzPJZLY2pRZf7m9g9kfTK2sUPoc1cVX2KCh8oz67Eh3W",
  "node_legacy/monaco-editor/min/vs/basic-languages/pgsql":
    "QmcMt61wp9FLkeNyKcnayqLHm7oUUwZxuHcYkZJTkmTLQF",
  "node_legacy/monaco-editor/min/vs/basic-languages/php":
    "QmVk5m1u8ipSNh6Gp71mignUFT4A2AGCTjVjqqVmi2PvaX",
  "node_legacy/monaco-editor/min/vs/basic-languages/postiats":
    "QmVHM9oANdB4q9bSMpAg2EgM58FWn6cAYGcWkJYmEatgNX",
  "node_legacy/monaco-editor/min/vs/basic-languages/powerquery":
    "QmazjgHmZ9BxyQaerWaqd5tpkak1H8EcSWgYNmPviKhbq7",
  "node_legacy/monaco-editor/min/vs/basic-languages/powershell":
    "QmVEjag9xQc767fcr3dmwZqXoYpM4EZRWv5hKEQQgLj4iH",
  "node_legacy/monaco-editor/min/vs/basic-languages/pug":
    "QmXH8msnkosCFwBTTu3snvN5kRfHD9XN2uxEThr5s8zvyQ",
  "node_legacy/monaco-editor/min/vs/basic-languages/python":
    "QmeBstJ9SNezyD46ctTkPt722cPrMq1jAyocvJviXmCAne",
  "node_legacy/monaco-editor/min/vs/basic-languages/r":
    "QmXDoBFCawo8P73JP95itwu5XLUgcXP7p5ESC4s2ptGSxg",
  "node_legacy/monaco-editor/min/vs/basic-languages/razor":
    "QmevpfMPxpVgTNx5khSmgLJvwWM97mfhRKvD2BNJfH8vRK",
  "node_legacy/monaco-editor/min/vs/basic-languages/redis":
    "QmNYuWiohuPWWjuWksQihTf4wyCXpZitS22Q2F9Zn7WEVv",
  "node_legacy/monaco-editor/min/vs/basic-languages/redshift":
    "QmRwGxW3JfMaSxPp1HLxqgudEvCAhRViDKVBBmvWUxCJdH",
  "node_legacy/monaco-editor/min/vs/basic-languages/restructuredtext":
    "QmaJJkoH5bAdk44aSd6La9fv6pp7rBCWaMYMAyM3NeW81G",
  "node_legacy/monaco-editor/min/vs/basic-languages/ruby":
    "QmPcNxpnmwHY5RLduDsfbdaTgdeGgab2WMzeZqoT7uoYwm",
  "node_legacy/monaco-editor/min/vs/basic-languages/rust":
    "QmQxZQGN5H3Hc62BGDmWkkfNvbJZzNTt9hxz5aeUDgFFs6",
  "node_legacy/monaco-editor/min/vs/basic-languages/sb":
    "QmWxXcMDQc75toYz7MqVQmCHjm7HqFf2VA8ruuJvwarXGH",
  "node_legacy/monaco-editor/min/vs/basic-languages/scala":
    "QmWm9ecveEw7FzmM4n74UGJp7CxQ2rM5r4VfUMXxDWEvBs",
  "node_legacy/monaco-editor/min/vs/basic-languages/scheme":
    "QmZnPhA5Z6seiaAjqQWJFgwpPF1CedEbCmgyDRkED6BiVk",
  "node_legacy/monaco-editor/min/vs/basic-languages/scss":
    "QmPDiEAwBo2GvfAzsy4wuS8HfnEg6bhFD8FXExmbZoraJK",
  "node_legacy/monaco-editor/min/vs/basic-languages/shell":
    "QmXi23r773GX3UiK99N5nxJKJEYX3WKDSVic7Wvd7omxrp",
  "node_legacy/monaco-editor/min/vs/basic-languages/solidity":
    "QmYatCWQNfpkamevRwfPKeMnf9si1tpfETTZS2JjC9aUr5",
  "node_legacy/monaco-editor/min/vs/basic-languages/sophia":
    "QmSEU5hP4NWbTaWVEnDFJi8r9oSpVq7Ycb7QntFqhkxaHA",
  "node_legacy/monaco-editor/min/vs/basic-languages/sql":
    "QmV4TDHJauXLeB2afqonFtgUPh8s95EAT5j95VdAaPdL85",
  "node_legacy/monaco-editor/min/vs/basic-languages/st":
    "QmP3bhF61vHS12XYTknowQYP5z3ALQoQo19kWfhRJ7QDr1",
  "node_legacy/monaco-editor/min/vs/basic-languages/swift":
    "QmaPYcPu9X2PuVgeUwBDfagsNmaRqwEHUboceSrVftyZiR",
  "node_legacy/monaco-editor/min/vs/basic-languages/systemverilog":
    "QmVFwum1sixYEB4krgsUReyHniQ1GWUiUXijYAnGEwFCaS",
  "node_legacy/monaco-editor/min/vs/basic-languages/tcl":
    "QmfARxmPVWAYuVLmsXCwkk315joAeht7jXz7693u28ptx2",
  "node_legacy/monaco-editor/min/vs/basic-languages/twig":
    "QmZPHGkzaXfqAABXQUa6cDvR6ZhV5RBwg9phZR155vJ2cN",
  "node_legacy/monaco-editor/min/vs/basic-languages/typescript":
    "QmTg2B2eAsiLYe69KqhdQw1AVtdJwYKuUYyeyrLCBkYB66",
  "node_legacy/monaco-editor/min/vs/basic-languages/vb":
    "QmQ6Y1g1N3vCgA6bjtVn863BePevZPWgfNTfARaMvCjUGG",
  "node_legacy/monaco-editor/min/vs/basic-languages/xml":
    "QmeQ5714oEi36YTxm5eiLLbuhrUnY4ZPDdBXH17vVUyCLQ",
  "node_legacy/monaco-editor/min/vs/basic-languages/yaml":
    "QmUd2WPxAB1RSV1XWLXFHYAXehxEhNKQpbJ3zz7umZEFed",
  "node_legacy/monaco-editor/min/vs/basic-languages":
    "Qmc8mbJnMDLZhQwGtG8RfJJs1TgAnqiprLn5uXf6sVcZYj",
  "node_legacy/monaco-editor/min/vs/editor":
    "QmVUFqWPXS1FAn3RaWeMPnwKyvioXcaRBRN1ovQXfp4Lco",
  "node_legacy/monaco-editor/min/vs/language/css":
    "QmPDnPXa8zWX5YR5EG1b3dZTsxzkM5WpLQ6SgVUFCDgMPe",
  "node_legacy/monaco-editor/min/vs/language/html":
    "QmTiGyK6pmfpxMHD6yDg8xQgLMNtYsMeAd8YeLzWEkSrTq",
  "node_legacy/monaco-editor/min/vs/language/json":
    "QmVtB8VTKSAcmyDex98sCTWwNwBNK5hufJo9CP6dqkERXo",
  "node_legacy/monaco-editor/min/vs/language/typescript":
    "QmUzSLvk4bGTNtMJ3CMXrD5esEJomL4kuQUkc4QHiZCFpc",
  "node_legacy/monaco-editor/min/vs/language":
    "Qmd3Ze4ABrkuNrc1Hr5rwMHQyLKFusgJvkqgBsVjn7R22d",
  "node_legacy/monaco-editor/min/vs":
    "QmQZVEsJzjJEGB62w18pbKtKnDkyueYfPj1sK5kvRsYaBr",
  "node_legacy/monaco-editor/min":
    "QmPJtimwMPUVq2HQvQAyA4p5CuLtxtMUhHpLBKg4ViM1Um",
  "node_legacy/monaco-editor/min-maps/vs/base/worker":
    "QmYRoYuqj7s3BniW4aGfKYtrSrPirhAfMbeZSm8c4LH1R2",
  "node_legacy/monaco-editor/min-maps/vs/base":
    "QmRUR4auT2Gtx1ynyLNDvxoppqNXJN9bKV7iJXJo4ojYvc",
  "node_legacy/monaco-editor/min-maps/vs/editor":
    "QmPePiiaqLJifhM3KmDLM9Ki6fTVVhpbV5vkZiZUJ6JQpQ",
  "node_legacy/monaco-editor/min-maps/vs":
    "QmVD3qzMtKhaCSdESxNKGAA48KvjPHgznV6e5ygpY1nUjC",
  "node_legacy/monaco-editor/min-maps":
    "QmWS6URBS2wPhcuKFEZrRK4uhR8SbKZhqH8CNnUq5qKLNQ",
  "node_legacy/monaco-editor": "QmQt4dedt4JAQn7AMnXmLqtZ24GDg9cibi6KYTzgjiTgDA",
  "node_legacy": "QmU5XCza6Pd17Gw9XsaPhJRcUiVi3aTnngQuDQMWt5KD3K",
  "src/emotion-react-renderer/dist":
    "Qme5XNmCToindZrUoxTpjdP8ydY2CpKdWzNYafyxUpt5DF",
  "src/emotion-react-renderer/src":
    "QmVSzquyAHah16xWEGMHoGTgEj3ZLNDenkoTCtQVuzaNDe",
  "src/emotion-react-renderer":
    "QmT2nZS9nmU8YtJvqEymxRPENumAHEySnfoMjU5obp8jZu",
  "src/examples": "QmPysz1ZmDwk5yvsZtiKsnUekFXZiAERnPJh1Z8G5GZ5f7",
  "src/qrious/dist": "QmXzecEjL8DUyY3QpjncnCf6pRpVmhcph3whb4t6RAiaVV",
  "src/qrious/src/service/element":
    "QmcP8FAooT6RDNr8SELNUQgQiGAfEXFULUoJ5FQCF4t7hN",
  "src/qrious/src/service": "QmVdYoXyeaPxymoWj9gaAWww2DJQTStjYtzqeZ9EdPH2bK",
  "src/qrious/src": "QmPS8uZ98ntMQpiUEdff7aszmuKLGS9r3grQFrrdYGy3qu",
  "src/qrious": "QmQryLCaZ48YTiU4gEgWRr5A3bNBLhaHPzkhXyr2mmwLVJ",
  "src/shadb/dist/vendor": "QmTZzgTNwYe9ioj2zaZmme3LZLscde4D54r8J6HpaaHJ5x",
  "src/shadb/dist": "QmPs9fBmE8aZQd62NYjBoWBvdwKZkf45nu81byMAEgmwuQ",
  "src/shadb/src/vendor": "QmZcc5JirQ5ySPiELM4nJaVBLsKVL3vvNg2KE5uj7rGSr3",
  "src/shadb/src": "QmQqL9VeFmzKpNiihj8AuLZ7ngMn2w1Yi8AkzU78CUJvfJ",
  "src/shadb": "QmW4Z9fDQgT7R61zEABGFGDucGbkvNjWf42sovXLVqgtUp",
  "src/smart-monaco-editor/dist/scripts":
    "QmUZruQhR3JEi3knevKng6AKpxN3vcswuRrCp4DiW9aYMM",
  "src/smart-monaco-editor/dist":
    "QmYdCBihHj9hDN6znBDFhC1WRvPbJeMmpPeJsiK2ea5AYm",
  "src/smart-monaco-editor/node_legacy/@emotion/cache@11.0.0/types":
    "QmUEN3GDGpShVYbF8hWwkgFWdCFf4MGFXggEBLLJCW7MHn",
  "src/smart-monaco-editor/node_legacy/@emotion/cache@11.0.0":
    "QmRrpV1ht67hartnVdCGUL6HoZ3VSqxoCJihFi3Qunud26",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4/types":
    "QmanceJtx35wfrY3dqZfRGiFZg7birgBaL65fkJRmRNZiF",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4":
    "QmYv3i1pQ5bjKy3iEEWX66FfxNsUe1GC522xbt4XRdwwyU",
  "src/smart-monaco-editor/node_legacy/@emotion/serialize@1.0.0/types":
    "QmUnre3UQbzpYq1XmEdf5cD24wcsBqWNnHkH75Z9SvsNPR",
  "src/smart-monaco-editor/node_legacy/@emotion/serialize@1.0.0":
    "QmbohaYyrYyu47WW4W3BRV5pxJQY5mVyAiQce9Bn1pQzCT",
  "src/smart-monaco-editor/node_legacy/@emotion/styled@11.0.0/types":
    "QmS5uFuLqN8AGfAiDTZnbjKbueGKve723gjTyVjTBaaz8F",
  "src/smart-monaco-editor/node_legacy/@emotion/styled@11.0.0":
    "QmQgjmWjt2jnyXUyLhMGRCDDWzeTPFpxAPtqyzYxadDENh",
  "src/smart-monaco-editor/node_legacy/@emotion/utils@1.0.0/types":
    "QmUXun6ie598RTouvr2WWASvmZZqErUtHuPXxd1LtdaFZ3",
  "src/smart-monaco-editor/node_legacy/@emotion/utils@1.0.0":
    "QmaWRA2PvGCN9iJefsPvvhtEPVgSH1jNWQsZAXYgcWqVhF",
  "src/smart-monaco-editor/node_legacy/@emotion":
    "QmdkLmXqY4cR3eCHDkEu6wr26oG12tRr7XRVpeNqieU11j",
  "src/smart-monaco-editor/node_legacy/@types/prop-types@15.7.3":
    "QmR4pDyXHid6f9yeQLtTVnCtpjmo43m7JAPwTd1Jbjj3Ta",
  "src/smart-monaco-editor/node_legacy/@types/react-dom@17.0.0":
    "QmRb3L5eSa6HX9KGJKyecoLnfSPNd6tzZdAMg6oQJj2Bsq",
  "src/smart-monaco-editor/node_legacy/@types/react@17.0.0":
    "QmdafiC1ixpU9mcYwH52sYg6yqMJtbAfRtCYzdh7aFD2Tm",
  "src/smart-monaco-editor/node_legacy/@types":
    "QmXxX7YkfkHhWb4j4EiHC7uoUxTjocGSAJna3ShsmuFGRR",
  "src/smart-monaco-editor/node_legacy/@zedvision/qrious@10.12.14/dist":
    "QmVr2gYmRGvQaHm4cbQt11LsXYQq4nMLG4H4MKYgJFvgc7",
  "src/smart-monaco-editor/node_legacy/@zedvision/qrious@10.12.14":
    "QmXJmZqywmjXZaXd4DHrhHLmVj5EDtuAA4gGvbnGXanhvK",
  "src/smart-monaco-editor/node_legacy/@zedvision":
    "QmQqBzB3Xs73A4pZwJpBKV8pcBp81oxYo6dHeDa2PCHF6u",
  "src/smart-monaco-editor/node_legacy/csstype@3.0.6":
    "Qme2hqcm1oQ6yWugA5iMA1qF5vHLNttgYHk9o6pTwSbf3M",
  "src/smart-monaco-editor/node_legacy/framer-motion@3.2.1/dist":
    "QmZTE4Vfab4JarTE9Urhf6QCGi5S4bo7Go6ZFxUKoRNv2y",
  "src/smart-monaco-editor/node_legacy/framer-motion@3.2.1":
    "QmXh5T3JpZhUEGQjPKVLgPCFfiEzMUgdLwmn1QmPs2S7rJ",
  "src/smart-monaco-editor/node_legacy/popmotion@9.1.0/lib":
    "QmTaZJ5REPK49oBHT76FsF8LX952W1mhEKgEzv81pqy997",
  "src/smart-monaco-editor/node_legacy/popmotion@9.1.0":
    "QmTnZe14NmEVosHmhQG1c1L8wvCDnfoaNzcdqszV9RnvBX",
  "src/smart-monaco-editor/node_legacy":
    "QmeDfigXf5xKxJVjmtujdYmYS4wzjeprCaP2BNuCQPkjcG",
  "src/smart-monaco-editor/src/scripts":
    "Qme94rT99UbaVwYxeK2ERakcHAABqofabkBbiSUuKztFzg",
  "src/smart-monaco-editor/src":
    "QmSQUM9Zkyn5Y6RQTfPKqf5VP5xhKVi76sxsVHLqNHcJvP",
  "src/smart-monaco-editor": "QmVsxbJAyuDZJXMfnbTYc4PCUuUWaKqK77azYp2TpJq5CA",
  "src/workers/ipfs/dist": "QmXLKBxQmafNmqJyFg9h4XzHVcabJmXD5k8zdJX33seNRS",
  "src/workers/ipfs/node_legacy":
    "QmSxTFf8YACtJvwT4M2s7sJ4yv4PFB4LYViYLt7vMyMtHJ",
  "src/workers/ipfs/src": "QmUqoKmHckW1HgxPr5nprzQiwHLgsuryoGeuHFjJiYCeo1",
  "src/workers/ipfs": "Qmf9ccWRmu4KUYnGfR3SGiYCXNc9me6StNmcwzW2VbBXJs",
  "src/workers": "QmcYhnRWpGCRZdCcGG4DFkecZxsvss4skakxUrUWX33y3V",
  "src": "QmfUhsH57Gsfu1JNZiVzLjwoToezF2GGi9J7716m69zBgA",
  "": "QmRZ9DjSXXNdF9hciDmLzgXEeDNazhUvfBMj7RbiCsVhQM",
  "foo": "bar",
};
