export const files = {
  "assets/app.css": "Qmbh94S3j1gDwhW9eMQ16ZKeZe3sRSQCYqWtCRVARU8HYM",
  "assets/fonts/KFOlCnqEu92Fr1MmEU9fBBc9.ttf":
    "QmVB1APqxwoFrkjZ9B2kYmukzGPdVrdct1JdxhkPbeY28Q",
  "assets/fonts/KFOlCnqEu92Fr1MmSU5fBBc9.ttf":
    "QmSuFCECZFdYirnXLK6xfaZWPmqP77LsRCnrdsmU9KVoMT",
  "assets/fonts/KFOlCnqEu92Fr1MmWUlfBBc9.ttf":
    "Qmd8qKxYJaKoiR9EsxgQqwkD5XBzayCHKwNJuhQuUF5ApJ",
  "assets/fonts/KFOmCnqEu92Fr1Mu4mxP.ttf":
    "QmRbTrHtUz6mKUsu7FFzfUBcr4VuoCt9TtpMnJG1P135bS",
  "assets/normalize.min.css": "QmVaRzLwnw3Nnoq8KHNBSTun6m3v2WvVaUbRpukVpcGJUX",
  "assets/roboto.css": "QmafZGaL6TznhmwtJ78ggkm7phbCiuEVXcTxfLwbZG6PoT",
  "assets/social-media-computer-icons-share-icon-png":
    "QmcsMurTbnEVPqP42x15FiisSjQdXJ7vGGHhf279UtwPxE",
  "assets/synthwave.jpg": "QmVP5gg9nYuPg1au5pBmdn75xmUvuGevRPLhEngyEyQfkT",
  "assets/triangle-geometry.png":
    "QmZ5Nic3MRHT8m9SY5ZrSp38UHGEYmJqgk4RAmDV3xXqa1",
  "assets/zed-icon-big.png": "QmeHY7RZzR5wm9ELZr5xgq6XMQKjRAHgmxoQaCzHjgpRm8",
  "favicon.ico": "QmWF8oNe7SDdaY6t4WrJ8ZzM46dHEFmHDXzd8MBeNrELxe",
  "index.html": "QmUUC2yVMVXEArgBwk3whFHbmoXXzVNX8SDp8SR4eoMXcg",
  "index2.html": "QmedxQEiYx4VFnVGV9bGN3LsR95QpPU9hSiAroh2fzZhkd",
  "ipfs.json": "QmbBV3Li2S1VDtjj2EMW9AFtuMDppanNMYgJr3nzEpwKTf",
  "manifest.json": "QmTBHTEYaAy537jiSxtGsyDWNAAXQsvtCtmLgBvbGPFdK3",
  "node_legacy/@babel/standalone/LICENSE":
    "QmZqNk275fZv9p2XtmVbDu5cwqnkhKrrFN3wbYJqGzpznc",
  "node_legacy/@babel/standalone/README.md":
    "QmV18L3zWuKHtn3spzbA1kw75z9Y35GTX2awRvw8RbpDtg",
  "node_legacy/@babel/standalone/babel.js":
    "QmYsHEj7QyeLRK17JqduUcZo73AxxYLZTJ1T5ZMyrFPQqC",
  "node_legacy/@babel/standalone/babel.min.js":
    "QmdCiW5wGiJKavAHxWwg6Q1ADWVoVVwQjVC1zHMRGdR287",
  "node_legacy/@babel/standalone/package.json":
    "QmdKc28DprNXfJdbv9MRbxBQ8GXxbfDXebJXDruZdM7HHU",
  "node_legacy/@babel/standalone/test/babel.js":
    "QmU9MLBmqmBr2TAAS5RTwrmTzhiBdD1qswZDksfcp6QzgE",
  "node_legacy/comlink/comlink.min.js":
    "QmQzvUvopsHv6N1mhbQpVVT6PwZj9zLJUE4L4BA3CxCwrQ",
  "node_legacy/comlink/comlink.min.mjs":
    "QmUsHbNdKZvSFn4ApwxVeYTYV8DJTe3HdDkjvi9ZExUn9Y",
  "node_legacy/ipfs-message-port-client/CHANGELOG.md":
    "QmUq6Tyne3kbYL4f8J7UAYTdgbLxdNbeqj58cYwpCvzXAc",
  "node_legacy/ipfs-message-port-client/README.md":
    "QmQUmsZToya8C5Pu41CCQQtHuAahn8xUVU8FR53vq9QX35",
  "node_legacy/ipfs-message-port-client/dist/index.min.js":
    "QmXqLpDLYfktGNWBGdr1r5nsTwMvP5Y3Lwd1Xwy6s81jtW",
  "node_legacy/ipfs-message-port-client/dist/src/block.d.ts":
    "QmUWVkbpcyRLKY3yFJXnRRgG5G4dCEEUsP8FFHWtN2YkRd",
  "node_legacy/ipfs-message-port-client/dist/src/block.d.ts.map":
    "QmPvz7CqN3RLhzbufMB8wK444BZCSkGvWq9AJK4ECHX93z",
  "node_legacy/ipfs-message-port-client/dist/src/client/error.d.ts":
    "QmSJQU16sAy7NuEinHpMgrHZwZZQaBFCj8XB6PS2aU1921",
  "node_legacy/ipfs-message-port-client/dist/src/client/error.d.ts.map":
    "QmQewEQUzFyyVw8k9fAwaFPwvKkfV3fRLjLqY2M3iZ8yoJ",
  "node_legacy/ipfs-message-port-client/dist/src/client/query.d.ts":
    "QmYRKS8caS91hFcYbhTkwX2KWPBapbQoQRHuNbsPNoijzt",
  "node_legacy/ipfs-message-port-client/dist/src/client/query.d.ts.map":
    "QmaEEUreywjiUq93qJDNT8HN72ALJSESTrwxaRtCdvDtBU",
  "node_legacy/ipfs-message-port-client/dist/src/client/service.d.ts":
    "QmRnxKaZrDGtdUnrYMNmGBvXsnA8fD8ggfpDYZLdPFNjke",
  "node_legacy/ipfs-message-port-client/dist/src/client/service.d.ts.map":
    "QmdNJQNA8G5qwQoPh9ey9bzUqw8pE7qV5zgbQqxC6WXjph",
  "node_legacy/ipfs-message-port-client/dist/src/client/transport.d.ts":
    "QmV1qVFBd6gJxbW4uPD67ko1MmtqBsmam1V94LrAv9hyEB",
  "node_legacy/ipfs-message-port-client/dist/src/client/transport.d.ts.map":
    "QmSnKrhz5dojaJkK19wAQQrySRTXoXx4wXMQvQVQmJcPet",
  "node_legacy/ipfs-message-port-client/dist/src/client.d.ts":
    "QmUUHVrXqWauAcqXHUaCmcw71gYptp7sK5cAsBCDPhm42f",
  "node_legacy/ipfs-message-port-client/dist/src/client.d.ts.map":
    "QmYUyubPoTDrazxwtPRFnYGWq2SMoFLYmX1nbgZDmteipP",
  "node_legacy/ipfs-message-port-client/dist/src/core.d.ts":
    "QmQPRVcyWpBP6bwRdFocM4v6Lpt36e9iDD35d4wwcq6WzV",
  "node_legacy/ipfs-message-port-client/dist/src/core.d.ts.map":
    "QmRAVrwJ6gt5eHfHPPJ8KaPEHojZCZ3kHqMctxjF4P1wjj",
  "node_legacy/ipfs-message-port-client/dist/src/dag.d.ts":
    "QmeimNBbcYuqNHMaCvJ6rSySuvYuANKDPQcc1boc8P4sdG",
  "node_legacy/ipfs-message-port-client/dist/src/dag.d.ts.map":
    "QmZo4hzo424dXHx11L3625TT72CQiTYGJVF7HaqnPsSB7c",
  "node_legacy/ipfs-message-port-client/dist/src/files.d.ts":
    "QmXuKVxkVXwEVTwnqwQSiqWTFh5xPKuS5u3yAWBvY9c7NQ",
  "node_legacy/ipfs-message-port-client/dist/src/files.d.ts.map":
    "QmW6SQBewAS4J7d1ReDwMtrD57mDuF93oBAsWrUUwcZEzW",
  "node_legacy/ipfs-message-port-client/dist/src/index.d.ts":
    "QmYRhrdN3wgmUx1ZHgTj6JpZHR3eb8zd99aD4WhL2rtNPh",
  "node_legacy/ipfs-message-port-client/dist/src/index.d.ts.map":
    "QmQJrfPuGGSYoTVsa1b3pqtFoNdBZbxFKr24oj2y4w7ors",
  "node_legacy/ipfs-message-port-client/dist/src/interface.d.ts":
    "QmdKAxbZ9NRUxfNJAB3pB3VR1cdctWRQY6zkmCn3ujBStC",
  "node_legacy/ipfs-message-port-client/dist/src/interface.d.ts.map":
    "QmU9hRnTB1QEZQALwteoEZLTxhtSKThouZJPxyLke3BHdL",
  "node_legacy/ipfs-message-port-client/dist/tsconfig.tsbuildinfo":
    "QmbCy1WbUnddDkpiM8Deh19h9JFP2ejkrZ4TQPHErJAbgM",
  "node_legacy/ipfs-message-port-client/package.json":
    "QmVXhgNs2u1wuxewRi7M2RyCyhRdLfdPgu469GKxTvi6sC",
  "node_legacy/ipfs-message-port-client/src/block.js":
    "QmSW4Ck3dNWoF4Exqy884kCCS7AZUgWmGj6Vwg9r1pAXaL",
  "node_legacy/ipfs-message-port-client/src/client/error.js":
    "QmTbGgaCwY4JDiv2Qv4Y4MwieKjmphDP6DHewJ6seFFxm2",
  "node_legacy/ipfs-message-port-client/src/client/query.js":
    "QmQY3Rj4re78mfr2RAQHB9qYMBMoyFjydro2UPaGqRUkYX",
  "node_legacy/ipfs-message-port-client/src/client/service.js":
    "QmXchTXDvKJyHvgqYxD9wSAfoxvEgu6nu5QQwKPcUNWJCj",
  "node_legacy/ipfs-message-port-client/src/client/transport.js":
    "QmWanpJwoykjvXpjqMfjaMoS2Vm5Cm8UwSGfmSS11TQuco",
  "node_legacy/ipfs-message-port-client/src/client.js":
    "QmQ6R54rfxetZgtDEb98Xxvazy4kWqhw386YyoLH3dbHBZ",
  "node_legacy/ipfs-message-port-client/src/core.js":
    "QmdnVG4msum227JzZcRo795kvmo5PvakxjtWMtSKngqJKN",
  "node_legacy/ipfs-message-port-client/src/dag.js":
    "QmU4if7NHvttPqF5tYrHU2Mt5YA5mCNV2NtX5oerjqBf7J",
  "node_legacy/ipfs-message-port-client/src/files.js":
    "QmYSnnScYoafgZgdr3AsTtyFa2KgLztnqEbjkUNZDF4KBT",
  "node_legacy/ipfs-message-port-client/src/index.js":
    "Qmc3gjvhbNEeQGQnaXWUdZsFjtedg1RGxYb5zXbohFfwZz",
  "node_legacy/ipfs-message-port-client/src/interface.ts":
    "QmXbDWtNsYsYMLutQtaiEtYeKPoqFYHgTMkQumZ8uuzJRJ",
  "node_legacy/ipfs-message-port-protocol/CHANGELOG.md":
    "QmaitWezQsZVfoAqaEUPkYKExCGDz4ZVtJCRDfQPxuY6Ut",
  "node_legacy/ipfs-message-port-protocol/README.md":
    "QmZDxHpq3YjMwsUMfU9V7deMSc8xc9NsvSoTnbTeyza9N7",
  "node_legacy/ipfs-message-port-protocol/dist/index.min.js":
    "QmURJa7VYT8Y27Un3gL64QH6M8HiWwd3f8YqYb7pK15A4Z",
  "node_legacy/ipfs-message-port-protocol/dist/src/block.d.ts":
    "QmecrcJmkX9rEJ5ef7EkksvmmVAdrumshEitVAAjMbsqDS",
  "node_legacy/ipfs-message-port-protocol/dist/src/block.d.ts.map":
    "Qme7wUPuJgWdjrjy2p6j3oEVmzn7ZUmz9CtNmEjdEW9AFt",
  "node_legacy/ipfs-message-port-protocol/dist/src/cid.d.ts":
    "QmVpYZRSrmQzUCtmqRJX8uadUJ8zGpv3h6R9Rpv9FdBPD2",
  "node_legacy/ipfs-message-port-protocol/dist/src/cid.d.ts.map":
    "QmWGsjSLL6kHhghXbeB9ymTBbabb7dZRLkNqtpYCSyxdwD",
  "node_legacy/ipfs-message-port-protocol/dist/src/core.d.ts":
    "QmeJYfxSzWM2fNwL8Gf4XpQtuFzyUcL1QKQugsSRdndw5q",
  "node_legacy/ipfs-message-port-protocol/dist/src/core.d.ts.map":
    "QmdsiTaqTXndRQATkLSovCxCNvtzoTALLfDzxRVYvpcQiQ",
  "node_legacy/ipfs-message-port-protocol/dist/src/dag.d.ts":
    "QmVqcasp2e3cp829HYac9ABJiLQcCSjHuxWjf2L9eubTeW",
  "node_legacy/ipfs-message-port-protocol/dist/src/dag.d.ts.map":
    "Qma8ZsmVDeepnwKgra89zRgK1Cu7iKcQLNXpjCx4BL9wXC",
  "node_legacy/ipfs-message-port-protocol/dist/src/data.d.ts":
    "QmNWwGLhv3ojiNTCMYpYRF9XEXfcGgqvnmHpeD6SkyH393",
  "node_legacy/ipfs-message-port-protocol/dist/src/data.d.ts.map":
    "QmeFr1wqj9eFNttfysqqrdJidnuAh2HpS7xVPjcuWhJMLj",
  "node_legacy/ipfs-message-port-protocol/dist/src/error.d.ts":
    "QmaegXnQtmoBaRdx7NfQ3gZCH2He8HvpaBuMBgc4fLctcR",
  "node_legacy/ipfs-message-port-protocol/dist/src/error.d.ts.map":
    "QmNMoPQc1RGQ3DMSFHKRQLMTuUDbzgaH1LoaDdAKf9XgfL",
  "node_legacy/ipfs-message-port-protocol/dist/src/index.d.ts":
    "Qmev5QfxHsAUmgBqdiWcaodnbZSAoUP1gmVmTwM8FH7348",
  "node_legacy/ipfs-message-port-protocol/dist/src/index.d.ts.map":
    "Qme8AciEXCfQy8eZhwMhpFcCdE7cH12URucWDFHGEHPHRP",
  "node_legacy/ipfs-message-port-protocol/dist/src/rpc.d.ts":
    "QmeFcw7QGmdxg6VY9DNVqQzbCeBaGxuM237VZpH9qGLBsi",
  "node_legacy/ipfs-message-port-protocol/dist/src/rpc.d.ts.map":
    "Qmdm1zVmD4w4KEPp7hYLYS5ZnaSm2VzMWXege7DsA4tevp",
  "node_legacy/ipfs-message-port-protocol/dist/tsconfig.tsbuildinfo":
    "QmeN2WPDixMMxQLjkSoUN6j4U5fpna7fKQXBZF7EmbBX2k",
  "node_legacy/ipfs-message-port-protocol/package.json":
    "QmXxfqU3s8979NJrV4oroGn3rPoHzXqKUGEVQvYFrJWA3h",
  "node_legacy/ipfs-message-port-protocol/src/block.js":
    "QmWzZAqjdrf8PSNobDwLdBJsdyfP5BB7V2UjGsG4LdKNMp",
  "node_legacy/ipfs-message-port-protocol/src/cid.js":
    "QmbZ5yYK2ggguW6swvnMbT8HLHs1E1WxgEuftg8nLimG3t",
  "node_legacy/ipfs-message-port-protocol/src/core.js":
    "QmQAykQTfEtDHB3UCqvFSyAPFK3KSTCgkpHeDMqTZJZ6Sr",
  "node_legacy/ipfs-message-port-protocol/src/dag.js":
    "QmfUsi6ShpH7y6FpJLvHLPAyL81R7RpfASBcfo9AK4Rwt2",
  "node_legacy/ipfs-message-port-protocol/src/data.ts":
    "QmVUwxsZhtjqwGafu7hnMZKq9VicvjfPnGQTQ4BvZhLyjb",
  "node_legacy/ipfs-message-port-protocol/src/error.js":
    "QmNSG2karhxy5SRrq9mfN9We7vKVRwYZAp6yW13s17vDoe",
  "node_legacy/ipfs-message-port-protocol/src/index.js":
    "QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH",
  "node_legacy/ipfs-message-port-protocol/src/rpc.ts":
    "QmVpcmcHLNnaksnneZhMF9SNWZL8TXbktXtcrhoGhrJpuq",
  "node_legacy/ipfs-message-port-server/CHANGELOG.md":
    "QmRmmWZNGJaUWDmL1C5LyAqATLCmGW7qyPiMHfn6JLzFz4",
  "node_legacy/ipfs-message-port-server/README.md":
    "QmPLYzjhR7Unhr6hAfGEr5fDEBb6bTzaviDf9ofLY7Ym5U",
  "node_legacy/ipfs-message-port-server/dist/index.min.js":
    "Qma7jRp5r2MuGba6vPTWBnGSvVrRWuq4MD18CnkAUWWYvn",
  "node_legacy/ipfs-message-port-server/dist/src/block.d.ts":
    "QmPkKfpabCqTmbmQDyT9LHn5TWmiwgUiPRznMHY1SGPczN",
  "node_legacy/ipfs-message-port-server/dist/src/block.d.ts.map":
    "QmZ9oZiRczq8L6oqciu4JumTz6ftBy89oQF6ZLwkcK1kp4",
  "node_legacy/ipfs-message-port-server/dist/src/core.d.ts":
    "QmWMnernUrxDkWM6BDigCtAh5e2eJctyF2F5cHHabvA6CU",
  "node_legacy/ipfs-message-port-server/dist/src/core.d.ts.map":
    "QmRxjN11sya71haCMM2UUztJFr2ZdVhTDzjR8SobhKLVdA",
  "node_legacy/ipfs-message-port-server/dist/src/dag.d.ts":
    "QmTmNw2gbLMZo219WRg5BYac27gNaKhnjeEsvRJX1zaRdg",
  "node_legacy/ipfs-message-port-server/dist/src/dag.d.ts.map":
    "QmZmFCNRErT8E6E2XSmwWj6HT1NnSY8iA93W6n1p6mmxyh",
  "node_legacy/ipfs-message-port-server/dist/src/files.d.ts":
    "QmdxURyDqBtg9zg9ZGz494LiKUo33ZVeBjHcDgmvSspvbx",
  "node_legacy/ipfs-message-port-server/dist/src/files.d.ts.map":
    "QmcHWcyi2fLfqqzDNanASJ657S9kVZAFiCEAyMz8rzoUKR",
  "node_legacy/ipfs-message-port-server/dist/src/index.d.ts":
    "Qmb9cG8dEmKyFyixMe1s2xZnKnyFYFCR1Nxyi75UAt9hVP",
  "node_legacy/ipfs-message-port-server/dist/src/index.d.ts.map":
    "Qme8AciEXCfQy8eZhwMhpFcCdE7cH12URucWDFHGEHPHRP",
  "node_legacy/ipfs-message-port-server/dist/src/ipfs.d.ts":
    "QmUGhC2wh3gBgVCrx2tUcE9DExFnjob8BFFKMm4rPgko2s",
  "node_legacy/ipfs-message-port-server/dist/src/ipfs.d.ts.map":
    "QmZVgFECqULeWjwuu332CgHC4DN1xj71Hoq31xXkveNKkT",
  "node_legacy/ipfs-message-port-server/dist/src/server.d.ts":
    "QmVWDant3dtzrpwtd8RM9M6VpyDYrFANxpr3AJfKwkBTf1",
  "node_legacy/ipfs-message-port-server/dist/src/server.d.ts.map":
    "QmQbVgoCyef9VusSrBCG1m6mbbsVbDwVWPiriyfdi3Hbh6",
  "node_legacy/ipfs-message-port-server/dist/src/service.d.ts":
    "QmS7wvmAd7ecfeXK1Tzp4bKYWFo1JZDJhPfkArC8B4rJ1R",
  "node_legacy/ipfs-message-port-server/dist/src/service.d.ts.map":
    "QmZNt3LU7HXu5CrvEByPxiQJdm9yv6SfhSHeEzPKSr4tvT",
  "node_legacy/ipfs-message-port-server/dist/tsconfig.tsbuildinfo":
    "QmPrSE7a29CkHY7XGege1yv2ouDGE5P4jYkDG6ke8KSfKV",
  "node_legacy/ipfs-message-port-server/package.json":
    "QmesLEDq9JrCY78TBekbmeCxB4vgAhC1CAQzo87XoJe1GW",
  "node_legacy/ipfs-message-port-server/src/block.js":
    "QmXttM5tparJqJ8L3NVzg1dW7xeWw7qhCHHKakz3JDfSyp",
  "node_legacy/ipfs-message-port-server/src/core.js":
    "QmWTYMkNW1H5qayyqCQs1v8muagN6upyN6s95LzPGxMYMA",
  "node_legacy/ipfs-message-port-server/src/dag.js":
    "QmTDonUhPQsVNiERqrg447azfrFhAHgMei1sVXfZFUiyZ1",
  "node_legacy/ipfs-message-port-server/src/files.js":
    "QmbZHM4ZrnbUypKNeFJge6yKHwmdGcTPnbq4EayCqrVsGT",
  "node_legacy/ipfs-message-port-server/src/index.js":
    "QmTUGjQzu4uKBDXdBptyM1bHB23f8jbhVuFxaCk5FbYG6F",
  "node_legacy/ipfs-message-port-server/src/ipfs.ts":
    "QmQKg5riZgL6guTjrVzobTq45FcVDzRycwkr5JgoJKXpD8",
  "node_legacy/ipfs-message-port-server/src/server.js":
    "QmQVGV8mY4bWrr17knNQQ85ypuNhz1ay8aEZHib9t85c1T",
  "node_legacy/ipfs-message-port-server/src/service.js":
    "QmRhSC4xzYCejn1fXKbG5MaeprRRXSPQkGBJzL2ryVGJtA",
  "node_legacy/monaco-editor/min/vs/base/browser/ui/codicons/codicon/codicon.ttf":
    "QmNiTPD7q8ucTwfMqePmN45DarksfCAJytgSJutKP5WjGc",
  "node_legacy/monaco-editor/min/vs/base/worker/workerMain.js":
    "QmaYZiYoPdF3DFVMLbXrYMEqaemD7WxszVFbAhMguP8yRT",
  "node_legacy/monaco-editor/min/vs/basic-languages/abap/abap.js":
    "QmZFkpZqXwUFY3T4kPpBsuAZ8mT9gi8YEFYKoLcsV7tA4V",
  "node_legacy/monaco-editor/min/vs/basic-languages/apex/apex.js":
    "QmcCdEaPbcyhgAvB3m7ueXUwJXpNoEaWcH2dRMA1xou8rB",
  "node_legacy/monaco-editor/min/vs/basic-languages/azcli/azcli.js":
    "QmZTN2xXAofV9PKCCGChWsbkbNvkvWUavYFmT4rM5hpNH4",
  "node_legacy/monaco-editor/min/vs/basic-languages/bat/bat.js":
    "QmXDJ1V11EqVuoexobiqkdwBNAasJcgLcGpUYJqe9L6o7R",
  "node_legacy/monaco-editor/min/vs/basic-languages/cameligo/cameligo.js":
    "QmVpMuxhBzj1S5k31YXmQvdFvCgzEYQiLCHmLyhyKqJJVV",
  "node_legacy/monaco-editor/min/vs/basic-languages/clojure/clojure.js":
    "QmeqLMhR7aeeKMZtPF6WuDdDrfAKm4J2LHdgXYFrQwFauZ",
  "node_legacy/monaco-editor/min/vs/basic-languages/coffee/coffee.js":
    "QmdKB6rCwgAenbnvr21x2APtabiF8s31eYUwMefH4J8tHf",
  "node_legacy/monaco-editor/min/vs/basic-languages/cpp/cpp.js":
    "QmWvRmNf4PGQ6kbp2X6MFTcmotjfZVgonobF2E3CdUKc7o",
  "node_legacy/monaco-editor/min/vs/basic-languages/csharp/csharp.js":
    "QmRg9X8xW8KekFgxK4tynhr7dgXLKwXsCr7tMBUw31Rh2r",
  "node_legacy/monaco-editor/min/vs/basic-languages/csp/csp.js":
    "QmUPzSLKKj8ivJTdRUBYFZJb2Q2yiB6VZPg8FYHPUGgbJK",
  "node_legacy/monaco-editor/min/vs/basic-languages/css/css.js":
    "QmadEpbXqVyX4ErQ9qvb6GhACSqMfDUV1WhvnYg5LW2s8S",
  "node_legacy/monaco-editor/min/vs/basic-languages/dart/dart.js":
    "QmXMHLEmQzUew27DKC9WuJFbYWg9pjdYUMhca31Nt6HbSG",
  "node_legacy/monaco-editor/min/vs/basic-languages/dockerfile/dockerfile.js":
    "QmXVvNdgsigcK3eRtenJp8ia2eHJJ6L3uyneYA8nidMgmZ",
  "node_legacy/monaco-editor/min/vs/basic-languages/ecl/ecl.js":
    "QmQH9nP2doHnQvoeMawGFaWu7TCVEAHpJwFyc9yU6tJcsq",
  "node_legacy/monaco-editor/min/vs/basic-languages/fsharp/fsharp.js":
    "QmUkwA8WmdjbSZ34LmjNe6R6k5Ft1EVaRpLpSVP7hmZ9Kx",
  "node_legacy/monaco-editor/min/vs/basic-languages/go/go.js":
    "QmS5esLpJkxipDxjAPUJJvdE2jbnoY67S4aMFkLcxuonUa",
  "node_legacy/monaco-editor/min/vs/basic-languages/graphql/graphql.js":
    "QmZ5ZXHq6nehocF8RuHgu5hPzLvDtq5mZQ29Fju5ue3Wfb",
  "node_legacy/monaco-editor/min/vs/basic-languages/handlebars/handlebars.js":
    "QmPGKyew9wMki65Si2M9pjaxFkVGBbaJyRB67i4mEaWn8C",
  "node_legacy/monaco-editor/min/vs/basic-languages/hcl/hcl.js":
    "QmXboLLLni5Yp2aKMQnjHvH2yykWSHayX4PdmvqNBhBDKo",
  "node_legacy/monaco-editor/min/vs/basic-languages/html/html.js":
    "QmWcDG5urt7RMzpxTzCiaUanBz8KEUREEkkx8nGsv37BvP",
  "node_legacy/monaco-editor/min/vs/basic-languages/ini/ini.js":
    "QmZDXUYG6u1y6VYjtdS3wFvnif8FDB2GzV2Uoq7vDWCXRP",
  "node_legacy/monaco-editor/min/vs/basic-languages/java/java.js":
    "Qmbnh4EBxBJ8w6CeNd1EmAGVfHPVg155DSGCRLiVHynB82",
  "node_legacy/monaco-editor/min/vs/basic-languages/javascript/javascript.js":
    "Qmdguk5bHN2f97zz7eVetPpa7RTTX4Lf4gxbmoEJgAdq7C",
  "node_legacy/monaco-editor/min/vs/basic-languages/julia/julia.js":
    "QmUzHfeKF1Kz87WG7iPz1g1zPDmqUTLH2fzNGNaHmnmTzi",
  "node_legacy/monaco-editor/min/vs/basic-languages/kotlin/kotlin.js":
    "QmYFXjuVVYW8hqDkN6YE6JpTxtirsBxisw3NeaDJnYu8rF",
  "node_legacy/monaco-editor/min/vs/basic-languages/less/less.js":
    "QmeYgZTRJ8aPPnJk1G6vojHPjRk4Az7aHDYZorP9D9iaiF",
  "node_legacy/monaco-editor/min/vs/basic-languages/lexon/lexon.js":
    "Qmd7M1B6GCu2eD21ZrqfbdoYbrjZfVHCCwBVSBRAtvorKH",
  "node_legacy/monaco-editor/min/vs/basic-languages/lua/lua.js":
    "QmYdtU9ypLHHyU5SAEZTtKDKwzJ9thtmtgcZBY6pneWgFa",
  "node_legacy/monaco-editor/min/vs/basic-languages/m3/m3.js":
    "QmXw8qydketMwHhFe35ZAn1vFiAno91ZkywuPSTTmaug5v",
  "node_legacy/monaco-editor/min/vs/basic-languages/markdown/markdown.js":
    "QmSGfh3PrR4fq8DL78GKQggMgur4uQegFgHy3BtFA8A8Eu",
  "node_legacy/monaco-editor/min/vs/basic-languages/mips/mips.js":
    "Qmb1qgoDgczooDVx6NbTUZRqixwD4emF6VvU6PbMvXQYhR",
  "node_legacy/monaco-editor/min/vs/basic-languages/msdax/msdax.js":
    "QmT6EGZgFms4Ezzg5jqrhHi38zfU41myXwUQxPjEcR1FTY",
  "node_legacy/monaco-editor/min/vs/basic-languages/mysql/mysql.js":
    "QmRgtSha7dCVnfJqaEpUunK2Q4StGz7r7jxtys55fC8Qff",
  "node_legacy/monaco-editor/min/vs/basic-languages/objective-c/objective-c.js":
    "QmVaYsb3J6RJH65apeaNrNcceXPPMgqwpJ2beq7tx8NzYr",
  "node_legacy/monaco-editor/min/vs/basic-languages/pascal/pascal.js":
    "QmR6C7usYK7MNQ4vmz3HQG1T3DBrevWTTRYxFoxE7kDscx",
  "node_legacy/monaco-editor/min/vs/basic-languages/pascaligo/pascaligo.js":
    "QmS9BBXZtWsM5UyDM65Z9tWfcNYu3rYP4NjVjX6eYaPr29",
  "node_legacy/monaco-editor/min/vs/basic-languages/perl/perl.js":
    "QmdqAeciXXVREvQwLJ1ToDVvXVriYaigpQTtPfdXgPDj6C",
  "node_legacy/monaco-editor/min/vs/basic-languages/pgsql/pgsql.js":
    "QmVH36tbPWxeV2DMYmxHZGJKGtwhyyuYwSCrBsKiTSbemU",
  "node_legacy/monaco-editor/min/vs/basic-languages/php/php.js":
    "QmWhwoK59ocejfuZj8qMETSTou3bWurVPPKiiTgvcBj3Ls",
  "node_legacy/monaco-editor/min/vs/basic-languages/postiats/postiats.js":
    "QmbDG5yTQZhH5QfPCEoZTmzJsKn3QSBzmi1QfQFR3AzZnH",
  "node_legacy/monaco-editor/min/vs/basic-languages/powerquery/powerquery.js":
    "QmPPrNqERHgbgLzfkrwT3D2fUH5YLoL9omAUUbTP9TMTZa",
  "node_legacy/monaco-editor/min/vs/basic-languages/powershell/powershell.js":
    "QmVvNiybBgEYikaDz2huyHNnAMLw6o3FhqBnKAaCmLHrJa",
  "node_legacy/monaco-editor/min/vs/basic-languages/pug/pug.js":
    "QmamyRXx8XVppHWvZxZWCh112gcaDf7bCESUutPyotrdbU",
  "node_legacy/monaco-editor/min/vs/basic-languages/python/python.js":
    "QmTFrAfkoMeyoLWB47Xe1bLy7nkA2xZjxNNrEknhhUvJBf",
  "node_legacy/monaco-editor/min/vs/basic-languages/r/r.js":
    "Qmao8D4L1ZYsTLM1w2yM3kq4SvRgcwj9xPktR93QhPRTyc",
  "node_legacy/monaco-editor/min/vs/basic-languages/razor/razor.js":
    "QmNwCi4YqzVZzGUwCB3eVg7LCAYwYyaHBmvFpaQcJF7SpF",
  "node_legacy/monaco-editor/min/vs/basic-languages/redis/redis.js":
    "QmQXsYkWv1nwEjCFMyDVBSdsFrzSXPTupoMraLSGrcxsF5",
  "node_legacy/monaco-editor/min/vs/basic-languages/redshift/redshift.js":
    "QmbkYiy4CvSsqQZjpJc6FgCbcUGdtkXLgJxJQhaZC9n5ti",
  "node_legacy/monaco-editor/min/vs/basic-languages/restructuredtext/restructuredtext.js":
    "QmcUWoeFjgyqyKSftJHDwaYdFUjNXCEm1z95RK34rBgTZC",
  "node_legacy/monaco-editor/min/vs/basic-languages/ruby/ruby.js":
    "QmXLJ9Zhkcsh2bM9n4p5Cwg3k8ZwVpwrrukFEBG7g1RDXm",
  "node_legacy/monaco-editor/min/vs/basic-languages/rust/rust.js":
    "QmTRThLUwCMfDjH2wDcDGEXGLF2oigxTroZfwuBtkKE2sr",
  "node_legacy/monaco-editor/min/vs/basic-languages/sb/sb.js":
    "QmfEbXETeeYRkJVfktYAh51mfC4qJzD1ZUV43VckKMJy6x",
  "node_legacy/monaco-editor/min/vs/basic-languages/scala/scala.js":
    "QmdgwsSevzBx3dSJjrBNqgdARJ1s5TMyXiB2oaVXMpUroo",
  "node_legacy/monaco-editor/min/vs/basic-languages/scheme/scheme.js":
    "QmbJCZuFHw1MQjn3Bh7KTGscHkNiMjbwD2B6UQGarXcZiS",
  "node_legacy/monaco-editor/min/vs/basic-languages/scss/scss.js":
    "Qmd4uVipGnHD6nQF2bdwKRCpRQ7sYKnryEq6UyYAkz1jxM",
  "node_legacy/monaco-editor/min/vs/basic-languages/shell/shell.js":
    "QmVKg2uvWPtD9srpG9WKim1CmKSfbP8TBv71qEf9roQ8bs",
  "node_legacy/monaco-editor/min/vs/basic-languages/solidity/solidity.js":
    "QmbCNVcnX8wntud9T8Uq7kfvLNL3Q65qwTS6usDxhKeb18",
  "node_legacy/monaco-editor/min/vs/basic-languages/sophia/sophia.js":
    "QmZYH395WYrar35h5PH8pJBDcegxVtmEkVjC7Yosj5e9qx",
  "node_legacy/monaco-editor/min/vs/basic-languages/sql/sql.js":
    "QmeWS2mdWwr4SKAtB13cvGruk4rmwYjSakPJR4zAKZNPyS",
  "node_legacy/monaco-editor/min/vs/basic-languages/st/st.js":
    "QmSoNKSLsvLxyJSwNK5AqjWPgJd8b2CXZ4vX6eNpSfacHw",
  "node_legacy/monaco-editor/min/vs/basic-languages/swift/swift.js":
    "QmZPosVaVJPWhUkyWRpmjdqurTRa1ssxjHA8QSM34H1ajV",
  "node_legacy/monaco-editor/min/vs/basic-languages/systemverilog/systemverilog.js":
    "Qme87Uh1qFCFvDE6FMgdEHspHbjTfxkiJn96arLgMpfdgZ",
  "node_legacy/monaco-editor/min/vs/basic-languages/tcl/tcl.js":
    "QmdCzYWegu14LfYnjz4UZZGpiAtYhLYyspMPtm2VNbwX1d",
  "node_legacy/monaco-editor/min/vs/basic-languages/twig/twig.js":
    "QmW8rhcCwQB7gC5AGDCXeR2jnUYwqr4weCaETNvmVKTbfR",
  "node_legacy/monaco-editor/min/vs/basic-languages/typescript/typescript.js":
    "QmQ1Crjdww6QTSQqqhXiE2sm9jHDpRKXFoT4KgiKV7qhWt",
  "node_legacy/monaco-editor/min/vs/basic-languages/vb/vb.js":
    "QmXuPTjQVeRTQ2iWKKyGLAubzJHPDVdLebxs325moWdkbD",
  "node_legacy/monaco-editor/min/vs/basic-languages/xml/xml.js":
    "QmfG5GEMc9wkzJ7FxgemKVfd6TzAXn43KWKXK9PMQHoUBU",
  "node_legacy/monaco-editor/min/vs/basic-languages/yaml/yaml.js":
    "QmfUCo7tZHXvCMRz3G7kkZD3gG5DxobQTgQEUtaskzv1Hs",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.css":
    "QmZWFNbmB5HLfwq4QP8RKsPG6zHLDKgrkdDYN3ymPrUKzu",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.js":
    "QmTkA1GXJSnUQM9fPdWaLLr6a1LDb21GbYDe36KULRU9sL",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.de.js":
    "QmNrrmzkY8kd6tUMV28zWq7kV2Md399hMrkybY5GxSAwj8",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.es.js":
    "QmUMh7KQR53MfAbtCnRhzeGRUXWUzTRQ99k7saBAeomZmz",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.fr.js":
    "QmYDDUsPLQvr3hMCCdWTcXLzNrYwoSqspT3HnsFD15Y8vd",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.it.js":
    "QmRk93Av3u7uD1FHiHSLr4HVo5HWLXFLZm8MZdtwF2AsdP",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.ja.js":
    "QmaHnTvzRDA97ck1eDZ7DNsWUuUqGtFsK3YvLSbqaL3gHx",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.js":
    "QmS5fsNEasUqmayahezzUnpeD4FjauMFfxs6dyLPe7oY9g",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.ko.js":
    "QmWmAmQ2ygqqryJbQizQg7E4BKW2upN5vL8Zni5vPY2vvf",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.ru.js":
    "QmVAWv6kBj9Mk8M5ezoUc95Prv55FSu2a9kUgqHHrRnXjB",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.zh-cn.js":
    "QmV5dsTsuhBh9peECfchYP1oxTcr7dLZET4EH1vHNKAt23",
  "node_legacy/monaco-editor/min/vs/editor/editor.main.nls.zh-tw.js":
    "QmPs9Y5QZgyY7rD8a7V6DKLam8V5R9dPbeuj3cws7LKs1s",
  "node_legacy/monaco-editor/min/vs/language/css/cssMode.js":
    "QmWBQS2KhHcfBen4LKkm3VGaVdqtQuFFJ1YFy2SRvj4FsE",
  "node_legacy/monaco-editor/min/vs/language/css/cssWorker.js":
    "QmUbtq2bbGWW1FRLByE2uhbyLvBvwp27J7p71orLJV65Ff",
  "node_legacy/monaco-editor/min/vs/language/html/htmlMode.js":
    "QmT7VVRruxkPwtq4BCHgb2HEAckeaHVqv7hQHE9r7L8ZWK",
  "node_legacy/monaco-editor/min/vs/language/html/htmlWorker.js":
    "QmenovHLYHzpiK57KkUCrz7nfeifQ7nG86tBcULPJTm3cq",
  "node_legacy/monaco-editor/min/vs/language/json/jsonMode.js":
    "QmST2SUQgh85a1TanmJgjAGBkfzX6igN6p8WmgcLArxeEv",
  "node_legacy/monaco-editor/min/vs/language/json/jsonWorker.js":
    "QmUCyLJnTnrGQJ6JZyfbcLcmaVk8R5WSTSD6HUwL4qozAk",
  "node_legacy/monaco-editor/min/vs/language/typescript/tsMode.js":
    "QmfWtTJ1f24x65B4CNEyeYgFVGugRhVWB5nmVW1p8QPDDZ",
  "node_legacy/monaco-editor/min/vs/language/typescript/tsWorker.js":
    "QmYKGudEpMPegen7soyXBDsVZ3DYmr4yWZTGLSwjjv8a4i",
  "node_legacy/monaco-editor/min/vs/loader.js":
    "QmS6fG3Dxm86p7TQ73uVpC9dXgWH93mDv6C3yAvTHbbFt6",
  "node_legacy/monaco-editor/min-maps/vs/base/worker/workerMain.js.map":
    "QmYadh9JYvX5joq1keNqTAr6VMMBrwcds2XbWqEeySo445",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.js.map":
    "QmQUh8i2A3cCfJ5mSEbrqykAxQUyQM5YYJjPjM9W3P93rn",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.de.js.map":
    "QmPVeo6ASTGAEMfyyqC7euLZFGFDaVvEaYA8bUEEEPozoX",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.es.js.map":
    "Qmd5dH7RuLxYVNtXGsj5hCEAFnSceRQfEEg7YDeDJgtcyk",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.fr.js.map":
    "QmZ97YyGW5XARgMA3eqH9voLZoHD1c2P2irhUHEqfJEW7j",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.it.js.map":
    "QmZnf94CQAmXqp69Dee8LKbay7y21GZZfr8K3FrPKMpaL7",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.ja.js.map":
    "QmabnR8TLoTZqiD8LMnnhHs3pSh4xwqvEKpsqptnyGfPJB",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.js.map":
    "QmcpRXXZjyeMGSRdqBgXsqsVTsy8aQanWG81ePHN7GJVEC",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.ko.js.map":
    "QmcnVGb2YLrF8forGTCAWZ6U6T9Kps6SWWMzDhMAa2B8Vx",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.ru.js.map":
    "QmRPrNLsQEeEyfCewcbeoK3u3NP5tmnWQJKw5i43Ew3Grj",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.zh-cn.js.map":
    "QmQomb5JtZBqJ8FFWyCcEn52gfX728fmBiNVFq9ooYb6UF",
  "node_legacy/monaco-editor/min-maps/vs/editor/editor.main.nls.zh-tw.js.map":
    "QmTm3ppJoshcu6GSXEpfk2YRx5ftn4WvTPdrpGoFpJUpop",
  "node_legacy/monaco-editor/min-maps/vs/loader.js.map":
    "QmTjTFnCNWdurh7ejmnTp6PB5ffmr1r2ttqGhFxmvmhYn7",
  "node_legacy/monaco-editor/monaco.d.ts":
    "QmUjPjKFub8iLaw5anZPmPqj3F9jmT2Y54HNZWUaNFicxr",
  "node_legacy/monaco-editor/package.json":
    "QmZcryZqRY2N7kTaE3fQuEuPirbWDCvMeBVzV5QRdP28u4",
  "node_legacy/regex.js": "QmW6Zb7r6mgzB4j2XMMFUToUfcHEbfHFwdZ9X31DSuJuZE",
  "node_legacy/rng.js": "Qma7h4zLfzavfQ5XWHVmdPgXEMT5tZE9o9syWfHQfRjzdS",
  "node_legacy/simple-window-manager.es.js":
    "QmSkRETmFZ3t2dzUsPoeTS5o4MMkS5csX5hHJeEERsCrrv",
  "node_legacy/stringify.js": "QmRBevsDvKdofdKgReQKM3gCwqVn9kUTRXkW97GrsHLCmr",
  "node_legacy/v4.js": "QmQmbGmvapVDYZ4A7NFBcXMuckrBin9GG7eCzjq6JFX1Cb",
  "node_legacy/validate.js": "QmPFsS1CAfre1T5H9pqhRuDX387xhZjdPghLpMY7uKx8vT",
  "package.json": "QmUrjjo6zB8Hp1YLPi9xocxwbyTdgpsZ24T6hwYwBCwrE4",
  "src/codeLoader.js": "QmUXsWzdjDNyodpZWT7qq4ASdtSp9Q1LRpjtSQeyMiQHDt",
  "src/data.js": "QmRKJPktSjMy6qREy5yZPwHgMtFJgDvKSDR6g54UwEPmFf",
  "src/db.js": "QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH",
  "src/emotion-react-renderer/dist/DraggableWindow.js":
    "QmQPPUCAwhuyA4urN77XktyKKiKU8nbiBLhtPD82Kqam21",
  "src/emotion-react-renderer/dist/renderer.js":
    "QmSDuXVDvgBhkNeirJJshK6pf8UqroKbhtCZ5GCWZ7T6gg",
  "src/emotion-react-renderer/package.json":
    "QmajYAoQQbYsc9bJyAsP1YX7iZcVkhwv5SMeDCPz1gnaEa",
  "src/emotion-react-renderer/src/DraggableWindow.tsx":
    "Qmana9ZxBTpD1yihJ84bVDUb1BgWm8oK1tgrfsxXYY6u5c",
  "src/emotion-react-renderer/src/renderer.ts":
    "QmQNdoLdcbKsbgVXbybqtoCxGDRRzzuCjrpnKTfcgSfR9z",
  "src/emotion-react-renderer/tsconfig.json":
    "QmVf1pkrppvUoQ7dmSQ5XH7WM1PY7SqAwxR3TR8pT2oGVA",
  "src/examples/app.tsx": "QmT5yUxG2so3ddoG8CuABVg9hyWtxqQHRMarWKHobUM454",
  "src/examples/starterNoFramerMotion.js":
    "QmWVABuMCi74dqH3AiGtWU1SEBzvmhiRCADWYCupQZYuAs",
  "src/examples/starter_framer.js":
    "QmaVBy5PCmFhEKZ7gMtLZUyAy8FBfgDnPeLm6HgCnrC6KF",
  "src/formatter.js": "QmWcaaZFJLVKDFMneB43W98QQ3QSifrmwupLamwFMvd3pg",
  "src/hash.js": "QmNwbA46c7bRTXeZtxbvcja1g5Pq4G9m59ZfFWQc4sUiQR",
  "src/importScript.d.ts": "QmV1V5Fb2ZxP5Kn31nSU7FS2TtrDMg6wR7sMTsKeeR1txL",
  "src/importScript.js": "QmWNzoXJSf9aHxMEbDGsdMfyfJKwtpfL1Q9ni1xuSF5c9X",
  "src/ipfsClient.js": "Qmb8GxidnERUJmTzcu6NzQeYhqDUT4YQYpEstvQkGekSQW",
  "src/openWindows.js": "QmYDbjLyo4iF1SWgfrDZfKiSupeXDiQVKn81AvGdMBHdwh",
  "src/qrious/AUTHORS.md": "QmWzBXD5ULj9EAVt7ffrffyZ15pUwjDXpoquHnoaRBaQpx",
  "src/qrious/LICENSE.md": "Qmf71mxCKmPQnJZadhscUSszFDFkNBZFkbEenEKyPgLFTc",
  "src/qrious/README.md": "QmdPbXiPxjM7xyoJvMkgbwjZ7awWtbZjo4vvDr3y5C36pB",
  "src/qrious/demo.html": "Qmdcpx9zVreub9xBE6QxhfGtZ7Sodsnyx9KCyMyLhqibn2",
  "src/qrious/demo_min.html": "Qmc6Me5Zv7VBGoAbQp3xe8fDEGW28SFCrKYG6yWz4h4SLQ",
  "src/qrious/dist/qrious.esm.js":
    "QmaqQCyrDX8cYAvNr1YacrAc9CQyH3Nt6hSmP7JV7JX65H",
  "src/qrious/package.json": "QmWuJiMpmDqUaJsRaM2uB14CCyF2BCKZzjmmAy2i9g4bsd",
  "src/qrious/src/QRious.js": "QmWyhyMT7B8vJWGm6kMXrXBhS7pgx4Dqv8TRepBqDxyW7e",
  "src/qrious/src/service/element/BrowserElementService.js":
    "QmaquwSn36sfzcn6seaTvR6YPhJoFVQvh9z9174tzTEjgi",
  "src/refs.d.ts": "QmV4VN2uGcNzHPQi51JkVC4p9RzDpe5sEk4sX4u9ub3J4p",
  "src/renderPreviewWindow.js":
    "QmfP1aS1vf8RLz8WYW7WwKnbmzAQAjQhm6dVvGACreV7Zn",
  "src/sendSignalToQrCode.js": "QmeZxocsjhuRy2v7WdzGegZDsiHVPpZw7WNAqyb5j2mN3G",
  "src/shadb/dist/diff.d.ts": "QmXv6B78NKbJLMyErUn6XRUkXxvkata8i6CR5JCC721QJx",
  "src/shadb/dist/diff.js": "QmbfZsnJhysseRS92eSEc2SX7hBaaLPTojb7oqc6XaBqzy",
  "src/shadb/dist/diffChars.d.ts":
    "QmR9hNHu2ZNp9CopGNmME4KgNuyAzMZcZ1hUaZwnjXfkE4",
  "src/shadb/dist/diffChars.js":
    "QmNRK5ZC2ZEdMfrTozGkgGJdHiMWYbfk84Gi3kBD4rgMBQ",
  "src/shadb/dist/getDbObj.d.ts":
    "QmSN6JKpmgGd8mwb8gEKViV5juyt4jpw4e5wQqFpzGUiF2",
  "src/shadb/dist/getDbObj.js":
    "QmW2LmUqcg8fzLtjroo3JHbUUXDq16X9n3dBUE4WUVQzG3",
  "src/shadb/dist/sha256.d.ts":
    "QmQCcqJvRmWrgHXvwifwqPziL9UUNckyDZbPbLGb4SbS9k",
  "src/shadb/dist/sha256.js": "QmWZyJbdb4B22fLgpbDqNo6wU2sWccyecceKz6bor64hFi",
  "src/shadb/dist/shaDB.d.ts": "Qmb1jkMJhCGHnrFigsUkCNo1uwebGfrxXQH4EHSpnh6zFY",
  "src/shadb/dist/shaDB.js": "QmX5mSevBrVHk6mpp1VNaCMqmCYC7azWBUFgrzpHnG4NDp",
  "src/shadb/dist/vendor/diffChars.d.ts":
    "Qmf31P3dFhCyz9X8GkuUytpn3cmJwsggF4kPTbmwaiekRt",
  "src/shadb/dist/vendor/diffChars.js":
    "QmcC8KRucgoFQ5EQ43yykZAVDCoYUeCS9tNaHmhXhaVAaQ",
  "src/shadb/dist/vendor/diffMin.d.ts":
    "QmUEzhNXqsRtc45fB5if9wchLEL1wgmY58wX27E5zUCJtp",
  "src/shadb/dist/vendor/diffMin.js":
    "QmQvwZBWXeTmVqjfipWeA5k2L7MMQd4ooqEe7qVAJs8VwV",
  "src/shadb/dist/vendor/idb.d.ts":
    "QmRDw3SijUK8mQZ2H5CzJtKk8zknGsCz4mz58EzsjEC738",
  "src/shadb/dist/vendor/idb.js":
    "QmeDaTt5WPt58TYHpMzMyURp7hMdfUiKm6AbwEtZsQGoc9",
  "src/shadb/package.json": "QmYkgqguk7JX55kCVHftricRVTG5qyJheRqYCPk8hyfXXw",
  "src/shadb/src/diff.js": "Qmda6YhbwL9XYtLgmK3HGPpGw5zFcRox54cRKaJjNUMWAE",
  "src/shadb/src/diffChars.js":
    "QmWyRfBNH9Epu8Fg6qKghPCm41ht6xG54jZ6iANubmRv6d",
  "src/shadb/src/getDbObj.js": "QmWHmVpjUyjtseZDdvxbZNYiDx3MXTgmZhwBpqCP8CrEtb",
  "src/shadb/src/sha256.js": "QmUYHM48BTQuN4TFNHBH5dYaZ16FRNu2tbeF6JdHnBKc6g",
  "src/shadb/src/shaDB.js": "QmQ7TuHw5n1XZVwpfsxfMeWUHYqc35tEQx4ypbJw523GJV",
  "src/shadb/src/vendor/diffChars.js":
    "QmRGpEFyhuqLyPYt67ZFftdPK9PMf8UXuvHfXVhZyQ3YAJ",
  "src/shadb/src/vendor/diffMin.js":
    "QmXDjtDjFxzUemcTkNDbQqSimHTNDcpLsfxq5PhbwmuXSf",
  "src/shadb/src/vendor/idb.js":
    "QmdrnoscF7ihtuyZCd1iv7g6Zpvem23yNn6AHU6xTaV5XU",
  "src/shadb/tsconfig.json": "QmSweNRyD6aAUjpMnt8zKE5LAxvvLoZPy9Qj3r4THEhaUd",
  "src/shadb/tsconfig.tsbuildinfo":
    "QmVG97P9PM2B3VPjWWHmonDgfZtQuMXYgM49MKmmrr58Tb",
  "src/share.js": "QmSecn3oGHWisrFPkNJp8FQN2x7EHUjBb6PeTwjjK3suhR",
  "src/smart-monaco-editor/LICENSE.md":
    "QmQAGWaCTkwWF9GMjvoLgCMMgec8bKWRgzB29yti3b5zAL",
  "src/smart-monaco-editor/README.md":
    "Qme5mqxxvVorXuV6y3Wit23U9pUhaMfSDR2YDx1esCCruY",
  "src/smart-monaco-editor/dist/editor.d.ts":
    "QmZZZ3UjjGrNVCuyDx67fvvmf1rPmq8wnh9DUcdAoLMtsK",
  "src/smart-monaco-editor/dist/editor.js":
    "QmQUj2vVZrDVfp9oYj5D5jqcrQT5SNrkvdSwh2smYeVFMm",
  "src/smart-monaco-editor/dist/monaco.d.ts":
    "QmPNrqP54db6P45nw6d3BFmerEAxLzbz2ynbByCrLderPF",
  "src/smart-monaco-editor/dist/monaco.js":
    "QmbJtqvS31TXa9GHm4e8FjK837kpHPU13fZkHbgkFL1FQR",
  "src/smart-monaco-editor/dist/scripts/screenshots.d.ts":
    "QmS5gMBfgk8pSufk8fk4D9VXz74GvEaKgB8sP1dJTDKMtQ",
  "src/smart-monaco-editor/dist/scripts/screenshots.js":
    "QmZj5ZmAy4A2ow36UjUkWKkK1HXKL1tMofYxTYLVoSMJoD",
  "src/smart-monaco-editor/favicon.ico":
    "QmWF8oNe7SDdaY6t4WrJ8ZzM46dHEFmHDXzd8MBeNrELxe",
  "src/smart-monaco-editor/index.html":
    "QmVQxvRvunUpXoZqC67ZUPoNSRpvyB4dKNmEQTtntCNqms",
  "src/smart-monaco-editor/node_legacy/@emotion/cache@11.0.0/types/index.d.ts":
    "QmUCj2Y8UvRu3qr495TxRWLjotqJVpGW4m2f373ML9J4q9",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4/types/css-prop.d.ts":
    "QmcqPuhFmv4w5Uaa1zarPmNPW2rEUEuTVpRbkMvkpuRTu2",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4/types/helper.d.ts":
    "QmTgJLTGDTZvVBrNvXmtPZT9W4ekHjXDM4ao62wLddJFo2",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4/types/index.d.ts":
    "Qma8jqDFMjj4MFpsCgZu2BA4PoRBgJpqNRjvG1S7JRwNLN",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4/types/jsx-namespace.d.ts":
    "QmNjM3vwg7JVnPCgNY55nxr6MDNnZfnR46xhNkqMRRWrSH",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4/types/theming.d.ts":
    "QmRR1zmJ1QThGaMQP9CZyo89ny6b6cnN6T4EsNfVuMgMBZ",
  "src/smart-monaco-editor/node_legacy/@emotion/serialize@1.0.0/types/index.d.ts":
    "QmTe7sNkKt6fppui5WQ6KTp4dXAChyirJpmfaiwja8EFLu",
  "src/smart-monaco-editor/node_legacy/@emotion/styled@11.0.0/types/base.d.ts":
    "QmcrDAZs3J1SbebjXv1XmfK5BEdrYAqy4E7vEVFVqjM4RV",
  "src/smart-monaco-editor/node_legacy/@emotion/styled@11.0.0/types/index.d.ts":
    "QmWD3WGSdBRhBbmmv1P4JJyA4XMfazmV8CkY7pFrnVYMeb",
  "src/smart-monaco-editor/node_legacy/@emotion/utils@1.0.0/types/index.d.ts":
    "QmbvhexADU4v3XaaBXJxD4X1g7DMxFPsCWvytbsqvHpAKq",
  "src/smart-monaco-editor/node_legacy/@types/framer-motion.d.ts":
    "QmbiNzDjbM9doX5U9qMgmP3e1yJkVfA1TFMWgbdvxwvLq7",
  "src/smart-monaco-editor/node_legacy/@types/prop-types@15.7.3/index.d.ts":
    "QmXaJ9waDpQDB5rY24AWJwebJhXAvPZ8Zg6xyardJjkVeY",
  "src/smart-monaco-editor/node_legacy/@types/react-dom@17.0.0/index.d.ts":
    "QmUp6zxmTL2cBSqSummQCsVUr8ksVPku73xR47jjGqPyTL",
  "src/smart-monaco-editor/node_legacy/@types/react@17.0.0/global.d.ts":
    "QmRoYgDX13hcDWSUDRNxFZcnPyTqWzzkhJNF9X29Vxrr6g",
  "src/smart-monaco-editor/node_legacy/@types/react@17.0.0/index.d.ts":
    "QmXfhdDibqw2JGSQdiSz55jT81znjCU7yvQ4dmGW5UeKkx",
  "src/smart-monaco-editor/node_legacy/@zedvision/qrious@10.12.14/dist/qrious.d.ts":
    "QmY8cwFxtfD1dPVtvXhWR5uvMpaFVN8VJ2JXNbR2U2hYne",
  "src/smart-monaco-editor/node_legacy/csstype@3.0.6/index.d.ts":
    "QmW9j7PM3CWM83KSKZi7fkGLXVV8MBY7gEyFfHNbde8RjQ",
  "src/smart-monaco-editor/node_legacy/popmotion@9.1.0/index.d.ts":
    "QmfVp3E9UrnADC6nJMc46brtFfymJLfhTn42Av9ftYQUaB",
  "src/smart-monaco-editor/node_legacy/popmotion@9.1.0/lib/index.d.ts":
    "QmfVp3E9UrnADC6nJMc46brtFfymJLfhTn42Av9ftYQUaB",
  "src/smart-monaco-editor/package.json":
    "QmefDXS3tESGfSjxk4vAhUR2PwcKjo8v96rNs4MM8GrFSt",
  "src/smart-monaco-editor/src/editor.d.ts":
    "QmXFYH4YMX7W5dDHwbLZS5NqtCSqRf6n9NcmaEZjFsLBtF",
  "src/smart-monaco-editor/src/editor.ts":
    "QmNqf8x3KgCLyrhPAH1KP1XwYfkN5jMxgR4w5KofN164Aj",
  "src/smart-monaco-editor/src/monaco.d.ts":
    "QmdsjvXNr9ufGi4osAtDQuo4tji41DfCKzbCNhLo7F5Gc1",
  "src/smart-monaco-editor/src/monaco.js":
    "QmPU117QEcnXLQb58T54ehhMzj79d6BYATsSz3wgiV7Gj1",
  "src/smart-monaco-editor/src/refs.d.ts":
    "QmUXoLQ9zNGWxd1c1yNBjSf4RoTwFMEbLcq8hL2ewCd6ba",
  "src/smart-monaco-editor/src/scripts/screenshots.d.ts":
    "QmS5gMBfgk8pSufk8fk4D9VXz74GvEaKgB8sP1dJTDKMtQ",
  "src/smart-monaco-editor/src/scripts/screenshots.js":
    "QmYUzn9XSFiduCLmzj4Ewcn5GnxwPaDKYDGAxdakydncmg",
  "src/smart-monaco-editor/tsconfig.json":
    "QmTqtxpjAgAVTAsFTHNuHE2cRCXSzKzfsrVwhFSaGsqea8",
  "src/smart-monaco-editor/tsconfig.tsbuildinfo":
    "QmYzfRXuBwRw4nNpqTzts1y2JAo4HLgq9iPYebBcGCKsTv",
  "src/starterTsx.tsx": "QmQ9AHQxPPsDqonKSH5q5zHeiHHSds2P7gcmUVEWkm4QW7",
  "src/templates.js": "QmWSt41VoKvyHGZPBqQSMEJiMjVDU8HdbbefpgTtyFfEG3",
  "src/transpile.js": "QmYGwmxD1aJH2PiEJ22dRtio3qUniGjpWzwmdEngMEYmfe",
  "src/workBox.js": "QmNPf2EGKEnBtd5M3zDLPoNRWes2ofCJMhDAuXFYvRvPd9",
  "src/workers/ipfs/README.md":
    "QmbdTTJXo4rWcSfDFooCBXWGYtCnbixPpSJh9hjAQ6KMFw",
  "src/workers/ipfs/dist/gateways.d.ts":
    "QmaqVQHmb2ESQaLajE5YAbgw1PzYPRwpLbwEFLJfEBARWk",
  "src/workers/ipfs/dist/gateways.js":
    "QmNVuHYaC7MuqYnsRJ2J9kY7TotGALZ868F2jx4ryvmETK",
  "src/workers/ipfs/dist/ipfs.client.d.ts":
    "QmViTDo9BBn2p3h6UyQuFXkRAjqVnKMV9PhkqsaKe73xwE",
  "src/workers/ipfs/dist/ipfs.client.js":
    "Qmdp2HBvcvTJPkYqHHJ75RauWt8koyoqqVAhmPWGP8Q5i6",
  "src/workers/ipfs/dist/ipfs.server.d.ts":
    "QmS5gMBfgk8pSufk8fk4D9VXz74GvEaKgB8sP1dJTDKMtQ",
  "src/workers/ipfs/dist/ipfs.server.js":
    "QmZBVJyLM1r4wZHySwQ3hxKUQCZXsV3fL63BScffj7L2BJ",
  "src/workers/ipfs/node_legacy/ipfs.min.js":
    "QmWQMs9pJDk38iaxBKSgCXbwuPXgRqsqHQtTabqQHoRhKF",
  "src/workers/ipfs/node_legacy/server.min.js":
    "QmWQMs9pJDk38iaxBKSgCXbwuPXgRqsqHQtTabqQHoRhKF",
  "src/workers/ipfs/package.json":
    "QmP8eQ14iUnhEAmCf73LzY913v9zvcEifPZCgE5fswUTYE",
  "src/workers/ipfs/src/gateways.js":
    "QmVGZy8bP96dMrzL4vTg7ppfpJVAFbtUZ1Go57fvsParbe",
  "src/workers/ipfs/src/ipfs.client.ts":
    "QmPHeiaXEFPhPXsg2DpZkdb7NYp9GZ1MCarVFMRdg83Ada",
  "src/workers/ipfs/src/ipfs.server.ts":
    "QmdcUyYNDxR9fKZ6jfuRa6Uzb8vS6BJWiAGaQfUjpoVjrW",
  "src/workers/ipfs/src/ref.d.ts":
    "QmZV7knX51sBSfDb7mFNcghGtF3RKyczc6z4Uz7zXS25zo",
  "src/workers/ipfs/tsconfig.json":
    "QmYHbMSMqJLVt643gR6twoh1Fh2pmRefGPr9GEfXQSemHg",
  "src/workers/ipfsWorker.js": "QmX5UdE5UyETFtJWyE1CZGWv9erxTJHWNWju7y7GbnambK",
  "src/workers/shasums.umd.js":
    "QmZRi154mJGuG6wriiZCxvVjNoj2fNYGRDn1KJsKJy7D2c",
  "src/workers/sw.js": "QmQ7Vq8grvgM4mW3oi42iYb8vKeN8P46pLvHFvy4tkBCcZ",
  "src/workers/transpile.worker.js":
    "QmRpc28tAYSDx9c5hb8maUAYh7SuLh4pzGnr4h37p3JMqu",
  "src/workers/tsconfig.json": "QmNt8xKcRnN8TVbPqU9kNwUPNy7tinifkhWe8ADPTSVCvJ",
  "tsconfig.json": "QmdYYNAMVJJgs9nYR2tc4oVC6Fxcwcv7K1b8QH4H2372EY",
  "assets/fonts": "QmYAJJ726yRoCVerLBgUHdLax1JKS85SYLrnrG54WxSDtK",
  "assets/synthwave-vscode": "QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn",
  "assets": "QmcLAE4ZmMJ1GT977zHKnX7zzcwVRS25cYzFTTiA9hxtyd",
  "node_legacy/@babel/standalone/test":
    "QmWWWLKmada8efNn6Q3dkck2vCC6uCEcMarW1DuKTpp17o",
  "node_legacy/@babel/standalone":
    "QmQy3Bma1iBoLnQqsPDoEoooBbMRA17uwTPvhqP82KtxVa",
  "node_legacy/@babel": "QmdtRfBeZw1CytNk7aYZLZXDChmridNt6UKzqLShm5o6G5",
  "node_legacy/comlink": "QmZHtMFozWJWWpF8ZZ3kgcTpidCfJN3cuqMYKEG1ox2h3R",
  "node_legacy/ipfs-message-port-client/dist/src/client":
    "QmQ3Td4DsTeRsvo6LFpwdh1SV5uAyr49pShjHrNY2muM2X",
  "node_legacy/ipfs-message-port-client/dist/src":
    "QmPPCE6EengZqMSCTA3fQTcjTZPq8FiiuG79kfpbY4PwwC",
  "node_legacy/ipfs-message-port-client/dist":
    "QmYbrh9kpaoG7MJuSpFTY9LWBa2qAqUdpfcrSQJm7ytyij",
  "node_legacy/ipfs-message-port-client/src/client":
    "QmQBWbefZoDQG2hhRXyWjrRAUdpEQb8Bmx4tQy6aHFAkdW",
  "node_legacy/ipfs-message-port-client/src":
    "QmdKUSLoWme89P7kcZWpCwjn9CfzMSWCTP2U3noaXTRrpf",
  "node_legacy/ipfs-message-port-client":
    "QmYaX7QFPJj1ovRSMTE7AWHVfMxRuDWq6sKE3nxSfqsysx",
  "node_legacy/ipfs-message-port-protocol/dist/src":
    "QmXr2ZSJ3Nc4jnLhDHkDAxoy1Hfh2mYzyxtdrL88Cc1Gc6",
  "node_legacy/ipfs-message-port-protocol/dist":
    "QmRi9BoigTgJEQRtVDzXVivx2xh44sW9ZeLxtpq1qwLtzY",
  "node_legacy/ipfs-message-port-protocol/src":
    "QmP4KTorzecP4eZBVWzKrVosky6WmvoyEL6TMUGNDxR8jE",
  "node_legacy/ipfs-message-port-protocol":
    "QmP4qHtkxFawacLHUbovMnKU9qiBwkMm5TsmJV8iSQ3tjo",
  "node_legacy/ipfs-message-port-server/dist/src":
    "QmWHWuUnjvSkRDr7kpSK8Szk3yqt3QM238rXtFXFh2RtQF",
  "node_legacy/ipfs-message-port-server/dist":
    "QmPkR6pt39uVMWdUWyXi1ED5GaP86eZBqwe7vj1YRHRQte",
  "node_legacy/ipfs-message-port-server/src":
    "QmWLL769pVAv36kRuYHF62XnTnoogCwXCCi6WRYH28BG3M",
  "node_legacy/ipfs-message-port-server":
    "QmW3RctEn78UZUsdffPNVMWxEsLmwCDDCWs4AexqUZMkC5",
  "node_legacy/monaco-editor/min/vs/base/browser/ui/codicons/codicon":
    "QmRDaTDHFannojUDz7oBNzTewktam3SmeCaQZo7U7Wj9op",
  "node_legacy/monaco-editor/min/vs/base/browser/ui/codicons":
    "QmaWwv6hAgo2L7j4Vh76KE3jaKMhjiLPQXLuzAM4fQBxej",
  "node_legacy/monaco-editor/min/vs/base/browser/ui":
    "QmcXZHatGpMeybjiyMePnwDBxNoEzYK3boMwLeACGMBdoz",
  "node_legacy/monaco-editor/min/vs/base/browser":
    "QmfGWbFf3Qi9sxWLRqXhSxgw2YGwpm71KmUoQ8c5MHsoLE",
  "node_legacy/monaco-editor/min/vs/base/worker":
    "QmRQV9Kr5Cs86GHeP7y6crpMeCraFpaCzFZqoy7vUFgi5N",
  "node_legacy/monaco-editor/min/vs/base":
    "QmcqxBpgaBsqRRQWGj1fhaJocuVYiKLDWQ6pVZG2tM1TpF",
  "node_legacy/monaco-editor/min/vs/basic-languages/abap":
    "QmdD1PHzo83oaZBpMBmxpvVzTcCsWQHvxgKpcQecpLmAMY",
  "node_legacy/monaco-editor/min/vs/basic-languages/apex":
    "QmTjnGzVTrGc98JXd2CQQiyzM2rNDUqgMqVcFo98C9Em8K",
  "node_legacy/monaco-editor/min/vs/basic-languages/azcli":
    "QmNNttjyvAQJ2ezkVZ1uLEY7jeHaLMN6Eaus21g6GxxBNK",
  "node_legacy/monaco-editor/min/vs/basic-languages/bat":
    "Qmd3gdbgmF4uxSxQeMA7RzuDFX1zhPFWu7G61HkXDvqMWR",
  "node_legacy/monaco-editor/min/vs/basic-languages/cameligo":
    "QmWgUMqHjFewF9aWDMqPyUEHNJ1Ym1Z5zeEwB99JwL6Bth",
  "node_legacy/monaco-editor/min/vs/basic-languages/clojure":
    "QmZkZfcsi1VPHc6pRQgLNoCDo5rnxn2bmDa1AxePMg2pQ5",
  "node_legacy/monaco-editor/min/vs/basic-languages/coffee":
    "QmPURt8baQoBhYmrTAs8NL8HkGZi8PZ19PfSB2pVQLdXfy",
  "node_legacy/monaco-editor/min/vs/basic-languages/cpp":
    "QmXnmDVMxGDeArrvjvCF5AdrwFLEzvJ8pPLuUjRaUEyARK",
  "node_legacy/monaco-editor/min/vs/basic-languages/csharp":
    "QmSMaVZMSq4E6aFFWKvg99BHB1LFYLKZXGUaCFijNSS6dC",
  "node_legacy/monaco-editor/min/vs/basic-languages/csp":
    "QmQUzb89MH5KxyxUnTmdJGF2b99BDXDtTFRZiPN2o55nJa",
  "node_legacy/monaco-editor/min/vs/basic-languages/css":
    "Qmbsi8m64DACNhACHijXKjY72gdyoU3w6CALEtNY8Rrf4t",
  "node_legacy/monaco-editor/min/vs/basic-languages/dart":
    "QmZei8VbbN3TDFR2GRWMQqSwde9MZXa5dQCWpGJPzDYmh1",
  "node_legacy/monaco-editor/min/vs/basic-languages/dockerfile":
    "QmcYwm2cwNnMojJPte7UhUSFBAvNcJtEhT4Abf8QY2F1eD",
  "node_legacy/monaco-editor/min/vs/basic-languages/ecl":
    "QmNM7SxnJSqZ5EBeZq1upNvjHzPRidaqVjauMM6HczkkVk",
  "node_legacy/monaco-editor/min/vs/basic-languages/fsharp":
    "QmXf5yfYtVpEbbEkitYmvEo56Y2f1YYZiwAmyUnYAybzHR",
  "node_legacy/monaco-editor/min/vs/basic-languages/go":
    "QmUp5rFQAq9WjQ8tatvWFD7g2jFmQtTAv6Q8z3UtsRgB5v",
  "node_legacy/monaco-editor/min/vs/basic-languages/graphql":
    "QmXR6Lws4HHjEXmeQTPD3eNT6WQC5kR7Abumym5DsHitne",
  "node_legacy/monaco-editor/min/vs/basic-languages/handlebars":
    "QmWkee9R4z8U3KwVRVzpMjzkBmN2YKvUFjUH8WmRVmctCx",
  "node_legacy/monaco-editor/min/vs/basic-languages/hcl":
    "QmePzWfav1VLiaKDS2qnSHdYGp39XdY714jw9CxzZJp1vQ",
  "node_legacy/monaco-editor/min/vs/basic-languages/html":
    "QmY9B726m4hGxzKhTTBzDfJE6vXCNhkQkJ7H3dPTV6qssw",
  "node_legacy/monaco-editor/min/vs/basic-languages/ini":
    "Qmbj2JSV5Pfkwhm3YFE1bF1dpbkPhrALNnSgDfiEviVrGZ",
  "node_legacy/monaco-editor/min/vs/basic-languages/java":
    "QmQcdjyRJuXVcjCp3jRaxTVgxgu7w7DRec1WdpNfebo1GL",
  "node_legacy/monaco-editor/min/vs/basic-languages/javascript":
    "QmTSDaDyxvY1uBiRr59brYUSyKNdmpUs8g9NuhEyxjpp52",
  "node_legacy/monaco-editor/min/vs/basic-languages/julia":
    "QmXuNDEHH4acTrGBu3LzwL4zKkks8HWvxzzXEdcXCmom4k",
  "node_legacy/monaco-editor/min/vs/basic-languages/kotlin":
    "QmdQ7XYQ8Wd21DKb4fjztkSrWQasfgiDqEoZtZVXEXmT6N",
  "node_legacy/monaco-editor/min/vs/basic-languages/less":
    "QmZ6pkVFYqShAnWSBy5X63u32iB4TsLEsKV4hnRXiS8Lip",
  "node_legacy/monaco-editor/min/vs/basic-languages/lexon":
    "QmbuGxBZNg24ssFVbJxMZxifwgVRS6H47NxUVPQw9fqFck",
  "node_legacy/monaco-editor/min/vs/basic-languages/lua":
    "QmaUan8TETJwft881McTA6w2JCciJkkH64ddiUVLEfF5HT",
  "node_legacy/monaco-editor/min/vs/basic-languages/m3":
    "QmdaifCwD9qBT1UYzyptJxW8NBBwPk8KnJuss9ffD1jvqu",
  "node_legacy/monaco-editor/min/vs/basic-languages/markdown":
    "QmcPECs4cgKq2z6j38282GtBzEANxcmbQhoP5RUpvB89Vh",
  "node_legacy/monaco-editor/min/vs/basic-languages/mips":
    "QmT7iLvmzG6Tm8ncANRmMQ1e7u9uLaeHkEALUjKVKyVKwp",
  "node_legacy/monaco-editor/min/vs/basic-languages/msdax":
    "QmTxaJASuwFj9nFsTAyWqsjr3BW513aHegxoM33ULNcLiZ",
  "node_legacy/monaco-editor/min/vs/basic-languages/mysql":
    "QmYLBnpm7Cmy7WpWFwksSYQ8sRjNbpLAHwYd1zu7j2wS4j",
  "node_legacy/monaco-editor/min/vs/basic-languages/objective-c":
    "Qmb2r5AhCKpWEUfqiAtAVwPJCJLrPZP3rxaG3k9jJePhw8",
  "node_legacy/monaco-editor/min/vs/basic-languages/pascal":
    "QmXsTNe1A6xFuGjSusq5f9abfVJ7T6JGZu7x6eDBFSp8oi",
  "node_legacy/monaco-editor/min/vs/basic-languages/pascaligo":
    "QmNnrp7JKh3vQJk1KuJ4Sqte7EJsfbbrwvy5xpUNoMHQBy",
  "node_legacy/monaco-editor/min/vs/basic-languages/perl":
    "QmY5xRh6PtH7Ctwy2VA4prLagXHGQY24NEbViHi1xu2H9E",
  "node_legacy/monaco-editor/min/vs/basic-languages/pgsql":
    "QmcoFfEojNbWawGomuEQ4iYejtiWgVPsCSYQmpFbhbPver",
  "node_legacy/monaco-editor/min/vs/basic-languages/php":
    "QmaPk1cEE3AgDyrUAVM4aqhREnUQd4LasVcJFq5oJbKFe6",
  "node_legacy/monaco-editor/min/vs/basic-languages/postiats":
    "QmXpQ4nbyF4cn4MueK5qq5yc3HwXPPwu9nAtEJae8Ae2wE",
  "node_legacy/monaco-editor/min/vs/basic-languages/powerquery":
    "QmRCnhtNiJWHtsiaQep87m1fQ3mXjY4ZNtuoi5nRULztDy",
  "node_legacy/monaco-editor/min/vs/basic-languages/powershell":
    "QmQf5s1rG9smTGNvAbg92KYC6t43bvnFRBoUrHxGqi61HA",
  "node_legacy/monaco-editor/min/vs/basic-languages/pug":
    "QmbWi1Bwxbgjgwv1Y3eytsKHRZS8Rx3PgA1us6hsaYr23s",
  "node_legacy/monaco-editor/min/vs/basic-languages/python":
    "QmWxGykjwKHmK2cKEPomWCwyB6r2NZEdwN2k7zFexJWkUT",
  "node_legacy/monaco-editor/min/vs/basic-languages/r":
    "QmQr3X6U6dXejx2TeTJztPkrN9SezQv45ob18JAoBuV9DE",
  "node_legacy/monaco-editor/min/vs/basic-languages/razor":
    "QmcG59EmpE9xSfFRRXXSG9wGB1CdCzAA9beX8LPFfMfoR2",
  "node_legacy/monaco-editor/min/vs/basic-languages/redis":
    "Qmc6rBb2ssmt2RzisLUFScC7VFQRvssMbG8httBEVZXoiN",
  "node_legacy/monaco-editor/min/vs/basic-languages/redshift":
    "Qmc4HpE18351d6E6L3wi7XQxZvb4SmK1sHQLFC2nEkdVZi",
  "node_legacy/monaco-editor/min/vs/basic-languages/restructuredtext":
    "QmXpuCKdfNF79YNgyJd8r9ETFa8D9bQtmt12punafZnud2",
  "node_legacy/monaco-editor/min/vs/basic-languages/ruby":
    "QmWRS8EfEuwxwvyJEBwjaJeaHd12cVZ6invTZgdr9zRY1c",
  "node_legacy/monaco-editor/min/vs/basic-languages/rust":
    "QmcvPfV4jTahRsUZHSjm5iy8bb9mURHAUnSYkw8dsAQstH",
  "node_legacy/monaco-editor/min/vs/basic-languages/sb":
    "QmcB4xyRe3fkzt7BMkmQagQGR4px83mMLqzeZQnjZmU7Tj",
  "node_legacy/monaco-editor/min/vs/basic-languages/scala":
    "QmezSQWgnnUQdavh7wKJeXoLm7kCHt5VqsUSjNtvC7ii6Q",
  "node_legacy/monaco-editor/min/vs/basic-languages/scheme":
    "QmZSN1RLK3u3oYTmSraKrekea8Wg5cauiU6td9e2VUz29z",
  "node_legacy/monaco-editor/min/vs/basic-languages/scss":
    "QmevN6zCrdjn1LNvMC8e4MJSyMNyXR2HbTQ7Q8tgantYqM",
  "node_legacy/monaco-editor/min/vs/basic-languages/shell":
    "QmYpPiFnrdrhNhrvX7AvLYTDeTb7ivN1HBk7Fpg3mLVZjx",
  "node_legacy/monaco-editor/min/vs/basic-languages/solidity":
    "QmVw6HLsUWBoD5N5ALgWiJPhfLmoW6Uoh1Qc3HarabH7L4",
  "node_legacy/monaco-editor/min/vs/basic-languages/sophia":
    "QmQvU8QfGx1dDcSC11KX2JWsWF67J2pzX7fQXsd7oNLZE1",
  "node_legacy/monaco-editor/min/vs/basic-languages/sql":
    "Qmd8cgNP3Wh9eXyhGCEpSzMW6bfvNGyw97aUfPDL2PWBi5",
  "node_legacy/monaco-editor/min/vs/basic-languages/st":
    "QmVFdZk8rBqWGrwsr7DyhEVQZmhgkq2aVCS4GBJY87g5Rq",
  "node_legacy/monaco-editor/min/vs/basic-languages/swift":
    "QmVS3sfPq5sRdkdmr3xgd5Rre5wg3r1d2gSRxNPFFHSDJv",
  "node_legacy/monaco-editor/min/vs/basic-languages/systemverilog":
    "QmVNjnudJtNAa2r5K5BDMGtWsRiQfD2tNCZCYp9txSPdn8",
  "node_legacy/monaco-editor/min/vs/basic-languages/tcl":
    "QmZidpArXZtSBzjbe75DhpceaEbob2Yi6gxrPyMJ84VWEs",
  "node_legacy/monaco-editor/min/vs/basic-languages/twig":
    "QmTBnhVucBks3khJDfrTnKpuKLkDkrNuUQhVECV6xSwe5Y",
  "node_legacy/monaco-editor/min/vs/basic-languages/typescript":
    "QmQTonhaNaPKtAqzTZ7CUysVSoJfHD78u5c47HvUniq7Zq",
  "node_legacy/monaco-editor/min/vs/basic-languages/vb":
    "QmcHTAmPTEPy6TFuAWzPffP8U8zmHdZbHjSY2Biy7DCy12",
  "node_legacy/monaco-editor/min/vs/basic-languages/xml":
    "Qmdc9EQ5FJGYYRhwqX8KohpEJYeUrVEGncfFwmW4KQ2wBc",
  "node_legacy/monaco-editor/min/vs/basic-languages/yaml":
    "QmdXaTF1Y9KEUNN4tZejgRBiuboMrT4TPd2TdTMsmbXHrT",
  "node_legacy/monaco-editor/min/vs/basic-languages":
    "QmRrt8dUbKmQWEj1uC9rpp4prJGjFKnJtkDGg8ibjoCJgn",
  "node_legacy/monaco-editor/min/vs/editor":
    "QmYYEXfBuLaErv7roYNbmxQ82YbGSsXBeM8g4ZFtJjP2iA",
  "node_legacy/monaco-editor/min/vs/language/css":
    "QmPDnPXa8zWX5YR5EG1b3dZTsxzkM5WpLQ6SgVUFCDgMPe",
  "node_legacy/monaco-editor/min/vs/language/html":
    "QmW8nrzVyQwpJAJRM9BYiuwu1itAMty5XC7Jfs1QJymFhB",
  "node_legacy/monaco-editor/min/vs/language/json":
    "Qmbu4LSU5bdfpd9Jft1oCDwyWXzvW6tTDnHGTRvnefTafV",
  "node_legacy/monaco-editor/min/vs/language/typescript":
    "QmZtzcC6WcDVootD8sXrx6SWJKWHDu5pTGGB8MmKwcG2qc",
  "node_legacy/monaco-editor/min/vs/language":
    "Qmb2JKjzm8PNo1K4kZv8d3DjNjYXcQA9vhJkfawCV8xGtn",
  "node_legacy/monaco-editor/min/vs":
    "QmYTU2Rx5ickjz98zN26cXVWJ4kykwSRnLb5y1ayo7m1gR",
  "node_legacy/monaco-editor/min":
    "QmQtvM9NihaXm52a4Smde4L4nepnTdeanVHua9diqSAzbQ",
  "node_legacy/monaco-editor/min-maps/vs/base/worker":
    "QmYRoYuqj7s3BniW4aGfKYtrSrPirhAfMbeZSm8c4LH1R2",
  "node_legacy/monaco-editor/min-maps/vs/base":
    "QmRUR4auT2Gtx1ynyLNDvxoppqNXJN9bKV7iJXJo4ojYvc",
  "node_legacy/monaco-editor/min-maps/vs/editor":
    "QmPePiiaqLJifhM3KmDLM9Ki6fTVVhpbV5vkZiZUJ6JQpQ",
  "node_legacy/monaco-editor/min-maps/vs":
    "QmVD3qzMtKhaCSdESxNKGAA48KvjPHgznV6e5ygpY1nUjC",
  "node_legacy/monaco-editor/min-maps":
    "QmWS6URBS2wPhcuKFEZrRK4uhR8SbKZhqH8CNnUq5qKLNQ",
  "node_legacy/monaco-editor": "QmNmd5vm8JDYkYaPGLuaph41Q2FRXS89mAntwV6HU8euwh",
  "node_legacy": "QmY2TXCWcJcZngN5BWysbDFuAmVox9DMGZKdUkXLT621E7",
  "src/emotion-react-renderer/dist":
    "QmeGrbwX5LFaAr5rDS18h7izH3X4MSyirBmf7X8k6UZryL",
  "src/emotion-react-renderer/src":
    "Qma9o1V19rdr87xZBYTkh1X1exe9cvGqT6Rhr5gaLfFxnB",
  "src/emotion-react-renderer":
    "QmPHTEXFHNbyfhaX1Yj7VTurfPxZcThWUxcD4FAHvd9PMV",
  "src/examples": "QmasbQ63fdpt8XKSug4SkL8u4oQMWuaVd7xob5f8dfXDqM",
  "src/qrious/dist": "QmQeLhgtbob32M7FbtGELAfqLDgzq4LqasUpN2kUp6vGVa",
  "src/qrious/src/service/element":
    "QmcP8FAooT6RDNr8SELNUQgQiGAfEXFULUoJ5FQCF4t7hN",
  "src/qrious/src/service": "QmVdYoXyeaPxymoWj9gaAWww2DJQTStjYtzqeZ9EdPH2bK",
  "src/qrious/src": "QmPS8uZ98ntMQpiUEdff7aszmuKLGS9r3grQFrrdYGy3qu",
  "src/qrious": "QmaV8BhUj8AMQ2e6UKuXN8hhHdNrTP8yurLzzAeqPH5EUZ",
  "src/shadb/dist/vendor": "QmTZzgTNwYe9ioj2zaZmme3LZLscde4D54r8J6HpaaHJ5x",
  "src/shadb/dist": "QmPs9fBmE8aZQd62NYjBoWBvdwKZkf45nu81byMAEgmwuQ",
  "src/shadb/src/vendor": "QmZcc5JirQ5ySPiELM4nJaVBLsKVL3vvNg2KE5uj7rGSr3",
  "src/shadb/src": "QmQqL9VeFmzKpNiihj8AuLZ7ngMn2w1Yi8AkzU78CUJvfJ",
  "src/shadb": "QmSizaV4YcU84Aa5iYqXvEqfEZLEbfmQRpkoVUgnfkAHZ8",
  "src/smart-monaco-editor/dist/scripts":
    "QmUZruQhR3JEi3knevKng6AKpxN3vcswuRrCp4DiW9aYMM",
  "src/smart-monaco-editor/dist":
    "QmSvV5P2nWechQFGB3r6Hs3xshAGFu1gPoLhpERzzuEJx1",
  "src/smart-monaco-editor/node_legacy/@emotion/cache@11.0.0/types":
    "QmUEN3GDGpShVYbF8hWwkgFWdCFf4MGFXggEBLLJCW7MHn",
  "src/smart-monaco-editor/node_legacy/@emotion/cache@11.0.0":
    "QmRrpV1ht67hartnVdCGUL6HoZ3VSqxoCJihFi3Qunud26",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4/types":
    "QmanceJtx35wfrY3dqZfRGiFZg7birgBaL65fkJRmRNZiF",
  "src/smart-monaco-editor/node_legacy/@emotion/react@11.1.4":
    "QmYv3i1pQ5bjKy3iEEWX66FfxNsUe1GC522xbt4XRdwwyU",
  "src/smart-monaco-editor/node_legacy/@emotion/serialize@1.0.0/types":
    "QmUnre3UQbzpYq1XmEdf5cD24wcsBqWNnHkH75Z9SvsNPR",
  "src/smart-monaco-editor/node_legacy/@emotion/serialize@1.0.0":
    "QmbohaYyrYyu47WW4W3BRV5pxJQY5mVyAiQce9Bn1pQzCT",
  "src/smart-monaco-editor/node_legacy/@emotion/styled@11.0.0/types":
    "QmS5uFuLqN8AGfAiDTZnbjKbueGKve723gjTyVjTBaaz8F",
  "src/smart-monaco-editor/node_legacy/@emotion/styled@11.0.0":
    "QmQgjmWjt2jnyXUyLhMGRCDDWzeTPFpxAPtqyzYxadDENh",
  "src/smart-monaco-editor/node_legacy/@emotion/utils@1.0.0/types":
    "QmUXun6ie598RTouvr2WWASvmZZqErUtHuPXxd1LtdaFZ3",
  "src/smart-monaco-editor/node_legacy/@emotion/utils@1.0.0":
    "QmaWRA2PvGCN9iJefsPvvhtEPVgSH1jNWQsZAXYgcWqVhF",
  "src/smart-monaco-editor/node_legacy/@emotion":
    "QmdkLmXqY4cR3eCHDkEu6wr26oG12tRr7XRVpeNqieU11j",
  "src/smart-monaco-editor/node_legacy/@types/prop-types@15.7.3":
    "QmR4pDyXHid6f9yeQLtTVnCtpjmo43m7JAPwTd1Jbjj3Ta",
  "src/smart-monaco-editor/node_legacy/@types/react-dom@17.0.0":
    "QmRb3L5eSa6HX9KGJKyecoLnfSPNd6tzZdAMg6oQJj2Bsq",
  "src/smart-monaco-editor/node_legacy/@types/react@17.0.0":
    "QmdafiC1ixpU9mcYwH52sYg6yqMJtbAfRtCYzdh7aFD2Tm",
  "src/smart-monaco-editor/node_legacy/@types":
    "QmfVpWFFoyKAKZbfzoVjcR51rKM5psMfreg7QPPgaCdd1i",
  "src/smart-monaco-editor/node_legacy/@zedvision/qrious@10.12.14/dist":
    "QmVr2gYmRGvQaHm4cbQt11LsXYQq4nMLG4H4MKYgJFvgc7",
  "src/smart-monaco-editor/node_legacy/@zedvision/qrious@10.12.14":
    "QmXJmZqywmjXZaXd4DHrhHLmVj5EDtuAA4gGvbnGXanhvK",
  "src/smart-monaco-editor/node_legacy/@zedvision":
    "QmQqBzB3Xs73A4pZwJpBKV8pcBp81oxYo6dHeDa2PCHF6u",
  "src/smart-monaco-editor/node_legacy/csstype@3.0.6":
    "Qme2hqcm1oQ6yWugA5iMA1qF5vHLNttgYHk9o6pTwSbf3M",
  "src/smart-monaco-editor/node_legacy/popmotion@9.1.0/lib":
    "QmTaZJ5REPK49oBHT76FsF8LX952W1mhEKgEzv81pqy997",
  "src/smart-monaco-editor/node_legacy/popmotion@9.1.0":
    "QmTnZe14NmEVosHmhQG1c1L8wvCDnfoaNzcdqszV9RnvBX",
  "src/smart-monaco-editor/node_legacy":
    "QmeggxxSfuAMXckECWSebkqkBy7VT4SrCpcy69o38zbc78",
  "src/smart-monaco-editor/src/scripts":
    "Qme94rT99UbaVwYxeK2ERakcHAABqofabkBbiSUuKztFzg",
  "src/smart-monaco-editor/src":
    "QmdLrJeHHhaB8kPwzDpcn9PFAeJavdpvmgRcykvpqnHi6g",
  "src/smart-monaco-editor": "QmTtSWwErKhAVmdueBPMt2pK3AeBueVdzEHhpeodYEjwJj",
  "src/workers/ipfs/dist": "QmXLKBxQmafNmqJyFg9h4XzHVcabJmXD5k8zdJX33seNRS",
  "src/workers/ipfs/node_legacy":
    "QmSxTFf8YACtJvwT4M2s7sJ4yv4PFB4LYViYLt7vMyMtHJ",
  "src/workers/ipfs/src": "QmUqoKmHckW1HgxPr5nprzQiwHLgsuryoGeuHFjJiYCeo1",
  "src/workers/ipfs": "QmRJdk7syiVkfPZ5gtdr5WGmLikwV6iH5KBfZ2p7QXxPv3",
  "src/workers": "QmRw44Q8QM77uF97RouGnnr8onaYFasWQ2gg15MHtN6K58",
  "src": "QmT1iqviBY8Jdwyg9D6UFJJJ6WP4TSPWqRafVyxytEv8UR",
  "": "QmVZu6niC81b3uciGCsUWu3wDLqsxJ42254pS7prkMqTbw",
  "foo": "bar",
};
