name: Continuous Integration

on:
  push:
    branches:
      - main
      - fix-chat
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc" # Uses v22.11.0

      - name: Cache Yarn cache and PnP files
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: |
            ./.yarn/cache
            ./.yarn/unplugged
            ./.yarn/install-state.gz
            ./.pnp.cjs
            ./.pnp.loader.mjs
          key: ${{ runner.os }}-yarn-pnp-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            ${{ runner.os }}-yarn-pnp-

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run Linters
        run: yarn eslint --max-warnings=200

      - name: Run Type Checking
        run: yarn types:check

      - name: Run Tests
        env:
          NODE_OPTIONS: "--disable-warning=DEP0040"
        run: cd packages/code && yarn vitest run

      - name: Install Playwright Browsers for Chat Tests
        run: cd packages/chat && npx playwright install chromium

      - name: Start Chat Dev Server
        run: |
          cd packages/chat
          yarn dev &
          sleep 5
        continue-on-error: true

      - name: Run Chat Cucumber Tests
        env:
          NODE_OPTIONS: "--disable-warning=DEP0040"
          CI: true
        run: cd packages/chat && yarn test:cucumber
        continue-on-error: true
